"""
Overridden version of the simplify.py file from sqlglot.

SQLGlot rewrote its `simplify` optimizer pass from a set of free functions
into a `Simplifier` class. Rather than re-forking the whole (much larger)
class, this module subclasses `Simplifier` and overrides only the methods
PyDough customizes: `_simplify` (to splice in extra pre/post-order rewrite
rules) and `simplify_datetrunc` (to guard against `datetime.datetime`
values).
"""

from __future__ import annotations

import datetime
import typing as t

from sqlglot import exp
from sqlglot.helper import merge_ranges
from sqlglot.optimizer.simplify import (
    FINAL,
    SIMPLIFIABLE,
    Simplifier,
    UnsupportedUnit,
    _datetrunc_eq_expression,
    _datetrunc_range,
    _parenthesize_nested_connector,
    _trunc_unit,
    annotate_types_on_change,
    catch,
    datetime_floor,
    date_literal,
    extract_date,
    extract_type,
    flatten,
    is_null,
    propagate_constants,
    simplify_parens,
)

if t.TYPE_CHECKING:
    from sqlglot.dialects.dialect import DialectType

# ruff: noqa
# mypy: ignore-errors
# ruff & mypy should not try to typecheck or verify any of this


class PyDoughSimplifier(Simplifier):
    """
    PyDough's overridden version of sqlglot's `Simplifier`, adding extra
    pre/post-order rewrite rules on top of the stock ones.
    """

    def _simplify(
        self,
        expression: exp.Expr,
        constant_propagation: bool,
        coalesce_simplification: bool,
    ):
        pre_transformation_stack = [expression]
        post_transformation_stack = []

        while pre_transformation_stack:
            original = pre_transformation_stack.pop()
            node = original

            if not isinstance(node, SIMPLIFIABLE):
                if isinstance(node, exp.Query):
                    self.simplify(node, constant_propagation, coalesce_simplification)
                continue

            parent = node.parent
            root = node is expression

            node = self.rewrite_between(node)
            node = self.uniq_sort(node, root)
            node = self.absorb_and_eliminate(node, root)
            node = self.simplify_concat(node)
            node = self.simplify_conditionals(node)

            # PyDough Change: new pre-order transformations
            node = rewrite_case_to_nullif(node)
            node = rewrite_coalesce_nullif(node)
            node = rewrite_sum_nullif(node)
            node = rewrite_coalesce_count(node)
            node = rewrite_length_literal(node)
            node = rewrite_division(node)

            if constant_propagation:
                node = propagate_constants(node, root)

            if node is not original:
                original.replace(node)

            pre_transformation_stack.extend(
                n for n in node.iter_expressions(reverse=True) if not n.meta_get(FINAL)
            )
            post_transformation_stack.append((node, parent))

        while post_transformation_stack:
            original, parent = post_transformation_stack.pop()
            root = original is expression

            # Resets parent, arg_key, index pointers, same as stock sqlglot.
            for k, v in tuple(original.args.items()):
                if v is None:
                    original.args.pop(k)
                else:
                    original._set_parent(k, v)

            # Post-order transformations
            node = self.simplify_not(original)
            node = flatten(node)
            node = self.simplify_connectors(node, root)
            node = self.remove_complements(node, root)

            if coalesce_simplification:
                node = self.simplify_coalesce(node)
            node.parent = parent

            node = self.simplify_literals(node, root)
            node = self.simplify_equality(node)
            node = simplify_parens(node, dialect=self.dialect)
            node = self.simplify_datetrunc(node)
            node = self.sort_comparison(node)
            node = self.simplify_startswith(node)

            # PyDough Change: new post-order transformations
            node = rewrite_nullif_coalesce(node)
            # Length is rewritten both before and after since LENGTH(literal) can
            # be generated by the PyDough->SQLGlot generation, so doing it in
            # pre-order may enable other optimizations. However, other rules may
            # reduce terms into string literals, thus generating more LENGTH calls
            # on a literal.
            node = rewrite_length_literal(node)

            if node is not original:
                original.replace(node)

        return node

    @annotate_types_on_change
    @catch(ModuleNotFoundError, UnsupportedUnit)
    def simplify_datetrunc(self, expression: exp.Expr) -> exp.Expr:
        """Simplify expressions like `DATE_TRUNC('year', x) >= CAST('2021-01-01' AS DATE)`"""
        comparison = expression.__class__

        if isinstance(expression, self.DATETRUNCS):
            this = expression.this
            trunc_type = extract_type(this)
            date = extract_date(this)
            #### Start of PyDough Change ####
            # If date is datetime.datetime, it should NOT enter the if statement
            # because `datetime_floor` only works correctly on datetime.date
            if date and not isinstance(date, datetime.datetime) and expression.unit:
                return date_literal(
                    datetime_floor(
                        date, _trunc_unit(expression.unit, self.dialect), self.dialect
                    ),
                    trunc_type,
                )
            #### End of PyDough Change ####
        elif comparison not in self.DATETRUNC_COMPARISONS:
            return expression

        if isinstance(expression, exp.Binary):
            l, r = expression.left, expression.right  # noqa: E741

            if not self._is_datetrunc_predicate(l, r) or not isinstance(
                l, (exp.DateTrunc, exp.TimestampTrunc)
            ):
                return expression

            trunc_arg = l.this
            unit = _trunc_unit(l.args["unit"], self.dialect)
            date = extract_date(r)

            if not date:
                return expression

            simplified = self.DATETRUNC_BINARY_COMPARISONS[comparison](
                trunc_arg, date, unit, self.dialect, extract_type(r)
            )
            if simplified is None:
                return expression

            return _parenthesize_nested_connector(simplified, expression.parent)

        if isinstance(expression, exp.In):
            l = expression.this  # noqa: E741
            rs = expression.expressions

            if (
                rs
                and all(self._is_datetrunc_predicate(l, r) for r in rs)
                and isinstance(l, (exp.DateTrunc, exp.TimestampTrunc))
            ):
                unit = _trunc_unit(l.args["unit"], self.dialect)

                ranges = []
                for r in rs:
                    date = extract_date(r)
                    if not date:
                        return expression
                    drange = _datetrunc_range(date, unit, self.dialect)
                    if drange:
                        ranges.append(drange)

                if not ranges:
                    return expression

                ranges = merge_ranges(ranges)
                target_type = extract_type(*rs)

                simplified = exp.or_(
                    *[
                        _datetrunc_eq_expression(l, drange, target_type)
                        for drange in ranges
                    ],
                    copy=False,
                )
                return _parenthesize_nested_connector(simplified, expression.parent)

        return expression


def simplify(
    expression: exp.Expression,
    constant_propagation: bool = False,
    dialect: DialectType = None,
) -> exp.Expression:
    """
    Rewrite sqlglot AST to simplify expressions.

    Example:
        >>> import sqlglot
        >>> expression = sqlglot.parse_one("TRUE AND TRUE")
        >>> simplify(expression).sql()
        'TRUE'

    Args:
        expression: expression to simplify
        constant_propagation: whether the constant propagation rule should be used
        dialect: the dialect to use for simplification
    Returns:
        sqlglot.Expression: simplified expression
    """
    return PyDoughSimplifier(dialect=dialect).simplify(
        expression,
        constant_propagation=constant_propagation,
        # PyDough always ran the coalesce-simplification rule (it wasn't
        # optional prior to sqlglot introducing this flag).
        coalesce_simplification=True,
    )


def rewrite_case_to_nullif(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite expressions like `CASE WHEN x != y THEN x ELSE NULL END` to
    `NULLIF(x, y)`

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Case):
        return expr

    if (
        not (expr.args.get("this") is None and is_null(expr.args.get("default", None)))
        and len(expr.args.get("ifs", [])) == 1
    ):
        return expr

    if_expr = expr.args["ifs"][0]
    condition = if_expr.args.get("this")
    result = if_expr.args.get("true")

    if not isinstance(condition, exp.NEQ):
        return expr

    lhs = condition.args.get("this")
    rhs = condition.args.get("expression")

    if lhs == result:
        return exp.Nullif(this=lhs, expression=rhs, copy=False)

    if rhs == result:
        return exp.Nullif(this=rhs, expression=lhs, copy=False)

    return expr


def rewrite_coalesce_nullif(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite expressions like `COALESCE(NULLIF(x, y), z)` to
    `CASE WHEN x = y THEN z ELSE x END`, or if `y` and `z` are the same then
    just to `COALESCE(x, z)`.

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Coalesce):
        return expr

    if len(expr.expressions) != 1 or expr.args.get("is_nvl"):
        return expr

    first = expr.this
    second = expr.expressions[0]

    if not isinstance(first, exp.Nullif):
        return expr

    lhs: exp.Expression = first.args.get("this")
    rhs: exp.Expression = first.args.get("expression")

    if rhs == second:
        return exp.Coalesce(this=lhs, expressions=[second], copy=False)

    return exp.Case(
        whens=[
            exp.When(
                this=exp.EQ(this=lhs, expression=rhs, copy=False),
                true=second,
                copy=False,
            )
        ],
        default=lhs,
        copy=False,
    )


def rewrite_sum_nullif(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite `SUM(NULLIF(x, 0))` to `SUM(x)`.

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Sum):
        return expr

    arg = expr.this
    if not isinstance(arg, exp.Nullif):
        return expr

    lhs: exp.Expression = arg.args.get("this")
    rhs: exp.Expression = arg.args.get("expression")

    if isinstance(rhs, exp.Literal) and rhs.is_number and float(rhs.this) == 0:
        return exp.Sum(this=lhs, copy=False)

    return expr


def rewrite_coalesce_count(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite `COALESCE(COUNT(x), 0)` to `COUNT(x)`.

    `COUNT(*)` always returns 0 (never NULL) so COALESCE is redundant.
    `COUNT_IF(cond)` is intentionally excluded: when all rows in a group
    have a NULL condition (e.g. from a LEFT JOIN producing NULL rows),
    COUNT_IF returns NULL rather than 0 on some backends (e.g. DuckDB).

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Coalesce):
        return expr

    return expr.this if isinstance(expr.this, exp.Count) else expr


def rewrite_nullif_coalesce(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite `NULLIF(COALESCE(x, y), y)` to `NULLIF(x, y)`.

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Nullif):
        return expr

    lhs: exp.Expression = expr.args.get("this")
    rhs: exp.Expression = expr.args.get("expression")

    if not isinstance(lhs, exp.Coalesce) or len(lhs.expressions) != 1:
        return expr

    if lhs.expressions[0] == rhs:
        return exp.Nullif(this=lhs.args.get("this"), expression=rhs, copy=False)
    else:
        return expr


def rewrite_length_literal(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite `LENGTH('literal')` to the length of the literal.

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Length):
        return expr

    arg = expr.this
    if isinstance(arg, exp.Literal) and arg.is_string:
        return exp.Literal.number(len(arg.this))

    return expr


def rewrite_division(expr: exp.Expression) -> exp.Expression:
    """
    Rewrite division expressions to fold constants and remove redundant
    divisions. Examples:

    - `x / 1` to `x`
    - `0 / x` to `0`
    - `x / x` to `1`
    - `4 / 2` to `2`

    Args:
        `expr`: The expression to rewrite.

    Returns:
        The rewritten expression.
    """
    if not isinstance(expr, exp.Div):
        return expr

    numerator = expr.args.get("this")
    denominator = expr.args.get("expression")

    if (
        isinstance(denominator, exp.Literal)
        and denominator.is_number
        and float(denominator.this) == 0.0
    ):
        # Don't rewrite division by zero, as it may be handled differently in
        # different databases
        return expr

    # `x / x` -> `1`
    if numerator == denominator:
        return exp.Literal.number(1)

    # `0 / x` -> `0`
    if (
        isinstance(numerator, exp.Literal)
        and numerator.is_number
        and float(numerator.this) == 0.0
    ):
        return exp.Literal.number(0)

    # `x / 1` -> `x`
    if (
        isinstance(denominator, exp.Literal)
        and denominator.is_number
        and float(denominator.this) == 1.0
    ):
        return numerator

    # Attempt to fold constants for cases like `4 / 2` -> `2`
    if (
        isinstance(numerator, exp.Literal)
        and numerator.is_int
        and isinstance(denominator, exp.Literal)
        and denominator.is_int
    ):
        num_term: int = numerator.this
        denom_term: int = denominator.this
        if denom_term != 0 and num_term % denom_term == 0:
            return exp.Literal.number(num_term // denom_term)

    return expr
