ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        language_version: python3.12
        args: [ --fix, --exit-non-zero-on-fix]
      - id: ruff-format
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
      - id: mypy
        args: [--check-untyped-defs, --ignore-missing-imports]
        additional_dependencies: [types-pytz]
  - repo: https://github.com/aio-libs/sort-all
    rev: 'v1.3.0'
    hooks:
      - id: sort-all
