FROM mcr.microsoft.com/devcontainers/universal:2

COPY /demos/setup_tpch.sh setup_tpch.sh

# TODO: Move the DB download into the dockerfile so it can be cached.
# RUN ./setup_tpch.sh /workspaces/tpch.db
