SELECT
  SBCUSTSTATE AS state,
  COUNT(DISTINCT SBCUSTCITY) AS a1,
  COUNT(*) AS a2,
  COUNT(CASE WHEN LOWER(SBCUSTNAME) LIKE 'j%' THEN SBCUSTNAME ELSE NULL END) AS a3,
  COALESCE(SUM(TRUNC(CAST(SBCUSTPOSTALCODE AS DOUBLE PRECISION), 0)), 0) AS a4,
  MIN(SBCUSTPHONE) AS a5,
  MAX(SBCUSTPHONE) AS a6,
  ANY_VALUE(LOWER(SBCUSTSTATE)) AS a7,
  ANY_VALUE(LOWER(SBCUSTSTATE)) AS a8,
  ANY_VALUE(LOWER(SBCUSTSTATE)) AS a9
FROM MAIN.SBCUSTOMER
GROUP BY
  SBCUSTSTATE
ORDER BY
  1 NULLS FIRST
