WITH _T0 AS (
  SELECT
    LENGTH(CASE WHEN sbtickerexchange <> 'NYSE Arca' THEN sbtickerexchange ELSE NULL END) AS AUG_EXCHANGE,
    COUNT(*) AS COUNT_ONE
  FROM MAIN.SBTICKER
  GROUP BY
    1
)
SELECT
  AUG_EXCHANGE AS aug_exchange,
  COUNT_ONE AS su1,
  COUNT_ONE * 2 AS su2,
  COUNT_ONE * -1 AS su3,
  COUNT_ONE * -3 AS su4,
  0 AS su5,
  COUNT_ONE * 0.5 AS su6,
  0 AS su7,
  COALESCE(AUG_EXCHANGE, 0) AS su8,
  COUNT_ONE AS co1,
  COUNT_ONE AS co2,
  COUNT_ONE AS co3,
  COUNT_ONE AS co4,
  COUNT_ONE AS co5,
  COUNT_ONE AS co6,
  0 AS co7,
  COUNT_ONE * IFF(NOT AUG_EXCHANGE IS NULL, 1, 0) AS co8,
  1 AS nd1,
  1 AS nd2,
  1 AS nd3,
  1 AS nd4,
  1 AS nd5,
  1 AS nd6,
  0 AS nd7,
  CAST(NOT AUG_EXCHANGE IS NULL AS BIGINT) AS nd8,
  1 AS av1,
  2 AS av2,
  -1 AS av3,
  -3 AS av4,
  0 AS av5,
  0.5 AS av6,
  NULL AS av7,
  AUG_EXCHANGE AS av8,
  1 AS mi1,
  2 AS mi2,
  -1 AS mi3,
  -3 AS mi4,
  0 AS mi5,
  0.5 AS mi6,
  NULL AS mi7,
  AUG_EXCHANGE AS mi8,
  1 AS ma1,
  2 AS ma2,
  -1 AS ma3,
  -3 AS ma4,
  0 AS ma5,
  0.5 AS ma6,
  NULL AS ma7,
  AUG_EXCHANGE AS ma8,
  1 AS an1,
  2 AS an2,
  -1 AS an3,
  -3 AS an4,
  0 AS an5,
  0.5 AS an6,
  NULL AS an7,
  AUG_EXCHANGE AS an8,
  1 AS me1,
  2 AS me2,
  -1 AS me3,
  -3 AS me4,
  0 AS me5,
  0.5 AS me6,
  NULL AS me7,
  AUG_EXCHANGE AS me8,
  1 AS qu1,
  2 AS qu2,
  -1 AS qu3,
  -3 AS qu4,
  0 AS qu5,
  0.5 AS qu6,
  NULL AS qu7,
  AUG_EXCHANGE AS qu8
FROM _T0
ORDER BY
  1 NULLS FIRST
