WITH "_S1" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    o_custkey
), "_T2" AS (
  SELECT
    CUSTOMER.c_acctbal AS C_ACCTBAL,
    CUSTOMER.c_nationkey AS C_NATIONKEY,
    "_S1".N_ROWS,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CUSTOMER.c_acctbal DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(CUSTOMER.c_acctbal) OVER (PARTITION BY CUSTOMER.c_nationkey) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CUSTOMER.c_acctbal
      ELSE NULL
    END AS EXPR_17,
    CASE
      WHEN FLOOR(0.2 * COUNT(CUSTOMER.c_acctbal) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CUSTOMER.c_acctbal DESC NULLS LAST)
      THEN CUSTOMER.c_acctbal
      ELSE NULL
    END AS EXPR_18
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN "_S1" "_S1"
    ON CUSTOMER.c_custkey = "_S1".O_CUSTKEY
), "_T1" AS (
  SELECT
    ANY_VALUE(C_ACCTBAL) AS ANYTHING_C_ACCTBAL,
    AVG(C_ACCTBAL) AS AVG_C_ACCTBAL,
    AVG(EXPR_17) AS AVG_EXPR_17,
    COUNT(C_ACCTBAL) AS COUNT_C_ACCTBAL,
    MAX(C_ACCTBAL) AS MAX_C_ACCTBAL,
    MAX(EXPR_18) AS MAX_EXPR_18,
    MIN(C_ACCTBAL) AS MIN_C_ACCTBAL,
    COUNT(DISTINCT C_ACCTBAL) AS NDISTINCT_C_ACCTBAL,
    STDDEV_POP(C_ACCTBAL) AS POPULATION_STD_C_ACCTBAL,
    VARIANCE_POP(C_ACCTBAL) AS POPULATION_VAR_C_ACCTBAL,
    STDDEV(C_ACCTBAL) AS SAMPLE_STD_C_ACCTBAL,
    VARIANCE(C_ACCTBAL) AS SAMPLE_VAR_C_ACCTBAL,
    SUM(C_ACCTBAL) AS SUM_C_ACCTBAL,
    SUM(N_ROWS) AS SUM_N_ROWS
  FROM "_T2"
  GROUP BY
    C_NATIONKEY
)
SELECT
  COALESCE(SUM_C_ACCTBAL, 0) AS sum_value,
  AVG_C_ACCTBAL AS avg_value,
  AVG_EXPR_17 AS median_value,
  MIN_C_ACCTBAL AS min_value,
  MAX_C_ACCTBAL AS max_value,
  MAX_EXPR_18 AS quantile_value,
  ANYTHING_C_ACCTBAL AS anything_value,
  COUNT_C_ACCTBAL AS count_value,
  NDISTINCT_C_ACCTBAL AS count_distinct_value,
  SAMPLE_VAR_C_ACCTBAL AS variance_s_value,
  POPULATION_VAR_C_ACCTBAL AS variance_p_value,
  SAMPLE_STD_C_ACCTBAL AS stddev_s_value,
  POPULATION_STD_C_ACCTBAL AS stddev_p_value
FROM "_T1"
WHERE
  SUM_N_ROWS = 0 OR SUM_N_ROWS IS NULL
