WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
  GROUP BY
    o_custkey
), _T1 AS (
  SELECT
    PERCENTILE_DISC(0.8) WITHIN GROUP (ORDER BY
      CUSTOMER.c_acctbal) AS AGG_7,
    ANY_VALUE(CUSTOMER.c_acctbal) AS ANYTHING_C_ACCTBAL,
    AVG(CUSTOMER.c_acctbal) AS AVG_C_ACCTBAL,
    COUNT(CUSTOMER.c_acctbal) AS COUNT_C_ACCTBAL,
    MAX(CUSTOMER.c_acctbal) AS MAX_C_ACCTBAL,
    MEDIAN(CUSTOMER.c_acctbal) AS MEDIAN_C_ACCTBAL,
    MIN(CUSTOMER.c_acctbal) AS MIN_C_ACCTBAL,
    COUNT(DISTINCT CUSTOMER.c_acctbal) AS NDISTINCT_C_ACCTBAL,
    STDDEV(CUSTOMER.c_acctbal) AS SAMPLE_STD_C_ACCTBAL,
    VARIANCE(CUSTOMER.c_acctbal) AS SAMPLE_VARIANCE_C_ACCTBAL,
    SUM(CUSTOMER.c_acctbal) AS SUM_C_ACCTBAL,
    SUM(_S1.N_ROWS) AS SUM_N_ROWS,
    CUSTOMER.c_nationkey AS C_NATIONKEY
  FROM TPCH.CUSTOMER AS CUSTOMER
  LEFT JOIN _S1 AS _S1
    ON CUSTOMER.c_custkey = _S1.O_CUSTKEY
  GROUP BY
    CUSTOMER.c_nationkey
)
SELECT
  COALESCE(_T1.SUM_C_ACCTBAL, 0) AS sum_value,
  _T1.AVG_C_ACCTBAL AS avg_value,
  _T1.MEDIAN_C_ACCTBAL AS median_value,
  _T1.MIN_C_ACCTBAL AS min_value,
  _T1.MAX_C_ACCTBAL AS max_value,
  _T1.AGG_7 AS quantile_value,
  _T1.ANYTHING_C_ACCTBAL AS anything_value,
  _T1.COUNT_C_ACCTBAL AS count_value,
  _T1.NDISTINCT_C_ACCTBAL AS count_distinct_value,
  _T1.SAMPLE_VARIANCE_C_ACCTBAL AS variance_value,
  _T1.SAMPLE_STD_C_ACCTBAL AS stddev_value
FROM TPCH.NATION AS NATION
JOIN _T1 AS _T1
  ON NATION.n_nationkey = _T1.C_NATIONKEY
  AND (
    _T1.SUM_N_ROWS = 0 OR _T1.SUM_N_ROWS IS NULL
  )
