WITH "_t1" AS (
  SELECT
    S_NAME,
    S_SUPPKEY
  FROM TPCH.SUPPLIER
  WHERE
    S_NAME = 'Supplier#000009450'
), "_s11" AS (
  SELECT
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY,
    SUM(
      LINEITEM.L_EXTENDEDPRICE * (
        1 - LINEITEM.L_DISCOUNT
      ) * (
        1 - LINEITEM.L_TAX
      ) - LINEITEM.L_QUANTITY * PARTSUPP.PS_SUPPLYCOST
    ) AS SUM_REVENUE
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN "_t1" "_t4"
    ON PARTSUPP.PS_SUPPKEY = "_t4".S_SUPPKEY
  JOIN TPCH.PART PART
    ON PART.P_CONTAINER LIKE 'LG%' AND PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) IN (1995, 1996)
    AND LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY
    AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
  GROUP BY
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY
)
SELECT
  PART.P_NAME AS part_name,
  ROUND(COALESCE("_s11".SUM_REVENUE, 0), 2) AS revenue_generated
FROM TPCH.PARTSUPP PARTSUPP
JOIN "_t1" "_t1"
  ON PARTSUPP.PS_SUPPKEY = "_t1".S_SUPPKEY
JOIN TPCH.PART PART
  ON PART.P_CONTAINER LIKE 'LG%' AND PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
LEFT JOIN "_s11" "_s11"
  ON PARTSUPP.PS_PARTKEY = "_s11".PS_PARTKEY
  AND PARTSUPP.PS_SUPPKEY = "_s11".PS_SUPPKEY
ORDER BY
  2 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 8 ROWS ONLY
