WITH "_s6" AS (
  SELECT
    PARTSUPP.PS_PARTKEY,
    SUM(LINEITEM.L_QUANTITY) AS SUM_L_QUANTITY,
    SUM(
      LINEITEM.L_EXTENDEDPRICE * (
        1 - LINEITEM.L_DISCOUNT
      ) * (
        1 - LINEITEM.L_TAX
      ) - LINEITEM.L_QUANTITY * PARTSUPP.PS_SUPPLYCOST
    ) AS SUM_REVENUE
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN TPCH.SUPPLIER SUPPLIER
    ON PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
    AND SUPPLIER.S_NAME = 'Supplier#000000182'
  JOIN TPCH.PART PART
    ON PART.P_CONTAINER LIKE 'MED%' AND PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1994
    AND LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY
    AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
  GROUP BY
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY
)
SELECT
  PART.P_NAME AS part_name,
  ROUND(COALESCE("_s6".SUM_REVENUE, 0) / COALESCE("_s6".SUM_L_QUANTITY, 0), 2) AS revenue_ratio
FROM "_s6" "_s6"
JOIN TPCH.PART PART
  ON PART.P_PARTKEY = "_s6".PS_PARTKEY
ORDER BY
  2 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
