WITH "_s0" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_t2" AS (
  SELECT
    PR_NAME,
    PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_s12" AS (
  SELECT DISTINCT
    TRUNC(CAST(CAST("_s0".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER
  FROM "_s0" "_s0"
  JOIN "_t2" "_t2"
    ON "_s0".CA_DT < TRUNC(ADD_MONTHS(CAST("_t2".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s0".CA_DT >= "_t2".PR_RELEASE
), "_t5" AS (
  SELECT
    PR_ID,
    PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_s9" AS (
  SELECT
    COUNTRIES.CO_ID,
    "_t5".PR_ID
  FROM "_t5" "_t5"
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.CO_NAME = 'CN'
), "_s13" AS (
  SELECT
    TRUNC(CAST(CAST("_s2".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(DISTINCT INCIDENTS.IN_DEVICE_ID) AS NDISTINCT_IN_DEVICE_ID
  FROM "_s0" "_s2"
  JOIN "_t2" "_t4"
    ON "_s2".CA_DT < TRUNC(ADD_MONTHS(CAST("_t4".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s2".CA_DT >= "_t4".PR_RELEASE
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_s2".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN "_s9" "_s9"
    ON INCIDENTS.IN_REPAIR_COUNTRY_ID = "_s9".CO_ID
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID AND DEVICES.DE_PRODUCT_ID = "_s9".PR_ID
  GROUP BY
    TRUNC(CAST(CAST("_s2".CA_DT AS DATE) AS DATE), 'Q')
), "_s21" AS (
  SELECT
    TRUNC(CAST(CAST("_s14".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(*) AS N_ROWS
  FROM "_s0" "_s14"
  JOIN "_t2" "_t8"
    ON "_s14".CA_DT < TRUNC(ADD_MONTHS(CAST("_t8".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s14".CA_DT >= "_t8".PR_RELEASE
  JOIN MAIN.DEVICES DEVICES
    ON "_s14".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  JOIN "_t5" "_t9"
    ON DEVICES.DE_PRODUCT_ID = "_t9".PR_ID
  GROUP BY
    TRUNC(CAST(CAST("_s14".CA_DT AS DATE) AS DATE), 'Q')
)
SELECT
  "_s12".QUARTER AS quarter,
  COALESCE("_s13".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  COALESCE("_s21".N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(COALESCE("_s13".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_s12".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_s21".N_ROWS, 0)) OVER (ORDER BY "_s12".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_s12" "_s12"
LEFT JOIN "_s13" "_s13"
  ON "_s12".QUARTER = "_s13".QUARTER
LEFT JOIN "_s21" "_s21"
  ON "_s12".QUARTER = "_s21".QUARTER
ORDER BY
  1 NULLS FIRST
