WITH "_s2" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_t2" AS (
  SELECT
    PR_NAME,
    PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_t3" AS (
  SELECT
    CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    CO_NAME = 'CN'
), "_s16" AS (
  SELECT DISTINCT
    TRUNC(CAST(CAST("_s2".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER
  FROM "_s2" "_s2"
  JOIN "_t2" "_t2"
    ON "_s2".CA_DT < TRUNC(ADD_MONTHS(CAST("_t2".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s2".CA_DT >= "_t2".PR_RELEASE
  CROSS JOIN "_t3" "_t3"
), "_t7" AS (
  SELECT
    PR_ID,
    PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_s13" AS (
  SELECT
    COUNTRIES.CO_ID,
    "_t7".PR_ID
  FROM "_t7" "_t7"
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.CO_NAME = 'CN'
), "_s17" AS (
  SELECT
    TRUNC(CAST(CAST("_s6".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(DISTINCT INCIDENTS.IN_DEVICE_ID) AS NDISTINCT_IN_DEVICE_ID
  FROM "_s2" "_s6"
  JOIN "_t2" "_t5"
    ON "_s6".CA_DT < TRUNC(ADD_MONTHS(CAST("_t5".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s6".CA_DT >= "_t5".PR_RELEASE
  CROSS JOIN "_t3" "_t6"
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_s6".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN "_s13" "_s13"
    ON INCIDENTS.IN_REPAIR_COUNTRY_ID = "_s13".CO_ID
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID AND DEVICES.DE_PRODUCT_ID = "_s13".PR_ID
  GROUP BY
    TRUNC(CAST(CAST("_s6".CA_DT AS DATE) AS DATE), 'Q')
), "_s29" AS (
  SELECT
    TRUNC(CAST(CAST("_s20".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(*) AS N_ROWS
  FROM "_s2" "_s20"
  JOIN "_t2" "_t10"
    ON "_s20".CA_DT < TRUNC(ADD_MONTHS(CAST("_t10".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s20".CA_DT >= "_t10".PR_RELEASE
  CROSS JOIN "_t3" "_t11"
  JOIN MAIN.DEVICES DEVICES
    ON "_s20".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  JOIN "_t7" "_t12"
    ON DEVICES.DE_PRODUCT_ID = "_t12".PR_ID
  CROSS JOIN "_t3" "_t13"
  GROUP BY
    TRUNC(CAST(CAST("_s20".CA_DT AS DATE) AS DATE), 'Q')
)
SELECT
  "_s16".QUARTER AS quarter,
  COALESCE("_s17".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  COALESCE("_s29".N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(COALESCE("_s17".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_s16".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_s29".N_ROWS, 0)) OVER (ORDER BY "_s16".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_s16" "_s16"
LEFT JOIN "_s17" "_s17"
  ON "_s16".QUARTER = "_s17".QUARTER
LEFT JOIN "_s29" "_s29"
  ON "_s16".QUARTER = "_s29".QUARTER
ORDER BY
  1 NULLS FIRST
