WITH "_S2" AS (
  SELECT
    ca_dt AS CA_DT
  FROM MAIN.CALENDAR
), "_T2" AS (
  SELECT
    pr_name AS PR_NAME,
    pr_release AS PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'RubyCopper-Star'
), "_T3" AS (
  SELECT
    co_name AS CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    co_name = 'CN'
), "_S16" AS (
  SELECT DISTINCT
    TRUNC(CAST(CAST("_S2".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER
  FROM "_S2" "_S2"
  JOIN "_T2" "_T2"
    ON "_S2".CA_DT < TRUNC(ADD_MONTHS(CAST("_T2".PR_RELEASE AS DATE), 24), 'Q')
    AND "_S2".CA_DT >= "_T2".PR_RELEASE
  CROSS JOIN "_T3" "_T3"
), "_T7" AS (
  SELECT
    pr_id AS PR_ID,
    pr_name AS PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'RubyCopper-Star'
), "_S13" AS (
  SELECT
    COUNTRIES.co_id AS CO_ID,
    "_T7".PR_ID
  FROM "_T7" "_T7"
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.co_name = 'CN'
), "_S17" AS (
  SELECT
    TRUNC(CAST(CAST("_S6".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(DISTINCT INCIDENTS.in_device_id) AS NDISTINCT_IN_DEVICE_ID
  FROM "_S2" "_S6"
  JOIN "_T2" "_T5"
    ON "_S6".CA_DT < TRUNC(ADD_MONTHS(CAST("_T5".PR_RELEASE AS DATE), 24), 'Q')
    AND "_S6".CA_DT >= "_T5".PR_RELEASE
  CROSS JOIN "_T3" "_T6"
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_S6".CA_DT = TRUNC(CAST(CAST(INCIDENTS.in_error_report_ts AS DATE) AS DATE), 'DD')
  JOIN "_S13" "_S13"
    ON INCIDENTS.in_repair_country_id = "_S13".CO_ID
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id AND DEVICES.de_product_id = "_S13".PR_ID
  GROUP BY
    TRUNC(CAST(CAST("_S6".CA_DT AS DATE) AS DATE), 'Q')
), "_S29" AS (
  SELECT
    TRUNC(CAST(CAST("_S20".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    COUNT(*) AS N_ROWS
  FROM "_S2" "_S20"
  JOIN "_T2" "_T10"
    ON "_S20".CA_DT < TRUNC(ADD_MONTHS(CAST("_T10".PR_RELEASE AS DATE), 24), 'Q')
    AND "_S20".CA_DT >= "_T10".PR_RELEASE
  CROSS JOIN "_T3" "_T11"
  JOIN MAIN.DEVICES DEVICES
    ON "_S20".CA_DT = TRUNC(CAST(CAST(DEVICES.de_purchase_ts AS DATE) AS DATE), 'DD')
  JOIN "_T7" "_T12"
    ON DEVICES.de_product_id = "_T12".PR_ID
  CROSS JOIN "_T3" "_T13"
  GROUP BY
    TRUNC(CAST(CAST("_S20".CA_DT AS DATE) AS DATE), 'Q')
)
SELECT
  "_S16".QUARTER AS quarter,
  COALESCE("_S17".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  COALESCE("_S29".N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(COALESCE("_S17".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_S16".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_S29".N_ROWS, 0)) OVER (ORDER BY "_S16".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_S16" "_S16"
LEFT JOIN "_S17" "_S17"
  ON "_S16".QUARTER = "_S17".QUARTER
LEFT JOIN "_S29" "_S29"
  ON "_S16".QUARTER = "_S29".QUARTER
ORDER BY
  1 NULLS FIRST
