SELECT
  (
    LINEITEM.L_EXTENDEDPRICE * (
      1 - (
        POWER(LINEITEM.L_DISCOUNT, 2)
      )
    ) + 1.0
  ) / PART.P_RETAILPRICE AS computed_value,
  LINEITEM.L_QUANTITY + LINEITEM.L_EXTENDEDPRICE AS total,
  LINEITEM.L_EXTENDEDPRICE - LINEITEM.L_QUANTITY AS delta,
  LINEITEM.L_QUANTITY * LINEITEM.L_DISCOUNT AS product,
  LINEITEM.L_EXTENDEDPRICE / LINEITEM.L_QUANTITY AS ratio,
  POWER(LINEITEM.L_DISCOUNT, 2) AS exponent
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.PART PART
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
