SELECT
  TBL.IDX AS idx,
  TBL.ARR_F AS arr_f
FROM (VALUES
  (1, SYS.ODCINUMBERLIST(1.1)),
  (2, SYS.ODCINUMBERLIST()),
  (3, SYS.ODCINUMBERLIST(-2.3, 0.0)),
  (
    4,
    SYS.ODCINUMBERLIST(3.14, NULL, NULL, BINARY_DOUBLE_INFINITY, -BINARY_DOUBLE_INFINITY)
  )) AS TBL(IDX, ARR_F)
