SELECT
  TBL.IDX AS idx,
  TBL.ARR_S AS arr_s,
  TBL.ARR_I AS arr_i
FROM (VALUES
  (1, SYS.ODCIVARCHAR2LIST('A'), SYS.ODCINUMBERLIST(10)),
  (2, SYS.ODCIVARCHAR2LIST(), SYS.ODCINUMBERLIST()),
  (3, SYS.ODCIVARCHAR2LIST('B', 'C'), SYS.ODCINUMBERLIST(20, 30)),
  (
    4,
    SYS.ODCIVARCHAR2LIST('D', 'E', NULL, 'F'),
    SYS.ODCINUMBERLIST(40, 50, NULL, 60)
  )) AS TBL(IDX, ARR_S, ARR_I)
