WITH "_s3" AS (
  SELECT
    O_CUSTKEY,
    TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(
      CAST(CAST(LAG(O_ORDERDATE, 1) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS DATE) AS DATE),
      'DD'
    ) AS DAY_DIFF
  FROM TPCH.ORDERS
  WHERE
    O_ORDERPRIORITY = '1-URGENT'
)
SELECT
  ANY_VALUE(CUSTOMER.C_NAME) AS name,
  AVG("_s3".DAY_DIFF) AS avg_diff
FROM TPCH.CUSTOMER CUSTOMER
JOIN TPCH.NATION NATION
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'JAPAN'
JOIN "_s3" "_s3"
  ON CUSTOMER.C_CUSTKEY = "_s3".O_CUSTKEY
GROUP BY
  "_s3".O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
