WITH "_t1" AS (
  SELECT
    CUSTOMER.C_NAME,
    ORDERS.O_CUSTKEY,
    TRUNC(CAST(CAST(ORDERS.O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(
      CAST(CAST(LAG(ORDERS.O_ORDERDATE, 1) OVER (PARTITION BY ORDERS.O_CUSTKEY ORDER BY ORDERS.O_ORDERDATE) AS DATE) AS DATE),
      'DD'
    ) AS DAY_DIFF
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'JAPAN'
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND ORDERS.O_ORDERPRIORITY = '1-URGENT'
)
SELECT
  ANY_VALUE(C_NAME) AS name,
  AVG(DAY_DIFF) AS avg_diff
FROM "_t1"
GROUP BY
  O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
