WITH "_s1" AS (
  SELECT
    C_NATIONKEY,
    SUM(GREATEST(C_ACCTBAL, 0)) AS EXPR_0,
    COUNT(GREATEST(C_ACCTBAL, 0)) AS EXPR_1_0
  FROM TPCH.CUSTOMER
  GROUP BY
    C_NATIONKEY
), "_s3" AS (
  SELECT
    NATION.N_REGIONKEY,
    SUM("_s1".EXPR_0) AS SUM_EXPR,
    SUM("_s1".EXPR_1_0) AS SUM_EXPR_1
  FROM TPCH.NATION NATION
  JOIN "_s1" "_s1"
    ON NATION.N_NATIONKEY = "_s1".C_NATIONKEY
  GROUP BY
    NATION.N_REGIONKEY
)
SELECT
  REGION.R_NAME AS region_name,
  "_s3".SUM_EXPR / "_s3".SUM_EXPR_1 AS avg_bal_without_debt_erasure
FROM TPCH.REGION REGION
JOIN "_s3" "_s3"
  ON REGION.R_REGIONKEY = "_s3".N_REGIONKEY
