WITH "_t0" AS (
  SELECT
    TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(
      CAST(CAST(LAG(O_ORDERDATE, 1) OVER (PARTITION BY O_CLERK ORDER BY O_ORDERDATE) AS DATE) AS DATE),
      'DD'
    ) AS DELTA
  FROM TPCH.ORDERS
  WHERE
    O_ORDERPRIORITY = '1-URGENT'
)
SELECT
  AVG(DELTA) AS avg_delta
FROM "_t0"
