WITH "_S3" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    TRUNC(CAST(CAST(o_orderdate AS DATE) AS DATE), 'DD') - TRUNC(
      CAST(CAST(LAG(o_orderdate, 1) OVER (PARTITION BY o_custkey ORDER BY o_orderdate) AS DATE) AS DATE),
      'DD'
    ) AS DAY_DIFF
  FROM TPCH.ORDERS
  WHERE
    o_orderpriority = '1-URGENT'
)
SELECT
  ANY_VALUE(CUSTOMER.c_name) AS name,
  AVG("_S3".DAY_DIFF) AS avg_diff
FROM TPCH.CUSTOMER CUSTOMER
JOIN TPCH.NATION NATION
  ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'JAPAN'
JOIN "_S3" "_S3"
  ON CUSTOMER.c_custkey = "_S3".O_CUSTKEY
GROUP BY
  "_S3".O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
