WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
), "_t" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    CUSTOMER.C_CUSTKEY,
    "_s1".N_ROWS,
    AVG(CAST(COALESCE("_s1".N_ROWS, 0) AS DOUBLE PRECISION)) OVER (PARTITION BY CUSTOMER.C_NATIONKEY) AS "_w"
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN "_s1" "_s1"
    ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
)
SELECT
  C_CUSTKEY AS cust_key,
  N_ROWS AS n_orders
FROM "_t"
WHERE
  N_ROWS <> 0 AND "_w" > COALESCE(N_ROWS, 0)
ORDER BY
  C_ACCTBAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
