WITH _S1 AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    o_custkey
), _T1 AS (
  SELECT
    CUSTOMER.c_acctbal AS C_ACCTBAL,
    CUSTOMER.c_custkey AS C_CUSTKEY,
    _S1.N_ROWS,
    COUNT(*) OVER (PARTITION BY CUSTOMER.c_nationkey) AS N_CUST
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN _S1 _S1
    ON CUSTOMER.c_custkey = _S1.O_CUSTKEY
)
SELECT
  C_CUSTKEY AS cust_key,
  N_ROWS AS n_orders,
  N_CUST AS n_cust
FROM _T1
WHERE
  N_ROWS <> 0
ORDER BY
  C_ACCTBAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
