WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
), "_t1" AS (
  SELECT
    CUSTOMER.C_CUSTKEY,
    "_s1".N_ROWS
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN "_s1" "_s1"
    ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
  ORDER BY
    CUSTOMER.C_ACCTBAL DESC NULLS LAST,
    COALESCE("_s1".N_ROWS, 0) NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
)
SELECT
  C_CUSTKEY AS cust_key,
  N_ROWS AS n_orders
FROM "_t1"
WHERE
  N_ROWS <> 0
ORDER BY
  1 NULLS FIRST
