WITH "_t2" AS (
  SELECT
    O_CUSTKEY
  FROM TPCH.ORDERS
), "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM "_t2"
  GROUP BY
    O_CUSTKEY
), "_s2" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    CUSTOMER.C_CUSTKEY,
    "_s1".N_ROWS
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN "_s1" "_s1"
    ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
  ORDER BY
    1 DESC NULLS LAST,
    2 DESC NULLS LAST
  FETCH FIRST 10 ROWS ONLY
), "_u_0" AS (
  SELECT
    O_CUSTKEY AS "_u_1"
  FROM "_t2"
  GROUP BY
    O_CUSTKEY
)
SELECT
  "_s2".C_CUSTKEY AS cust_key,
  COALESCE("_s2".N_ROWS, 0) AS n_orders
FROM "_s2" "_s2"
LEFT JOIN "_u_0" "_u_0"
  ON "_s2".C_CUSTKEY = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
ORDER BY
  "_s2".C_ACCTBAL DESC NULLS LAST,
  1 DESC NULLS LAST
