WITH "_T2" AS (
  SELECT
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
), "_S1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM "_T2"
  GROUP BY
    O_CUSTKEY
), "_S2" AS (
  SELECT
    CUSTOMER.c_acctbal AS C_ACCTBAL,
    CUSTOMER.c_custkey AS C_CUSTKEY,
    "_S1".N_ROWS
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN "_S1" "_S1"
    ON CUSTOMER.c_custkey = "_S1".O_CUSTKEY
  ORDER BY
    1 DESC NULLS LAST,
    2 DESC NULLS LAST
  FETCH FIRST 10 ROWS ONLY
)
SELECT
  "_S2".C_CUSTKEY AS cust_key,
  NVL("_S2".N_ROWS, 0) AS n_orders
FROM "_S2" "_S2"
JOIN "_T2" "_S3"
  ON "_S2".C_CUSTKEY = "_S3".O_CUSTKEY
ORDER BY
  "_S2".C_ACCTBAL DESC NULLS LAST,
  1 DESC NULLS LAST
