SELECT
  TO_CHAR(O_ORDERDATE, 'YYYY-MM-DD') AS cast_to_string,
  TO_CHAR(O_TOTALPRICE) AS cast_to_string2,
  TRUNC(CAST(O_TOTALPRICE AS DOUBLE PRECISION), 0) AS cast_to_integer,
  CAST(O_SHIPPRIORITY AS DOUBLE PRECISION) AS cast_to_float
FROM TPCH.ORDERS
