WITH "_s1" AS (
  SELECT DISTINCT
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE
  FROM TPCH.ORDERS
), "_s5" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    SUM(LINEITEM.L_EXTENDEDPRICE) AS SUM_L_EXTENDEDPRICE
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
  GROUP BY
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE))
)
SELECT
  "_s1".YEAR_O_ORDERDATE AS year,
  COALESCE("_s5".SUM_L_EXTENDEDPRICE, 0) AS bug
FROM TPCH.CUSTOMER CUSTOMER
CROSS JOIN "_s1" "_s1"
LEFT JOIN "_s5" "_s5"
  ON "_s1".YEAR_O_ORDERDATE = "_s5".YEAR_O_ORDERDATE
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
