WITH "_S1" AS (
  SELECT DISTINCT
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) AS YEAR_O_ORDERDATE
  FROM TPCH.ORDERS
), "_S5" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) AS YEAR_O_ORDERDATE,
    SUM(LINEITEM.l_extendedprice) AS SUM_L_EXTENDEDPRICE
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey
  GROUP BY
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE))
)
SELECT
  "_S1".YEAR_O_ORDERDATE AS year,
  COALESCE("_S5".SUM_L_EXTENDEDPRICE, 0) AS bug
FROM TPCH.CUSTOMER CUSTOMER
CROSS JOIN "_S1" "_S1"
LEFT JOIN "_S5" "_S5"
  ON "_S1".YEAR_O_ORDERDATE = "_S5".YEAR_O_ORDERDATE
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
