WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
)
SELECT
  CUSTOMER.C_ACCTBAL < 0 AS in_debt,
  "_s1".N_ROWS <= 12 OR "_s1".N_ROWS IS NULL AS at_most_12_orders,
  REGION.R_NAME = 'EUROPE' AS is_european,
  NATION.N_NAME <> 'GERMANY' AS non_german,
  CUSTOMER.C_ACCTBAL > 0 AS non_empty_acct,
  NOT "_s1".N_ROWS IS NULL AND "_s1".N_ROWS >= 5 AS at_least_5_orders,
  REGION.R_NAME = 'ASIA' OR REGION.R_NAME = 'EUROPE' AS is_eurasian,
  CUSTOMER.C_ACCTBAL < 0 AND REGION.R_NAME = 'EUROPE' AS is_european_in_debt
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
JOIN TPCH.NATION NATION
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
