SELECT
  CASE WHEN ANY_VALUE(CUSTOMER.C_ACCTBAL) > 1000 THEN 'High' ELSE 'Low' END AS iff_col,
  ANY_VALUE(CUSTOMER.C_NAME) IN ('Alice', 'Bob', 'Charlie') AS isin_col,
  COALESCE(MIN(ORDERS.O_TOTALPRICE), 0.0) AS default_val,
  NOT MIN(ORDERS.O_TOTALPRICE) IS NULL AS has_acct_bal,
  MIN(ORDERS.O_TOTALPRICE) IS NULL AS no_acct_bal,
  CASE
    WHEN ANY_VALUE(CUSTOMER.C_ACCTBAL) > 0
    THEN ANY_VALUE(CUSTOMER.C_ACCTBAL)
    ELSE NULL
  END AS no_debt_bal
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
WHERE
  CUSTOMER.C_ACCTBAL <= 1000 AND CUSTOMER.C_ACCTBAL >= 100
GROUP BY
  CUSTOMER.C_CUSTKEY
