WITH "_t1" AS (
  SELECT
    CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    NOT CO_NAME LIKE '%C%'
), "_t5" AS (
  SELECT
    PR_NAME,
    PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'AmethystCopper-I'
), "_s5" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_s17" AS (
  SELECT
    "_s9".CA_DT,
    "_t7".CO_NAME,
    COUNT(*) AS N_ROWS
  FROM "_t1" "_t7"
  CROSS JOIN "_t5" "_t8"
  JOIN "_s5" "_s9"
    ON "_s9".CA_DT < ADD_MONTHS(CAST("_t8".PR_RELEASE AS DATE), 24)
    AND "_s9".CA_DT >= "_t8".PR_RELEASE
  JOIN MAIN.DEVICES DEVICES
    ON "_s9".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  JOIN MAIN.PRODUCTS PRODUCTS
    ON DEVICES.DE_PRODUCT_ID = PRODUCTS.PR_ID AND PRODUCTS.PR_NAME = 'AmethystCopper-I'
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.CO_ID = DEVICES.DE_PURCHASE_COUNTRY_ID
    AND COUNTRIES.CO_NAME = "_t7".CO_NAME
  GROUP BY
    "_s9".CA_DT,
    "_t7".CO_NAME
), "_s19" AS (
  SELECT
    TRUNC(CAST("_s5".CA_DT AS DATE), 'YEAR') AS START_OF_YEAR,
    "_t4".CO_NAME,
    SUM("_s17".N_ROWS) AS SUM_N_ROWS
  FROM "_t1" "_t4"
  CROSS JOIN "_t5" "_t5"
  JOIN "_s5" "_s5"
    ON "_s5".CA_DT < ADD_MONTHS(CAST("_t5".PR_RELEASE AS DATE), 24)
    AND "_s5".CA_DT >= "_t5".PR_RELEASE
  LEFT JOIN "_s17" "_s17"
    ON "_s17".CA_DT = "_s5".CA_DT AND "_s17".CO_NAME = "_t4".CO_NAME
  GROUP BY
    TRUNC(CAST("_s5".CA_DT AS DATE), 'YEAR'),
    "_t4".CO_NAME
)
SELECT
  "_t1".CO_NAME AS country_name,
  "_s19".START_OF_YEAR AS start_of_year,
  COALESCE("_s19".SUM_N_ROWS, 0) AS n_purchases
FROM "_t1" "_t1"
JOIN MAIN.PRODUCTS PRODUCTS
  ON PRODUCTS.PR_NAME = 'AmethystCopper-I'
LEFT JOIN "_s19" "_s19"
  ON "_s19".CO_NAME = "_t1".CO_NAME
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
