WITH "_t1" AS (
  SELECT
    CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    NOT CO_NAME LIKE '%C%'
), "_s7" AS (
  SELECT DISTINCT
    TRUNC(CAST(CALENDAR.CA_DT AS DATE), 'YEAR') AS START_OF_YEAR,
    "_t4".CO_NAME
  FROM "_t1" "_t4"
  JOIN MAIN.PRODUCTS PRODUCTS
    ON PRODUCTS.PR_NAME = 'AmethystCopper-I'
  JOIN MAIN.CALENDAR CALENDAR
    ON CALENDAR.CA_DT < ADD_MONTHS(CAST(PRODUCTS.PR_RELEASE AS DATE), 24)
    AND CALENDAR.CA_DT >= PRODUCTS.PR_RELEASE
)
SELECT
  "_t1".CO_NAME AS country_name,
  "_s7".START_OF_YEAR AS start_of_year
FROM "_t1" "_t1"
JOIN MAIN.PRODUCTS PRODUCTS
  ON PRODUCTS.PR_NAME = 'AmethystCopper-I'
LEFT JOIN "_s7" "_s7"
  ON "_s7".CO_NAME = "_t1".CO_NAME
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
