WITH "_T1" AS (
  SELECT
    co_name AS CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    NOT co_name LIKE '%C%'
), "_S7" AS (
  SELECT DISTINCT
    TRUNC(CAST(CALENDAR.ca_dt AS DATE), 'YEAR') AS START_OF_YEAR,
    "_T4".CO_NAME
  FROM "_T1" "_T4"
  JOIN MAIN.PRODUCTS PRODUCTS
    ON PRODUCTS.pr_name = 'AmethystCopper-I'
  JOIN MAIN.CALENDAR CALENDAR
    ON CALENDAR.ca_dt < ADD_MONTHS(CAST(PRODUCTS.pr_release AS DATE), 24)
    AND CALENDAR.ca_dt >= PRODUCTS.pr_release
)
SELECT
  "_T1".CO_NAME AS country_name,
  "_S7".START_OF_YEAR AS start_of_year
FROM "_T1" "_T1"
JOIN MAIN.PRODUCTS PRODUCTS
  ON PRODUCTS.pr_name = 'AmethystCopper-I'
LEFT JOIN "_S7" "_S7"
  ON "_S7".CO_NAME = "_T1".CO_NAME
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
