SELECT
  SBTRANSACTION.sbtxdatetime AS date_time,
  COUNT(*) OVER (PARTITION BY TRUNC(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP), 'DAY') ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS txn_within_day,
  COUNT(
    CASE WHEN SBTRANSACTION.sbtxtype = 'buy' THEN SBTRANSACTION.sbtxtype ELSE NULL END
  ) OVER (PARTITION BY TRUNC(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP), 'DAY') ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS n_buys_within_day,
  ROUND(
    (
      100.0 * SUM(SBTICKER.sbtickersymbol IN ('AAPL', 'AMZN')) OVER (ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    ) / COUNT(*) OVER (ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS pct_apple_txns,
  SUM(
    CASE
      WHEN SBTRANSACTION.sbtxtype = 'buy'
      THEN SBTRANSACTION.sbtxshares
      ELSE 0 - SBTRANSACTION.sbtxshares
    END
  ) OVER (ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS share_change,
  ROUND(
    AVG(CAST(SBTRANSACTION.sbtxamount AS DOUBLE PRECISION)) OVER (ORDER BY SBTRANSACTION.sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS rolling_avg_amount
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBTICKER SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
WHERE
  EXTRACT(MONTH FROM CAST(SBTRANSACTION.sbtxdatetime AS DATE)) = 4
  AND EXTRACT(YEAR FROM CAST(SBTRANSACTION.sbtxdatetime AS DATE)) = 2023
  AND SBTRANSACTION.sbtxstatus = 'success'
ORDER BY
  1 NULLS FIRST
