SELECT
  SBTRANSACTION.SBTXDATETIME AS date_time,
  COUNT(*) OVER (
    PARTITION BY TRUNC(CAST(CAST(SBTRANSACTION.SBTXDATETIME AS DATE) AS DATE), 'DD')
    ORDER BY SBTRANSACTION.SBTXDATETIME
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS txn_within_day,
  COUNT(
    CASE WHEN SBTRANSACTION.SBTXTYPE = 'buy' THEN SBTRANSACTION.SBTXTYPE ELSE NULL END
  ) OVER (
    PARTITION BY TRUNC(CAST(CAST(SBTRANSACTION.SBTXDATETIME AS DATE) AS DATE), 'DD')
    ORDER BY SBTRANSACTION.SBTXDATETIME
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS n_buys_within_day,
  ROUND(
    (
      100.0 * SUM(SBTICKER.SBTICKERSYMBOL IN ('AAPL', 'AMZN')) OVER (
        ORDER BY SBTRANSACTION.SBTXDATETIME
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
      )
    ) / COUNT(*) OVER (
      ORDER BY SBTRANSACTION.SBTXDATETIME
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ),
    2
  ) AS pct_apple_txns,
  SUM(
    CASE
      WHEN SBTRANSACTION.SBTXTYPE = 'buy'
      THEN SBTRANSACTION.SBTXSHARES
      ELSE (
        -1
      ) * SBTRANSACTION.SBTXSHARES
    END
  ) OVER (
    ORDER BY SBTRANSACTION.SBTXDATETIME
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS share_change,
  ROUND(
    AVG(CAST(SBTRANSACTION.SBTXAMOUNT AS DOUBLE PRECISION)) OVER (
      ORDER BY SBTRANSACTION.SBTXDATETIME
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ),
    2
  ) AS rolling_avg_amount
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBTICKER SBTICKER
  ON SBTICKER.SBTICKERID = SBTRANSACTION.SBTXTICKERID
WHERE
  EXTRACT(MONTH FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE)) = 4
  AND EXTRACT(YEAR FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE)) = 2023
  AND SBTRANSACTION.SBTXSTATUS = 'success'
ORDER BY
  1 NULLS FIRST
