WITH "_t" AS (
  SELECT
    O_CUSTKEY,
    O_TOTALPRICE,
    ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE DESC, O_ORDERKEY) AS "_w"
  FROM TPCH.ORDERS
), "_s1" AS (
  SELECT
    O_CUSTKEY,
    SUM(O_TOTALPRICE) AS SUM_O_TOTALPRICE
  FROM "_t"
  WHERE
    "_w" <= 5
  GROUP BY
    O_CUSTKEY
)
SELECT
  CUSTOMER.C_NAME AS name,
  COALESCE("_s1".SUM_O_TOTALPRICE, 0) AS total_recent_value
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
