WITH "_s1" AS (
  SELECT
    L_DISCOUNT,
    L_EXTENDEDPRICE,
    L_ORDERKEY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(L_SHIPDATE AS DATE)) = 1994 AND L_SHIPMODE = 'AIR'
), "_t5" AS (
  SELECT
    ANY_VALUE(ORDERS.O_CUSTKEY) AS ANYTHING_O_CUSTKEY,
    ANY_VALUE(ORDERS.O_ORDERDATE) AS ANYTHING_O_ORDERDATE,
    SUM("_s1".L_EXTENDEDPRICE * (
      1 - "_s1".L_DISCOUNT
    )) AS SUM_R
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_s1" "_s1"
    ON ORDERS.O_ORDERKEY = "_s1".L_ORDERKEY
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1994
  GROUP BY
    ORDERS.O_ORDERKEY
), "_t" AS (
  SELECT
    ANYTHING_O_CUSTKEY,
    ANYTHING_O_ORDERDATE,
    SUM_R,
    LAG(COALESCE(SUM_R, 0), 1) OVER (PARTITION BY ANYTHING_O_CUSTKEY ORDER BY ANYTHING_O_ORDERDATE) AS "_w"
  FROM "_t5"
), "_s3" AS (
  SELECT
    ANYTHING_O_CUSTKEY,
    COALESCE(SUM_R, 0) - LAG(COALESCE(SUM_R, 0), 1) OVER (PARTITION BY ANYTHING_O_CUSTKEY ORDER BY ANYTHING_O_ORDERDATE) AS REVENUE_DELTA
  FROM "_t"
  WHERE
    NOT "_w" IS NULL
)
SELECT
  ANY_VALUE(CUSTOMER.C_NAME) AS name,
  CASE
    WHEN ABS(MIN("_s3".REVENUE_DELTA)) > MAX("_s3".REVENUE_DELTA)
    THEN MIN("_s3".REVENUE_DELTA)
    ELSE MAX("_s3".REVENUE_DELTA)
  END AS largest_diff
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_s3" "_s3"
  ON CUSTOMER.C_CUSTKEY = "_s3".ANYTHING_O_CUSTKEY
WHERE
  CUSTOMER.C_MKTSEGMENT = 'AUTOMOBILE'
GROUP BY
  "_s3".ANYTHING_O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
