WITH _S1 AS (
  SELECT
    l_discount AS L_DISCOUNT,
    l_extendedprice AS L_EXTENDEDPRICE,
    l_orderkey AS L_ORDERKEY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(l_shipdate AS DATETIME)) = 1994 AND l_shipmode = 'AIR'
), _T5 AS (
  SELECT
    ANY_VALUE(ORDERS.o_custkey) AS ANYTHING_O_CUSTKEY,
    ANY_VALUE(ORDERS.o_orderdate) AS ANYTHING_O_ORDERDATE,
    SUM(_S1.L_EXTENDEDPRICE * (
      1 - _S1.L_DISCOUNT
    )) AS SUM_R
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN _S1 _S1
    ON ORDERS.o_orderkey = _S1.L_ORDERKEY
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1994
  GROUP BY
    ORDERS.o_orderkey
), _T AS (
  SELECT
    ANYTHING_O_CUSTKEY,
    ANYTHING_O_ORDERDATE,
    SUM_R,
    LAG(NVL(SUM_R, 0), 1) OVER (PARTITION BY ANYTHING_O_CUSTKEY ORDER BY ANYTHING_O_ORDERDATE) AS _W
  FROM _T5
), _T1 AS (
  SELECT
    _T.ANYTHING_O_CUSTKEY,
    CUSTOMER.c_name AS C_NAME,
    NVL(_T.SUM_R, 0) - LAG(NVL(_T.SUM_R, 0), 1) OVER (PARTITION BY _T.ANYTHING_O_CUSTKEY ORDER BY _T.ANYTHING_O_ORDERDATE) AS REVENUE_DELTA
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN _T _T
    ON CUSTOMER.c_custkey = _T.ANYTHING_O_CUSTKEY AND NOT _T._W IS NULL
  WHERE
    CUSTOMER.c_mktsegment = 'AUTOMOBILE'
)
SELECT
  ANY_VALUE(C_NAME) AS name,
  CASE
    WHEN ABS(MIN(REVENUE_DELTA)) > MAX(REVENUE_DELTA)
    THEN MIN(REVENUE_DELTA)
    ELSE MAX(REVENUE_DELTA)
  END AS largest_diff
FROM _T1
GROUP BY
  ANYTHING_O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
