WITH "_S1" AS (
  SELECT
    l_discount AS L_DISCOUNT,
    l_extendedprice AS L_EXTENDEDPRICE,
    l_orderkey AS L_ORDERKEY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(l_shipdate AS DATE)) = 1994 AND l_shipmode = 'AIR'
), "_T5" AS (
  SELECT
    ANY_VALUE(ORDERS.o_custkey) AS ANYTHING_O_CUSTKEY,
    ANY_VALUE(ORDERS.o_orderdate) AS ANYTHING_O_ORDERDATE,
    SUM("_S1".L_EXTENDEDPRICE * (
      1 - "_S1".L_DISCOUNT
    )) AS SUM_R
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_S1" "_S1"
    ON ORDERS.o_orderkey = "_S1".L_ORDERKEY
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1994
  GROUP BY
    ORDERS.o_orderkey
), "_T" AS (
  SELECT
    ANYTHING_O_CUSTKEY,
    ANYTHING_O_ORDERDATE,
    SUM_R,
    LAG(COALESCE(SUM_R, 0), 1) OVER (PARTITION BY ANYTHING_O_CUSTKEY ORDER BY ANYTHING_O_ORDERDATE) AS "_W"
  FROM "_T5"
), "_S3" AS (
  SELECT
    ANYTHING_O_CUSTKEY,
    COALESCE(SUM_R, 0) - LAG(COALESCE(SUM_R, 0), 1) OVER (PARTITION BY ANYTHING_O_CUSTKEY ORDER BY ANYTHING_O_ORDERDATE) AS REVENUE_DELTA
  FROM "_T"
  WHERE
    NOT "_W" IS NULL
)
SELECT
  ANY_VALUE(CUSTOMER.c_name) AS name,
  CASE
    WHEN ABS(MIN("_S3".REVENUE_DELTA)) > MAX("_S3".REVENUE_DELTA)
    THEN MIN("_S3".REVENUE_DELTA)
    ELSE MAX("_S3".REVENUE_DELTA)
  END AS largest_diff
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_S3" "_S3"
  ON CUSTOMER.c_custkey = "_S3".ANYTHING_O_CUSTKEY
WHERE
  CUSTOMER.c_mktsegment = 'AUTOMOBILE'
GROUP BY
  "_S3".ANYTHING_O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
