WITH "_t" AS (
  SELECT
    ORDERS.O_CUSTKEY,
    ORDERS.O_ORDERKEY,
    ORDERS.O_ORDERPRIORITY,
    ORDERS.O_TOTALPRICE,
    PRIORITY_TAXES.TAX_RATE,
    ROW_NUMBER() OVER (
      PARTITION BY ORDERS.O_ORDERKEY
      ORDER BY ORDERS.O_TOTALPRICE + (
        ORDERS.O_TOTALPRICE * PRIORITY_TAXES.TAX_RATE
      )
    ) AS "_w"
  FROM TPCH.ORDERS ORDERS
  JOIN (VALUES
    ('1-URGENT', 0.05),
    ('2-HIGH', 0.04),
    ('3-MEDIUM', 0.03),
    ('4-NOT SPECIFIED', 0.02)) AS PRIORITY_TAXES(PRIORITY_LVL, TAX_RATE)
    ON ORDERS.O_ORDERPRIORITY = PRIORITY_TAXES.PRIORITY_LVL
)
SELECT
  CUSTOMER.C_NAME AS name,
  "_t".O_ORDERKEY AS order_key,
  "_t".O_ORDERPRIORITY AS order_priority,
  "_t".O_TOTALPRICE + "_t".O_TOTALPRICE * "_t".TAX_RATE AS cheapest_order_price
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_t" "_t"
  ON CUSTOMER.C_CUSTKEY = "_t".O_CUSTKEY AND "_t"."_w" = 1
ORDER BY
  4 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
