SELECT
  PART.P_NAME AS name,
  DISCOUNTS.SHIPPING_TYPE AS shipping_type,
  LINEITEM.L_EXTENDEDPRICE AS extended_price,
  LINEITEM.L_DISCOUNT + DISCOUNTS.ADDED_DISCOUNT AS added_discount,
  LINEITEM.L_EXTENDEDPRICE * (
    1 - (
      LINEITEM.L_DISCOUNT + DISCOUNTS.ADDED_DISCOUNT
    )
  ) AS final_price
FROM (VALUES
  ('REG AIR', 0.05),
  ('SHIP', 0.06),
  ('TRUCK', 0.05)) AS DISCOUNTS(SHIPPING_TYPE, ADDED_DISCOUNT)
JOIN TPCH.LINEITEM LINEITEM
  ON DISCOUNTS.SHIPPING_TYPE = LINEITEM.L_SHIPMODE
JOIN TPCH.PART PART
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
ORDER BY
  5 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
