WITH "_s1" AS (
  SELECT
    S_ACCTBAL,
    S_NATIONKEY
  FROM TPCH.SUPPLIER
), "_s2" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
), "_s3" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s5" AS (
  SELECT
    "_s2".N_NATIONKEY,
    "_s3".R_NAME
  FROM "_s2" "_s2"
  JOIN "_s3" "_s3"
    ON "_s2".N_REGIONKEY = "_s3".R_REGIONKEY
), "_s12" AS (
  SELECT DISTINCT
    "_s5".R_NAME
  FROM (VALUES
    ('AFRICA', 5000.32),
    ('AMERICA', 8000.0),
    ('ASIA', 4600.32),
    ('EUROPE', 6400.5),
    ('MIDDLE EAST', 8999.99)) AS THRESHOLDS_COLLECTION(REGION_NAME, MIN_ACCOUNT_BALANCE)
  JOIN "_s1" "_s1"
    ON THRESHOLDS_COLLECTION.MIN_ACCOUNT_BALANCE < "_s1".S_ACCTBAL
  JOIN "_s5" "_s5"
    ON THRESHOLDS_COLLECTION.REGION_NAME = "_s5".R_NAME
    AND "_s1".S_NATIONKEY = "_s5".N_NATIONKEY
), "_s11" AS (
  SELECT
    "_s8".N_NATIONKEY,
    "_s9".R_NAME
  FROM "_s2" "_s8"
  JOIN "_s3" "_s9"
    ON "_s8".N_REGIONKEY = "_s9".R_REGIONKEY
), "_s13" AS (
  SELECT
    "_s11".R_NAME,
    COUNT(*) AS N_ROWS
  FROM (VALUES
    ('AFRICA', 5000.32),
    ('AMERICA', 8000.0),
    ('ASIA', 4600.32),
    ('EUROPE', 6400.5),
    ('MIDDLE EAST', 8999.99)) AS THRESHOLDS_COLLECTION_2(REGION_NAME, MIN_ACCOUNT_BALANCE)
  JOIN "_s1" "_s7"
    ON THRESHOLDS_COLLECTION_2.MIN_ACCOUNT_BALANCE < "_s7".S_ACCTBAL
  JOIN "_s11" "_s11"
    ON THRESHOLDS_COLLECTION_2.REGION_NAME = "_s11".R_NAME
    AND "_s11".N_NATIONKEY = "_s7".S_NATIONKEY
  GROUP BY
    "_s11".R_NAME
)
SELECT
  "_s12".R_NAME AS sup_region_name,
  "_s13".N_ROWS AS n_suppliers
FROM "_s12" "_s12"
JOIN "_s13" "_s13"
  ON "_s12".R_NAME = "_s13".R_NAME
