WITH "_t" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    CUSTOMER.C_CUSTKEY,
    CUSTOMER.C_MKTSEGMENT,
    CUSTOMER.C_NAME,
    CUSTOMERS_FILTERS.MRK_SEGMENT,
    NATION.N_NAME,
    CUSTOMERS_FILTERS.NATION_NAME,
    NTILE(1000) OVER (ORDER BY CUSTOMER.C_ACCTBAL) AS "_w"
  FROM (VALUES
    ('UNITED STATES', 'BUILDING'),
    ('JAPAN', 'AUTOMOBILE'),
    ('BRAZIL', 'MACHINERY')) AS CUSTOMERS_FILTERS(NATION_NAME, MRK_SEGMENT)
  CROSS JOIN TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
), "_s6" AS (
  SELECT
    "_t".C_CUSTKEY AS O_CUSTKEY,
    ANY_VALUE("_t".C_ACCTBAL) AS ANYTHING_C_ACCTBAL,
    ANY_VALUE("_t".C_NAME) AS ANYTHING_C_NAME,
    ANY_VALUE("_t".NATION_NAME) AS ANYTHING_NATION_NAME,
    COUNT(ORDERS.O_CUSTKEY) AS COUNT_O_CUSTKEY
  FROM "_t" "_t"
  LEFT JOIN TPCH.ORDERS ORDERS
    ON ORDERS.O_CUSTKEY = "_t".C_CUSTKEY
  WHERE
    "_t".C_MKTSEGMENT = "_t".MRK_SEGMENT
    AND "_t".NATION_NAME = "_t".N_NAME
    AND "_t"."_w" > 996
  GROUP BY
    "_t".C_CUSTKEY
), "_t4" AS (
  SELECT
    O_CUSTKEY,
    (
      EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(YEAR FROM CAST(LAG(O_ORDERDATE, 1) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS DATE))
    ) * 12 + (
      EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(MONTH FROM CAST(LAG(O_ORDERDATE, 1) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS DATE))
    ) AS MONTH_DIFF
  FROM TPCH.ORDERS
), "_s7" AS (
  SELECT
    O_CUSTKEY,
    AVG(MONTH_DIFF) AS AVG_MONTH_DIFF
  FROM "_t4"
  GROUP BY
    O_CUSTKEY
), "_t6" AS (
  SELECT
    O_CUSTKEY,
    O_TOTALPRICE - LEAD(O_TOTALPRICE, 1) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS PRICE_DIFF
  FROM TPCH.ORDERS
), "_s9" AS (
  SELECT
    O_CUSTKEY,
    AVG(PRICE_DIFF) AS AVG_PRICE_DIFF
  FROM "_t6"
  GROUP BY
    O_CUSTKEY
)
SELECT
  "_s6".ANYTHING_C_NAME AS name,
  ROW_NUMBER() OVER (PARTITION BY "_s6".ANYTHING_NATION_NAME ORDER BY "_s6".ANYTHING_C_ACCTBAL DESC) AS ranking_balance,
  COALESCE("_s6".COUNT_O_CUSTKEY, 0) AS n_orders,
  "_s7".AVG_MONTH_DIFF AS avg_month_orders,
  "_s9".AVG_PRICE_DIFF AS avg_price_diff,
  "_s6".ANYTHING_C_ACCTBAL / SUM("_s6".ANYTHING_C_ACCTBAL) OVER () AS proportion,
  CASE
    WHEN "_s6".ANYTHING_C_ACCTBAL > AVG(CAST("_s6".ANYTHING_C_ACCTBAL AS DOUBLE PRECISION)) OVER ()
    THEN TRUE
    ELSE FALSE
  END AS above_avg,
  COUNT("_s6".ANYTHING_C_ACCTBAL) OVER (
    ORDER BY "_s6".ANYTHING_C_ACCTBAL
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS n_poorer,
  "_s6".ANYTHING_C_ACCTBAL / COUNT(*) OVER () AS ratio
FROM "_s6" "_s6"
LEFT JOIN "_s7" "_s7"
  ON "_s6".O_CUSTKEY = "_s7".O_CUSTKEY
LEFT JOIN "_s9" "_s9"
  ON "_s6".O_CUSTKEY = "_s9".O_CUSTKEY
ORDER BY
  1 NULLS FIRST
