SELECT
  ALLDATATYPES.STRING_COL AS string_col,
  ALLDATATYPES.INT_COL AS int_col,
  ALLDATATYPES.FLOAT_COL AS float_col,
  ALLDATATYPES.NULLABLE_INT_COL AS nullable_int_col,
  ALLDATATYPES.BOOL_COL AS bool_col,
  ALLDATATYPES.NULL_COL AS null_col,
  ALLDATATYPES.DATETIME_COL AS datetime_col
FROM (VALUES
  (
    'red',
    0,
    1.5,
    1.0,
    1,
    NULL,
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
  ),
  (
    'orange',
    1,
    2.0,
    NULL,
    0,
    NULL,
    TO_TIMESTAMP('2024-01-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
  ),
  (NULL, 2, NULL, 7.0, 0, NULL, NULL)) AS ALLDATATYPES(STRING_COL, INT_COL, FLOAT_COL, NULLABLE_INT_COL, BOOL_COL, NULL_COL, DATETIME_COL)
