WITH "_S1" AS (
  SELECT
    COLUMN2 AS RULE_CATEGORY,
    COLUMN3 AS DISCOUNT
  FROM (VALUES
    (1, 'A', 0.1),
    (2, 'B', 0.15),
    (3, 'C', 0.05)) AS PRICING_COLLECTION(RULE_ID, RULE_CATEGORY, DISCOUNT)
)
SELECT
  COLUMN2 AS product_category,
  AVG(COLUMN3) AS avg_price,
  COUNT(*) AS n_products,
  MIN("_S1".DISCOUNT) AS min_discount
FROM (VALUES
  (1, 'A', 17.99),
  (2, 'B', 45.65),
  (3, 'A', 15.0),
  (4, 'B', 10.99)) AS PRODUCTS_COLLECTION(PRODUCT_ID, PRODUCT_CATEGORY, PRICE)
JOIN "_S1" "_S1"
  ON COLUMN2 = "_S1".RULE_CATEGORY
GROUP BY
  COLUMN2
