WITH "_T" AS (
  SELECT
    CUSTOMER.c_acctbal AS C_ACCTBAL,
    CUSTOMER.c_custkey AS C_CUSTKEY,
    CUSTOMER.c_mktsegment AS C_MKTSEGMENT,
    CUSTOMER.c_name AS C_NAME,
    COLUMN2 AS MRK_SEGMENT,
    NATION.n_name AS N_NAME,
    COLUMN1 AS NATION_NAME,
    NTILE(1000) OVER (ORDER BY CUSTOMER.c_acctbal) AS "_W"
  FROM (VALUES
    ('UNITED STATES', 'BUILDING'),
    ('JAPAN', 'AUTOMOBILE'),
    ('BRAZIL', 'MACHINERY')) AS CUSTOMERS_FILTERS(NATION_NAME, MRK_SEGMENT)
  CROSS JOIN TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
), "_S6" AS (
  SELECT
    "_T".C_CUSTKEY,
    ANY_VALUE("_T".C_ACCTBAL) AS ANYTHING_C_ACCTBAL,
    ANY_VALUE("_T".C_NAME) AS ANYTHING_C_NAME,
    ANY_VALUE("_T".NATION_NAME) AS ANYTHING_NATION_NAME,
    COUNT(ORDERS.o_custkey) AS COUNT_O_CUSTKEY
  FROM "_T" "_T"
  LEFT JOIN TPCH.ORDERS ORDERS
    ON ORDERS.o_custkey = "_T".C_CUSTKEY
  WHERE
    "_T".C_MKTSEGMENT = "_T".MRK_SEGMENT
    AND "_T".NATION_NAME = "_T".N_NAME
    AND "_T"."_W" > 996
  GROUP BY
    "_T".C_CUSTKEY
), "_T4" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    (
      EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) - EXTRACT(YEAR FROM CAST(LAG(o_orderdate, 1) OVER (PARTITION BY o_custkey ORDER BY o_orderdate) AS DATE))
    ) * 12 + (
      EXTRACT(MONTH FROM CAST(o_orderdate AS DATE)) - EXTRACT(MONTH FROM CAST(LAG(o_orderdate, 1) OVER (PARTITION BY o_custkey ORDER BY o_orderdate) AS DATE))
    ) AS MONTH_DIFF
  FROM TPCH.ORDERS
), "_S7" AS (
  SELECT
    O_CUSTKEY,
    AVG(MONTH_DIFF) AS AVG_MONTH_DIFF
  FROM "_T4"
  GROUP BY
    O_CUSTKEY
), "_T6" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    o_totalprice - LEAD(o_totalprice, 1) OVER (PARTITION BY o_custkey ORDER BY o_orderdate) AS PRICE_DIFF
  FROM TPCH.ORDERS
), "_S9" AS (
  SELECT
    O_CUSTKEY,
    AVG(PRICE_DIFF) AS AVG_PRICE_DIFF
  FROM "_T6"
  GROUP BY
    O_CUSTKEY
)
SELECT
  "_S6".ANYTHING_C_NAME AS name,
  ROW_NUMBER() OVER (PARTITION BY "_S6".ANYTHING_NATION_NAME ORDER BY "_S6".ANYTHING_C_ACCTBAL DESC) AS ranking_balance,
  COALESCE("_S6".COUNT_O_CUSTKEY, 0) AS n_orders,
  "_S7".AVG_MONTH_DIFF AS avg_month_orders,
  "_S9".AVG_PRICE_DIFF AS avg_price_diff,
  "_S6".ANYTHING_C_ACCTBAL / SUM("_S6".ANYTHING_C_ACCTBAL) OVER () AS proportion,
  CASE
    WHEN "_S6".ANYTHING_C_ACCTBAL > AVG(CAST("_S6".ANYTHING_C_ACCTBAL AS DOUBLE PRECISION)) OVER ()
    THEN TRUE
    ELSE FALSE
  END AS above_avg,
  COUNT("_S6".ANYTHING_C_ACCTBAL) OVER (ORDER BY "_S6".ANYTHING_C_ACCTBAL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS n_poorer,
  "_S6".ANYTHING_C_ACCTBAL / COUNT(*) OVER () AS ratio
FROM "_S6" "_S6"
LEFT JOIN "_S7" "_S7"
  ON "_S6".C_CUSTKEY = "_S7".O_CUSTKEY
LEFT JOIN "_S9" "_S9"
  ON "_S6".C_CUSTKEY = "_S9".O_CUSTKEY
ORDER BY
  1 NULLS FIRST
