SELECT
  DATEADD(DAY, -1, DATEADD(MONTH, 5, DATE_TRUNC('YEAR', CURRENT_TIMESTAMP()))) AS d1,
  DATEADD(HOUR, 24, DATE_TRUNC('MONTH', CURRENT_TIMESTAMP())) AS d2,
  DATEADD(
    SECOND,
    2,
    DATEADD(MINUTE, -150, DATEADD(HOUR, 12, DATE_TRUNC('DAY', CURRENT_TIMESTAMP())))
  ) AS d3
FROM (VALUES
  (NULL)) AS _q_0(_col_0)
