SELECT
  DATE_ADD(DATE_ADD(DATE_TRUNC('YEAR', CURRENT_TIMESTAMP()), 5, 'MONTH'), -1, 'DAY') AS d1,
  DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), 24, 'HOUR') AS d2,
  DATE_ADD(
    DATE_ADD(DATE_ADD(DATE_TRUNC('DAY', CURRENT_TIMESTAMP()), 12, 'HOUR'), -150, 'MINUTE'),
    2,
    'SECOND'
  ) AS d3
FROM (
  SELECT
    *
  FROM (VALUES
    (NULL))
)
