SELECT
  DATE_TRUNC('YEAR', CURRENT_TIMESTAMP) + INTERVAL '5 MONTH' - INTERVAL '1 DAY' AS d1,
  DATE_TRUNC('MONTH', CURRENT_TIMESTAMP) + INTERVAL '24 HOUR' AS d2,
  DATE_TRUNC('DAY', CURRENT_TIMESTAMP) + INTERVAL '12 HOUR' - INTERVAL '150 MINUTE' + INTERVAL '2 SECOND' AS d3
FROM (VALUES
  (NULL)) AS _q_0(_col_0)
