WITH _t0 AS (
  SELECT
    o_orderdate
  FROM tpch.orders
  ORDER BY
    o_custkey NULLS FIRST,
    1 NULLS FIRST
  LIMIT 10
)
SELECT
  DATE_TRUNC('YEAR', CAST(o_orderdate AS TIMESTAMP)) AS d1,
  DATE_TRUNC('MONTH', CAST(o_orderdate AS TIMESTAMP)) AS d2,
  CAST(o_orderdate AS TIMESTAMP) - INTERVAL '11 YEAR' + INTERVAL '9 MONTH' - INTERVAL '7 DAY' + INTERVAL '5 HOUR' - INTERVAL '3 MINUTE' + INTERVAL '1 SECOND' AS d3,
  CAST('2025-07-04 12:00:00' AS TIMESTAMP) AS d4,
  CAST('2025-07-04 12:58:00' AS TIMESTAMP) AS d5,
  CAST('2025-07-26 02:45:25' AS TIMESTAMP) AS d6
FROM _t0
ORDER BY
  o_orderdate NULLS FIRST
