SELECT
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR') + NUMTOYMINTERVAL(5, 'month') + NUMTODSINTERVAL(1, 'day') AS d1,
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTODSINTERVAL(24, 'hour') AS d2,
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DAY') + NUMTODSINTERVAL(12, 'hour') + NUMTODSINTERVAL(150, 'minute') + NUMTODSINTERVAL(2, 'second') AS d3
FROM (VALUES
  (NULL)) AS "_Q_0"("_COL_0")
