SELECT
  DATEADD(DAY, -1, DATEADD(MONTH, 5, TRUNC(CURRENT_TIMESTAMP(), 'YEAR'))) AS d1,
  TRUNC(CURRENT_TIMESTAMP(), 'MONTH') + INTERVAL '24' HOUR AS d2,
  DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) + INTERVAL '12' HOUR - INTERVAL '150' MINUTE + INTERVAL '2' SECOND AS d3
FROM VALUES
  (NULL) AS _q_0(_col_0)
