WITH "_T0" AS (
  SELECT
    o_orderdate AS O_ORDERDATE
  FROM TPCH.ORDERS
  ORDER BY
    o_custkey NULLS FIRST,
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
)
SELECT
  TRUNC(CAST(O_ORDERDATE AS TIMESTAMP), 'YEAR') AS d1,
  TRUNC(CAST(O_ORDERDATE AS TIMESTAMP), 'MONTH') AS d2,
  CAST(O_ORDERDATE AS TIMESTAMP) + NUMTOYMINTERVAL(11, 'year') + NUMTOYMINTERVAL(9, 'month') + NUMTODSINTERVAL(7, 'day') + NUMTODSINTERVAL(5, 'hour') + NUMTODSINTERVAL(3, 'minute') + NUMTODSINTERVAL(1, 'second') AS d3,
  TO_DATE('2025-07-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS') AS d4,
  TO_DATE('2025-07-04 12:58:00', 'YYYY-MM-DD HH24:MI:SS') AS d5,
  TO_DATE('2025-07-26 02:45:25', 'YYYY-MM-DD HH24:MI:SS') AS d6
FROM "_T0"
ORDER BY
  O_ORDERDATE NULLS FIRST
