SELECT
  DATE_SUB(DATE_ADD(TRUNC(CURRENT_TIMESTAMP, 'YEAR'), 5, 'MONTH'), 1, DAY) AS d1,
  DATE_ADD(TRUNC(CURRENT_TIMESTAMP, 'MONTH'), 24, 'HOUR') AS d2,
  DATE_ADD(
    DATE_SUB(DATE_ADD(TRUNC(CURRENT_TIMESTAMP, 'DAY'), 12, 'HOUR'), 150, MINUTE),
    2,
    'SECOND'
  ) AS d3
FROM (VALUES
  (NULL)) AS "_Q_0"("_COL_0")
