WITH "_T0" AS (
  SELECT
    o_orderdate AS O_ORDERDATE
  FROM TPCH.ORDERS
  ORDER BY
    o_custkey NULLS FIRST,
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
)
SELECT
  TRUNC(CAST(O_ORDERDATE AS TIMESTAMP), 'YEAR') AS d1,
  TRUNC(CAST(O_ORDERDATE AS TIMESTAMP), 'MONTH') AS d2,
  DATE_ADD(
    DATE_SUB(
      DATE_ADD(
        DATE_SUB(DATE_ADD(DATE_SUB(CAST(O_ORDERDATE AS TIMESTAMP), 11, YEAR), 9, 'MONTH'), 7, DAY),
        5,
        'HOUR'
      ),
      3,
      MINUTE
    ),
    1,
    'SECOND'
  ) AS d3,
  TIME_STR_TO_TIME('2025-07-04 12:00:00') AS d4,
  TIME_STR_TO_TIME('2025-07-04 12:58:00') AS d5,
  TIME_STR_TO_TIME('2025-07-26 02:45:25') AS d6
FROM "_T0"
ORDER BY
  O_ORDERDATE NULLS FIRST
