WITH _q_0 AS (
  SELECT
    1 AS _
)
SELECT
  DATE_SUB(
    DATE_ADD(
      STR_TO_DATE(CONCAT(YEAR(CURRENT_TIMESTAMP()), ' 1 1'), '%Y %c %e'),
      INTERVAL '5' MONTH
    ),
    INTERVAL '1' DAY
  ) AS d1,
  DATE_ADD(
    CAST(STR_TO_DATE(
      CONCAT(YEAR(CURRENT_TIMESTAMP()), ' ', MONTH(CURRENT_TIMESTAMP()), ' 1'),
      '%Y %c %e'
    ) AS DATETIME),
    INTERVAL '24' HOUR
  ) AS d2,
  DATE_ADD(
    DATE_SUB(
      DATE_ADD(CAST(CAST(CURRENT_TIMESTAMP() AS DATE) AS DATETIME), INTERVAL '12' HOUR),
      INTERVAL '150' MINUTE
    ),
    INTERVAL '2' SECOND
  ) AS d3
FROM _q_0
