SELECT
  TO_DATE('2025-07-04 12:58:45', 'YYYY-MM-DD HH24:MI:SS') AS "_expr0",
  TO_DATE('2024-12-31 11:59:00', 'YYYY-MM-DD HH24:MI:SS') AS "_expr1",
  TO_DATE('2025-01-01', 'YYYY-MM-DD') AS "_expr2",
  TO_DATE('1999-03-14', 'YYYY-MM-DD') AS "_expr3",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr4",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr5",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr6",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr7",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr8",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr9",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr10",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr11",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr12",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr13",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr14",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr15",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr16",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr17",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) AS "_expr18",
  CAST(o_orderdate AS TIMESTAMP) AS "_expr19",
  TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), SECOND) AS "_expr20",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR') + NUMTODSINTERVAL(8, 'minute') + NUMTOYMINTERVAL(141, 'month') AS "_expr21",
  TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), SECOND), HOUR) AS "_expr22",
  TIMESTAMP_TRUNC(
    TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), HOUR), SECOND),
    HOUR
  ) AS "_expr23",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(96, 'hour') + NUMTOYMINTERVAL(15, 'year') AS "_expr24",
  TIMESTAMP_TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR') + NUMTOYMINTERVAL(3, 'year'), MINUTE) + NUMTOYMINTERVAL(65, 'month') AS "_expr25",
  TRUNC(CAST(o_orderdate AS TIMESTAMP) + NUMTODSINTERVAL(56, 'hour'), 'YEAR') AS "_expr26",
  TIMESTAMP_TRUNC(
    TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(63, 'day'), MINUTE),
    SECOND
  ) AS "_expr27",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') AS "_expr28",
  TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(312, 'hour'), SECOND) + NUMTOYMINTERVAL(48, 'year') AS "_expr29",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(75, 'day'), 'DAY') + NUMTODSINTERVAL(600, 'minute') + NUMTODSINTERVAL(294, 'day') AS "_expr30",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTOYMINTERVAL(480, 'month') + NUMTOYMINTERVAL(45, 'year') AS "_expr31",
  TIMESTAMP_TRUNC(
    TRUNC(
      SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(270, 'minute') + NUMTODSINTERVAL(34, 'second'),
      'DAY'
    ),
    SECOND
  ) AS "_expr32",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTODSINTERVAL(213, 'second') AS "_expr33",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTODSINTERVAL(13, 'minute') + NUMTOYMINTERVAL(28, 'year') + NUMTODSINTERVAL(344, 'second') AS "_expr34",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DAY') AS "_expr35",
  TO_DATE('2116-01-01 00:49:00', 'YYYY-MM-DD HH24:MI:SS') AS "_expr36",
  TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR'), 'DAY') AS "_expr37",
  TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DAY'), 'YEAR') AS "_expr38",
  TO_DATE('2025-07-01 00:22:00', 'YYYY-MM-DD HH24:MI:SS') AS "_expr39",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR') AS "_expr40",
  TRUNC(
    CAST(o_orderdate AS TIMESTAMP) + NUMTODSINTERVAL(82, 'second') + NUMTODSINTERVAL(415, 'second') + NUMTODSINTERVAL(160, 'second'),
    'YEAR'
  ) AS "_expr41",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTOYMINTERVAL(192, 'month') AS "_expr42",
  TIMESTAMP_TRUNC(
    TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), HOUR), MINUTE),
    HOUR
  ) + NUMTODSINTERVAL(486, 'minute') AS "_expr43",
  TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), SECOND) + NUMTODSINTERVAL(50, 'hour') AS "_expr44",
  TIMESTAMP_TRUNC(
    SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(297, 'day') + NUMTOYMINTERVAL(72, 'month') + NUMTOYMINTERVAL(92, 'month'),
    HOUR
  ) AS "_expr45",
  TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(285, 'second'), 'DAY') AS "_expr46",
  TO_DATE('1999-05-15', 'YYYY-MM-DD') AS "_expr47",
  TRUNC(
    TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTODSINTERVAL(1, 'hour'),
    'MONTH'
  ) + NUMTODSINTERVAL(21, 'day') AS "_expr48",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(212, 'minute') + NUMTOYMINTERVAL(368, 'year') AS "_expr49",
  TO_DATE('2024-01-01', 'YYYY-MM-DD') AS "_expr50",
  TO_DATE('1999-03-14', 'YYYY-MM-DD') AS "_expr51",
  TIMESTAMP_TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(60, 'hour'), 'DAY'), MINUTE) + NUMTOYMINTERVAL(196, 'year') AS "_expr52",
  TIMESTAMP_TRUNC(
    SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(40, 'hour') + NUMTODSINTERVAL(385, 'day'),
    MINUTE
  ) + NUMTODSINTERVAL(29, 'hour') AS "_expr53",
  TIMESTAMP_TRUNC(
    TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(405, 'day'), HOUR),
    MINUTE
  ) AS "_expr54",
  TIMESTAMP_TRUNC(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YEAR'), SECOND) + NUMTOYMINTERVAL(98, 'year') + NUMTOYMINTERVAL(96, 'month') AS "_expr55",
  TRUNC(
    TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), MINUTE), SECOND),
    'DAY'
  ) + NUMTODSINTERVAL(78, 'second') AS "_expr56",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(136, 'hour') + NUMTODSINTERVAL(104, 'minute') + NUMTOYMINTERVAL(104, 'month') + NUMTODSINTERVAL(312, 'day') AS "_expr57",
  SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTOYMINTERVAL(45, 'month') + NUMTODSINTERVAL(135, 'second') AS "_expr58",
  EXTRACT(YEAR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) AS "_expr59",
  2025 AS "_expr60",
  1999 AS "_expr61",
  EXTRACT(MONTH FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) AS "_expr62",
  6 AS "_expr63",
  3 AS "_expr64",
  EXTRACT(DAY FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) AS "_expr65",
  4 AS "_expr66",
  4 AS "_expr67",
  EXTRACT(HOUR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP)) AS "_expr68",
  0 AS "_expr69",
  0 AS "_expr70",
  EXTRACT(MINUTE FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP)) AS "_expr71",
  30 AS "_expr72",
  0 AS "_expr73",
  EXTRACT(SECOND FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP)) AS "_expr74",
  45 AS "_expr75",
  0 AS "_expr76",
  EXTRACT(YEAR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE)) AS "_expr77",
  EXTRACT(YEAR FROM TO_DATE('2022-11-24', 'YYYY-MM-DD')) - EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) AS "_expr78",
  (
    EXTRACT(YEAR FROM CAST(CAST('1999-03-14' AS TIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM TO_DATE('2005-06-30', 'YYYY-MM-DD'))
  ) * 12 + (
    EXTRACT(MONTH FROM CAST(CAST('1999-03-14' AS TIMESTAMP) AS DATE)) - EXTRACT(MONTH FROM TO_DATE('2005-06-30', 'YYYY-MM-DD'))
  ) AS "_expr79",
  (
    EXTRACT(YEAR FROM TO_DATE('2022-11-24', 'YYYY-MM-DD')) - EXTRACT(YEAR FROM TO_DATE('2006-05-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  ) * 12 + (
    EXTRACT(MONTH FROM TO_DATE('2022-11-24', 'YYYY-MM-DD')) - EXTRACT(MONTH FROM TO_DATE('2006-05-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  ) AS "_expr80",
  CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS "_expr81",
  CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - CAST(CAST('1999-03-14' AS TIMESTAMP) AS DATE) AS "_expr82",
  (
    TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATETIME), 'HH24') - TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATETIME), 'HH24')
  ) * 24 AS "_expr83",
  (
    TRUNC(CAST(CAST(o_orderdate AS DATE) AS DATETIME), 'HH24') - TRUNC(CAST(TO_DATE('2005-06-30', 'YYYY-MM-DD') AS DATETIME), 'HH24')
  ) * 24 AS "_expr84",
  (
    TRUNC(CAST(TO_DATE('2006-05-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS') AS DATETIME), 'MI') - TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATETIME), 'MI')
  ) * 1440 AS "_expr85",
  (
    TRUNC(CAST(TO_DATE('2021-01-01 07:35:00', 'YYYY-MM-DD HH24:MI:SS') AS DATETIME), 'MI') - TRUNC(CAST(CAST(o_orderdate AS DATE) AS DATETIME), 'MI')
  ) * 1440 AS "_expr86",
  (
    TO_DATE('2021-01-01 07:35:00', 'YYYY-MM-DD HH24:MI:SS') - TO_DATE('2022-11-24', 'YYYY-MM-DD')
  ) * 86400 AS "_expr87",
  (
    CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE) - TO_DATE('2005-06-30', 'YYYY-MM-DD')
  ) * 86400 AS "_expr88",
  EXTRACT(YEAR FROM TO_DATE('2006-05-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS')) - EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) AS "_expr89",
  EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) - EXTRACT(YEAR FROM CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE)) AS "_expr90",
  (
    EXTRACT(YEAR FROM TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS')) - EXTRACT(YEAR FROM CAST(o_orderdate AS DATE))
  ) * 12 + (
    EXTRACT(MONTH FROM TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS')) - EXTRACT(MONTH FROM CAST(o_orderdate AS DATE))
  ) AS "_expr91",
  (
    EXTRACT(YEAR FROM CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS'))
  ) * 12 + (
    EXTRACT(MONTH FROM CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE)) - EXTRACT(MONTH FROM TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS'))
  ) AS "_expr92",
  CAST(o_orderdate AS DATE) - CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS "_expr93",
  CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS') AS "_expr94",
  (
    TRUNC(CAST(CAST(CAST('1999-03-14' AS TIMESTAMP) AS DATE) AS DATETIME), 'HH24') - TRUNC(CAST(TO_DATE('2022-11-24', 'YYYY-MM-DD') AS DATETIME), 'HH24')
  ) * 24 AS "_expr95",
  (
    TRUNC(CAST(TO_DATE('2020-12-31 00:31:06', 'YYYY-MM-DD HH24:MI:SS') AS DATETIME), 'HH24') - TRUNC(CAST(CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE) AS DATETIME), 'HH24')
  ) * 24 AS "_expr96",
  (
    TRUNC(CAST(TO_DATE('2020-12-31 00:31:06', 'YYYY-MM-DD HH24:MI:SS') AS DATETIME), 'MI') - TRUNC(CAST(TO_DATE('2005-06-30', 'YYYY-MM-DD') AS DATETIME), 'MI')
  ) * 1440 AS "_expr97",
  (
    TRUNC(CAST(CAST(CAST('2018-02-14 12:41:06' AS TIMESTAMP) AS DATE) AS DATETIME), 'MI') - TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATETIME), 'MI')
  ) * 1440 AS "_expr98",
  (
    CAST(CAST('1999-03-14' AS TIMESTAMP) AS DATE) - CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)
  ) * 86400 AS "_expr99",
  (
    TO_DATE('2019-07-04 11:30:00', 'YYYY-MM-DD HH24:MI:SS') - TO_DATE('2022-11-24', 'YYYY-MM-DD')
  ) * 86400 AS "_expr100"
FROM TPCH.ORDERS
