SELECT
  DATE_ADD(DATE_ADD(MONTH, 5, TRUNC(CURRENT_TIMESTAMP(), 'YEAR')), -1) AS d1,
  TRUNC(CURRENT_TIMESTAMP(), 'MONTH') + INTERVAL '24' HOUR AS d2,
  DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) + INTERVAL '12' HOUR - INTERVAL '150' MINUTE + INTERVAL '2' SECOND AS d3
FROM VALUES
  (NULL) AS _0(_col_0)
