SELECT
  DATE_ADD('DAY', -1, DATE_ADD('MONTH', 5, DATE_TRUNC('YEAR', CURRENT_TIMESTAMP))) AS d1,
  DATE_ADD('HOUR', 24, DATE_TRUNC('MONTH', CURRENT_TIMESTAMP)) AS d2,
  DATE_ADD(
    'SECOND',
    2,
    DATE_ADD('MINUTE', -150, DATE_ADD('HOUR', 12, DATE_TRUNC('DAY', CURRENT_TIMESTAMP)))
  ) AS d3
FROM (VALUES
  (NULL)) AS _q_0(_col_0)
