SELECT
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS ts_now_1,
  DATE_TRUNC('DAY', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS ts_now_2,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS ts_now_3,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '1' HOUR AS ts_now_4,
  CAST('2025-01-01' AS DATE) AS ts_now_5,
  CAST('1995-10-08' AS DATE) AS ts_now_6,
  EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)) AS year_col,
  2020 AS year_py,
  1995 AS year_pd,
  EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) AS month_col,
  2 AS month_str,
  1 AS month_dt,
  EXTRACT(DAY FROM CAST(o_orderdate AS TIMESTAMP)) AS day_col,
  25 AS day_str,
  23 AS hour_str,
  59 AS minute_str,
  59 AS second_ts,
  DATE_DIFF('DAY', CAST(o_orderdate AS TIMESTAMP), CAST('1992-01-01' AS TIMESTAMP)) AS dd_col_str,
  DATE_DIFF('DAY', CAST('1992-01-01' AS TIMESTAMP), CAST(o_orderdate AS TIMESTAMP)) AS dd_str_col,
  DATE_DIFF('MONTH', CAST('1995-10-10 00:00:00' AS TIMESTAMP), CAST(o_orderdate AS TIMESTAMP)) AS dd_pd_col,
  DATE_DIFF('YEAR', CAST(o_orderdate AS TIMESTAMP), CAST('1992-01-01 12:30:45' AS TIMESTAMP)) AS dd_col_dt,
  CAST(DATE_DIFF(
    'DAY',
    CAST(CAST('1992-01-01' AS TIMESTAMP) AS DATE) - CAST(DAYOFWEEK(CAST('1992-01-01' AS TIMESTAMP)) AS INT),
    CAST(CAST('1992-01-01 12:30:45' AS TIMESTAMP) AS DATE) - CAST(DAYOFWEEK(CAST('1992-01-01 12:30:45' AS TIMESTAMP)) AS INT)
  ) / 7 AS BIGINT) AS dd_dt_str,
  DAYOFWEEK(o_orderdate) AS dow_col,
  3 AS dow_str1,
  4 AS dow_str2,
  5 AS dow_str3,
  6 AS dow_str4,
  0 AS dow_str5,
  1 AS dow_str6,
  2 AS dow_str7,
  3 AS dow_dt,
  2 AS dow_pd,
  CASE
    WHEN DAYOFWEEK(o_orderdate) = 0
    THEN 'Sunday'
    WHEN DAYOFWEEK(o_orderdate) = 1
    THEN 'Monday'
    WHEN DAYOFWEEK(o_orderdate) = 2
    THEN 'Tuesday'
    WHEN DAYOFWEEK(o_orderdate) = 3
    THEN 'Wednesday'
    WHEN DAYOFWEEK(o_orderdate) = 4
    THEN 'Thursday'
    WHEN DAYOFWEEK(o_orderdate) = 5
    THEN 'Friday'
    WHEN DAYOFWEEK(o_orderdate) = 6
    THEN 'Saturday'
  END AS dayname_col,
  'Monday' AS dayname_str1,
  'Tuesday' AS dayname_str2,
  'Wednesday' AS dayname_str3,
  'Thursday' AS dayname_str4,
  'Friday' AS dayname_str5,
  'Saturday' AS dayname_str6,
  'Sunday' AS dayname_dt,
  CASE
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_col,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-03-27' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_str1,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-27' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_str2,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-06-27' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_str3,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-27' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_str4,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1999-12-31' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_str5,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1993-08-15 00:00:00' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS monthname_dt
FROM tpch.orders
