SELECT
  CAST('2025-07-04 12:58:45' AS TIMESTAMP) AS _expr0,
  CAST('2024-12-31 11:59:00' AS TIMESTAMP) AS _expr1,
  CAST('2025-01-01' AS DATE) AS _expr2,
  CAST('1999-03-14' AS DATE) AS _expr3,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr4,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr5,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr6,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr7,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr8,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr9,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr10,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr11,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr12,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr13,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr14,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr15,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr16,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr17,
  CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ) AS _expr18,
  CAST(o_orderdate AS TIMESTAMP) AS _expr19,
  DATE_TRUNC('SECOND', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr20,
  DATEADD(
    MONTH,
    -141,
    DATEADD(
      MINUTE,
      8,
      DATE_TRUNC('YEAR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr21,
  DATE_TRUNC(
    'HOUR',
    DATE_TRUNC(
      'SECOND',
      DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr22,
  DATE_TRUNC(
    'HOUR',
    DATE_TRUNC(
      'SECOND',
      DATE_TRUNC('HOUR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr23,
  DATEADD(
    YEAR,
    15,
    DATEADD(HOUR, -96, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr24,
  DATEADD(
    MONTH,
    65,
    DATE_TRUNC(
      'MINUTE',
      DATEADD(
        YEAR,
        -3,
        DATE_TRUNC('YEAR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr25,
  DATE_TRUNC('YEAR', DATEADD(HOUR, -56, CAST(o_orderdate AS TIMESTAMP))) AS _expr26,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC(
      'MINUTE',
      DATEADD(DAY, -63, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr27,
  DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr28,
  DATEADD(
    YEAR,
    48,
    DATE_TRUNC(
      'SECOND',
      DATEADD(HOUR, -312, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr29,
  DATEADD(
    DAY,
    -294,
    DATEADD(
      MINUTE,
      600,
      DATE_TRUNC(
        'DAY',
        DATEADD(DAY, 75, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr30,
  DATEADD(
    YEAR,
    -45,
    DATEADD(
      MONTH,
      480,
      DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr31,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC(
      'DAY',
      DATEADD(
        SECOND,
        -34,
        DATEADD(MINUTE, -270, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr32,
  DATEADD(
    SECOND,
    213,
    DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr33,
  DATEADD(
    SECOND,
    344,
    DATEADD(
      YEAR,
      28,
      DATEADD(
        MINUTE,
        13,
        DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr34,
  DATE_TRUNC('DAY', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr35,
  CAST('2116-01-01 00:49:00' AS TIMESTAMP) AS _expr36,
  DATE_TRUNC(
    'DAY',
    DATE_TRUNC('YEAR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr37,
  DATE_TRUNC(
    'YEAR',
    DATE_TRUNC('DAY', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr38,
  CAST('2025-07-01 00:22:00' AS TIMESTAMP) AS _expr39,
  DATE_TRUNC('YEAR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr40,
  DATE_TRUNC(
    'YEAR',
    DATEADD(
      SECOND,
      -160,
      DATEADD(SECOND, 415, DATEADD(SECOND, 82, CAST(o_orderdate AS TIMESTAMP)))
    )
  ) AS _expr41,
  DATEADD(MONTH, 192, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr42,
  DATEADD(
    MINUTE,
    486,
    DATE_TRUNC(
      'HOUR',
      DATE_TRUNC(
        'MINUTE',
        DATE_TRUNC('HOUR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr43,
  DATEADD(
    HOUR,
    -50,
    DATE_TRUNC('SECOND', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr44,
  DATE_TRUNC(
    'HOUR',
    DATEADD(
      MONTH,
      -92,
      DATEADD(
        MONTH,
        72,
        DATEADD(DAY, 297, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr45,
  DATE_TRUNC(
    'DAY',
    DATEADD(SECOND, 285, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr46,
  CAST('1999-05-15' AS DATE) AS _expr47,
  DATEADD(
    DAY,
    -21,
    DATE_TRUNC(
      'MONTH',
      DATEADD(
        HOUR,
        1,
        DATE_TRUNC('MONTH', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr48,
  DATEADD(
    YEAR,
    368,
    DATEADD(MINUTE, 212, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr49,
  CAST('2024-01-01' AS DATE) AS _expr50,
  CAST('1999-03-14' AS DATE) AS _expr51,
  DATEADD(
    YEAR,
    196,
    DATE_TRUNC(
      'MINUTE',
      DATE_TRUNC(
        'DAY',
        DATEADD(HOUR, -60, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr52,
  DATEADD(
    HOUR,
    29,
    DATE_TRUNC(
      'MINUTE',
      DATEADD(
        DAY,
        -385,
        DATEADD(HOUR, -40, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr53,
  DATE_TRUNC(
    'MINUTE',
    DATE_TRUNC(
      'HOUR',
      DATEADD(DAY, 405, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
    )
  ) AS _expr54,
  DATEADD(
    MONTH,
    96,
    DATEADD(
      YEAR,
      98,
      DATE_TRUNC(
        'SECOND',
        DATE_TRUNC('YEAR', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr55,
  DATEADD(
    SECOND,
    78,
    DATE_TRUNC(
      'DAY',
      DATE_TRUNC(
        'SECOND',
        DATE_TRUNC('MINUTE', CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr56,
  DATEADD(
    DAY,
    312,
    DATEADD(
      MONTH,
      -104,
      DATEADD(
        MINUTE,
        104,
        DATEADD(HOUR, 136, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
      )
    )
  ) AS _expr57,
  DATEADD(
    SECOND,
    -135,
    DATEADD(MONTH, 45, CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ))
  ) AS _expr58,
  YEAR(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr59,
  2025 AS _expr60,
  1999 AS _expr61,
  MONTH(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr62,
  6 AS _expr63,
  3 AS _expr64,
  DAY(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr65,
  4 AS _expr66,
  4 AS _expr67,
  HOUR(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr68,
  0 AS _expr69,
  0 AS _expr70,
  MINUTE(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr71,
  30 AS _expr72,
  0 AS _expr73,
  SECOND(CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)) AS _expr74,
  45 AS _expr75,
  0 AS _expr76,
  DATEDIFF(
    YEAR,
    CAST('2018-02-14 12:41:06' AS TIMESTAMP),
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)
  ) AS _expr77,
  DATEDIFF(YEAR, CAST(o_orderdate AS DATETIME), CAST('2022-11-24' AS DATE)) AS _expr78,
  DATEDIFF(MONTH, CAST('2005-06-30' AS DATE), CAST('1999-03-14' AS TIMESTAMP)) AS _expr79,
  DATEDIFF(MONTH, CAST('2006-05-01 12:00:00' AS TIMESTAMP), CAST('2022-11-24' AS DATE)) AS _expr80,
  DATEDIFF(
    DAY,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)
  ) AS _expr81,
  DATEDIFF(
    DAY,
    CAST('1999-03-14' AS TIMESTAMP),
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)
  ) AS _expr82,
  DATEDIFF(
    HOUR,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)
  ) AS _expr83,
  DATEDIFF(HOUR, CAST('2005-06-30' AS DATE), CAST(o_orderdate AS DATETIME)) AS _expr84,
  DATEDIFF(
    MINUTE,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST('2006-05-01 12:00:00' AS TIMESTAMP)
  ) AS _expr85,
  DATEDIFF(MINUTE, CAST(o_orderdate AS DATETIME), CAST('2021-01-01 07:35:00' AS TIMESTAMP)) AS _expr86,
  DATEDIFF(SECOND, CAST('2022-11-24' AS DATE), CAST('2021-01-01 07:35:00' AS TIMESTAMP)) AS _expr87,
  DATEDIFF(SECOND, CAST('2005-06-30' AS DATE), CAST('2018-02-14 12:41:06' AS TIMESTAMP)) AS _expr88,
  DATEDIFF(YEAR, CAST(o_orderdate AS DATETIME), CAST('2006-05-01 12:00:00' AS TIMESTAMP)) AS _expr89,
  DATEDIFF(YEAR, CAST('2018-02-14 12:41:06' AS TIMESTAMP), CAST(o_orderdate AS DATETIME)) AS _expr90,
  DATEDIFF(MONTH, CAST(o_orderdate AS DATETIME), CAST('2019-07-04 11:30:00' AS TIMESTAMP)) AS _expr91,
  DATEDIFF(
    MONTH,
    CAST('2019-07-04 11:30:00' AS TIMESTAMP),
    CAST('2018-02-14 12:41:06' AS TIMESTAMP)
  ) AS _expr92,
  DATEDIFF(
    DAY,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST(o_orderdate AS DATETIME)
  ) AS _expr93,
  DATEDIFF(
    DAY,
    CAST('2019-07-04 11:30:00' AS TIMESTAMP),
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ)
  ) AS _expr94,
  DATEDIFF(HOUR, CAST('2022-11-24' AS DATE), CAST('1999-03-14' AS TIMESTAMP)) AS _expr95,
  DATEDIFF(
    HOUR,
    CAST('2018-02-14 12:41:06' AS TIMESTAMP),
    CAST('2020-12-31 00:31:06' AS TIMESTAMP)
  ) AS _expr96,
  DATEDIFF(MINUTE, CAST('2005-06-30' AS DATE), CAST('2020-12-31 00:31:06' AS TIMESTAMP)) AS _expr97,
  DATEDIFF(
    MINUTE,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST('2018-02-14 12:41:06' AS TIMESTAMP)
  ) AS _expr98,
  DATEDIFF(
    SECOND,
    CAST(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS TIMESTAMPNTZ),
    CAST('1999-03-14' AS TIMESTAMP)
  ) AS _expr99,
  DATEDIFF(SECOND, CAST('2022-11-24' AS DATE), CAST('2019-07-04 11:30:00' AS TIMESTAMP)) AS _expr100
FROM tpch.orders
