SELECT
  CAST('2025-07-04 12:58:45' AS TIMESTAMP) AS _expr0,
  CAST('2024-12-31 11:59:00' AS TIMESTAMP) AS _expr1,
  CAST('2025-01-01' AS DATE) AS _expr2,
  CAST('1999-03-14' AS DATE) AS _expr3,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr4,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr5,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr6,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr7,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr8,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr9,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr10,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr11,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr12,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr13,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr14,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr15,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr16,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr17,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS _expr18,
  CAST(o_orderdate AS TIMESTAMP) AS _expr19,
  DATE_TRUNC('SECOND', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr20,
  DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '8' MINUTE - INTERVAL '141' MONTH AS _expr21,
  DATE_TRUNC(
    'HOUR',
    DATE_TRUNC(
      'SECOND',
      DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))
    )
  ) AS _expr22,
  DATE_TRUNC(
    'HOUR',
    DATE_TRUNC(
      'SECOND',
      DATE_TRUNC('HOUR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))
    )
  ) AS _expr23,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '96' HOUR + INTERVAL '15' YEAR AS _expr24,
  DATE_TRUNC(
    'MINUTE',
    DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) - INTERVAL '3' YEAR
  ) + INTERVAL '65' MONTH AS _expr25,
  DATE_TRUNC('YEAR', CAST(o_orderdate AS TIMESTAMP) - INTERVAL '56' HOUR) AS _expr26,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC(
      'MINUTE',
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '63' DAY
    )
  ) AS _expr27,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr28,
  DATE_TRUNC(
    'SECOND',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '312' HOUR
  ) + INTERVAL '48' YEAR AS _expr29,
  DATE_TRUNC('DAY', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '75' DAY) + INTERVAL '600' MINUTE - INTERVAL '294' DAY AS _expr30,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '480' MONTH - INTERVAL '45' YEAR AS _expr31,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC(
      'DAY',
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '270' MINUTE - INTERVAL '34' SECOND
    )
  ) AS _expr32,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '213' SECOND AS _expr33,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '13' MINUTE + INTERVAL '28' YEAR + INTERVAL '344' SECOND AS _expr34,
  DATE_TRUNC('DAY', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr35,
  CAST('2116-01-01 00:49:00' AS TIMESTAMP) AS _expr36,
  DATE_TRUNC('DAY', DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))) AS _expr37,
  DATE_TRUNC('YEAR', DATE_TRUNC('DAY', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))) AS _expr38,
  CAST('2025-07-01 00:22:00' AS TIMESTAMP) AS _expr39,
  DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr40,
  DATE_TRUNC(
    'YEAR',
    CAST(o_orderdate AS TIMESTAMP) + INTERVAL '82' SECOND + INTERVAL '415' SECOND - INTERVAL '160' SECOND
  ) AS _expr41,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '192' MONTH AS _expr42,
  DATE_TRUNC(
    'HOUR',
    DATE_TRUNC(
      'MINUTE',
      DATE_TRUNC('HOUR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))
    )
  ) + INTERVAL '486' MINUTE AS _expr43,
  DATE_TRUNC('SECOND', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) - INTERVAL '50' HOUR AS _expr44,
  DATE_TRUNC(
    'HOUR',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '297' DAY + INTERVAL '72' MONTH - INTERVAL '92' MONTH
  ) AS _expr45,
  DATE_TRUNC(
    'DAY',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '285' SECOND
  ) AS _expr46,
  CAST('1999-05-15' AS DATE) AS _expr47,
  DATE_TRUNC(
    'MONTH',
    DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '1' HOUR
  ) - INTERVAL '21' DAY AS _expr48,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '212' MINUTE + INTERVAL '368' YEAR AS _expr49,
  CAST('2024-01-01' AS DATE) AS _expr50,
  CAST('1999-03-14' AS DATE) AS _expr51,
  DATE_TRUNC(
    'MINUTE',
    DATE_TRUNC(
      'DAY',
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '60' HOUR
    )
  ) + INTERVAL '196' YEAR AS _expr52,
  DATE_TRUNC(
    'MINUTE',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) - INTERVAL '40' HOUR - INTERVAL '385' DAY
  ) + INTERVAL '29' HOUR AS _expr53,
  DATE_TRUNC(
    'MINUTE',
    DATE_TRUNC(
      'HOUR',
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '405' DAY
    )
  ) AS _expr54,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))
  ) + INTERVAL '98' YEAR + INTERVAL '96' MONTH AS _expr55,
  DATE_TRUNC(
    'DAY',
    DATE_TRUNC(
      'SECOND',
      DATE_TRUNC('MINUTE', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP))
    )
  ) + INTERVAL '78' SECOND AS _expr56,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '136' HOUR + INTERVAL '104' MINUTE - INTERVAL '104' MONTH + INTERVAL '312' DAY AS _expr57,
  CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) + INTERVAL '45' MONTH - INTERVAL '135' SECOND AS _expr58,
  EXTRACT(YEAR FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr59,
  2025 AS _expr60,
  1999 AS _expr61,
  EXTRACT(MONTH FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr62,
  6 AS _expr63,
  3 AS _expr64,
  EXTRACT(DAY FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr65,
  4 AS _expr66,
  4 AS _expr67,
  EXTRACT(HOUR FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr68,
  0 AS _expr69,
  0 AS _expr70,
  EXTRACT(MINUTE FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr71,
  30 AS _expr72,
  0 AS _expr73,
  EXTRACT(SECOND FROM CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) AS _expr74,
  45 AS _expr75,
  0 AS _expr76,
  DATE_DIFF(
    'YEAR',
    CAST('2018-02-14 12:41:06' AS TIMESTAMP),
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)
  ) AS _expr77,
  DATE_DIFF('YEAR', CAST(o_orderdate AS TIMESTAMP), CAST('2022-11-24' AS DATE)) AS _expr78,
  DATE_DIFF('MONTH', CAST('2005-06-30' AS DATE), CAST('1999-03-14' AS TIMESTAMP)) AS _expr79,
  DATE_DIFF('MONTH', CAST('2006-05-01 12:00:00' AS TIMESTAMP), CAST('2022-11-24' AS DATE)) AS _expr80,
  DATE_DIFF(
    'DAY',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)
  ) AS _expr81,
  DATE_DIFF(
    'DAY',
    CAST('1999-03-14' AS TIMESTAMP),
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)
  ) AS _expr82,
  DATE_DIFF(
    'HOUR',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)
  ) AS _expr83,
  DATE_DIFF('HOUR', CAST('2005-06-30' AS DATE), CAST(o_orderdate AS TIMESTAMP)) AS _expr84,
  DATE_DIFF(
    'MINUTE',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST('2006-05-01 12:00:00' AS TIMESTAMP)
  ) AS _expr85,
  DATE_DIFF('MINUTE', CAST(o_orderdate AS TIMESTAMP), CAST('2021-01-01 07:35:00' AS TIMESTAMP)) AS _expr86,
  DATE_DIFF('SECOND', CAST('2022-11-24' AS DATE), CAST('2021-01-01 07:35:00' AS TIMESTAMP)) AS _expr87,
  DATE_DIFF('SECOND', CAST('2005-06-30' AS DATE), CAST('2018-02-14 12:41:06' AS TIMESTAMP)) AS _expr88,
  DATE_DIFF('YEAR', CAST(o_orderdate AS TIMESTAMP), CAST('2006-05-01 12:00:00' AS TIMESTAMP)) AS _expr89,
  DATE_DIFF('YEAR', CAST('2018-02-14 12:41:06' AS TIMESTAMP), CAST(o_orderdate AS TIMESTAMP)) AS _expr90,
  DATE_DIFF('MONTH', CAST(o_orderdate AS TIMESTAMP), CAST('2019-07-04 11:30:00' AS TIMESTAMP)) AS _expr91,
  DATE_DIFF(
    'MONTH',
    CAST('2019-07-04 11:30:00' AS TIMESTAMP),
    CAST('2018-02-14 12:41:06' AS TIMESTAMP)
  ) AS _expr92,
  DATE_DIFF(
    'DAY',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST(o_orderdate AS TIMESTAMP)
  ) AS _expr93,
  DATE_DIFF(
    'DAY',
    CAST('2019-07-04 11:30:00' AS TIMESTAMP),
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)
  ) AS _expr94,
  DATE_DIFF('HOUR', CAST('2022-11-24' AS DATE), CAST('1999-03-14' AS TIMESTAMP)) AS _expr95,
  DATE_DIFF(
    'HOUR',
    CAST('2018-02-14 12:41:06' AS TIMESTAMP),
    CAST('2020-12-31 00:31:06' AS TIMESTAMP)
  ) AS _expr96,
  DATE_DIFF('MINUTE', CAST('2005-06-30' AS DATE), CAST('2020-12-31 00:31:06' AS TIMESTAMP)) AS _expr97,
  DATE_DIFF(
    'MINUTE',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST('2018-02-14 12:41:06' AS TIMESTAMP)
  ) AS _expr98,
  DATE_DIFF(
    'SECOND',
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP),
    CAST('1999-03-14' AS TIMESTAMP)
  ) AS _expr99,
  DATE_DIFF('SECOND', CAST('2022-11-24' AS DATE), CAST('2019-07-04 11:30:00' AS TIMESTAMP)) AS _expr100
FROM tpch.orders
