SELECT
  DATETIME('2025-07-04 12:58:45') AS _expr0,
  DATETIME('2024-12-31 11:59:00') AS _expr1,
  DATETIME('2025-01-01') AS _expr2,
  DATETIME('1999-03-14') AS _expr3,
  CURRENT_TIMESTAMP() AS _expr4,
  CURRENT_TIMESTAMP() AS _expr5,
  CURRENT_TIMESTAMP() AS _expr6,
  CURRENT_TIMESTAMP() AS _expr7,
  CURRENT_TIMESTAMP() AS _expr8,
  CURRENT_TIMESTAMP() AS _expr9,
  CURRENT_TIMESTAMP() AS _expr10,
  CURRENT_TIMESTAMP() AS _expr11,
  CURRENT_TIMESTAMP() AS _expr12,
  CURRENT_TIMESTAMP() AS _expr13,
  CURRENT_TIMESTAMP() AS _expr14,
  CURRENT_TIMESTAMP() AS _expr15,
  CURRENT_TIMESTAMP() AS _expr16,
  CURRENT_TIMESTAMP() AS _expr17,
  CURRENT_TIMESTAMP() AS _expr18,
  DATETIME(order_date) AS _expr19,
  DATE_TRUNC('SECOND', CURRENT_TIMESTAMP()) AS _expr20,
  DATE_ADD(DATE_ADD(DATE_TRUNC('YEAR', CURRENT_TIMESTAMP()), 8, 'MINUTE'), -141, 'MONTH') AS _expr21,
  DATE_TRUNC('HOUR', DATE_TRUNC('SECOND', DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()))) AS _expr22,
  DATE_TRUNC('HOUR', DATE_TRUNC('SECOND', DATE_TRUNC('HOUR', CURRENT_TIMESTAMP()))) AS _expr23,
  DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), -96, 'HOUR'), 15, 'YEAR') AS _expr24,
  DATE_ADD(
    DATE_TRUNC('MINUTE', DATE_ADD(DATE_TRUNC('YEAR', CURRENT_TIMESTAMP()), -3, 'YEAR')),
    65,
    'MONTH'
  ) AS _expr25,
  DATE_TRUNC('YEAR', DATE_ADD(DATETIME(order_date), -56, 'HOUR')) AS _expr26,
  DATE_TRUNC('SECOND', DATE_TRUNC('MINUTE', DATE_ADD(CURRENT_TIMESTAMP(), -63, 'DAY'))) AS _expr27,
  DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()) AS _expr28,
  DATE_ADD(DATE_TRUNC('SECOND', DATE_ADD(CURRENT_TIMESTAMP(), -312, 'HOUR')), 48, 'YEAR') AS _expr29,
  DATE_ADD(
    DATE_ADD(DATE_TRUNC('DAY', DATE_ADD(CURRENT_TIMESTAMP(), 75, 'DAY')), 600, 'MINUTE'),
    -294,
    'DAY'
  ) AS _expr30,
  DATE_ADD(DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), 480, 'MONTH'), -45, 'YEAR') AS _expr31,
  DATE_TRUNC(
    'SECOND',
    DATE_TRUNC('DAY', DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), -270, 'MINUTE'), -34, 'SECOND'))
  ) AS _expr32,
  DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), 213, 'SECOND') AS _expr33,
  DATE_ADD(
    DATE_ADD(DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), 13, 'MINUTE'), 28, 'YEAR'),
    344,
    'SECOND'
  ) AS _expr34,
  DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) AS _expr35,
  DATE_ADD(DATE_ADD(DATE_TRUNC('HOUR', DATETIME('2025-01-01')), 49, 'MINUTE'), 91, 'YEAR') AS _expr36,
  DATE_TRUNC('DAY', DATE_TRUNC('YEAR', CURRENT_TIMESTAMP())) AS _expr37,
  DATE_TRUNC('YEAR', DATE_TRUNC('DAY', CURRENT_TIMESTAMP())) AS _expr38,
  DATE_ADD(DATE_TRUNC('MONTH', DATETIME('2025-07-04 12:58:45')), 22, 'MINUTE') AS _expr39,
  DATE_TRUNC('YEAR', CURRENT_TIMESTAMP()) AS _expr40,
  DATE_TRUNC(
    'YEAR',
    DATE_ADD(
      DATE_ADD(DATE_ADD(DATETIME(order_date), 82, 'SECOND'), 415, 'SECOND'),
      -160,
      'SECOND'
    )
  ) AS _expr41,
  DATE_ADD(CURRENT_TIMESTAMP(), 192, 'MONTH') AS _expr42,
  DATE_ADD(
    DATE_TRUNC('HOUR', DATE_TRUNC('MINUTE', DATE_TRUNC('HOUR', CURRENT_TIMESTAMP()))),
    486,
    'MINUTE'
  ) AS _expr43,
  DATE_ADD(DATE_TRUNC('SECOND', CURRENT_TIMESTAMP()), -50, 'HOUR') AS _expr44,
  DATE_TRUNC(
    'HOUR',
    DATE_ADD(DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), 297, 'DAY'), 72, 'MONTH'), -92, 'MONTH')
  ) AS _expr45,
  DATE_TRUNC('DAY', DATE_ADD(CURRENT_TIMESTAMP(), 285, 'SECOND')) AS _expr46,
  DATE_ADD(DATETIME('1999-03-14'), 62, 'DAY') AS _expr47,
  DATE_ADD(
    DATE_TRUNC('MONTH', DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), 1, 'HOUR')),
    -21,
    'DAY'
  ) AS _expr48,
  DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), 212, 'MINUTE'), 368, 'YEAR') AS _expr49,
  DATE_TRUNC(
    'MINUTE',
    DATE_TRUNC('MINUTE', DATE_TRUNC('YEAR', DATE_TRUNC('MONTH', DATETIME('2024-12-31 11:59:00'))))
  ) AS _expr50,
  DATE_TRUNC('DAY', DATE_TRUNC('HOUR', DATETIME('1999-03-14'))) AS _expr51,
  DATE_ADD(
    DATE_TRUNC('MINUTE', DATE_TRUNC('DAY', DATE_ADD(CURRENT_TIMESTAMP(), -60, 'HOUR'))),
    196,
    'YEAR'
  ) AS _expr52,
  DATE_ADD(
    DATE_TRUNC('MINUTE', DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), -40, 'HOUR'), -385, 'DAY')),
    29,
    'HOUR'
  ) AS _expr53,
  DATE_TRUNC('MINUTE', DATE_TRUNC('HOUR', DATE_ADD(CURRENT_TIMESTAMP(), 405, 'DAY'))) AS _expr54,
  DATE_ADD(
    DATE_ADD(DATE_TRUNC('SECOND', DATE_TRUNC('YEAR', CURRENT_TIMESTAMP())), 98, 'YEAR'),
    96,
    'MONTH'
  ) AS _expr55,
  DATE_ADD(
    DATE_TRUNC('DAY', DATE_TRUNC('SECOND', DATE_TRUNC('MINUTE', CURRENT_TIMESTAMP()))),
    78,
    'SECOND'
  ) AS _expr56,
  DATE_ADD(
    DATE_ADD(DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), 136, 'HOUR'), 104, 'MINUTE'), -104, 'MONTH'),
    312,
    'DAY'
  ) AS _expr57,
  DATE_ADD(DATE_ADD(CURRENT_TIMESTAMP(), 45, 'MONTH'), -135, 'SECOND') AS _expr58
FROM (
  SELECT
    o_orderdate AS order_date
  FROM tpch.ORDERS
)
