SELECT
  DATE_TRUNC('YEAR', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '5' MONTH - INTERVAL '1' DAY AS d1,
  DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '24' HOUR AS d2,
  DATE_TRUNC('DAY', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) + INTERVAL '12' HOUR - INTERVAL '150' MINUTE + INTERVAL '2' SECOND AS d3
FROM (VALUES
  (NULL)) AS _q_0(_col_0)
