WITH _T2 AS (
  SELECT
    c_acctbal AS C_ACCTBAL,
    c_custkey AS C_CUSTKEY,
    c_nationkey AS C_NATIONKEY
  FROM TPCH.CUSTOMER
), _T AS (
  SELECT
    C_ACCTBAL,
    C_CUSTKEY,
    C_NATIONKEY,
    ROW_NUMBER() OVER (PARTITION BY C_NATIONKEY ORDER BY C_ACCTBAL DESC, C_CUSTKEY) AS _W
  FROM _T2
), _S4 AS (
  SELECT
    n_nationkey AS N_NATIONKEY,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
), _T_2 AS (
  SELECT
    _S5.C_ACCTBAL,
    _S4.N_NATIONKEY,
    _S4.N_REGIONKEY,
    ROW_NUMBER() OVER (PARTITION BY _S4.N_REGIONKEY ORDER BY _S5.C_ACCTBAL DESC, _S5.C_CUSTKEY) AS _W
  FROM _S4 _S4
  JOIN _T2 _S5
    ON _S4.N_NATIONKEY = _S5.C_NATIONKEY
), _S7 AS (
  SELECT
    C_ACCTBAL,
    N_NATIONKEY,
    N_REGIONKEY
  FROM _T_2
  WHERE
    _W = 1
), _T_3 AS (
  SELECT
    _S8.N_NATIONKEY,
    _S8.N_REGIONKEY,
    PARTSUPP.ps_availqty AS PS_AVAILQTY,
    PARTSUPP.ps_partkey AS PS_PARTKEY,
    SUPPLIER.s_nationkey AS S_NATIONKEY,
    SUPPLIER.s_suppkey AS S_SUPPKEY,
    ROW_NUMBER() OVER (PARTITION BY _S8.N_REGIONKEY ORDER BY PARTSUPP.ps_availqty DESC, PARTSUPP.ps_partkey) AS _W
  FROM _S4 _S8
  JOIN TPCH.SUPPLIER SUPPLIER
    ON SUPPLIER.s_nationkey = _S8.N_NATIONKEY
  JOIN TPCH.PARTSUPP PARTSUPP
    ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
), _T_4 AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY,
    PS_AVAILQTY,
    PS_PARTKEY,
    S_NATIONKEY,
    S_SUPPKEY,
    ROW_NUMBER() OVER (PARTITION BY N_REGIONKEY ORDER BY PS_AVAILQTY DESC, S_SUPPKEY) AS _W
  FROM _T_3
  WHERE
    _W = 1
), _S13 AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY,
    PS_AVAILQTY,
    PS_PARTKEY,
    S_SUPPKEY
  FROM _T_4
  WHERE
    N_NATIONKEY = S_NATIONKEY AND _W = 1
), _T_5 AS (
  SELECT
    C_CUSTKEY,
    C_NATIONKEY,
    ROW_NUMBER() OVER (ORDER BY C_ACCTBAL DESC, C_CUSTKEY) AS _W
  FROM _T2
), _S15 AS (
  SELECT
    C_CUSTKEY,
    C_NATIONKEY
  FROM _T_5
  WHERE
    _W = 1
)
SELECT
  REGION.r_name,
  NATION.n_name,
  _T.C_CUSTKEY AS c_key,
  _T.C_ACCTBAL AS c_bal,
  _S7.C_ACCTBAL AS cr_bal,
  _S13.S_SUPPKEY AS s_key,
  _S13.PS_PARTKEY AS p_key,
  _S13.PS_AVAILQTY AS p_qty,
  _S15.C_CUSTKEY AS cg_key
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.n_regionkey = REGION.r_regionkey
JOIN _T _T
  ON NATION.n_nationkey = _T.C_NATIONKEY AND _T._W = 1
LEFT JOIN _S7 _S7
  ON NATION.n_nationkey = _S7.N_NATIONKEY AND REGION.r_regionkey = _S7.N_REGIONKEY
LEFT JOIN _S13 _S13
  ON NATION.n_nationkey = _S13.N_NATIONKEY AND REGION.r_regionkey = _S13.N_REGIONKEY
LEFT JOIN _S15 _S15
  ON NATION.n_nationkey = _S15.C_NATIONKEY
ORDER BY
  2 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
