WITH "_t2" AS (
  SELECT
    C_ACCTBAL,
    C_CUSTKEY,
    C_NATIONKEY
  FROM TPCH.CUSTOMER
), "_t" AS (
  SELECT
    C_ACCTBAL,
    C_CUSTKEY,
    C_NATIONKEY,
    ROW_NUMBER() OVER (PARTITION BY C_NATIONKEY ORDER BY C_ACCTBAL DESC, C_CUSTKEY) AS "_w"
  FROM "_t2"
), "_s4" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
), "_t_2" AS (
  SELECT
    "_s5".C_ACCTBAL,
    "_s4".N_NATIONKEY,
    "_s4".N_REGIONKEY,
    ROW_NUMBER() OVER (PARTITION BY "_s4".N_REGIONKEY ORDER BY "_s5".C_ACCTBAL DESC, "_s5".C_CUSTKEY) AS "_w"
  FROM "_s4" "_s4"
  JOIN "_t2" "_s5"
    ON "_s4".N_NATIONKEY = "_s5".C_NATIONKEY
), "_s7" AS (
  SELECT
    C_ACCTBAL,
    N_NATIONKEY,
    N_REGIONKEY
  FROM "_t_2"
  WHERE
    "_w" = 1
), "_t_3" AS (
  SELECT
    "_s8".N_NATIONKEY,
    "_s8".N_REGIONKEY,
    PARTSUPP.PS_AVAILQTY,
    PARTSUPP.PS_PARTKEY,
    SUPPLIER.S_NATIONKEY,
    SUPPLIER.S_SUPPKEY,
    ROW_NUMBER() OVER (
      PARTITION BY "_s8".N_REGIONKEY
      ORDER BY PARTSUPP.PS_AVAILQTY DESC, PARTSUPP.PS_PARTKEY
    ) AS "_w"
  FROM "_s4" "_s8"
  JOIN TPCH.SUPPLIER SUPPLIER
    ON SUPPLIER.S_NATIONKEY = "_s8".N_NATIONKEY
  JOIN TPCH.PARTSUPP PARTSUPP
    ON PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
), "_t_4" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY,
    PS_AVAILQTY,
    PS_PARTKEY,
    S_NATIONKEY,
    S_SUPPKEY,
    ROW_NUMBER() OVER (PARTITION BY N_REGIONKEY ORDER BY PS_AVAILQTY DESC, S_SUPPKEY) AS "_w"
  FROM "_t_3"
  WHERE
    "_w" = 1
), "_s13" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY,
    PS_AVAILQTY,
    PS_PARTKEY,
    S_SUPPKEY
  FROM "_t_4"
  WHERE
    N_NATIONKEY = S_NATIONKEY AND "_w" = 1
), "_t_5" AS (
  SELECT
    C_CUSTKEY,
    C_NATIONKEY,
    ROW_NUMBER() OVER (ORDER BY C_ACCTBAL DESC, C_CUSTKEY) AS "_w"
  FROM "_t2"
), "_s15" AS (
  SELECT
    C_CUSTKEY,
    C_NATIONKEY
  FROM "_t_5"
  WHERE
    "_w" = 1
)
SELECT
  REGION.R_NAME AS r_name,
  NATION.N_NAME AS n_name,
  "_t".C_CUSTKEY AS c_key,
  "_t".C_ACCTBAL AS c_bal,
  "_s7".C_ACCTBAL AS cr_bal,
  "_s13".S_SUPPKEY AS s_key,
  "_s13".PS_PARTKEY AS p_key,
  "_s13".PS_AVAILQTY AS p_qty,
  "_s15".C_CUSTKEY AS cg_key
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
JOIN "_t" "_t"
  ON NATION.N_NATIONKEY = "_t".C_NATIONKEY AND "_t"."_w" = 1
LEFT JOIN "_s7" "_s7"
  ON NATION.N_NATIONKEY = "_s7".N_NATIONKEY AND REGION.R_REGIONKEY = "_s7".N_REGIONKEY
LEFT JOIN "_s13" "_s13"
  ON NATION.N_NATIONKEY = "_s13".N_NATIONKEY
  AND REGION.R_REGIONKEY = "_s13".N_REGIONKEY
LEFT JOIN "_s15" "_s15"
  ON NATION.N_NATIONKEY = "_s15".C_NATIONKEY
ORDER BY
  2 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
