WITH _T0 AS (
  SELECT
    COUNT(*) AS AGG_0,
    COUNT_IF((
      (
        DAYOFWEEK(NOTIFICATIONS.created_at) + 6
      ) % 7
    ) IN (5, 6)) AS AGG_1,
    DATE_TRUNC('WEEK', CAST(NOTIFICATIONS.created_at AS TIMESTAMP)) AS WEEK
  FROM MAIN.NOTIFICATIONS AS NOTIFICATIONS
  JOIN MAIN.USERS AS USERS
    ON NOTIFICATIONS.user_id = USERS.uid AND USERS.country IN ('US', 'CA')
  WHERE
    NOTIFICATIONS.created_at < DATE_TRUNC('WEEK', CURRENT_TIMESTAMP())
    AND NOTIFICATIONS.created_at >= DATEADD(WEEK, -3, DATE_TRUNC('WEEK', CURRENT_TIMESTAMP()))
  GROUP BY
    DATE_TRUNC('WEEK', CAST(NOTIFICATIONS.created_at AS TIMESTAMP))
)
SELECT
  WEEK AS week,
  AGG_0 AS num_notifs,
  COALESCE(AGG_1, 0) AS weekend_notifs
FROM _T0
