WITH _T0 AS (
  SELECT
    balance AS BALANCE
  FROM MAIN.WALLET_USER_BALANCE_DAILY
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY updated_at DESC) = 1
)
SELECT
  USERS.uid AS user_id,
  _T0.BALANCE AS latest_balance
FROM MAIN.USERS AS USERS
JOIN _T0 AS _T0
  ON USERS.uid = USERS.uid
