WITH _T0 AS (
  SELECT
    SBTRANSACTION.sbtxcustid AS CUSTOMER_ID,
    SBTRANSACTION.sbtxtype AS TRANSACTION_TYPE
  FROM MAIN.SBTRANSACTION AS SBTRANSACTION
), _S1 AS (
  SELECT
    _T0.CUSTOMER_ID AS CUSTOMER_ID
  FROM _T0 AS _T0
  WHERE
    _T0.TRANSACTION_TYPE = 'buy'
), _S0 AS (
  SELECT
    SBCUSTOMER.sbcustid AS _ID
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
)
SELECT
  _S0._ID AS _id
FROM _S0 AS _S0
WHERE
  EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0._ID = _S1.CUSTOMER_ID
  )
