WITH _S1 AS (
  SELECT
    SUM(sale_price) AS SUM_SALE_PRICE,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS._id,
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  COALESCE(_S1.SUM_SALE_PRICE, 0) AS total
FROM MAIN.SALESPERSONS AS SALESPERSONS
LEFT JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  COALESCE(_S1.SUM_SALE_PRICE, 0) DESC NULLS LAST
LIMIT 5
