WITH _u_0 AS (
  SELECT
    sbtxcustid AS _u_1
  FROM MAIN.SBTRANSACTION
  GROUP BY
    1
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _u_0 AS _u_0
  ON SBCUSTOMER.sbcustid = _u_0._u_1
WHERE
  _u_0._u_1 IS NULL
