WITH "_s3" AS (
  SELECT
    DOMAIN_PUBLICATION.DID,
    AVG(PUBLICATION.REFERENCE_NUM) AS AVG_REFERENCE_NUM
  FROM MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
  JOIN MAIN.PUBLICATION PUBLICATION
    ON DOMAIN_PUBLICATION.PID = PUBLICATION.PID
  GROUP BY
    DOMAIN_PUBLICATION.DID
)
SELECT
  DOMAIN.NAME AS name,
  "_s3".AVG_REFERENCE_NUM AS average_references
FROM MAIN.DOMAIN DOMAIN
LEFT JOIN "_s3" "_s3"
  ON DOMAIN.DID = "_s3".DID
