SELECT
  TRUNC(CAST(created_at AS TIMESTAMP), 'MONTH') AS year_month,
  COUNT(DISTINCT sender_id) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY
WHERE
  created_at < TRUNC(CURRENT_TIMESTAMP, 'MONTH')
  AND created_at >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'MONTH'), 2, MONTH)
  AND sender_type = 0
GROUP BY
  TRUNC(CAST(created_at AS TIMESTAMP), 'MONTH')
