WITH "_u_0" AS (
  SELECT
    AUTHOR.oid AS "_u_1"
  FROM MAIN.AUTHOR AUTHOR
  JOIN MAIN.WRITES WRITES
    ON AUTHOR.aid = WRITES.aid
  JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
    ON DOMAIN_PUBLICATION.pid = WRITES.pid
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.did = DOMAIN_PUBLICATION.did AND DOMAIN.name = 'Machine Learning'
  GROUP BY
    AUTHOR.oid
)
SELECT
  ORGANIZATION.name AS oranization_name,
  ORGANIZATION.oid AS organization_id
FROM MAIN.ORGANIZATION ORGANIZATION
LEFT JOIN "_u_0" "_u_0"
  ON ORGANIZATION.oid = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
