SELECT
  COALESCE(SUM(STATUS = 'success'), 0) / NULLIF(COUNT(*), 0) AS "_expr0"
FROM MAIN.WALLET_TRANSACTIONS_DAILY
WHERE
  (
    (
      EXTRACT(YEAR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM CAST(CREATED_AT AS DATE))
    ) * 12 + (
      EXTRACT(MONTH FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(MONTH FROM CAST(CREATED_AT AS DATE))
    )
  ) = 1
