SELECT
  PAYMENT_DATE AS payment_date,
  PAYMENT_METHOD AS payment_method,
  COALESCE(SUM(PAYMENT_AMOUNT), 0) AS total_amount
FROM MAIN.PAYMENTS_RECEIVED
WHERE
  FLOOR(
    (
      TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(PAYMENT_DATE AS DATE) AS DATE), 'DD') + (
        MOD((
          TO_CHAR(CAST(PAYMENT_DATE AS DATE), 'D') + 5
        ), 7)
      ) - (
        MOD((
          TO_CHAR(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE), 'D') + 5
        ), 7)
      )
    ) / 7
  ) = 1
GROUP BY
  PAYMENT_DATE,
  PAYMENT_METHOD
ORDER BY
  1 DESC NULLS LAST,
  2 NULLS FIRST
