SELECT
  RESTAURANT.NAME AS name,
  RESTAURANT.FOOD_TYPE AS food_type
FROM MAIN.LOCATION LOCATION
JOIN MAIN.RESTAURANT RESTAURANT
  ON LOCATION.RESTAURANT_ID = RESTAURANT.ID
WHERE
  LOWER(LOCATION.CITY_NAME) = 'san francisco'
  AND LOWER(LOCATION.STREET_NAME) = 'market st'
