WITH "_u_0" AS (
  SELECT
    PATIENT_ID AS "_u_1"
  FROM MAIN.TREATMENTS
  GROUP BY
    PATIENT_ID
), "_t1" AS (
  SELECT
    MIN(EXTRACT(YEAR FROM CAST(TREATMENTS.START_DT AS DATE))) AS MIN_YEAR_START_DT
  FROM MAIN.PATIENTS PATIENTS
  LEFT JOIN "_u_0" "_u_0"
    ON PATIENTS.PATIENT_ID = "_u_0"."_u_1"
  LEFT JOIN MAIN.TREATMENTS TREATMENTS
    ON PATIENTS.PATIENT_ID = TREATMENTS.PATIENT_ID
  WHERE
    NOT "_u_0"."_u_1" IS NULL
  GROUP BY
    PATIENTS.PATIENT_ID
), "_t0" AS (
  SELECT
    MIN_YEAR_START_DT,
    COUNT(*) AS N_ROWS
  FROM "_t1"
  GROUP BY
    MIN_YEAR_START_DT
)
SELECT
  TO_CHAR(MIN_YEAR_START_DT) AS year,
  N_ROWS AS number_of_new_patients,
  N_ROWS - LAG(N_ROWS, 1) OVER (ORDER BY MIN_YEAR_START_DT) AS npi
FROM "_t0"
ORDER BY
  1 NULLS FIRST
