WITH "_u_0" AS (
  SELECT
    CUSTOMER_ID AS "_u_1"
  FROM MAIN.SALES
  GROUP BY
    CUSTOMER_ID
)
SELECT
  CUSTOMERS."_id"
FROM MAIN.CUSTOMERS CUSTOMERS
LEFT JOIN "_u_0" "_u_0"
  ON CUSTOMERS."_id" = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
