WITH _S3 AS (
  SELECT
    DOMAIN_PUBLICATION.did AS DID,
    AVG(PUBLICATION.reference_num) AS AVG_REFERENCE_NUM
  FROM MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
  JOIN MAIN.PUBLICATION PUBLICATION
    ON DOMAIN_PUBLICATION.pid = PUBLICATION.pid
  GROUP BY
    DOMAIN_PUBLICATION.did
)
SELECT
  DOMAIN.name,
  _S3.AVG_REFERENCE_NUM AS average_references
FROM MAIN.DOMAIN DOMAIN
LEFT JOIN _S3 _S3
  ON DOMAIN.did = _S3.DID
