WITH _S1 AS (
  SELECT
    SUM(
      DATEDIFF(SECOND, CAST(session_start_ts AS DATETIME), CAST(session_end_ts AS DATETIME))
    ) AS SUM_DURATION,
    user_id AS USER_ID
  FROM MAIN.USER_SESSIONS
  WHERE
    session_end_ts < '2023-06-08' AND session_start_ts >= '2023-06-01'
  GROUP BY
    2
)
SELECT
  USERS.uid,
  COALESCE(_S1.SUM_DURATION, 0) AS total_duration
FROM MAIN.USERS AS USERS
JOIN _S1 AS _S1
  ON USERS.uid = _S1.USER_ID
ORDER BY
  2 DESC NULLS LAST
