WITH _S1 AS (
  SELECT
    COUNT(*) AS AGG_0,
    COUNT_IF(sbtxstatus = 'success') AS AGG_1,
    sbtxcustid AS CUSTOMER_ID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  (
    100.0 * COALESCE(_S1.AGG_1, 0)
  ) / COALESCE(_S1.AGG_0, 0) AS success_rate
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.CUSTOMER_ID
WHERE
  NOT _S1.AGG_0 IS NULL AND _S1.AGG_0 >= 5
ORDER BY
  SUCCESS_RATE NULLS FIRST
