SELECT
  TRUNC(CAST(PAYMENTS_RECEIVED.payment_date AS TIMESTAMP), 'WEEK') AS payment_week,
  COUNT(*) AS total_payments,
  NVL(
    SUM(
      (
        MOD((
          DAY_OF_WEEK(PAYMENTS_RECEIVED.payment_date) + 6
        ), 7)
      ) IN (5, 6)
    ),
    0
  ) AS weekend_payments
FROM MAIN.PAYMENTS_RECEIVED PAYMENTS_RECEIVED
JOIN MAIN.SALES SALES
  ON PAYMENTS_RECEIVED.sale_id = SALES."_id" AND SALES.sale_price > 30000
WHERE
  DATEDIFF(CURRENT_TIMESTAMP, CAST(PAYMENTS_RECEIVED.payment_date AS DATETIME), WEEK) <= 8
  AND DATEDIFF(CURRENT_TIMESTAMP, CAST(PAYMENTS_RECEIVED.payment_date AS DATETIME), WEEK) >= 1
GROUP BY
  TRUNC(CAST(PAYMENTS_RECEIVED.payment_date AS TIMESTAMP), 'WEEK')
