WITH "_t1" AS (
  SELECT
    ANY_VALUE(CARS.MAKE) AS ANYTHING_MAKE,
    ANY_VALUE(CARS.MODEL) AS ANYTHING_MODEL,
    COUNT(SALES.CAR_ID) AS COUNT_CAR_ID
  FROM MAIN.CARS CARS
  LEFT JOIN MAIN.SALES SALES
    ON CARS."_id" = SALES.CAR_ID
  WHERE
    LOWER(CARS.VIN_NUMBER) LIKE '%m5%'
  GROUP BY
    CARS."_id"
)
SELECT
  ANYTHING_MAKE AS make,
  ANYTHING_MODEL AS model,
  COALESCE(SUM(COUNT_CAR_ID), 0) AS num_sales
FROM "_t1"
GROUP BY
  ANYTHING_MAKE,
  ANYTHING_MODEL
