WITH _S0 AS (
  SELECT
    SUM(sale_price) AS AGG_0,
    customer_id AS CUSTOMER_ID,
    DATE_TRUNC('QUARTER', CAST(sale_date AS TIMESTAMP)) AS QUARTER
  FROM MAIN.SALES
  WHERE
    DATE_PART(YEAR, sale_date) = 2023
  GROUP BY
    customer_id,
    DATE_TRUNC('QUARTER', CAST(sale_date AS TIMESTAMP))
), _T1 AS (
  SELECT
    SUM(_S0.AGG_0) AS AGG_0,
    CUSTOMERS.state AS CUSTOMER_STATE,
    _S0.QUARTER
  FROM _S0 AS _S0
  JOIN MAIN.CUSTOMERS AS CUSTOMERS
    ON CUSTOMERS._id = _S0.CUSTOMER_ID
  GROUP BY
    CUSTOMERS.state,
    _S0.QUARTER
)
SELECT
  QUARTER AS quarter,
  CUSTOMER_STATE AS customer_state,
  COALESCE(AGG_0, 0) AS total_sales
FROM _T1
WHERE
  NOT AGG_0 IS NULL AND AGG_0 > 0
ORDER BY
  QUARTER NULLS FIRST,
  CUSTOMER_STATE NULLS FIRST
