WITH _S1 AS (
  SELECT
    MAX(sbdphigh) AS MAX_SBDPHIGH,
    MIN(sbdplow) AS MIN_SBDPLOW,
    sbdptickerid AS SBDPTICKERID
  FROM MAIN.SBDAILYPRICE
  WHERE
    sbdpdate <= CAST('2023-04-04' AS DATE) AND sbdpdate >= CAST('2023-04-01' AS DATE)
  GROUP BY
    sbdptickerid
)
SELECT
  SBTICKER.sbtickersymbol AS symbol,
  _S1.MAX_SBDPHIGH - _S1.MIN_SBDPLOW AS price_change
FROM MAIN.SBTICKER AS SBTICKER
LEFT JOIN _S1 AS _S1
  ON SBTICKER.sbtickerid = _S1.SBDPTICKERID
ORDER BY
  _S1.MAX_SBDPHIGH - _S1.MIN_SBDPLOW DESC NULLS LAST
LIMIT 3
