WITH "_s1" AS (
  SELECT
    SBTXCUSTID,
    SUM(SBTXAMOUNT) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTNAME AS name,
  COALESCE("_s1".SUM_SBTXAMOUNT, 0) AS total_amount
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
