WITH "_t" AS (
  SELECT
    BALANCE,
    USER_ID,
    ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY UPDATED_AT DESC) AS "_w"
  FROM MAIN.WALLET_USER_BALANCE_DAILY
)
SELECT
  USER_ID AS user_id,
  BALANCE AS latest_balance
FROM "_t"
WHERE
  "_w" = 1
