SELECT
  ANY_VALUE(CONFERENCE.name) AS name,
  NVL(NULLIF(COUNT(PUBLICATION.cid), 0), 0) AS num_publications
FROM MAIN.CONFERENCE CONFERENCE
LEFT JOIN MAIN.PUBLICATION PUBLICATION
  ON CONFERENCE.cid = PUBLICATION.cid
GROUP BY
  CONFERENCE.cid
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
