WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
), _T0 AS (
  SELECT
    RANK() OVER (ORDER BY COALESCE(_S1.SUM_SALE_PRICE, 0) DESC) AS SALES_RANK,
    COALESCE(_S1.SUM_SALE_PRICE, 0) AS TOTAL_SALES,
    SALESPERSONS.first_name AS FIRST_NAME,
    SALESPERSONS.last_name AS LAST_NAME,
    _S1.N_ROWS
  FROM MAIN.SALESPERSONS AS SALESPERSONS
  JOIN _S1 AS _S1
    ON SALESPERSONS._id = _S1.SALESPERSON_ID
)
SELECT
  FIRST_NAME AS first_name,
  LAST_NAME AS last_name,
  TOTAL_SALES AS total_sales,
  N_ROWS AS num_sales,
  SALES_RANK AS sales_rank
FROM _T0
ORDER BY
  TOTAL_SALES DESC NULLS LAST
