SELECT
  DEVICE_TYPE AS device_type,
  AVG((
    CAST(SESSION_END_TS AS DATE) - CAST(SESSION_START_TS AS DATE)
  ) * 86400) AS avg_session_duration_seconds
FROM MAIN.USER_SESSIONS
GROUP BY
  DEVICE_TYPE
