WITH "_s1" AS (
  SELECT
    CAR_ID,
    COUNT(*) AS N_ROWS,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    CAR_ID
)
SELECT
  CARS.MAKE AS make,
  CARS.MODEL AS model,
  COALESCE("_s1".N_ROWS, 0) AS total_sales,
  COALESCE("_s1".SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.CARS CARS
LEFT JOIN "_s1" "_s1"
  ON CARS."_id" = "_s1".CAR_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
