WITH "_s3" AS (
  SELECT
    COUPONS.MERCHANT_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.COUPONS COUPONS
  JOIN MAIN.MERCHANTS MERCHANTS
    ON (
      (
        EXTRACT(YEAR FROM CAST(COUPONS.CREATED_AT AS DATE)) - EXTRACT(YEAR FROM CAST(MERCHANTS.CREATED_AT AS DATE))
      ) * 12 + (
        EXTRACT(MONTH FROM CAST(COUPONS.CREATED_AT AS DATE)) - EXTRACT(MONTH FROM CAST(MERCHANTS.CREATED_AT AS DATE))
      )
    ) = 0
    AND COUPONS.MERCHANT_ID = MERCHANTS.MID
  GROUP BY
    COUPONS.MERCHANT_ID
)
SELECT
  MERCHANTS.MID AS merchant_id,
  MERCHANTS.NAME AS merchant_name,
  COALESCE("_s3".N_ROWS, 0) AS coupons_per_merchant
FROM MAIN.MERCHANTS MERCHANTS
LEFT JOIN "_s3" "_s3"
  ON MERCHANTS.MID = "_s3".MERCHANT_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
