WITH _u_0 AS (
  SELECT
    NOTIFICATIONS.user_id AS _u_1
  FROM MAIN.NOTIFICATIONS AS NOTIFICATIONS
  JOIN MAIN.USERS AS USERS
    ON NOTIFICATIONS.created_at <= DATEADD(YEAR, 1, CAST(USERS.created_at AS TIMESTAMP))
    AND NOTIFICATIONS.created_at >= USERS.created_at
    AND NOTIFICATIONS.user_id = USERS.uid
  GROUP BY
    NOTIFICATIONS.user_id
)
SELECT
  USERS.username,
  USERS.email,
  USERS.created_at
FROM MAIN.USERS AS USERS
LEFT JOIN _u_0 AS _u_0
  ON USERS.uid = _u_0._u_1
WHERE
  _u_0._u_1 IS NULL
