WITH "_S1" AS (
  SELECT
    sbdptickerid AS SBDPTICKERID,
    COUNT(sbdpclose) AS COUNT_SBDPCLOSE,
    SUM(sbdpclose) AS SUM_SBDPCLOSE
  FROM MAIN.SBDAILYPRICE
  WHERE
    (
      CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - CAST(sbdpdate AS DATE)
    ) <= 7
  GROUP BY
    sbdptickerid
)
SELECT
  SBTICKER.sbtickertype AS ticker_type,
  SUM("_S1".SUM_SBDPCLOSE) / SUM("_S1".COUNT_SBDPCLOSE) AS ACP
FROM MAIN.SBTICKER SBTICKER
JOIN "_S1" "_S1"
  ON SBTICKER.sbtickerid = "_S1".SBDPTICKERID
GROUP BY
  SBTICKER.sbtickertype
