WITH "_T0" AS (
  SELECT
    TRUNC(CAST(start_dt AS TIMESTAMP), 'MONTH') AS START_MONTH,
    COUNT(*) AS N_ROWS,
    COUNT(DISTINCT diag_id) AS NDISTINCT_DIAG_ID
  FROM MAIN.TREATMENTS
  WHERE
    (
      TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTOYMINTERVAL(12, 'month')
    ) <= TRUNC(CAST(start_dt AS TIMESTAMP), 'MONTH')
    AND TRUNC(CAST(start_dt AS TIMESTAMP), 'MONTH') < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
  GROUP BY
    TRUNC(CAST(start_dt AS TIMESTAMP), 'MONTH')
)
SELECT
  LTRIM(
    NVL2(
      EXTRACT(YEAR FROM CAST(START_MONTH AS DATE)),
      '-' || EXTRACT(YEAR FROM CAST(START_MONTH AS DATE)),
      NULL
    ) || NVL2(
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(START_MONTH AS DATE))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(START_MONTH AS DATE)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(START_MONTH AS DATE))), -2)
      END,
      '-' || CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(START_MONTH AS DATE))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(START_MONTH AS DATE)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(START_MONTH AS DATE))), -2)
      END,
      NULL
    ),
    '-'
  ) AS start_month,
  NDISTINCT_DIAG_ID AS PMPD,
  N_ROWS AS PMTC
FROM "_T0"
ORDER BY
  1 DESC NULLS LAST
