SELECT
  COUNT(*) AS TUC
FROM MAIN.USER_SESSIONS
WHERE
  session_end_ts >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 1, MONTH), 'DAY')
  OR session_start_ts >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 1, MONTH), 'DAY')
