WITH "_S1" AS (
  SELECT
    salesperson_id AS SALESPERSON_ID,
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    (
      TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(sale_date AS DATE) AS DATE), 'DD')
    ) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  "_S1".N_ROWS AS total_sales,
  COALESCE("_S1".SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN "_S1" "_S1"
  ON SALESPERSONS."_id" = "_S1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
