WITH "_u_0" AS (
  SELECT
    RECEIVER_ID AS "_u_1"
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    RECEIVER_TYPE = 1
  GROUP BY
    RECEIVER_ID
)
SELECT
  MERCHANTS.MID AS merchant
FROM MAIN.MERCHANTS MERCHANTS
LEFT JOIN "_u_0" "_u_0"
  ON MERCHANTS.MID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
