WITH _S0 AS (
  SELECT
    SUM(sale_price) AS SUM_SALE_PRICE,
    customer_id AS CUSTOMER_ID,
    DATE_TRUNC('QUARTER', CAST(sale_date AS TIMESTAMP)) AS QUARTER
  FROM MAIN.SALES
  WHERE
    DATE_PART(YEAR, CAST(sale_date AS DATETIME)) = 2023
  GROUP BY
    customer_id,
    DATE_TRUNC('QUARTER', CAST(sale_date AS TIMESTAMP))
), _T2 AS (
  SELECT
    SUM(_S0.SUM_SALE_PRICE) AS SUM_SUM_SALE_PRICE,
    _S0.QUARTER,
    CUSTOMERS.state AS STATE
  FROM _S0 AS _S0
  JOIN MAIN.CUSTOMERS AS CUSTOMERS
    ON CUSTOMERS._id = _S0.CUSTOMER_ID
  GROUP BY
    _S0.QUARTER,
    CUSTOMERS.state
)
SELECT
  QUARTER AS quarter,
  STATE AS customer_state,
  COALESCE(SUM_SUM_SALE_PRICE, 0) AS total_sales
FROM _T2
WHERE
  NOT SUM_SUM_SALE_PRICE IS NULL AND SUM_SUM_SALE_PRICE > 0
ORDER BY
  QUARTER NULLS FIRST,
  STATE NULLS FIRST
