WITH "_S0" AS (
  SELECT
    TRUNC(CAST(sale_date AS TIMESTAMP), 'QUARTER') AS QUARTER,
    customer_id AS CUSTOMER_ID,
    SUM(sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    EXTRACT(YEAR FROM CAST(sale_date AS DATE)) = 2023
  GROUP BY
    TRUNC(CAST(sale_date AS TIMESTAMP), 'QUARTER'),
    customer_id
), "_T1" AS (
  SELECT
    "_S0".QUARTER,
    CUSTOMERS.state AS STATE,
    SUM("_S0".SUM_SALE_PRICE) AS SUM_SUM_SALE_PRICE
  FROM "_S0" "_S0"
  JOIN MAIN.CUSTOMERS CUSTOMERS
    ON CUSTOMERS."_id" = "_S0".CUSTOMER_ID
  GROUP BY
    "_S0".QUARTER,
    CUSTOMERS.state
)
SELECT
  QUARTER AS quarter,
  STATE AS customer_state,
  SUM_SUM_SALE_PRICE AS total_sales
FROM "_T1"
WHERE
  NOT SUM_SUM_SALE_PRICE IS NULL AND SUM_SUM_SALE_PRICE > 0
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
