WITH "_s1" AS (
  SELECT
    SBTXCUSTID,
    MIN(SBTXDATETIME) AS MIN_SBTXDATETIME
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTID AS cust_id,
  (
    (
      CAST("_s1".MIN_SBTXDATETIME AS DATE) - CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)
    ) * 86400
  ) / 86400.0 AS DaysFromJoinToFirstTransaction
FROM MAIN.SBCUSTOMER SBCUSTOMER
JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
