SELECT
  USERS.username,
  USERS.email,
  USERS.created_at
FROM MAIN.USERS USERS
JOIN MAIN.NOTIFICATIONS NOTIFICATIONS
  ON NOTIFICATIONS.user_id = USERS.uid
JOIN MAIN.USERS USERS_2
  ON NOTIFICATIONS.created_at <= DATE_ADD(CAST(USERS_2.created_at AS TIMESTAMP), 1, 'YEAR')
  AND NOTIFICATIONS.created_at >= USERS_2.created_at
  AND NOTIFICATIONS.user_id = USERS_2.uid
