WITH _S1 AS (
  SELECT
    sbtxcustid AS SBTXCUSTID,
    SUM(sbtxamount) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  NVL(_S1.SUM_SBTXAMOUNT, 0) AS total_amount
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN _S1 _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
