WITH _T1 AS (
  SELECT
    ANY_VALUE(ORGANIZATION.continent) AS ANYTHING_CONTINENT,
    COUNT(AUTHOR.oid) AS COUNT_OID
  FROM MAIN.ORGANIZATION ORGANIZATION
  LEFT JOIN MAIN.AUTHOR AUTHOR
    ON AUTHOR.oid = ORGANIZATION.oid
  GROUP BY
    ORGANIZATION.oid
)
SELECT
  ANYTHING_CONTINENT AS continent,
  NVL(SUM(COUNT_OID), 0) / COUNT(*) AS ratio
FROM _T1
GROUP BY
  ANYTHING_CONTINENT
ORDER BY
  2 DESC NULLS LAST
