WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    sale_date >= DATEADD(MONTH, -3, CURRENT_TIMESTAMP())
  GROUP BY
    3
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  COALESCE(_S1.N_ROWS, 0) AS total_sales,
  COALESCE(_S1.SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.SALESPERSONS AS SALESPERSONS
LEFT JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  4 DESC NULLS LAST
LIMIT 3
