WITH _S1 AS (
  SELECT
    SBDAILYPRICE.sbdptickerid AS TICKER_ID
  FROM MAIN.SBDAILYPRICE AS SBDAILYPRICE
), _S0 AS (
  SELECT
    SBTICKER.sbtickerid AS _ID,
    SBTICKER.sbtickersymbol AS SYMBOL
  FROM MAIN.SBTICKER AS SBTICKER
)
SELECT
  _S0._ID AS _id,
  _S0.SYMBOL AS symbol
FROM _S0 AS _S0
WHERE
  NOT EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0._ID = _S1.TICKER_ID
  )
