WITH _S0 AS (
  SELECT
    COUNT(*) AS NUM_TRANSACTIONS,
    sbtxcustid AS CUSTOMER_ID,
    sbtxtickerid AS TICKER_ID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid,
    sbtxtickerid
), _S2 AS (
  SELECT
    SUM(_S0.NUM_TRANSACTIONS) AS NUM_TRANSACTIONS_0,
    _S0.CUSTOMER_ID,
    SBTICKER.sbtickertype AS TICKER_TYPE
  FROM _S0 AS _S0
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = _S0.TICKER_ID
  GROUP BY
    _S0.CUSTOMER_ID,
    SBTICKER.sbtickertype
), _T0 AS (
  SELECT
    SUM(_S2.NUM_TRANSACTIONS_0) AS NUM_TRANSACTIONS,
    SBCUSTOMER.sbcuststate AS STATE,
    _S2.TICKER_TYPE
  FROM _S2 AS _S2
  JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
    ON SBCUSTOMER.sbcustid = _S2.CUSTOMER_ID
  GROUP BY
    SBCUSTOMER.sbcuststate,
    _S2.TICKER_TYPE
)
SELECT
  STATE AS state,
  TICKER_TYPE AS ticker_type,
  NUM_TRANSACTIONS AS num_transactions
FROM _T0
ORDER BY
  NUM_TRANSACTIONS DESC NULLS LAST
LIMIT 5
