WITH "_s0" AS (
  SELECT
    NVL(EXTRACT(YEAR FROM CAST(SBDPDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBDPDATE AS DATE)), 2, '0'), '') AS MONTH,
    SBDPTICKERID,
    COUNT(SBDPCLOSE) AS COUNT_SBDPCLOSE,
    MAX(SBDPHIGH) AS MAX_SBDPHIGH,
    MIN(SBDPLOW) AS MIN_SBDPLOW,
    SUM(SBDPCLOSE) AS SUM_SBDPCLOSE
  FROM MAIN.SBDAILYPRICE
  GROUP BY
    NVL(EXTRACT(YEAR FROM CAST(SBDPDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBDPDATE AS DATE)), 2, '0'), ''),
    SBDPTICKERID
), "_t0" AS (
  SELECT
    "_s0".MONTH,
    SBTICKER.SBTICKERSYMBOL,
    MAX("_s0".MAX_SBDPHIGH) AS MAX_MAX_SBDPHIGH,
    MIN("_s0".MIN_SBDPLOW) AS MIN_MIN_SBDPLOW,
    SUM("_s0".COUNT_SBDPCLOSE) AS SUM_COUNT_SBDPCLOSE,
    SUM("_s0".SUM_SBDPCLOSE) AS SUM_SUM_SBDPCLOSE
  FROM "_s0" "_s0"
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.SBTICKERID = "_s0".SBDPTICKERID
  GROUP BY
    "_s0".MONTH,
    SBTICKER.SBTICKERSYMBOL
)
SELECT
  SBTICKERSYMBOL AS symbol,
  MONTH AS month,
  SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE AS avg_close,
  MAX_MAX_SBDPHIGH AS max_high,
  MIN_MIN_SBDPLOW AS min_low,
  (
    (
      SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE
    ) - LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH)
  ) / NULLIF(
    LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH),
    0
  ) AS momc
FROM "_t0"
