WITH _S3 AS (
  SELECT
    COUNT(*) AS AGG_0,
    SBCUSTOMER.sbcustid AS _ID
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
  JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
    ON MONTH(SBCUSTOMER.sbcustjoindate) = MONTH(SBTRANSACTION.sbtxdatetime)
    AND SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
    AND YEAR(SBCUSTOMER.sbcustjoindate) = YEAR(SBTRANSACTION.sbtxdatetime)
  GROUP BY
    SBCUSTOMER.sbcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S3.AGG_0, 0) AS num_transactions
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S3 AS _S3
  ON SBCUSTOMER.sbcustid = _S3._ID
ORDER BY
  NUM_TRANSACTIONS DESC NULLS LAST
LIMIT 1
