SELECT
  TRUNC(CAST(CAST(NOTIFICATIONS.created_at AS DATE) AS DATE), 'IW') AS week,
  COUNT(*) AS num_notifs,
  SUM((
    MOD((
      TO_CHAR(NOTIFICATIONS.created_at, 'D') + 5
    ), 7)
  ) IN (5, 6)) AS weekend_notifs
FROM MAIN.NOTIFICATIONS NOTIFICATIONS
JOIN MAIN.USERS USERS
  ON NOTIFICATIONS.user_id = USERS.uid AND USERS.country IN ('US', 'CA')
WHERE
  NOTIFICATIONS.created_at < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'IW')
  AND NOTIFICATIONS.created_at >= (
    TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'IW') - NUMTODSINTERVAL(21, 'DAY')
  )
GROUP BY
  TRUNC(CAST(CAST(NOTIFICATIONS.created_at AS DATE) AS DATE), 'IW')
