WITH _S1 AS (
  SELECT
    doc_id AS DOC_ID,
    COUNT(*) AS N_ROWS,
    SUM(tot_drug_amt) AS SUM_TOT_DRUG_AMT
  FROM MAIN.TREATMENTS
  WHERE
    start_dt >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 6, MONTH), 'DAY')
  GROUP BY
    doc_id
), _T1 AS (
  SELECT
    DOCTORS.specialty AS SPECIALTY,
    SUM(_S1.N_ROWS) AS SUM_N_ROWS,
    SUM(_S1.SUM_TOT_DRUG_AMT) AS SUM_SUM_TOT_DRUG_AMT
  FROM MAIN.DOCTORS DOCTORS
  LEFT JOIN _S1 _S1
    ON DOCTORS.doc_id = _S1.DOC_ID
  GROUP BY
    DOCTORS.specialty
)
SELECT
  SPECIALTY AS specialty,
  SUM_N_ROWS AS num_treatments,
  NVL(SUM_SUM_TOT_DRUG_AMT, 0) AS total_drug_amount
FROM _T1
WHERE
  SUM_N_ROWS <> 0
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
