WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    sbtxtickerid AS SBTXTICKERID
  FROM MAIN.SBTRANSACTION
  WHERE
    sbtxdatetime >= DATE_TRUNC('DAY', DATEADD(DAY, -10, CURRENT_TIMESTAMP()))
    AND sbtxtype = 'buy'
  GROUP BY
    sbtxtickerid
)
SELECT
  SBTICKER.sbtickersymbol AS symbol,
  COALESCE(_S1.N_ROWS, 0) AS tx_count
FROM MAIN.SBTICKER AS SBTICKER
LEFT JOIN _S1 AS _S1
  ON SBTICKER.sbtickerid = _S1.SBTXTICKERID
ORDER BY
  TX_COUNT DESC NULLS LAST
LIMIT 2
