WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(sbtxamount) AS SUM_SBTXAMOUNT,
    sbtxtickerid AS SBTXTICKERID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    3
)
SELECT
  SBTICKER.sbtickersymbol AS symbol,
  COALESCE(_S1.N_ROWS, 0) AS num_transactions,
  COALESCE(_S1.SUM_SBTXAMOUNT, 0) AS total_amount
FROM MAIN.SBTICKER AS SBTICKER
LEFT JOIN _S1 AS _S1
  ON SBTICKER.sbtickerid = _S1.SBTXTICKERID
ORDER BY
  3 DESC NULLS LAST
LIMIT 10
