SELECT
  CARS.make,
  CARS.model,
  SALES.sale_price
FROM MAIN.SALES SALES
JOIN MAIN.CARS CARS
  ON CARS."_id" = SALES.car_id
JOIN MAIN.INVENTORY_SNAPSHOTS INVENTORY_SNAPSHOTS
  ON CARS."_id" = INVENTORY_SNAPSHOTS.car_id
  AND INVENTORY_SNAPSHOTS.snapshot_date = SALES.sale_date
  AND NOT INVENTORY_SNAPSHOTS.is_in_inventory
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
