WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(amount) AS SUM_AMOUNT,
    receiver_id AS RECEIVER_ID
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    created_at >= DATE_TRUNC('DAY', DATEADD(DAY, -150, CURRENT_TIMESTAMP()))
    AND receiver_type = 1
  GROUP BY
    receiver_id
)
SELECT
  MERCHANTS.name AS merchant_name,
  COALESCE(_S1.N_ROWS, 0) AS total_transactions,
  COALESCE(_S1.SUM_AMOUNT, 0) AS total_amount
FROM MAIN.MERCHANTS AS MERCHANTS
LEFT JOIN _S1 AS _S1
  ON MERCHANTS.mid = _S1.RECEIVER_ID
ORDER BY
  COALESCE(_S1.SUM_AMOUNT, 0) DESC NULLS LAST
LIMIT 2
