WITH _S1 AS (
  SELECT
    COALESCE(SUM(sale_price), 0) AS TOTAL_REVENUE,
    COUNT(*) AS N_ROWS,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    DATEDIFF(DAY, CAST(sale_date AS DATETIME), CURRENT_TIMESTAMP()) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  _S1.N_ROWS AS total_sales,
  _S1.TOTAL_REVENUE AS total_revenue
FROM MAIN.SALESPERSONS AS SALESPERSONS
JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  _S1.N_ROWS DESC NULLS LAST
LIMIT 5
