WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE,
    car_id AS CAR_ID
  FROM MAIN.SALES
  GROUP BY
    car_id
)
SELECT
  CARS.make,
  CARS.model,
  COALESCE(_S1.N_ROWS, 0) AS total_sales,
  COALESCE(_S1.SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.CARS AS CARS
LEFT JOIN _S1 AS _S1
  ON CARS._id = _S1.CAR_ID
ORDER BY
  TOTAL_REVENUE DESC NULLS LAST
LIMIT 5
