WITH _S1 AS (
  SELECT
    EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) AS MONTH_SBTXDATETIME,
    EXTRACT(YEAR FROM CAST(sbtxdatetime AS DATETIME)) AS YEAR_SBTXDATETIME,
    sbtxcustid AS SBTXCUSTID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  GROUP BY
    EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)),
    EXTRACT(YEAR FROM CAST(sbtxdatetime AS DATETIME)),
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  NVL(_S1.N_ROWS, 0) AS num_transactions
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN _S1 _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
  AND _S1.MONTH_SBTXDATETIME = EXTRACT(MONTH FROM CAST(SBCUSTOMER.sbcustjoindate AS DATETIME))
  AND _S1.YEAR_SBTXDATETIME = EXTRACT(YEAR FROM CAST(SBCUSTOMER.sbcustjoindate AS DATETIME))
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
