SELECT
  CUSTOMERS.STATE AS state,
  COUNT(DISTINCT SALES.CUSTOMER_ID) AS unique_customers,
  COALESCE(SUM(SALES.SALE_PRICE), 0) AS total_revenue
FROM MAIN.SALES SALES
JOIN MAIN.CUSTOMERS CUSTOMERS
  ON CUSTOMERS."_id" = SALES.CUSTOMER_ID
GROUP BY
  CUSTOMERS.STATE
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
