SELECT
  (
    (
      AVG(CAST(DAY100_PASI_SCORE AS DOUBLE PRECISION)) - AVG(CAST(DAY7_PASI_SCORE AS DOUBLE PRECISION))
    ) / NULLIF(AVG(CAST(DAY7_PASI_SCORE AS DOUBLE PRECISION)), 0)
  ) * 100 AS d7d100pir
FROM MAIN.OUTCOMES
WHERE
  NOT DAY100_PASI_SCORE IS NULL AND NOT DAY7_PASI_SCORE IS NULL
