WITH "_s3" AS (
  SELECT
    TREATMENTS.DRUG_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.ADVERSE_EVENTS ADVERSE_EVENTS
    ON ADVERSE_EVENTS.TREATMENT_ID = TREATMENTS.TREATMENT_ID
    AND TRUNC(CAST(ADVERSE_EVENTS.REPORTED_DT AS DATE), 'MONTH') = TRUNC(CAST(TREATMENTS.START_DT AS DATE), 'MONTH')
  GROUP BY
    TREATMENTS.DRUG_ID
)
SELECT
  DRUGS.DRUG_ID AS drug_id,
  DRUGS.DRUG_NAME AS drug_name,
  "_s3".N_ROWS AS num_adverse_events
FROM MAIN.DRUGS DRUGS
JOIN "_s3" "_s3"
  ON DRUGS.DRUG_ID = "_s3".DRUG_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
