SELECT
  NULLIF(COUNT(*), 0) AS n_transactions,
  COALESCE(SUM(SBTRANSACTION.sbtxamount), 0) AS total_amount
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON LOWER(SBCUSTOMER.sbcustcountry) = 'usa'
  AND SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
WHERE
  SBTRANSACTION.sbtxdatetime < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'WEEK')
  AND SBTRANSACTION.sbtxdatetime >= (
    TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'WEEK') + NUMTODSINTERVAL(1, 'week')
  )
