SELECT
  ANY_VALUE(CONFERENCE.NAME) AS name,
  COUNT(PUBLICATION.CID) AS count_publications
FROM MAIN.CONFERENCE CONFERENCE
LEFT JOIN MAIN.PUBLICATION PUBLICATION
  ON CONFERENCE.CID = PUBLICATION.CID
GROUP BY
  CONFERENCE.CID
ORDER BY
  2 DESC NULLS LAST,
  1 DESC NULLS LAST
