SELECT
  ANY_VALUE(USERS.USERNAME) AS username,
  COUNT(*) AS total_unread_notifs
FROM MAIN.USERS USERS
JOIN MAIN.NOTIFICATIONS NOTIFICATIONS
  ON NOTIFICATIONS.STATUS = 'unread'
  AND NOTIFICATIONS.TYPE = 'promotion'
  AND NOTIFICATIONS.USER_ID = USERS.UID
WHERE
  LOWER(USERS.COUNTRY) = 'us'
GROUP BY
  NOTIFICATIONS.USER_ID
