WITH "_u_0" AS (
  SELECT
    USER_ID AS "_u_1"
  FROM MAIN.NOTIFICATIONS
  GROUP BY
    USER_ID
)
SELECT
  USERS.UID AS uid,
  USERS.USERNAME AS username
FROM MAIN.USERS USERS
LEFT JOIN "_u_0" "_u_0"
  ON USERS.UID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
