WITH _S0 AS (
  SELECT
    SALES._id AS _ID,
    SALES.salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES AS SALES
), _T0 AS (
  SELECT
    PAYMENTS_RECEIVED.payment_method AS PAYMENT_METHOD,
    PAYMENTS_RECEIVED.sale_id AS SALE_ID
  FROM MAIN.PAYMENTS_RECEIVED AS PAYMENTS_RECEIVED
), _S1 AS (
  SELECT
    _T0.SALE_ID AS SALE_ID
  FROM _T0 AS _T0
  WHERE
    _T0.PAYMENT_METHOD = 'cash'
), _S3 AS (
  SELECT
    _S0.SALESPERSON_ID AS SALESPERSON_ID
  FROM _S0 AS _S0
  JOIN _S1 AS _S1
    ON _S0._ID = _S1.SALE_ID
), _S2 AS (
  SELECT
    SALESPERSONS._id AS _ID,
    SALESPERSONS._id AS SALESPERSON_ID
  FROM MAIN.SALESPERSONS AS SALESPERSONS
)
SELECT
  _S2.SALESPERSON_ID AS salesperson_id
FROM _S2 AS _S2
WHERE
  EXISTS(
    SELECT
      1 AS "1"
    FROM _S3 AS _S3
    WHERE
      _S2._ID = _S3.SALESPERSON_ID
  )
