WITH _S1 AS (
  SELECT
    SALES.customer_id AS CUSTOMER_ID
  FROM MAIN.SALES AS SALES
), _S0 AS (
  SELECT
    CUSTOMERS._id AS _ID
  FROM MAIN.CUSTOMERS AS CUSTOMERS
)
SELECT
  _S0._ID AS _id
FROM _S0 AS _S0
WHERE
  EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0._ID = _S1.CUSTOMER_ID
  )
