WITH _T AS (
  SELECT
    marketing_opt_in AS MARKETING_OPT_IN,
    user_id AS USER_ID,
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) AS _W
  FROM MAIN.USER_SETTING_SNAPSHOT
)
SELECT
  USERS.uid,
  _T.MARKETING_OPT_IN AS marketing_opt_in
FROM MAIN.USERS USERS
JOIN _T _T
  ON USERS.uid = _T.USER_ID AND _T._W = 1
