WITH _T0 AS (
  SELECT
    INVENTORY_SNAPSHOTS.car_id AS CAR_ID,
    INVENTORY_SNAPSHOTS.is_in_inventory AS IS_IN_INVENTORY,
    INVENTORY_SNAPSHOTS.snapshot_date AS SNAPSHOT_DATE
  FROM MAIN.INVENTORY_SNAPSHOTS AS INVENTORY_SNAPSHOTS
), _S3 AS (
  SELECT
    _T0.CAR_ID AS CAR_ID
  FROM _T0 AS _T0
  WHERE
    _S0.SALE_DATE = _T0.SNAPSHOT_DATE AND _T0.IS_IN_INVENTORY = 0
), _S1 AS (
  SELECT
    SALES.car_id AS CAR_ID,
    SALES.sale_date AS SALE_DATE,
    SALES.sale_price AS SALE_PRICE
  FROM MAIN.SALES AS SALES
), _S2 AS (
  SELECT
    CARS._id AS _ID_1_0_1,
    CARS.make AS MAKE,
    CARS.model AS MODEL
  FROM MAIN.CARS AS CARS
), _S0 AS (
  SELECT
    _S2._ID_1_0_1 AS _ID_1,
    _S2.MAKE AS MAKE,
    _S2.MODEL AS MODEL,
    _S1.SALE_DATE AS SALE_DATE,
    _S1.SALE_PRICE AS SALE_PRICE
  FROM _S1 AS _S1
  JOIN _S2 AS _S2
    ON _S1.CAR_ID = _S2._ID_1_0_1
)
SELECT
  _S0.MAKE AS make,
  _S0.MODEL AS model,
  _S0.SALE_PRICE AS sale_price
FROM _S0 AS _S0
WHERE
  EXISTS(
    SELECT
      1 AS "1"
    FROM _S3 AS _S3
    WHERE
      _S0._ID_1 = _S3.CAR_ID
  )
ORDER BY
  SALE_PRICE DESC NULLS LAST
LIMIT 1
