WITH _S3 AS (
  SELECT
    COUNT(*) AS AGG_0,
    COUPONS.merchant_id AS MERCHANT_ID
  FROM MAIN.COUPONS AS COUPONS
  JOIN MAIN.MERCHANTS AS MERCHANTS
    ON COUPONS.merchant_id = MERCHANTS.mid
    AND DATEDIFF(MONTH, MERCHANTS.created_at, COUPONS.created_at) = 0
  GROUP BY
    COUPONS.merchant_id
)
SELECT
  MERCHANTS.mid AS merchant_id,
  MERCHANTS.name AS merchant_name,
  COALESCE(_S3.AGG_0, 0) AS coupons_per_merchant
FROM MAIN.MERCHANTS AS MERCHANTS
LEFT JOIN _S3 AS _S3
  ON MERCHANTS.mid = _S3.MERCHANT_ID
ORDER BY
  COUPONS_PER_MERCHANT DESC NULLS LAST
LIMIT 1
