WITH _S1 AS (
  SELECT
    COUNT(*) AS AGG_0,
    SUM(sale_price) AS AGG_1,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  COALESCE(_S1.AGG_1, 0) AS total_sales,
  _S1.AGG_0 AS num_sales,
  RANK() OVER (ORDER BY COALESCE(_S1.AGG_1, 0) DESC) AS sales_rank
FROM MAIN.SALESPERSONS AS SALESPERSONS
JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  COALESCE(_S1.AGG_1, 0) DESC NULLS LAST
