WITH _S0 AS (
  SELECT
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(sbdpdate AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME))), (
          2 * -1
        ))
      END
    ) AS MONTH,
    sbdptickerid AS SBDPTICKERID,
    COUNT(sbdpclose) AS COUNT_SBDPCLOSE,
    MAX(sbdphigh) AS MAX_SBDPHIGH,
    MIN(sbdplow) AS MIN_SBDPLOW,
    SUM(sbdpclose) AS SUM_SBDPCLOSE
  FROM MAIN.SBDAILYPRICE
  GROUP BY
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(sbdpdate AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(sbdpdate AS DATETIME))), (
          2 * -1
        ))
      END
    ),
    sbdptickerid
), _T0 AS (
  SELECT
    _S0.MONTH,
    SBTICKER.sbtickersymbol AS SBTICKERSYMBOL,
    MAX(_S0.MAX_SBDPHIGH) AS MAX_MAX_SBDPHIGH,
    MIN(_S0.MIN_SBDPLOW) AS MIN_MIN_SBDPLOW,
    SUM(_S0.COUNT_SBDPCLOSE) AS SUM_COUNT_SBDPCLOSE,
    SUM(_S0.SUM_SBDPCLOSE) AS SUM_SUM_SBDPCLOSE
  FROM _S0 _S0
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.sbtickerid = _S0.SBDPTICKERID
  GROUP BY
    _S0.MONTH,
    SBTICKER.sbtickersymbol
)
SELECT
  SBTICKERSYMBOL AS symbol,
  MONTH AS month,
  SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE AS avg_close,
  MAX_MAX_SBDPHIGH AS max_high,
  MIN_MIN_SBDPLOW AS min_low,
  (
    (
      SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE
    ) - LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH)
  ) / LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH) AS momc
FROM _T0
