SELECT
  CONCAT_WS(
    '-',
    EXTRACT(YEAR FROM CAST(start_dt AS DATETIME)),
    CASE
      WHEN LENGTH(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))) >= 2
      THEN SUBSTRING(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME)), 1, 2)
      ELSE SUBSTRING(CONCAT('00', EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))), (
        2 * -1
      ))
    END
  ) AS month,
  COUNT(DISTINCT diag_id) AS PMPD,
  COUNT(*) AS PMTC
FROM main.treatments
WHERE
  DATE_ADD(DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()), -12, 'MONTH') <= DATE_TRUNC('MONTH', CAST(start_dt AS TIMESTAMP))
  AND DATE_TRUNC('MONTH', CAST(start_dt AS TIMESTAMP)) < DATE_TRUNC('MONTH', CURRENT_TIMESTAMP())
GROUP BY
  CONCAT_WS(
    '-',
    EXTRACT(YEAR FROM CAST(start_dt AS DATETIME)),
    CASE
      WHEN LENGTH(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))) >= 2
      THEN SUBSTRING(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME)), 1, 2)
      ELSE SUBSTRING(CONCAT('00', EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))), (
        2 * -1
      ))
    END
  )
ORDER BY
  month DESC
