WITH _T1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    COUNT_IF(sbtxstatus = 'success') AS SUM_EXPR_2,
    sbtxcustid AS SBTXCUSTID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    3
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  (
    100.0 * COALESCE(_T1.SUM_EXPR_2, 0)
  ) / _T1.N_ROWS AS success_rate
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
JOIN _T1 AS _T1
  ON SBCUSTOMER.sbcustid = _T1.SBTXCUSTID AND _T1.N_ROWS >= 5
ORDER BY
  2 NULLS FIRST
