SELECT
  MEDIAN(WALLET_MERCHANT_BALANCE_DAILY.balance) AS _expr0
FROM MAIN.WALLET_MERCHANT_BALANCE_DAILY AS WALLET_MERCHANT_BALANCE_DAILY
JOIN MAIN.MERCHANTS AS MERCHANTS
  ON CONTAINS(LOWER(MERCHANTS.category), 'retail')
  AND MERCHANTS.mid = WALLET_MERCHANT_BALANCE_DAILY.merchant_id
  AND MERCHANTS.status = 'active'
WHERE
  DATE_TRUNC('DAY', CAST(WALLET_MERCHANT_BALANCE_DAILY.updated_at AS TIMESTAMP)) = DATE_TRUNC('DAY', CURRENT_TIMESTAMP())
