SELECT
  COUNT(DISTINCT TREATMENTS.PATIENT_ID) AS patient_count
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DIAGNOSES DIAGNOSES
  ON DIAGNOSES.DIAG_ID = TREATMENTS.DIAG_ID
  AND LOWER(DIAGNOSES.DIAG_NAME) = 'psoriasis vulgaris'
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND LOWER(DRUGS.DRUG_TYPE) = 'biologic'
