SELECT
  SBTICKER.sbtickerid AS "_id"
FROM MAIN.SBTICKER SBTICKER
JOIN MAIN.SBDAILYPRICE SBDAILYPRICE
  ON SBDAILYPRICE.sbdpdate >= TO_DATE('2023-04-01', 'YYYY-MM-DD')
  AND SBDAILYPRICE.sbdptickerid = SBTICKER.sbtickerid
