WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    sbtxcustid AS SBTXCUSTID
  FROM MAIN.SBTRANSACTION
  WHERE
    CAST(sbtxdatetime AS TIMESTAMP) < CAST('2023-04-02' AS DATE)
    AND CAST(sbtxdatetime AS TIMESTAMP) >= CAST('2023-04-01' AS DATE)
    AND sbtxtype = 'sell'
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S1.N_ROWS, 0) AS num_tx
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
ORDER BY
  COALESCE(_S1.N_ROWS, 0) DESC NULLS LAST
LIMIT 1
