WITH "_s1" AS (
  SELECT
    SALESPERSON_ID,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS."_id",
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name,
  COALESCE("_s1".SUM_SALE_PRICE, 0) AS total
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_s1" "_s1"
  ON SALESPERSONS."_id" = "_s1".SALESPERSON_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
