WITH "_s1" AS (
  SELECT
    SBTXTICKERID,
    COUNT(*) AS N_ROWS,
    SUM(SBTXAMOUNT) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXTICKERID
)
SELECT
  SBTICKER.SBTICKERSYMBOL AS symbol,
  COALESCE("_s1".N_ROWS, 0) AS num_transactions,
  COALESCE("_s1".SUM_SBTXAMOUNT, 0) AS total_amount
FROM MAIN.SBTICKER SBTICKER
LEFT JOIN "_s1" "_s1"
  ON SBTICKER.SBTICKERID = "_s1".SBTXTICKERID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
