SELECT
  CAST(COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) AS DOUBLE PRECISION) / COUNT(*) AS _expr0
FROM main.wallet_transactions_daily
WHERE
  CAST(EXTRACT(YEAR FROM CAST(AGE(CURRENT_TIMESTAMP, CAST(created_at AS TIMESTAMP)) AS TIMESTAMP)) * 12 + EXTRACT(MONTH FROM CAST(AGE(CURRENT_TIMESTAMP, CAST(created_at AS TIMESTAMP)) AS TIMESTAMP)) AS BIGINT) = 1
