SELECT
  USERS.COUNTRY AS country,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.SENDER_ID) AS user_count,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0) AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
LEFT JOIN MAIN.USERS USERS
  ON USERS.UID = WALLET_TRANSACTIONS_DAILY.SENDER_ID
WHERE
  WALLET_TRANSACTIONS_DAILY.SENDER_TYPE = 0
GROUP BY
  USERS.COUNTRY
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
