WITH "_s1" AS (
  SELECT
    DOC_ID,
    COUNT(DISTINCT DRUG_ID) AS NDISTINCT_DRUG_ID
  FROM MAIN.TREATMENTS
  GROUP BY
    DOC_ID
)
SELECT
  DOCTORS.DOC_ID AS doc_id,
  DOCTORS.SPECIALTY AS specialty,
  "_s1".NDISTINCT_DRUG_ID AS num_distinct_drugs,
  DENSE_RANK() OVER (PARTITION BY DOCTORS.SPECIALTY ORDER BY "_s1".NDISTINCT_DRUG_ID DESC) AS SDRSDR
FROM MAIN.DOCTORS DOCTORS
JOIN "_s1" "_s1"
  ON DOCTORS.DOC_ID = "_s1".DOC_ID
