SELECT
  WALLET_TRANSACTIONS_DAILY.receiver_id AS merchants_id,
  ANY_VALUE(MERCHANTS.name) AS merchants_name,
  ANY_VALUE(MERCHANTS.category) AS category,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) AS total_revenue,
  ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) DESC) AS mrr
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON MERCHANTS.mid = WALLET_TRANSACTIONS_DAILY.receiver_id
  AND WALLET_TRANSACTIONS_DAILY.receiver_type = 1
  AND WALLET_TRANSACTIONS_DAILY.status = 'success'
GROUP BY
  WALLET_TRANSACTIONS_DAILY.receiver_id
