WITH _T0 AS (
  SELECT
    COUNT(*) AS AGG_0,
    COUNT_IF((
      (
        DAYOFWEEK(PAYMENTS_RECEIVED.payment_date) + 6
      ) % 7
    ) IN (5, 6)) AS AGG_1,
    DATE_TRUNC('WEEK', CAST(PAYMENTS_RECEIVED.payment_date AS TIMESTAMP)) AS PAYMENT_WEEK
  FROM MAIN.PAYMENTS_RECEIVED AS PAYMENTS_RECEIVED
  JOIN MAIN.SALES AS SALES
    ON PAYMENTS_RECEIVED.sale_id = SALES._id AND SALES.sale_price > 30000
  WHERE
    DATEDIFF(WEEK, PAYMENTS_RECEIVED.payment_date, CURRENT_TIMESTAMP()) <= 8
    AND DATEDIFF(WEEK, PAYMENTS_RECEIVED.payment_date, CURRENT_TIMESTAMP()) >= 1
  GROUP BY
    DATE_TRUNC('WEEK', CAST(PAYMENTS_RECEIVED.payment_date AS TIMESTAMP))
)
SELECT
  PAYMENT_WEEK AS payment_week,
  AGG_0 AS total_payments,
  COALESCE(AGG_1, 0) AS weekend_payments
FROM _T0
