WITH "_s1" AS (
  SELECT
    AMOUNT,
    RECEIVER_ID
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    CREATED_AT >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) - NUMTODSINTERVAL(150, 'day'), 'DD')
    AND RECEIVER_TYPE = 1
)
SELECT
  ANY_VALUE(MERCHANTS.NAME) AS merchant_name,
  COUNT("_s1".RECEIVER_ID) AS total_transactions,
  COALESCE(SUM("_s1".AMOUNT), 0) AS total_amount
FROM MAIN.MERCHANTS MERCHANTS
LEFT JOIN "_s1" "_s1"
  ON MERCHANTS.MID = "_s1".RECEIVER_ID
GROUP BY
  MERCHANTS.MID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 2 ROWS ONLY
