WITH "_u_0" AS (
  SELECT
    AUTHOR.OID AS "_u_1"
  FROM MAIN.AUTHOR AUTHOR
  JOIN MAIN.WRITES WRITES
    ON AUTHOR.AID = WRITES.AID
  JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
    ON DOMAIN_PUBLICATION.PID = WRITES.PID
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.DID = DOMAIN_PUBLICATION.DID AND DOMAIN.NAME = 'Machine Learning'
  GROUP BY
    AUTHOR.OID
)
SELECT
  ORGANIZATION.NAME AS oranization_name,
  ORGANIZATION.OID AS organization_id
FROM MAIN.ORGANIZATION ORGANIZATION
LEFT JOIN "_u_0" "_u_0"
  ON ORGANIZATION.OID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
