WITH _S1 AS (
  SELECT
    MAX(payment_date) AS MAX_PAYMENT_DATE,
    sale_id AS SALE_ID
  FROM MAIN.PAYMENTS_RECEIVED
  GROUP BY
    sale_id
)
SELECT
  ROUND(
    AVG(
      DATEDIFF(DAY, CAST(SALES.sale_date AS DATETIME), CAST(_S1.MAX_PAYMENT_DATE AS DATETIME))
    ),
    2
  ) AS avg_days_to_payment
FROM MAIN.SALES AS SALES
LEFT JOIN _S1 AS _S1
  ON SALES._id = _S1.SALE_ID
