WITH "_t0" AS (
  SELECT
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (ORDER BY WALLET_MERCHANT_BALANCE_DAILY.BALANCE DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(WALLET_MERCHANT_BALANCE_DAILY.BALANCE) OVER () - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN WALLET_MERCHANT_BALANCE_DAILY.BALANCE
      ELSE NULL
    END AS EXPR_1
  FROM MAIN.WALLET_MERCHANT_BALANCE_DAILY WALLET_MERCHANT_BALANCE_DAILY
  JOIN MAIN.MERCHANTS MERCHANTS
    ON LOWER(MERCHANTS.CATEGORY) LIKE '%retail%'
    AND MERCHANTS.MID = WALLET_MERCHANT_BALANCE_DAILY.MERCHANT_ID
    AND MERCHANTS.STATUS = 'active'
  WHERE
    TRUNC(CAST(CAST(WALLET_MERCHANT_BALANCE_DAILY.UPDATED_AT AS DATE) AS DATE), 'DD') = TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DD')
)
SELECT
  AVG(EXPR_1) AS "_expr0"
FROM "_t0"
