WITH "_t" AS (
  SELECT
    CAR_ID,
    IS_IN_INVENTORY,
    RANK() OVER (ORDER BY SNAPSHOT_DATE DESC) AS "_w"
  FROM MAIN.INVENTORY_SNAPSHOTS
  WHERE
    EXTRACT(MONTH FROM CAST(SNAPSHOT_DATE AS DATE)) = 3
    AND EXTRACT(YEAR FROM CAST(SNAPSHOT_DATE AS DATE)) = 2023
)
SELECT
  CARS."_id",
  CARS.MAKE AS make,
  CARS.MODEL AS model,
  CARS.YEAR AS year
FROM "_t" "_t"
JOIN MAIN.CARS CARS
  ON CARS."_id" = "_t".CAR_ID
WHERE
  "_t".IS_IN_INVENTORY AND "_t"."_w" = 1
