WITH "_S1" AS (
  SELECT
    sbtxcustid AS SBTXCUSTID,
    COUNT(*) AS N_ROWS,
    SUM(sbtxamount) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  "_S1".N_ROWS AS num_tx,
  NVL("_S1".SUM_SBTXAMOUNT, 0) AS total_amount,
  RANK() OVER (ORDER BY NVL("_S1".SUM_SBTXAMOUNT, 0) DESC) AS cust_rank
FROM MAIN.SBCUSTOMER SBCUSTOMER
JOIN "_S1" "_S1"
  ON SBCUSTOMER.sbcustid = "_S1".SBTXCUSTID
