WITH _S1 AS (
  SELECT
    AVG(sale_price) AS AGG_0,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  _S1.AGG_0 AS ASP
FROM MAIN.SALESPERSONS AS SALESPERSONS
LEFT JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  ASP DESC NULLS LAST
LIMIT 3
