WITH "_t1" AS (
  SELECT
    ANY_VALUE(ORGANIZATION.CONTINENT) AS ANYTHING_CONTINENT,
    COUNT(AUTHOR.OID) AS COUNT_OID
  FROM MAIN.ORGANIZATION ORGANIZATION
  LEFT JOIN MAIN.AUTHOR AUTHOR
    ON AUTHOR.OID = ORGANIZATION.OID
  GROUP BY
    ORGANIZATION.OID
)
SELECT
  ANYTHING_CONTINENT AS continent,
  COALESCE(SUM(COUNT_OID), 0) / COUNT(*) AS ratio
FROM "_t1"
GROUP BY
  ANYTHING_CONTINENT
ORDER BY
  2 DESC NULLS LAST
