WITH "_u_0" AS (
  SELECT
    SALES.SALESPERSON_ID AS "_u_1"
  FROM MAIN.SALES SALES
  JOIN MAIN.PAYMENTS_RECEIVED PAYMENTS_RECEIVED
    ON PAYMENTS_RECEIVED.PAYMENT_METHOD = 'cash'
    AND PAYMENTS_RECEIVED.SALE_ID = SALES."_id"
  GROUP BY
    SALES.SALESPERSON_ID
)
SELECT
  SALESPERSONS."_id" AS salesperson_id
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_u_0" "_u_0"
  ON SALESPERSONS."_id" = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
