WITH _S0 AS (
  SELECT
    COUNT(*) AS NUM_TRANSACTIONS,
    sbtxcustid AS SBTXCUSTID,
    sbtxtickerid AS SBTXTICKERID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    2,
    3
), _S2 AS (
  SELECT
    SUM(_S0.NUM_TRANSACTIONS) AS NUM_TRANSACTIONS,
    SBTICKER.sbtickertype AS SBTICKERTYPE,
    _S0.SBTXCUSTID
  FROM _S0 AS _S0
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = _S0.SBTXTICKERID
  GROUP BY
    2,
    3
)
SELECT
  SBCUSTOMER.sbcuststate AS state,
  _S2.SBTICKERTYPE AS ticker_type,
  SUM(_S2.NUM_TRANSACTIONS) AS num_transactions
FROM _S2 AS _S2
JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
  ON SBCUSTOMER.sbcustid = _S2.SBTXCUSTID
GROUP BY
  1,
  2
ORDER BY
  3 DESC NULLS LAST
LIMIT 5
