SELECT
  WALLET_TRANSACTIONS_DAILY.RECEIVER_ID AS merchants_id,
  ANY_VALUE(MERCHANTS.NAME) AS merchants_name,
  ANY_VALUE(MERCHANTS.CATEGORY) AS category,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0) AS total_revenue,
  ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0) DESC) AS mrr
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON MERCHANTS.MID = WALLET_TRANSACTIONS_DAILY.RECEIVER_ID
  AND WALLET_TRANSACTIONS_DAILY.RECEIVER_TYPE = 1
  AND WALLET_TRANSACTIONS_DAILY.STATUS = 'success'
GROUP BY
  WALLET_TRANSACTIONS_DAILY.RECEIVER_ID
