WITH _S1 AS (
  SELECT
    COUNT(*) AS AGG_0,
    sbtxcustid AS CUSTOMER_ID
  FROM MAIN.SBTRANSACTION
  WHERE
    CAST(sbtxdatetime AS TIMESTAMP) < CAST('2023-04-02' AS DATE)
    AND CAST(sbtxdatetime AS TIMESTAMP) >= CAST('2023-04-01' AS DATE)
    AND sbtxtype = 'sell'
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S1.AGG_0, 0) AS num_tx
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.CUSTOMER_ID
ORDER BY
  NUM_TX DESC NULLS LAST
LIMIT 1
