WITH "_S1" AS (
  SELECT
    salesperson_id AS SALESPERSON_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SALES
  WHERE
    DATEDIFF(CURRENT_TIMESTAMP, CAST(sale_date AS DATETIME), DAY) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS."_id",
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  "_S1".N_ROWS AS num_sales
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN "_S1" "_S1"
  ON SALESPERSONS."_id" = "_S1".SALESPERSON_ID
ORDER BY
  4 DESC NULLS LAST,
  1 NULLS FIRST
