WITH "_t1" AS (
  SELECT
    ANY_VALUE(TREATMENTS.DIAG_ID) AS ANYTHING_DIAG_ID,
    ANY_VALUE(TREATMENTS.PATIENT_ID) AS ANYTHING_PATIENT_ID,
    MAX(OUTCOMES.DAY100_ITCH_VAS) AS MAX_DAY100_ITCH_VAS
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.OUTCOMES OUTCOMES
    ON OUTCOMES.TREATMENT_ID = TREATMENTS.TREATMENT_ID
  GROUP BY
    OUTCOMES.TREATMENT_ID
), "_s3" AS (
  SELECT
    ANYTHING_DIAG_ID,
    MAX(MAX_DAY100_ITCH_VAS) AS MAX_MAX_DAY100_ITCH_VAS,
    COUNT(DISTINCT ANYTHING_PATIENT_ID) AS NDISTINCT_ANYTHING_PATIENT_ID
  FROM "_t1"
  GROUP BY
    ANYTHING_DIAG_ID
)
SELECT
  DIAGNOSES.DIAG_NAME AS diagnosis_name,
  "_s3".NDISTINCT_ANYTHING_PATIENT_ID AS num_patients,
  "_s3".MAX_MAX_DAY100_ITCH_VAS AS max_itch_score
FROM MAIN.DIAGNOSES DIAGNOSES
JOIN "_s3" "_s3"
  ON DIAGNOSES.DIAG_ID = "_s3".ANYTHING_DIAG_ID
ORDER BY
  3 DESC NULLS LAST,
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
