WITH "_t0" AS (
  SELECT
    WRITES.AID,
    COUNT(DISTINCT DOMAIN_PUBLICATION.DID) AS NDISTINCT_DID
  FROM MAIN.WRITES WRITES
  JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
    ON DOMAIN_PUBLICATION.PID = WRITES.PID
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.DID = DOMAIN_PUBLICATION.DID
    AND DOMAIN.NAME IN ('Data Science', 'Machine Learning')
  GROUP BY
    WRITES.AID
)
SELECT
  AUTHOR.NAME AS name
FROM MAIN.AUTHOR AUTHOR
JOIN "_t0" "_t0"
  ON AUTHOR.AID = "_t0".AID AND "_t0".NDISTINCT_DID = 2
