WITH "_u_0" AS (
  SELECT
    DOMAIN_CONFERENCE.CID AS "_u_1",
    WRITES.PID AS "_u_2"
  FROM MAIN.WRITES WRITES
  JOIN MAIN.DOMAIN_AUTHOR DOMAIN_AUTHOR
    ON DOMAIN_AUTHOR.AID = WRITES.AID
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.DID = DOMAIN_AUTHOR.DID AND LOWER(DOMAIN.NAME) LIKE '%sociology%'
  JOIN MAIN.DOMAIN_CONFERENCE DOMAIN_CONFERENCE
    ON DOMAIN.DID = DOMAIN_CONFERENCE.DID
  GROUP BY
    DOMAIN_CONFERENCE.CID,
    WRITES.PID
)
SELECT
  PUBLICATION.TITLE AS title
FROM MAIN.PUBLICATION PUBLICATION
LEFT JOIN "_u_0" "_u_0"
  ON PUBLICATION.CID = "_u_0"."_u_1" AND PUBLICATION.PID = "_u_0"."_u_2"
WHERE
  NOT "_u_0"."_u_1" IS NULL AND PUBLICATION.YEAR = 2020
