SELECT
  COUNT(*) AS TUC
FROM MAIN.USER_SESSIONS
WHERE
  session_end_ts >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -1), 'DAY')
  OR session_start_ts >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -1), 'DAY')
