WITH "_u_0" AS (
  SELECT
    DRUG_ID AS "_u_1"
  FROM MAIN.TREATMENTS
  GROUP BY
    DRUG_ID
)
SELECT
  DRUGS.DRUG_ID AS drug_id,
  DRUGS.DRUG_NAME AS drug_name
FROM MAIN.DRUGS DRUGS
LEFT JOIN "_u_0" "_u_0"
  ON DRUGS.DRUG_ID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
