WITH "_S0" AS (
  SELECT
    city_name AS CITY_NAME,
    COUNT(*) AS N_ROWS
  FROM MAIN.RESTAURANT
  GROUP BY
    city_name
)
SELECT
  GEOGRAPHIC.region AS rest_region,
  SUM("_S0".N_ROWS) AS n_restaurants
FROM "_S0" "_S0"
JOIN MAIN.GEOGRAPHIC GEOGRAPHIC
  ON GEOGRAPHIC.city_name = "_S0".CITY_NAME
GROUP BY
  GEOGRAPHIC.region
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
