WITH "_S1" AS (
  SELECT
    salesperson_id AS SALESPERSON_ID,
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  COALESCE("_S1".SUM_SALE_PRICE, 0) AS total_sales,
  "_S1".N_ROWS AS num_sales,
  RANK() OVER (ORDER BY COALESCE("_S1".SUM_SALE_PRICE, 0) DESC) AS sales_rank
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN "_S1" "_S1"
  ON SALESPERSONS."_id" = "_S1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
