SELECT
  MIN(SBDAILYPRICE.sbdpclose) AS lowest_price
FROM MAIN.SBDAILYPRICE AS SBDAILYPRICE
JOIN MAIN.SBTICKER AS SBTICKER
  ON SBDAILYPRICE.sbdptickerid = SBTICKER.sbtickerid
  AND SBTICKER.sbtickersymbol = 'VTI'
WHERE
  DATEDIFF(DAY, SBDAILYPRICE.sbdpdate, CURRENT_TIMESTAMP()) <= 7
