WITH "_u_0" AS (
  SELECT
    patient_id AS "_u_1"
  FROM MAIN.TREATMENTS
  GROUP BY
    patient_id
), "_T1" AS (
  SELECT
    MIN(EXTRACT(YEAR FROM CAST(TREATMENTS.start_dt AS DATE))) AS MIN_YEAR_START_DT
  FROM MAIN.PATIENTS PATIENTS
  LEFT JOIN "_u_0" "_u_0"
    ON PATIENTS.patient_id = "_u_0"."_u_1"
  LEFT JOIN MAIN.TREATMENTS TREATMENTS
    ON PATIENTS.patient_id = TREATMENTS.patient_id
  WHERE
    NOT "_u_0"."_u_1" IS NULL
  GROUP BY
    PATIENTS.patient_id
), "_T0" AS (
  SELECT
    MIN_YEAR_START_DT,
    COUNT(*) AS N_ROWS
  FROM "_T1"
  GROUP BY
    MIN_YEAR_START_DT
)
SELECT
  CAST(MIN_YEAR_START_DT AS VARCHAR2(4000)) AS year,
  N_ROWS AS number_of_new_patients,
  CASE
    WHEN (
      N_ROWS - COALESCE(LAG(N_ROWS, 1) OVER (ORDER BY MIN_YEAR_START_DT), N_ROWS)
    ) <> 0
    THEN N_ROWS - COALESCE(LAG(N_ROWS, 1) OVER (ORDER BY MIN_YEAR_START_DT), N_ROWS)
    ELSE NULL
  END AS npi
FROM "_T0"
ORDER BY
  1 NULLS FIRST
