SELECT
  SBCUSTCOUNTRY AS country,
  100 * (
    COALESCE(SUM(SBCUSTSTATUS = 'active'), 0) / COUNT(*)
  ) AS ar
FROM MAIN.SBCUSTOMER
WHERE
  SBCUSTJOINDATE <= TO_DATE('2022-12-31', 'YYYY-MM-DD')
  AND SBCUSTJOINDATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
GROUP BY
  SBCUSTCOUNTRY
