WITH _T2 AS (
  SELECT
    SBTRANSACTION.sbtxamount AS AMOUNT,
    SBTRANSACTION.sbtxcustid AS CUSTOMER_ID,
    SBTRANSACTION.sbtxdatetime AS DATE_TIME
  FROM MAIN.SBTRANSACTION AS SBTRANSACTION
), _S0 AS (
  SELECT
    _T2.AMOUNT AS AMOUNT,
    _T2.CUSTOMER_ID AS CUSTOMER_ID
  FROM _T2 AS _T2
  WHERE
    _T2.DATE_TIME < DATE_TRUNC('WEEK', CURRENT_TIMESTAMP())
    AND _T2.DATE_TIME >= DATEADD(WEEK, -1, DATE_TRUNC('WEEK', CURRENT_TIMESTAMP()))
), _T3 AS (
  SELECT
    SBCUSTOMER.sbcustid AS _ID,
    SBCUSTOMER.sbcustcountry AS COUNTRY
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
), _S1 AS (
  SELECT
    _T3._ID AS _ID
  FROM _T3 AS _T3
  WHERE
    LOWER(_T3.COUNTRY) = 'usa'
), _T1 AS (
  SELECT
    _S0.AMOUNT AS AMOUNT
  FROM _S0 AS _S0
  WHERE
    EXISTS(
      SELECT
        1 AS "1"
      FROM _S1 AS _S1
      WHERE
        _S0.CUSTOMER_ID = _S1._ID
    )
), _T0 AS (
  SELECT
    COUNT(*) AS AGG_0,
    SUM(_T1.AMOUNT) AS AGG_1
  FROM _T1 AS _T1
)
SELECT
  CASE WHEN _T0.AGG_0 > 0 THEN _T0.AGG_0 ELSE NULL END AS n_transactions,
  COALESCE(_T0.AGG_1, 0) AS total_amount
FROM _T0 AS _T0
