WITH _T0 AS (
  SELECT
    marketing_opt_in AS MARKETING_OPT_IN,
    user_id AS USER_ID
  FROM MAIN.USER_SETTING_SNAPSHOT
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) = 1
)
SELECT
  USERS.uid,
  _T0.MARKETING_OPT_IN AS marketing_opt_in
FROM MAIN.USERS AS USERS
JOIN _T0 AS _T0
  ON USERS.uid = _T0.USER_ID
