SELECT
  COUNT(*) AS num_transactions,
  CASE
    WHEN COUNT(*) > 0
    THEN COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0)
    ELSE NULL
  END AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS AS USERS
  ON USERS.country = 'US' AND USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
WHERE
  DATEDIFF(DAY, CAST(WALLET_TRANSACTIONS_DAILY.created_at AS DATETIME), CURRENT_TIMESTAMP()) <= 7
