SELECT
  COUNT(*) AS n_customers
FROM MAIN.SBCUSTOMER SBCUSTOMER
JOIN MAIN.SBTRANSACTION SBTRANSACTION
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
JOIN MAIN.SBTICKER SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  AND SBTICKER.sbtickersymbol IN ('AMZN', 'AAPL', 'GOOGL', 'META', 'NFLX')
WHERE
  SBCUSTOMER.sbcustemail LIKE '%.com'
