SELECT
  USERS.country,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.sender_id) AS user_count,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
LEFT JOIN MAIN.USERS USERS
  ON USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
WHERE
  WALLET_TRANSACTIONS_DAILY.sender_type = 0
GROUP BY
  USERS.country
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
