SELECT
  MIN(SBDAILYPRICE.SBDPCLOSE) AS lowest_price
FROM MAIN.SBDAILYPRICE SBDAILYPRICE
JOIN MAIN.SBTICKER SBTICKER
  ON SBDAILYPRICE.SBDPTICKERID = SBTICKER.SBTICKERID
  AND SBTICKER.SBTICKERSYMBOL = 'VTI'
WHERE
  (
    TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(SBDAILYPRICE.SBDPDATE AS DATE) AS DATE), 'DD')
  ) <= 7
