WITH "_t2" AS (
  SELECT
    END_DT,
    PATIENT_ID,
    TREATMENT_ID
  FROM MAIN.TREATMENTS
  WHERE
    EXTRACT(YEAR FROM CAST(END_DT AS DATE)) = 2022
), "_t3" AS (
  SELECT
    DAY100_PASI_SCORE,
    TREATMENT_ID
  FROM MAIN.OUTCOMES
  WHERE
    NOT DAY100_PASI_SCORE IS NULL
), "_u_0" AS (
  SELECT
    TREATMENT_ID AS "_u_1"
  FROM "_t3"
  GROUP BY
    TREATMENT_ID
), "_s3" AS (
  SELECT
    INS_TYPE,
    PATIENT_ID
  FROM MAIN.PATIENTS
), "_s10" AS (
  SELECT
    "_s3".INS_TYPE,
    COUNT(DISTINCT "_t2".PATIENT_ID) AS NDISTINCT_PATIENT_ID
  FROM "_t2" "_t2"
  LEFT JOIN "_u_0" "_u_0"
    ON "_t2".TREATMENT_ID = "_u_0"."_u_1"
  JOIN "_s3" "_s3"
    ON "_s3".PATIENT_ID = "_t2".PATIENT_ID
  WHERE
    NOT "_u_0"."_u_1" IS NULL
  GROUP BY
    "_s3".INS_TYPE
), "_u_2" AS (
  SELECT
    TREATMENT_ID AS "_u_3"
  FROM "_t3"
  GROUP BY
    TREATMENT_ID
), "_s9" AS (
  SELECT
    TREATMENT_ID,
    COUNT(DAY100_PASI_SCORE) AS COUNT_DAY100_PASI_SCORE,
    SUM(DAY100_PASI_SCORE) AS SUM_DAY100_PASI_SCORE
  FROM MAIN.OUTCOMES
  GROUP BY
    TREATMENT_ID
), "_s11" AS (
  SELECT
    SUM("_s9".SUM_DAY100_PASI_SCORE) / SUM("_s9".COUNT_DAY100_PASI_SCORE) AS AVG_DAY100_PASI_SCORE,
    "_s7".INS_TYPE
  FROM "_t2" "_t6"
  LEFT JOIN "_u_2" "_u_2"
    ON "_t6".TREATMENT_ID = "_u_2"."_u_3"
  JOIN "_s3" "_s7"
    ON "_s7".PATIENT_ID = "_t6".PATIENT_ID
  JOIN "_s9" "_s9"
    ON "_s9".TREATMENT_ID = "_t6".TREATMENT_ID
  WHERE
    NOT "_u_2"."_u_3" IS NULL
  GROUP BY
    "_s7".INS_TYPE
)
SELECT
  "_s10".INS_TYPE AS insurance_type,
  "_s10".NDISTINCT_PATIENT_ID AS num_distinct_patients,
  "_s11".AVG_DAY100_PASI_SCORE AS avg_pasi_score_day100
FROM "_s10" "_s10"
LEFT JOIN "_s11" "_s11"
  ON "_s10".INS_TYPE = "_s11".INS_TYPE
ORDER BY
  3 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
