SELECT
  COUNT(*) AS num_treatments
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DIAGNOSES DIAGNOSES
  ON DIAGNOSES.DIAG_ID = TREATMENTS.DIAG_ID
  AND LOWER(DIAGNOSES.DIAG_NAME) LIKE '%psoriasis%'
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND NOT DRUGS.FDA_APPR_DT IS NULL
WHERE
  NOT TREATMENTS.END_DT IS NULL
  AND TREATMENTS.END_DT >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -6), 'DD')
