SELECT
  COUNT(*) AS patient_count
FROM MAIN.PATIENTS PATIENTS
JOIN MAIN.TREATMENTS TREATMENTS
  ON PATIENTS.patient_id = TREATMENTS.patient_id
JOIN MAIN.DIAGNOSES DIAGNOSES
  ON DIAGNOSES.diag_id = TREATMENTS.diag_id
  AND LOWER(DIAGNOSES.diag_name) = 'psoriasis vulgaris'
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.drug_id = TREATMENTS.drug_id AND LOWER(DRUGS.drug_type) = 'biologic'
