WITH _u_0 AS (
  SELECT
    SALES.salesperson_id AS _u_1
  FROM MAIN.SALES AS SALES
  JOIN MAIN.PAYMENTS_RECEIVED AS PAYMENTS_RECEIVED
    ON PAYMENTS_RECEIVED.payment_method = 'cash'
    AND PAYMENTS_RECEIVED.sale_id = SALES._id
  GROUP BY
    SALES.salesperson_id
)
SELECT
  SALESPERSONS._id AS salesperson_id
FROM MAIN.SALESPERSONS AS SALESPERSONS
LEFT JOIN _u_0 AS _u_0
  ON SALESPERSONS._id = _u_0._u_1
WHERE
  NOT _u_0._u_1 IS NULL
