WITH "_u_0" AS (
  SELECT
    MERCHANT_ID AS "_u_1"
  FROM MAIN.COUPONS
  GROUP BY
    MERCHANT_ID
)
SELECT
  MERCHANTS.MID AS merchant_id,
  MERCHANTS.NAME AS merchant_name
FROM MAIN.MERCHANTS MERCHANTS
LEFT JOIN "_u_0" "_u_0"
  ON MERCHANTS.MID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
