WITH _S1 AS (
  SELECT
    SBTRANSACTION.sbtxcustid AS CUSTOMER_ID
  FROM MAIN.SBTRANSACTION AS SBTRANSACTION
), _S0 AS (
  SELECT
    SBCUSTOMER.sbcustid AS _ID,
    SBCUSTOMER.sbcustname AS NAME
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
)
SELECT
  _S0._ID AS _id,
  _S0.NAME AS name
FROM _S0 AS _S0
WHERE
  NOT EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0._ID = _S1.CUSTOMER_ID
  )
