WITH _S1 AS (
  SELECT
    country AS COUNTRY,
    uid AS UID
  FROM MAIN.USERS
)
SELECT
  _S1.COUNTRY AS country,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.sender_id) AS user_count,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
LEFT JOIN _S1 AS _S1
  ON WALLET_TRANSACTIONS_DAILY.sender_id = _S1.UID
WHERE
  WALLET_TRANSACTIONS_DAILY.sender_type = 0
GROUP BY
  _S1.COUNTRY
ORDER BY
  TOTAL_AMOUNT DESC NULLS LAST
LIMIT 5
