SELECT
  DATE_TRUNC('MONTH', CAST(WALLET_TRANSACTIONS_DAILY.created_at AS TIMESTAMP)) AS month,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.sender_id) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS AS USERS
  ON USERS.status = 'active' AND USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
WHERE
  WALLET_TRANSACTIONS_DAILY.sender_type = 0
  AND WALLET_TRANSACTIONS_DAILY.status = 'success'
  AND YEAR(WALLET_TRANSACTIONS_DAILY.created_at) = 2023
GROUP BY
  DATE_TRUNC('MONTH', CAST(WALLET_TRANSACTIONS_DAILY.created_at AS TIMESTAMP))
