WITH "_s0" AS (
  SELECT
    SBTXCUSTID,
    SBTXTICKERID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID,
    SBTXTICKERID
), "_s2" AS (
  SELECT
    SBTICKER.SBTICKERTYPE,
    "_s0".SBTXCUSTID,
    SUM("_s0".N_ROWS) AS SUM_N_ROWS
  FROM "_s0" "_s0"
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.SBTICKERID = "_s0".SBTXTICKERID
  GROUP BY
    SBTICKER.SBTICKERTYPE,
    "_s0".SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTSTATE AS state,
  "_s2".SBTICKERTYPE AS ticker_type,
  SUM("_s2".SUM_N_ROWS) AS num_transactions
FROM "_s2" "_s2"
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON SBCUSTOMER.SBCUSTID = "_s2".SBTXCUSTID
GROUP BY
  SBCUSTOMER.SBCUSTSTATE,
  "_s2".SBTICKERTYPE
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
