SELECT
  NULLIF(COUNT(*), 0) AS n_transactions,
  NVL(SUM(SBTRANSACTION.sbtxamount), 0) AS total_amount
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON LOWER(SBCUSTOMER.sbcustcountry) = 'usa'
  AND SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
WHERE
  SBTRANSACTION.sbtxdatetime < TRUNC(CURRENT_TIMESTAMP, 'WEEK')
  AND SBTRANSACTION.sbtxdatetime >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'WEEK'), 1, WEEK)
