WITH "_s1" AS (
  SELECT
    DRUG_ID,
    AVG(TOT_DRUG_AMT) AS AVG_TOT_DRUG_AMT,
    COUNT(*) AS N_ROWS
  FROM MAIN.TREATMENTS
  GROUP BY
    DRUG_ID
)
SELECT
  DRUGS.DRUG_NAME AS drug_name,
  COALESCE("_s1".N_ROWS, 0) AS num_treatments,
  "_s1".AVG_TOT_DRUG_AMT AS avg_drug_amount
FROM MAIN.DRUGS DRUGS
LEFT JOIN "_s1" "_s1"
  ON DRUGS.DRUG_ID = "_s1".DRUG_ID
ORDER BY
  2 DESC NULLS LAST,
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
