WITH "_s1" AS (
  SELECT
    TRUNC(CAST(PAYMENT_DATE AS DATE), 'MONTH') AS START_MONTH,
    SUM(PAYMENT_AMOUNT) AS SUM_PAYMENT_AMOUNT
  FROM MAIN.PAYMENTS_RECEIVED
  GROUP BY
    TRUNC(CAST(PAYMENT_DATE AS DATE), 'MONTH')
), "_t0" AS (
  SELECT
    DATETIME("_s1".START_MONTH, MONTHS.N || ' months') AS DT,
    SUM(CASE WHEN MONTHS.N > 0 THEN 0 ELSE COALESCE("_s1".SUM_PAYMENT_AMOUNT, 0) END) AS SUM_PAYMENT
  FROM (VALUES
    (0),
    (1),
    (2),
    (3),
    (4),
    (5),
    (6),
    (7),
    (8),
    (9),
    (10),
    (11)) AS MONTHS(N)
  JOIN "_s1" "_s1"
    ON (
      TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTODSINTERVAL(1, 'hour')
    ) >= DATETIME("_s1".START_MONTH, MONTHS.N || ' months')
  GROUP BY
    DATETIME("_s1".START_MONTH, MONTHS.N || ' months')
)
SELECT
  DT AS dt,
  SUM_PAYMENT AS total_payments,
  SUM_PAYMENT - LAG(SUM_PAYMENT, 1) OVER (ORDER BY DT) AS MoM_change
FROM "_t0"
ORDER BY
  1 NULLS FIRST
