SELECT
  COUNT(*) AS transaction_count
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  AND SBCUSTOMER.sbcustjoindate >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 70, DAY), 'DAY')
