WITH "_u_0" AS (
  SELECT
    PATIENT_ID AS "_u_1"
  FROM MAIN.TREATMENTS
  GROUP BY
    PATIENT_ID
)
SELECT
  PATIENTS.PATIENT_ID AS patient_id,
  PATIENTS.FIRST_NAME AS first_name,
  PATIENTS.LAST_NAME AS last_name
FROM MAIN.PATIENTS PATIENTS
LEFT JOIN "_u_0" "_u_0"
  ON PATIENTS.PATIENT_ID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
