WITH "_s1" AS (
  SELECT
    DID,
    COUNT(*) AS N_ROWS
  FROM MAIN.DOMAIN_PUBLICATION
  GROUP BY
    DID
), "_s3" AS (
  SELECT
    DID,
    COUNT(*) AS N_ROWS
  FROM MAIN.DOMAIN_KEYWORD
  GROUP BY
    DID
)
SELECT
  DOMAIN.DID AS domain_id,
  COALESCE("_s1".N_ROWS, 0) / NULLIF("_s3".N_ROWS, 0) AS ratio
FROM MAIN.DOMAIN DOMAIN
LEFT JOIN "_s1" "_s1"
  ON DOMAIN.DID = "_s1".DID
LEFT JOIN "_s3" "_s3"
  ON DOMAIN.DID = "_s3".DID
