SELECT
  ANY_VALUE(COUPONS.CODE) AS coupon_code,
  COUNT(WALLET_TRANSACTIONS_DAILY.TXID) AS redemption_count,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0) AS total_discount
FROM MAIN.COUPONS COUPONS
LEFT JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON COUPONS.CID = WALLET_TRANSACTIONS_DAILY.COUPON_ID
GROUP BY
  COUPONS.CID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
