SELECT
  COUNT(*) AS transaction_count
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON SBCUSTOMER.SBCUSTID = SBTRANSACTION.SBTXCUSTID
  AND SBCUSTOMER.SBCUSTJOINDATE >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) - NUMTODSINTERVAL(70, 'day'), 'DD')
