SELECT
  AVG(PATIENTS.weight_kg) AS avg_weight
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.drug_id = TREATMENTS.drug_id AND LOWER(DRUGS.drug_name) = 'drugalin'
JOIN MAIN.PATIENTS PATIENTS
  ON PATIENTS.patient_id = TREATMENTS.patient_id
