WITH "_s1" AS (
  SELECT
    SBTXTICKERID,
    SUM(SBTXTAX + SBTXCOMMISSION) AS SUM_EXPR,
    SUM(SBTXAMOUNT) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  WHERE
    SBTXDATETIME >= ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -1)
    AND SBTXTYPE = 'sell'
  GROUP BY
    SBTXTICKERID
)
SELECT
  SBTICKER.SBTICKERSYMBOL AS symbol,
  (
    100.0 * (
      COALESCE("_s1".SUM_SBTXAMOUNT, 0) - COALESCE("_s1".SUM_EXPR, 0)
    )
  ) / NULLIF("_s1".SUM_SBTXAMOUNT, 0) AS SPM
FROM MAIN.SBTICKER SBTICKER
JOIN "_s1" "_s1"
  ON SBTICKER.SBTICKERID = "_s1".SBTXTICKERID
ORDER BY
  1 NULLS FIRST
