SELECT
  (
    (
      COALESCE(SUM(SALES.sale_price), 0) - COALESCE(SUM(CARS.cost), 0)
    ) / COALESCE(SUM(CARS.cost), 0)
  ) * 100 AS GPM
FROM MAIN.SALES AS SALES
JOIN MAIN.CARS AS CARS
  ON CARS._id = SALES.car_id
WHERE
  YEAR(SALES.sale_date) = 2023
