WITH "_s1" AS (
  SELECT
    SALE_ID,
    MAX(PAYMENT_DATE) AS MAX_PAYMENT_DATE
  FROM MAIN.PAYMENTS_RECEIVED
  GROUP BY
    SALE_ID
)
SELECT
  ROUND(
    AVG(
      TRUNC(CAST(CAST("_s1".MAX_PAYMENT_DATE AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(SALES.SALE_DATE AS DATE) AS DATE), 'DD')
    ),
    2
  ) AS avg_days_to_payment
FROM MAIN.SALES SALES
LEFT JOIN "_s1" "_s1"
  ON SALES."_id" = "_s1".SALE_ID
