SELECT
  AVG(PATIENTS.WEIGHT_KG) AS avg_weight
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND LOWER(DRUGS.DRUG_NAME) = 'drugalin'
JOIN MAIN.PATIENTS PATIENTS
  ON PATIENTS.PATIENT_ID = TREATMENTS.PATIENT_ID
