WITH _T1 AS (
  SELECT
    MIN(EXTRACT(YEAR FROM CAST(TREATMENTS_2.start_dt AS DATETIME))) AS MIN_YEAR_START_DT
  FROM MAIN.PATIENTS PATIENTS
  JOIN MAIN.TREATMENTS TREATMENTS
    ON PATIENTS.patient_id = TREATMENTS.patient_id
  LEFT JOIN MAIN.TREATMENTS TREATMENTS_2
    ON PATIENTS.patient_id = TREATMENTS_2.patient_id
  GROUP BY
    PATIENTS.patient_id
), _T0 AS (
  SELECT
    MIN_YEAR_START_DT,
    COUNT(*) AS N_ROWS
  FROM _T1
  GROUP BY
    MIN_YEAR_START_DT
)
SELECT
  CAST(MIN_YEAR_START_DT AS CLOB) AS year,
  N_ROWS AS number_of_new_patients,
  CASE
    WHEN (
      N_ROWS - NVL(LAG(N_ROWS, 1) OVER (ORDER BY MIN_YEAR_START_DT), N_ROWS)
    ) <> 0
    THEN N_ROWS - NVL(LAG(N_ROWS, 1) OVER (ORDER BY MIN_YEAR_START_DT), N_ROWS)
    ELSE NULL
  END AS npi
FROM _T0
ORDER BY
  1 NULLS FIRST
