WITH _S0 AS (
  SELECT
    SUM(sale_price) AS SUM_SALE_PRICE,
    car_id AS CAR_ID
  FROM MAIN.SALES
  WHERE
    DATE_PART(YEAR, CAST(sale_date AS DATETIME)) = 2023
  GROUP BY
    car_id
)
SELECT
  (
    (
      COALESCE(SUM(_S0.SUM_SALE_PRICE), 0) - COALESCE(SUM(CARS.cost), 0)
    ) / COALESCE(SUM(CARS.cost), 0)
  ) * 100 AS GPM
FROM _S0 AS _S0
JOIN MAIN.CARS AS CARS
  ON CARS._id = _S0.CAR_ID
