WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    COUPONS.merchant_id AS MERCHANT_ID
  FROM MAIN.COUPONS AS COUPONS
  JOIN MAIN.MERCHANTS AS MERCHANTS
    ON COUPONS.merchant_id = MERCHANTS.mid
    AND DATEDIFF(MONTH, CAST(MERCHANTS.created_at AS DATETIME), CAST(COUPONS.created_at AS DATETIME)) = 0
  GROUP BY
    2
)
SELECT
  MERCHANTS.mid AS merchant_id,
  MERCHANTS.name AS merchant_name,
  COALESCE(_S3.N_ROWS, 0) AS coupons_per_merchant
FROM MAIN.MERCHANTS AS MERCHANTS
LEFT JOIN _S3 AS _S3
  ON MERCHANTS.mid = _S3.MERCHANT_ID
ORDER BY
  3 DESC NULLS LAST
LIMIT 1
