WITH "_u_0" AS (
  SELECT
    SBDPTICKERID AS "_u_1"
  FROM MAIN.SBDAILYPRICE
  GROUP BY
    SBDPTICKERID
)
SELECT
  SBTICKER.SBTICKERID AS "_id",
  SBTICKER.SBTICKERSYMBOL AS symbol
FROM MAIN.SBTICKER SBTICKER
LEFT JOIN "_u_0" "_u_0"
  ON SBTICKER.SBTICKERID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
