SELECT
  COUNT(SBTRANSACTION.sbtxcustid) AS transaction_count
FROM MAIN.SBTRANSACTION AS SBTRANSACTION
JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  AND SBCUSTOMER.sbcustjoindate >= DATEADD(DAY, -70, CURRENT_TIMESTAMP())
