SELECT DISTINCT
  AUTHOR.name AS author_name
FROM MAIN.AUTHOR AUTHOR
JOIN MAIN.WRITES WRITES
  ON AUTHOR.aid = WRITES.aid
JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
  ON DOMAIN_PUBLICATION.pid = WRITES.pid
JOIN MAIN.DOMAIN DOMAIN
  ON DOMAIN.did = DOMAIN_PUBLICATION.did AND DOMAIN.name = 'Computer Science'
