WITH "_s1" AS (
  SELECT
    DOC_ID,
    COUNT(*) AS N_ROWS,
    SUM(TOT_DRUG_AMT) AS SUM_TOT_DRUG_AMT
  FROM MAIN.TREATMENTS
  WHERE
    START_DT >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -6), 'DD')
  GROUP BY
    DOC_ID
), "_t1" AS (
  SELECT
    DOCTORS.SPECIALTY,
    SUM("_s1".N_ROWS) AS SUM_N_ROWS,
    SUM("_s1".SUM_TOT_DRUG_AMT) AS SUM_SUM_TOT_DRUG_AMT
  FROM MAIN.DOCTORS DOCTORS
  LEFT JOIN "_s1" "_s1"
    ON DOCTORS.DOC_ID = "_s1".DOC_ID
  GROUP BY
    DOCTORS.SPECIALTY
)
SELECT
  SPECIALTY AS specialty,
  SUM_N_ROWS AS num_treatments,
  COALESCE(SUM_SUM_TOT_DRUG_AMT, 0) AS total_drug_amount
FROM "_t1"
WHERE
  SUM_N_ROWS <> 0
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
