SELECT
  TRUNC(
    CAST(CAST(NOTIFICATIONS.CREATED_AT AS DATE) - MOD((
      TO_CHAR(CAST(NOTIFICATIONS.CREATED_AT AS DATE), 'D') + 5
    ), 7) AS DATE),
    'DD'
  ) AS week,
  COUNT(*) AS num_notifs,
  SUM((
    MOD((
      TO_CHAR(NOTIFICATIONS.CREATED_AT, 'D') + 5
    ), 7)
  ) IN (5, 6)) AS weekend_notifs
FROM MAIN.NOTIFICATIONS NOTIFICATIONS
JOIN MAIN.USERS USERS
  ON NOTIFICATIONS.USER_ID = USERS.UID AND USERS.COUNTRY IN ('US', 'CA')
WHERE
  NOTIFICATIONS.CREATED_AT < TRUNC(
    SYS_EXTRACT_UTC(SYSTIMESTAMP) - MOD((
      TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'D') + 5
    ), 7),
    'DD'
  )
  AND NOTIFICATIONS.CREATED_AT >= (
    TRUNC(
      SYS_EXTRACT_UTC(SYSTIMESTAMP) - MOD((
        TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'D') + 5
      ), 7),
      'DD'
    ) - NUMTODSINTERVAL(21, 'DAY')
  )
GROUP BY
  TRUNC(
    CAST(CAST(NOTIFICATIONS.CREATED_AT AS DATE) - MOD((
      TO_CHAR(CAST(NOTIFICATIONS.CREATED_AT AS DATE), 'D') + 5
    ), 7) AS DATE),
    'DD'
  )
