SELECT
  CUSTOMERS.state,
  COUNT(DISTINCT SALES.customer_id) AS unique_customers,
  COALESCE(SUM(SALES.sale_price), 0) AS total_revenue
FROM MAIN.SALES AS SALES
JOIN MAIN.CUSTOMERS AS CUSTOMERS
  ON CUSTOMERS._id = SALES.customer_id
GROUP BY
  CUSTOMERS.state
ORDER BY
  COALESCE(SUM(SALES.sale_price), 0) DESC NULLS LAST
LIMIT 5
