SELECT
  TRUNC(CAST(WALLET_TRANSACTIONS_DAILY.CREATED_AT AS DATE), 'MONTH') AS month,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.SENDER_ID) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS USERS
  ON USERS.STATUS = 'active' AND USERS.UID = WALLET_TRANSACTIONS_DAILY.SENDER_ID
WHERE
  EXTRACT(YEAR FROM CAST(WALLET_TRANSACTIONS_DAILY.CREATED_AT AS DATE)) = 2023
  AND WALLET_TRANSACTIONS_DAILY.SENDER_TYPE = 0
  AND WALLET_TRANSACTIONS_DAILY.STATUS = 'success'
GROUP BY
  TRUNC(CAST(WALLET_TRANSACTIONS_DAILY.CREATED_AT AS DATE), 'MONTH')
