WITH "_s1" AS (
  SELECT
    SBTXCUSTID,
    COUNT(*) AS N_ROWS,
    SUM(SBTXAMOUNT) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  WHERE
    SBTXDATETIME >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) - NUMTODSINTERVAL(30, 'day'), 'DD')
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTCOUNTRY AS country,
  COALESCE(SUM("_s1".N_ROWS), 0) AS num_transactions,
  COALESCE(SUM("_s1".SUM_SBTXAMOUNT), 0) AS total_amount
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
GROUP BY
  SBCUSTOMER.SBCUSTCOUNTRY
