WITH _S0 AS (
  SELECT
    COUNT(sbdpclose) AS COUNT_SBDPCLOSE,
    MAX(sbdphigh) AS MAX_HIGH,
    MIN(sbdplow) AS MIN_LOW,
    SUM(sbdpclose) AS SUM_SBDPCLOSE,
    CONCAT_WS(
      '-',
      DATE_PART(YEAR, CAST(sbdpdate AS DATETIME)),
      CASE
        WHEN LENGTH(DATE_PART(MONTH, CAST(sbdpdate AS DATETIME))) >= 2
        THEN SUBSTRING(DATE_PART(MONTH, CAST(sbdpdate AS DATETIME)), 1, 2)
        ELSE SUBSTRING(CONCAT('00', DATE_PART(MONTH, CAST(sbdpdate AS DATETIME))), (
          2 * -1
        ))
      END
    ) AS MONTH,
    sbdptickerid AS SBDPTICKERID
  FROM MAIN.SBDAILYPRICE
  GROUP BY
    CONCAT_WS(
      '-',
      DATE_PART(YEAR, CAST(sbdpdate AS DATETIME)),
      CASE
        WHEN LENGTH(DATE_PART(MONTH, CAST(sbdpdate AS DATETIME))) >= 2
        THEN SUBSTRING(DATE_PART(MONTH, CAST(sbdpdate AS DATETIME)), 1, 2)
        ELSE SUBSTRING(CONCAT('00', DATE_PART(MONTH, CAST(sbdpdate AS DATETIME))), (
          2 * -1
        ))
      END
    ),
    sbdptickerid
), _T0 AS (
  SELECT
    SUM(_S0.SUM_SBDPCLOSE) / SUM(_S0.COUNT_SBDPCLOSE) AS AVG_CLOSE,
    MAX(_S0.MAX_HIGH) AS MAX_HIGH,
    MIN(_S0.MIN_LOW) AS MIN_LOW,
    _S0.MONTH,
    SBTICKER.sbtickersymbol AS SBTICKERSYMBOL
  FROM _S0 AS _S0
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = _S0.SBDPTICKERID
  GROUP BY
    _S0.MONTH,
    SBTICKER.sbtickersymbol
)
SELECT
  SBTICKERSYMBOL AS symbol,
  MONTH AS month,
  AVG_CLOSE AS avg_close,
  MAX_HIGH AS max_high,
  MIN_LOW AS min_low,
  (
    AVG_CLOSE - LAG(AVG_CLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH)
  ) / LAG(AVG_CLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH) AS momc
FROM _T0
