SELECT
  COUNT(*) AS transaction_count
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  AND SBCUSTOMER.sbcustjoindate >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(70, 'day'), 'DAY')
