SELECT DISTINCT
  DOCTORS.LOC_STATE AS state
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND DRUGS.DRUG_TYPE = 'biologic'
JOIN MAIN.DOCTORS DOCTORS
  ON DOCTORS.DOC_ID = TREATMENTS.DOC_ID
