WITH "_u_0" AS (
  SELECT
    TREATMENTS.PATIENT_ID AS "_u_1"
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.OUTCOMES OUTCOMES
    ON OUTCOMES.TREATMENT_ID = TREATMENTS.TREATMENT_ID
  GROUP BY
    TREATMENTS.PATIENT_ID
)
SELECT
  PATIENTS.PATIENT_ID AS patient_id,
  PATIENTS.FIRST_NAME AS first_name,
  PATIENTS.LAST_NAME AS last_name
FROM MAIN.PATIENTS PATIENTS
LEFT JOIN "_u_0" "_u_0"
  ON PATIENTS.PATIENT_ID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
