WITH _S1 AS (
  SELECT
    NOTIFICATIONS.user_id AS USER_ID
  FROM MAIN.NOTIFICATIONS AS NOTIFICATIONS
), _S0 AS (
  SELECT
    USERS.uid AS UID,
    USERS.username AS USERNAME
  FROM MAIN.USERS AS USERS
)
SELECT
  _S0.UID AS uid,
  _S0.USERNAME AS username
FROM _S0 AS _S0
WHERE
  NOT EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0.UID = _S1.USER_ID
  )
