SELECT
  TRUNC(CAST(WALLET_TRANSACTIONS_DAILY.created_at AS TIMESTAMP), 'MONTH') AS month,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.sender_id) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS USERS
  ON USERS.status = 'active' AND USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
WHERE
  EXTRACT(YEAR FROM CAST(WALLET_TRANSACTIONS_DAILY.created_at AS DATE)) = 2023
  AND WALLET_TRANSACTIONS_DAILY.sender_type = 0
  AND WALLET_TRANSACTIONS_DAILY.status = 'success'
GROUP BY
  TRUNC(CAST(WALLET_TRANSACTIONS_DAILY.created_at AS TIMESTAMP), 'MONTH')
