WITH "_t1" AS (
  SELECT
    SBTXCUSTID,
    COUNT(*) AS N_ROWS,
    SUM(SBTXSTATUS = 'success') AS SUM_EXPR
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTNAME AS name,
  (
    100.0 * COALESCE("_t1".SUM_EXPR, 0)
  ) / "_t1".N_ROWS AS success_rate
FROM MAIN.SBCUSTOMER SBCUSTOMER
JOIN "_t1" "_t1"
  ON SBCUSTOMER.SBCUSTID = "_t1".SBTXCUSTID AND "_t1".N_ROWS >= 5
ORDER BY
  2 NULLS FIRST
