WITH _S1 AS (
  SELECT
    city_name AS CITY_NAME,
    region AS REGION
  FROM MAIN.GEOGRAPHIC
), _S6 AS (
  SELECT DISTINCT
    _S1.REGION
  FROM MAIN.LOCATION LOCATION
  LEFT JOIN _S1 _S1
    ON LOCATION.city_name = _S1.CITY_NAME
), _S7 AS (
  SELECT
    _S3.REGION,
    SUM(CASE WHEN NOT RESTAURANT.rating IS NULL THEN 1 ELSE 0 END) AS SUM_EXPR,
    SUM(RESTAURANT.rating) AS SUM_RATING
  FROM MAIN.LOCATION LOCATION
  LEFT JOIN _S1 _S3
    ON LOCATION.city_name = _S3.CITY_NAME
  JOIN MAIN.RESTAURANT RESTAURANT
    ON LOCATION.restaurant_id = RESTAURANT.id
  GROUP BY
    _S3.REGION
)
SELECT
  _S6.REGION AS region_name,
  _S7.SUM_RATING / _S7.SUM_EXPR AS avg_rating
FROM _S6 _S6
JOIN _S7 _S7
  ON _S6.REGION = _S7.REGION
ORDER BY
  1 NULLS FIRST,
  2 DESC NULLS LAST
