WITH _T0 AS (
  SELECT
    COUNT(*) AS NUM_CUSTOMERS,
    sbcustcountry AS COUNTRY
  FROM MAIN.SBCUSTOMER
  GROUP BY
    sbcustcountry
)
SELECT
  COUNTRY AS country,
  NUM_CUSTOMERS AS num_customers
FROM _T0
ORDER BY
  NUM_CUSTOMERS DESC NULLS LAST
LIMIT 5
