WITH "_u_0" AS (
  SELECT
    SBTRANSACTION.SBTXCUSTID AS "_u_1"
  FROM MAIN.SBTRANSACTION SBTRANSACTION
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.SBTICKERID = SBTRANSACTION.SBTXTICKERID
    AND SBTICKER.SBTICKERSYMBOL IN ('AMZN', 'AAPL', 'GOOGL', 'META', 'NFLX')
  GROUP BY
    SBTRANSACTION.SBTXCUSTID
)
SELECT
  COUNT(*) AS n_customers
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_u_0" "_u_0"
  ON SBCUSTOMER.SBCUSTID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL AND SBCUSTOMER.SBCUSTEMAIL LIKE '%.com'
