WITH "_u_0" AS (
  SELECT
    SBTXCUSTID AS "_u_1"
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTID AS "_id",
  SBCUSTOMER.SBCUSTNAME AS name
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_u_0" "_u_0"
  ON SBCUSTOMER.SBCUSTID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
