SELECT
  COUNT(*) AS TSC
FROM cassandra.defog.sales
WHERE
  DATE_DIFF(
    'DAY',
    CAST(DATE_TRUNC('DAY', CAST(sale_date AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('DAY', CURRENT_TIMESTAMP) AS TIMESTAMP)
  ) <= 7
