WITH "_s1" AS (
  SELECT
    CAR_ID,
    AVG(SALE_PRICE) AS AVG_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    CAR_ID
)
SELECT
  CARS.MAKE AS make,
  CARS.MODEL AS model,
  CARS.YEAR AS year,
  CARS.COLOR AS color,
  CARS.VIN_NUMBER AS vin_number,
  "_s1".AVG_SALE_PRICE AS avg_sale_price
FROM MAIN.CARS CARS
LEFT JOIN "_s1" "_s1"
  ON CARS."_id" = "_s1".CAR_ID
WHERE
  LOWER(CARS.MAKE) LIKE '%fords%' OR LOWER(CARS.MODEL) LIKE '%mustang%'
