SELECT DISTINCT
  AUTHOR.NAME AS author_name
FROM MAIN.AUTHOR AUTHOR
JOIN MAIN.WRITES WRITES
  ON AUTHOR.AID = WRITES.AID
JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
  ON DOMAIN_PUBLICATION.PID = WRITES.PID
JOIN MAIN.DOMAIN DOMAIN
  ON DOMAIN.DID = DOMAIN_PUBLICATION.DID AND DOMAIN.NAME = 'Computer Science'
