SELECT
  ADVERSE_EVENTS.DESCRIPTION AS description,
  ADVERSE_EVENTS.TREATMENT_ID AS treatment_id,
  DRUGS.DRUG_ID AS drug_id,
  DRUGS.DRUG_NAME AS drug_name
FROM MAIN.ADVERSE_EVENTS ADVERSE_EVENTS
JOIN MAIN.TREATMENTS TREATMENTS
  ON ADVERSE_EVENTS.TREATMENT_ID = TREATMENTS.TREATMENT_ID
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND DRUGS.DRUG_TYPE = 'topical'
