WITH _S0 AS (
  SELECT
    DATE_TRUNC('QUARTER', CAST(sale_date AS TIMESTAMP)) AS QUARTER,
    SUM(sale_price) AS SUM_SALE_PRICE,
    customer_id AS CUSTOMER_ID
  FROM MAIN.SALES
  WHERE
    YEAR(CAST(sale_date AS TIMESTAMP)) = 2023
  GROUP BY
    1,
    3
), _T1 AS (
  SELECT
    SUM(_S0.SUM_SALE_PRICE) AS SUM_SUM_SALE_PRICE,
    _S0.QUARTER,
    CUSTOMERS.state AS STATE
  FROM _S0 AS _S0
  JOIN MAIN.CUSTOMERS AS CUSTOMERS
    ON CUSTOMERS._id = _S0.CUSTOMER_ID
  GROUP BY
    2,
    3
)
SELECT
  QUARTER AS quarter,
  STATE AS customer_state,
  COALESCE(SUM_SUM_SALE_PRICE, 0) AS total_sales
FROM _T1
WHERE
  NOT SUM_SUM_SALE_PRICE IS NULL AND SUM_SUM_SALE_PRICE > 0
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
