SELECT
  ANY_VALUE(MERCHANTS.NAME) AS name,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.COUPON_ID) / NULLIF(COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.TXID), 0) AS CPUR
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON MERCHANTS.MID = WALLET_TRANSACTIONS_DAILY.RECEIVER_ID
  AND WALLET_TRANSACTIONS_DAILY.STATUS = 'success'
GROUP BY
  WALLET_TRANSACTIONS_DAILY.RECEIVER_ID
