SELECT
  USER_SESSIONS.USER_ID AS uid,
  SUM(
    (
      CAST(USER_SESSIONS.SESSION_END_TS AS DATE) - CAST(USER_SESSIONS.SESSION_START_TS AS DATE)
    ) * 86400
  ) AS total_duration
FROM MAIN.USERS USERS
JOIN MAIN.USER_SESSIONS USER_SESSIONS
  ON USERS.UID = USER_SESSIONS.USER_ID
  AND USER_SESSIONS.SESSION_END_TS < TO_DATE('2023-06-08', 'YYYY-MM-DD')
  AND USER_SESSIONS.SESSION_START_TS >= TO_DATE('2023-06-01', 'YYYY-MM-DD')
GROUP BY
  USER_SESSIONS.USER_ID
ORDER BY
  2 DESC NULLS LAST
