WITH "_u_0" AS (
  SELECT
    DOC_ID AS "_u_1"
  FROM MAIN.TREATMENTS
  GROUP BY
    DOC_ID
)
SELECT
  DOCTORS.DOC_ID AS doc_id,
  DOCTORS.FIRST_NAME AS first_name,
  DOCTORS.LAST_NAME AS last_name
FROM MAIN.DOCTORS DOCTORS
LEFT JOIN "_u_0" "_u_0"
  ON DOCTORS.DOC_ID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
