WITH _S1 AS (
  SELECT
    did AS DID,
    COUNT(DISTINCT aid) AS NDISTINCT_AID
  FROM MAIN.DOMAIN_AUTHOR
  GROUP BY
    did
)
SELECT
  DOMAIN.name,
  NVL(_S1.NDISTINCT_AID, 0) AS author_count
FROM MAIN.DOMAIN DOMAIN
LEFT JOIN _S1 _S1
  ON DOMAIN.did = _S1.DID
ORDER BY
  2 DESC NULLS LAST,
  1 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
