WITH _S0 AS (
  SELECT
    COUNT(sbdpclose) AS COUNT_SBDPCLOSE,
    MAX(sbdphigh) AS MAX_HIGH,
    MIN(sbdplow) AS MIN_LOW,
    CONCAT_WS('-', YEAR(sbdpdate), LPAD(MONTH(sbdpdate), 2, '0')) AS MONTH,
    SUM(sbdpclose) AS SUM_SBDPCLOSE,
    sbdptickerid AS SBDPTICKERID
  FROM MAIN.SBDAILYPRICE
  GROUP BY
    CONCAT_WS('-', YEAR(sbdpdate), LPAD(MONTH(sbdpdate), 2, '0')),
    sbdptickerid
), _T0 AS (
  SELECT
    MAX(_S0.MAX_HIGH) AS MAX_HIGH,
    MIN(_S0.MIN_LOW) AS MIN_LOW,
    SUM(_S0.COUNT_SBDPCLOSE) AS SUM_COUNT_SBDPCLOSE,
    SUM(_S0.SUM_SBDPCLOSE) AS SUM_SUM_SBDPCLOSE,
    _S0.MONTH,
    SBTICKER.sbtickersymbol AS SBTICKERSYMBOL
  FROM _S0 AS _S0
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = _S0.SBDPTICKERID
  GROUP BY
    _S0.MONTH,
    SBTICKER.sbtickersymbol
)
SELECT
  SBTICKERSYMBOL AS symbol,
  MONTH AS month,
  SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE AS avg_close,
  MAX_HIGH AS max_high,
  MIN_LOW AS min_low,
  (
    (
      SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE
    ) - LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH)
  ) / LAG(SUM_SUM_SBDPCLOSE / SUM_COUNT_SBDPCLOSE, 1) OVER (PARTITION BY SBTICKERSYMBOL ORDER BY MONTH) AS momc
FROM _T0
