WITH "_S7" AS (
  SELECT
    DOMAIN_CONFERENCE.cid AS CID,
    WRITES.pid AS PID
  FROM MAIN.WRITES WRITES
  JOIN MAIN.DOMAIN_AUTHOR DOMAIN_AUTHOR
    ON DOMAIN_AUTHOR.aid = WRITES.aid
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.did = DOMAIN_AUTHOR.did AND LOWER(DOMAIN.name) LIKE '%sociology%'
  JOIN MAIN.DOMAIN_CONFERENCE DOMAIN_CONFERENCE
    ON DOMAIN.did = DOMAIN_CONFERENCE.did
)
SELECT
  PUBLICATION.title
FROM MAIN.PUBLICATION PUBLICATION
JOIN "_S7" "_S7"
  ON PUBLICATION.cid = "_S7".CID AND PUBLICATION.pid = "_S7".PID
WHERE
  PUBLICATION.year = 2020
