SELECT
  CAST(SUM(CASE WHEN NOT cid IS NULL THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / CASE
    WHEN SUM(CASE WHEN NOT jid IS NULL THEN 1 ELSE 0 END) > 0
    THEN SUM(CASE WHEN NOT jid IS NULL THEN 1 ELSE 0 END)
    ELSE NULL
  END AS ratio
FROM main.publication
