WITH _S0 AS (
  SELECT
    NOTIFICATIONS.created_at AS CREATED_AT,
    NOTIFICATIONS.user_id AS USER_ID
  FROM MAIN.NOTIFICATIONS AS NOTIFICATIONS
), _S1 AS (
  SELECT
    USERS.created_at AS CREATED_AT,
    USERS.uid AS UID
  FROM MAIN.USERS AS USERS
), _T0 AS (
  SELECT
    _S0.CREATED_AT AS CREATED_AT,
    _S1.CREATED_AT AS CREATED_AT_1,
    _S0.USER_ID AS USER_ID
  FROM _S0 AS _S0
  JOIN _S1 AS _S1
    ON _S0.USER_ID = _S1.UID
), _S3 AS (
  SELECT
    _T0.USER_ID AS USER_ID
  FROM _T0 AS _T0
  WHERE
    _T0.CREATED_AT <= DATEADD(YEAR, 1, CAST(_T0.CREATED_AT_1 AS TIMESTAMP))
    AND _T0.CREATED_AT >= _T0.CREATED_AT_1
), _S2 AS (
  SELECT
    USERS.created_at AS CREATED_AT,
    USERS.email AS EMAIL,
    USERS.uid AS UID,
    USERS.username AS USERNAME
  FROM MAIN.USERS AS USERS
)
SELECT
  _S2.USERNAME AS username,
  _S2.EMAIL AS email,
  _S2.CREATED_AT AS created_at
FROM _S2 AS _S2
WHERE
  NOT EXISTS(
    SELECT
      1 AS "1"
    FROM _S3 AS _S3
    WHERE
      _S2.UID = _S3.USER_ID
  )
