WITH _S3 AS (
  SELECT
    WRITES.aid AS AID,
    COUNT(DISTINCT PUBLICATION.pid) AS NDISTINCT_PID
  FROM MAIN.WRITES WRITES
  JOIN MAIN.PUBLICATION PUBLICATION
    ON PUBLICATION.pid = WRITES.pid AND PUBLICATION.year = 2021
  GROUP BY
    WRITES.aid
)
SELECT
  AUTHOR.name,
  _S3.NDISTINCT_PID AS count_publication
FROM MAIN.AUTHOR AUTHOR
JOIN _S3 _S3
  ON AUTHOR.aid = _S3.AID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
