SELECT
  SALESPERSONS."_id" AS salesperson_id
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN MAIN.SALES SALES
  ON SALES.salesperson_id = SALESPERSONS."_id"
JOIN MAIN.PAYMENTS_RECEIVED PAYMENTS_RECEIVED
  ON PAYMENTS_RECEIVED.payment_method = 'cash'
  AND PAYMENTS_RECEIVED.sale_id = SALES."_id"
