WITH "_u_0" AS (
  SELECT
    DRUG_ID AS "_u_1"
  FROM MAIN.TREATMENTS
  WHERE
    NOT END_DT IS NULL
  GROUP BY
    DRUG_ID
), "_s3" AS (
  SELECT
    DRUG_ID,
    AVG(
      TOT_DRUG_AMT / CASE
        WHEN (
          TRUNC(CAST(CAST(END_DT AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(START_DT AS DATE) AS DATE), 'DD')
        ) <> 0
        THEN TRUNC(CAST(CAST(END_DT AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(START_DT AS DATE) AS DATE), 'DD')
        ELSE NULL
      END
    ) AS AVG_DDD
  FROM MAIN.TREATMENTS
  WHERE
    NOT END_DT IS NULL
  GROUP BY
    DRUG_ID
)
SELECT
  DRUGS.DRUG_NAME AS drug_name,
  "_s3".AVG_DDD AS avg_ddd
FROM MAIN.DRUGS DRUGS
LEFT JOIN "_u_0" "_u_0"
  ON DRUGS.DRUG_ID = "_u_0"."_u_1"
LEFT JOIN "_s3" "_s3"
  ON DRUGS.DRUG_ID = "_s3".DRUG_ID
WHERE
  NOT "_u_0"."_u_1" IS NULL
