WITH _S2 AS (
  SELECT
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(start_dt AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))), (
          2 * -1
        ))
      END
    ) AS TREATMENT_MONTH,
    COUNT(DISTINCT patient_id) AS NDISTINCT_PATIENT_ID
  FROM MAIN.TREATMENTS
  WHERE
    start_dt < TRUNC(CURRENT_TIMESTAMP, 'MONTH')
    AND start_dt >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'MONTH'), 3, MONTH)
  GROUP BY
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(start_dt AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(start_dt AS DATETIME)), 1, 2)
        ELSE SUBSTR(CONCAT('00', EXTRACT(MONTH FROM CAST(start_dt AS DATETIME))), (
          2 * -1
        ))
      END
    )
), _S3 AS (
  SELECT
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(TREATMENTS.start_dt AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME)), 1, 2)
        ELSE SUBSTR(
          CONCAT('00', EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME))),
          (
            2 * -1
          )
        )
      END
    ) AS TREATMENT_MONTH,
    COUNT(DISTINCT TREATMENTS.patient_id) AS NDISTINCT_PATIENT_ID
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.DRUGS DRUGS
    ON DRUGS.drug_id = TREATMENTS.drug_id AND DRUGS.drug_type = 'biologic'
  WHERE
    TREATMENTS.start_dt < TRUNC(CURRENT_TIMESTAMP, 'MONTH')
    AND TREATMENTS.start_dt >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'MONTH'), 3, MONTH)
  GROUP BY
    LISTAGG(
      '-',
      EXTRACT(YEAR FROM CAST(TREATMENTS.start_dt AS DATETIME)),
      CASE
        WHEN LENGTH(EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME))) >= 2
        THEN SUBSTR(EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME)), 1, 2)
        ELSE SUBSTR(
          CONCAT('00', EXTRACT(MONTH FROM CAST(TREATMENTS.start_dt AS DATETIME))),
          (
            2 * -1
          )
        )
      END
    )
)
SELECT
  _S2.TREATMENT_MONTH AS month,
  _S2.NDISTINCT_PATIENT_ID AS patient_count,
  NVL(_S3.NDISTINCT_PATIENT_ID, 0) AS biologic_treatment_count
FROM _S2 _S2
LEFT JOIN _S3 _S3
  ON _S2.TREATMENT_MONTH = _S3.TREATMENT_MONTH
ORDER BY
  1 DESC NULLS LAST
