SELECT
  ORGANIZATION.name AS oranization_name,
  ORGANIZATION.oid AS organization_id
FROM MAIN.ORGANIZATION ORGANIZATION
JOIN MAIN.AUTHOR AUTHOR
  ON AUTHOR.oid = ORGANIZATION.oid
JOIN MAIN.WRITES WRITES
  ON AUTHOR.aid = WRITES.aid
JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
  ON DOMAIN_PUBLICATION.pid = WRITES.pid
JOIN MAIN.DOMAIN DOMAIN
  ON DOMAIN.did = DOMAIN_PUBLICATION.did AND DOMAIN.name = 'Machine Learning'
