WITH "_s1" AS (
  SELECT
    SALESPERSON_ID,
    COUNT(*) AS N_ROWS,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name,
  COALESCE("_s1".SUM_SALE_PRICE, 0) AS total_sales,
  "_s1".N_ROWS AS num_sales,
  RANK() OVER (ORDER BY COALESCE("_s1".SUM_SALE_PRICE, 0) DESC) AS sales_rank
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN "_s1" "_s1"
  ON SALESPERSONS."_id" = "_s1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
