SELECT
  TREATMENTS_2.TREATMENT_ID AS treatment_id,
  TREATMENTS_2.START_DT AS treatment_start_date,
  TREATMENTS_2.END_DT AS treatment_end_date,
  CONCOMITANT_MEDS.START_DT AS concomitant_med_start_date,
  CONCOMITANT_MEDS.END_DT AS concomitant_med_end_date
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.CONCOMITANT_MEDS CONCOMITANT_MEDS
  ON CONCOMITANT_MEDS.TREATMENT_ID = TREATMENTS.TREATMENT_ID
JOIN MAIN.TREATMENTS TREATMENTS_2
  ON (
    TRUNC(CAST(CAST(CONCOMITANT_MEDS.START_DT AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(TREATMENTS_2.START_DT AS DATE) AS DATE), 'DD')
  ) <= 14
  AND CONCOMITANT_MEDS.TREATMENT_ID = TREATMENTS_2.TREATMENT_ID
  AND TREATMENTS_2.IS_PLACEBO
WHERE
  TREATMENTS.IS_PLACEBO = TRUE
