SELECT DISTINCT
  DOCTORS.loc_state AS state
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.drug_id = TREATMENTS.drug_id AND DRUGS.drug_type = 'biologic'
JOIN MAIN.DOCTORS DOCTORS
  ON DOCTORS.doc_id = TREATMENTS.doc_id
