WITH "_S3" AS (
  SELECT
    TREATMENTS.drug_id AS DRUG_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.ADVERSE_EVENTS ADVERSE_EVENTS
    ON ADVERSE_EVENTS.treatment_id = TREATMENTS.treatment_id
    AND TRUNC(CAST(ADVERSE_EVENTS.reported_dt AS TIMESTAMP), 'MONTH') = TRUNC(CAST(TREATMENTS.start_dt AS TIMESTAMP), 'MONTH')
  GROUP BY
    TREATMENTS.drug_id
)
SELECT
  DRUGS.drug_id,
  DRUGS.drug_name,
  "_S3".N_ROWS AS num_adverse_events
FROM MAIN.DRUGS DRUGS
JOIN "_S3" "_S3"
  ON DRUGS.drug_id = "_S3".DRUG_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
