SELECT
  ANY_VALUE(COUPONS.code) AS coupon_code,
  COUNT(WALLET_TRANSACTIONS_DAILY.txid) AS redemption_count,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) AS total_discount
FROM MAIN.COUPONS COUPONS
LEFT JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON COUPONS.cid = WALLET_TRANSACTIONS_DAILY.coupon_id
GROUP BY
  COUPONS.cid
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
