WITH "_s1" AS (
  SELECT
    SBTXCUSTID,
    COUNT(*) AS N_ROWS,
    SUM(SBTXAMOUNT) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTNAME AS name,
  "_s1".N_ROWS AS num_tx,
  COALESCE("_s1".SUM_SBTXAMOUNT, 0) AS total_amount,
  RANK() OVER (ORDER BY COALESCE("_s1".SUM_SBTXAMOUNT, 0) DESC) AS cust_rank
FROM MAIN.SBCUSTOMER SBCUSTOMER
JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
