WITH "_s3" AS (
  SELECT
    WRITES.AID,
    SUM(PUBLICATION.CITATION_NUM) AS SUM_CITATION_NUM
  FROM MAIN.WRITES WRITES
  JOIN MAIN.PUBLICATION PUBLICATION
    ON PUBLICATION.PID = WRITES.PID
  GROUP BY
    WRITES.AID
)
SELECT
  AUTHOR.NAME AS name,
  COALESCE("_s3".SUM_CITATION_NUM, 0) AS total_citations
FROM MAIN.AUTHOR AUTHOR
JOIN "_s3" "_s3"
  ON AUTHOR.AID = "_s3".AID
