WITH "_T0" AS (
  SELECT
    TRUNC(CAST(start_dt AS DATE), 'MONTH') AS START_MONTH,
    COUNT(*) AS N_ROWS,
    COUNT(DISTINCT diag_id) AS NDISTINCT_DIAG_ID
  FROM MAIN.TREATMENTS
  WHERE
    ADD_MONTHS(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), -12) <= TRUNC(CAST(start_dt AS DATE), 'MONTH')
    AND TRUNC(CAST(start_dt AS DATE), 'MONTH') < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
  GROUP BY
    TRUNC(CAST(start_dt AS DATE), 'MONTH')
)
SELECT
  NVL(EXTRACT(YEAR FROM START_MONTH), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM START_MONTH), 2, '0'), '') AS start_month,
  NDISTINCT_DIAG_ID AS PMPD,
  N_ROWS AS PMTC
FROM "_T0"
ORDER BY
  1 DESC NULLS LAST
