WITH "_t1" AS (
  SELECT
    MERCHANT_ID,
    START_DATE
  FROM MAIN.COUPONS
), "_s1" AS (
  SELECT
    MERCHANT_ID,
    MIN(START_DATE) AS MIN_START_DATE
  FROM "_t1"
  GROUP BY
    MERCHANT_ID
), "_s4" AS (
  SELECT
    MERCHANTS.MID AS MERCHANT_ID,
    "_s1".MIN_START_DATE,
    ANY_VALUE(MERCHANTS.CREATED_AT) AS ANYTHING_CREATED_AT,
    MAX(COUPONS.CID) AS MAX_CID
  FROM MAIN.MERCHANTS MERCHANTS
  LEFT JOIN "_s1" "_s1"
    ON MERCHANTS.MID = "_s1".MERCHANT_ID
  LEFT JOIN MAIN.COUPONS COUPONS
    ON COUPONS.MERCHANT_ID = MERCHANTS.MID AND COUPONS.START_DATE = "_s1".MIN_START_DATE
  GROUP BY
    MERCHANTS.MID,
    "_s1".MIN_START_DATE
)
SELECT
  "_s4".MERCHANT_ID AS merchants_id,
  "_s4".ANYTHING_CREATED_AT AS merchant_registration_date,
  "_s4".MIN_START_DATE AS earliest_coupon_start_date,
  "_s4".MAX_CID AS earliest_coupon_id
FROM "_s4" "_s4"
JOIN "_t1" "_s5"
  ON "_s4".MERCHANT_ID = "_s5".MERCHANT_ID
  AND "_s5".START_DATE <= ADD_MONTHS(CAST("_s4".ANYTHING_CREATED_AT AS DATE), 12)
