WITH "_s1" AS (
  SELECT
    SBTXCUSTID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  WHERE
    TRUNC(CAST(CAST(SBTXDATETIME AS DATE) AS DATE), 'DD') = TO_DATE('2023-04-01', 'YYYY-MM-DD')
    AND SBTXTYPE = 'sell'
  GROUP BY
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTID AS "_id",
  SBCUSTOMER.SBCUSTNAME AS name,
  COALESCE("_s1".N_ROWS, 0) AS num_tx
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
