WITH _T0 AS (
  SELECT
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (ORDER BY WALLET_MERCHANT_BALANCE_DAILY.balance DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(WALLET_MERCHANT_BALANCE_DAILY.balance) OVER () - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN WALLET_MERCHANT_BALANCE_DAILY.balance
      ELSE NULL
    END AS EXPR_1
  FROM MAIN.WALLET_MERCHANT_BALANCE_DAILY AS WALLET_MERCHANT_BALANCE_DAILY
  JOIN MAIN.MERCHANTS AS MERCHANTS
    ON LOWER(MERCHANTS.category) LIKE '%retail%'
    AND MERCHANTS.mid = WALLET_MERCHANT_BALANCE_DAILY.merchant_id
    AND MERCHANTS.status = 'active'
  WHERE
    DATE_TRUNC('DAY', CAST(WALLET_MERCHANT_BALANCE_DAILY.updated_at AS TIMESTAMP)) = DATE_TRUNC('DAY', CURRENT_TIMESTAMP())
)
SELECT
  AVG(EXPR_1) AS _expr0
FROM _T0
