WITH _T0 AS (
  SELECT
    COUNT_IF(status = 'success') AS AGG_0,
    COUNT(*) AS AGG_1
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    DATEDIFF(MONTH, created_at, CURRENT_TIMESTAMP()) = 1
)
SELECT
  COALESCE(AGG_0, 0) / AGG_1 AS _expr0
FROM _T0
