WITH _T1 AS (
  SELECT
    ANY_VALUE(TREATMENTS.diag_id) AS ANYTHING_DIAG_ID,
    ANY_VALUE(TREATMENTS.patient_id) AS ANYTHING_PATIENT_ID,
    MAX(OUTCOMES.day100_itch_vas) AS MAX_DAY100_ITCH_VAS
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.OUTCOMES OUTCOMES
    ON OUTCOMES.treatment_id = TREATMENTS.treatment_id
  GROUP BY
    OUTCOMES.treatment_id
), _S3 AS (
  SELECT
    ANYTHING_DIAG_ID,
    MAX(MAX_DAY100_ITCH_VAS) AS MAX_MAX_DAY100_ITCH_VAS,
    COUNT(DISTINCT ANYTHING_PATIENT_ID) AS NDISTINCT_ANYTHING_PATIENT_ID
  FROM _T1
  GROUP BY
    ANYTHING_DIAG_ID
)
SELECT
  DIAGNOSES.diag_name AS diagnosis_name,
  _S3.NDISTINCT_ANYTHING_PATIENT_ID AS num_patients,
  _S3.MAX_MAX_DAY100_ITCH_VAS AS max_itch_score
FROM MAIN.DIAGNOSES DIAGNOSES
JOIN _S3 _S3
  ON DIAGNOSES.diag_id = _S3.ANYTHING_DIAG_ID
ORDER BY
  3 DESC NULLS LAST,
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
