WITH "_s1" AS (
  SELECT
    SALESPERSON_ID,
    COUNT(*) AS N_ROWS,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    SALE_DATE >= ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -3)
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name,
  COALESCE("_s1".N_ROWS, 0) AS total_sales,
  COALESCE("_s1".SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_s1" "_s1"
  ON SALESPERSONS."_id" = "_s1".SALESPERSON_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
