WITH _S1 AS (
  SELECT
    sbtxcustid AS SBTXCUSTID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  WHERE
    TRUNC(CAST(sbtxdatetime AS TIMESTAMP), 'DAY') = TO_DATE('2023-04-01', 'YYYY-MM-DD')
    AND sbtxtype = 'sell'
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  NVL(_S1.N_ROWS, 0) AS num_tx
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN _S1 _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
