WITH "_u_0" AS (
  SELECT
    SALESPERSON_ID AS "_u_1"
  FROM MAIN.SALES
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS."_id",
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_u_0" "_u_0"
  ON SALESPERSONS."_id" = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
