WITH "_u_0" AS (
  SELECT
    NOTIFICATIONS.USER_ID AS "_u_1"
  FROM MAIN.NOTIFICATIONS NOTIFICATIONS
  JOIN MAIN.USERS USERS
    ON NOTIFICATIONS.CREATED_AT <= ADD_MONTHS(CAST(USERS.CREATED_AT AS DATE), 12)
    AND NOTIFICATIONS.CREATED_AT >= USERS.CREATED_AT
    AND NOTIFICATIONS.USER_ID = USERS.UID
  GROUP BY
    NOTIFICATIONS.USER_ID
)
SELECT
  USERS.USERNAME AS username,
  USERS.EMAIL AS email,
  USERS.CREATED_AT AS created_at
FROM MAIN.USERS USERS
LEFT JOIN "_u_0" "_u_0"
  ON USERS.UID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
