WITH _T0 AS (
  SELECT
    SUM(sale_price) AS AGG_0,
    COUNT(*) AS AGG_1,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    DATEDIFF(DAY, sale_date, CURRENT_TIMESTAMP()) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  _T0.AGG_1 AS total_sales,
  COALESCE(_T0.AGG_0, 0) AS total_revenue
FROM MAIN.SALESPERSONS AS SALESPERSONS
JOIN _T0 AS _T0
  ON SALESPERSONS._id = _T0.SALESPERSON_ID
ORDER BY
  TOTAL_SALES DESC NULLS LAST
LIMIT 5
