WITH _S1 AS (
  SELECT
    salesperson_id AS SALESPERSON_ID,
    SUM(sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS._id,
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  NVL(_S1.SUM_SALE_PRICE, 0) AS total
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN _S1 _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
