SELECT
  PATIENTS.patient_id,
  PATIENTS.first_name,
  PATIENTS.last_name
FROM MAIN.PATIENTS PATIENTS
JOIN MAIN.TREATMENTS TREATMENTS
  ON PATIENTS.patient_id = TREATMENTS.patient_id
JOIN MAIN.OUTCOMES OUTCOMES
  ON OUTCOMES.treatment_id = TREATMENTS.treatment_id
