WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SBCUSTOMER.sbcustid AS SBCUSTID
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
  JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
    ON DATE_PART(MONTH, CAST(SBCUSTOMER.sbcustjoindate AS DATETIME)) = DATE_PART(MONTH, CAST(SBTRANSACTION.sbtxdatetime AS DATETIME))
    AND DATE_PART(YEAR, CAST(SBCUSTOMER.sbcustjoindate AS DATETIME)) = DATE_PART(YEAR, CAST(SBTRANSACTION.sbtxdatetime AS DATETIME))
    AND SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  GROUP BY
    SBCUSTOMER.sbcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S3.N_ROWS, 0) AS num_transactions
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S3 AS _S3
  ON SBCUSTOMER.sbcustid = _S3.SBCUSTID
ORDER BY
  NUM_TRANSACTIONS DESC NULLS LAST
LIMIT 1
