WITH _S1 AS (
  SELECT
    COUNT(DISTINCT coupon_id) AS NDISTINCT_COUPON_ID,
    COUNT(DISTINCT txid) AS NDISTINCT_TXID,
    receiver_id AS RECEIVER_ID
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    status = 'success'
  GROUP BY
    receiver_id
)
SELECT
  MERCHANTS.name,
  (
    _S1.NDISTINCT_COUPON_ID * 1.0
  ) / _S1.NDISTINCT_TXID AS CPUR
FROM MAIN.MERCHANTS AS MERCHANTS
JOIN _S1 AS _S1
  ON MERCHANTS.mid = _S1.RECEIVER_ID
