WITH _S0 AS (
  SELECT
    MIN(snapshot_date) AS MIN_DATE
  FROM MAIN.USER_SETTING_SNAPSHOT
  WHERE
    YEAR(CAST(snapshot_date AS TIMESTAMP)) = 2023
)
SELECT
  AVG(USER_SETTING_SNAPSHOT.tx_limit_daily) AS avg_daily_limit,
  AVG(USER_SETTING_SNAPSHOT.tx_limit_monthly) AS avg_monthly_limit
FROM _S0 AS _S0
JOIN MAIN.USER_SETTING_SNAPSHOT AS USER_SETTING_SNAPSHOT
  ON USER_SETTING_SNAPSHOT.snapshot_date = _S0.MIN_DATE
  AND YEAR(CAST(USER_SETTING_SNAPSHOT.snapshot_date AS TIMESTAMP)) = 2023
