WITH "_s2" AS (
  SELECT
    NVL(EXTRACT(YEAR FROM CAST(SBCUSTJOINDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBCUSTJOINDATE AS DATE)), 2, '0'), '') AS MONTH,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBCUSTOMER
  WHERE
    SBCUSTJOINDATE < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
    AND SBCUSTJOINDATE >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -6), 'MONTH')
  GROUP BY
    NVL(EXTRACT(YEAR FROM CAST(SBCUSTJOINDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBCUSTJOINDATE AS DATE)), 2, '0'), '')
), "_s3" AS (
  SELECT
    NVL(EXTRACT(YEAR FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)), 2, '0'), '') AS MONTH,
    AVG(SBTRANSACTION.SBTXAMOUNT) AS AVG_SBTXAMOUNT
  FROM MAIN.SBCUSTOMER SBCUSTOMER
  JOIN MAIN.SBTRANSACTION SBTRANSACTION
    ON EXTRACT(MONTH FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)) = EXTRACT(MONTH FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE))
    AND EXTRACT(YEAR FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)) = EXTRACT(YEAR FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE))
    AND SBCUSTOMER.SBCUSTID = SBTRANSACTION.SBTXCUSTID
  WHERE
    SBCUSTOMER.SBCUSTJOINDATE < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
    AND SBCUSTOMER.SBCUSTJOINDATE >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -6), 'MONTH')
  GROUP BY
    NVL(EXTRACT(YEAR FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE)), 2, '0'), '')
)
SELECT
  "_s2".MONTH AS month,
  "_s2".N_ROWS AS customer_signups,
  "_s3".AVG_SBTXAMOUNT AS avg_tx_amount
FROM "_s2" "_s2"
LEFT JOIN "_s3" "_s3"
  ON "_s2".MONTH = "_s3".MONTH
