SELECT
  MERCHANTS.mid AS merchant
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON MERCHANTS.mid = WALLET_TRANSACTIONS_DAILY.receiver_id
  AND WALLET_TRANSACTIONS_DAILY.receiver_type = 1
