WITH "_t" AS (
  SELECT
    CAR_ID,
    IS_IN_INVENTORY,
    ROW_NUMBER() OVER (PARTITION BY CAR_ID ORDER BY SNAPSHOT_DATE DESC) AS "_w"
  FROM MAIN.INVENTORY_SNAPSHOTS
)
SELECT
  ANY_VALUE(CARS.MAKE) AS make,
  ANY_VALUE(CARS.MODEL) AS model,
  MAX(SALES.SALE_PRICE) AS highest_sale_price
FROM MAIN.CARS CARS
JOIN "_t" "_t"
  ON CARS."_id" = "_t".CAR_ID AND NOT "_t".IS_IN_INVENTORY AND "_t"."_w" = 1
LEFT JOIN MAIN.SALES SALES
  ON CARS."_id" = SALES.CAR_ID
GROUP BY
  CARS."_id"
ORDER BY
  3 DESC NULLS LAST
