WITH "_u_0" AS (
  SELECT
    DOMAIN_CONFERENCE.cid AS "_u_1",
    WRITES.pid AS "_u_2"
  FROM MAIN.WRITES WRITES
  JOIN MAIN.DOMAIN_AUTHOR DOMAIN_AUTHOR
    ON DOMAIN_AUTHOR.aid = WRITES.aid
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.did = DOMAIN_AUTHOR.did AND LOWER(DOMAIN.name) LIKE '%sociology%'
  JOIN MAIN.DOMAIN_CONFERENCE DOMAIN_CONFERENCE
    ON DOMAIN.did = DOMAIN_CONFERENCE.did
  GROUP BY
    DOMAIN_CONFERENCE.cid,
    WRITES.pid
)
SELECT
  PUBLICATION.title
FROM MAIN.PUBLICATION PUBLICATION
LEFT JOIN "_u_0" "_u_0"
  ON PUBLICATION.cid = "_u_0"."_u_1" AND PUBLICATION.pid = "_u_0"."_u_2"
WHERE
  NOT "_u_0"."_u_1" IS NULL AND PUBLICATION.year = 2020
