WITH _S1 AS (
  SELECT
    doc_id AS DOC_ID,
    COUNT(DISTINCT drug_id) AS NDISTINCT_DRUG_ID
  FROM MAIN.TREATMENTS
  GROUP BY
    doc_id
)
SELECT
  DOCTORS.doc_id,
  DOCTORS.specialty,
  _S1.NDISTINCT_DRUG_ID AS num_distinct_drugs,
  DENSE_RANK() OVER (PARTITION BY DOCTORS.specialty ORDER BY _S1.NDISTINCT_DRUG_ID DESC) AS SDRSDR
FROM MAIN.DOCTORS DOCTORS
JOIN _S1 _S1
  ON DOCTORS.doc_id = _S1.DOC_ID
