SELECT
  ANY_VALUE(MERCHANTS.NAME) AS merchant_name,
  COUNT(*) AS total_coupons
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.COUPONS COUPONS
  ON COUPONS.MERCHANT_ID = MERCHANTS.MID
WHERE
  LOWER(MERCHANTS.CATEGORY) LIKE '%retail%' AND MERCHANTS.STATUS = 'active'
GROUP BY
  COUPONS.MERCHANT_ID
