SELECT
  COUNT(*) AS num_transactions,
  CASE
    WHEN COUNT(*) <> 0
    THEN COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0)
    ELSE NULL
  END AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS USERS
  ON USERS.country = 'US' AND USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
WHERE
  (
    CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - CAST(WALLET_TRANSACTIONS_DAILY.created_at AS DATE)
  ) <= 7
