WITH "_s1" AS (
  SELECT
    CITY_NAME,
    REGION
  FROM MAIN.GEOGRAPHIC
), "_s6" AS (
  SELECT DISTINCT
    "_s1".REGION
  FROM MAIN.LOCATION LOCATION
  LEFT JOIN "_s1" "_s1"
    ON LOCATION.CITY_NAME = "_s1".CITY_NAME
), "_s7" AS (
  SELECT
    "_s3".REGION,
    SUM(NOT RESTAURANT.RATING IS NULL) AS SUM_EXPR,
    SUM(RESTAURANT.RATING) AS SUM_RATING
  FROM MAIN.LOCATION LOCATION
  LEFT JOIN "_s1" "_s3"
    ON LOCATION.CITY_NAME = "_s3".CITY_NAME
  JOIN MAIN.RESTAURANT RESTAURANT
    ON LOCATION.RESTAURANT_ID = RESTAURANT.ID
  GROUP BY
    "_s3".REGION
)
SELECT
  "_s6".REGION AS region_name,
  "_s7".SUM_RATING / "_s7".SUM_EXPR AS avg_rating
FROM "_s6" "_s6"
JOIN "_s7" "_s7"
  ON "_s6".REGION = "_s7".REGION
ORDER BY
  1 NULLS FIRST,
  2 DESC NULLS LAST
