SELECT
  AVG(
    EXTRACT(YEAR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM CAST(DATE_OF_BIRTH AS DATE))
  ) AS average_age
FROM MAIN.PATIENTS
WHERE
  GENDER = 'Male' AND INS_TYPE = 'private'
