WITH "_S1" AS (
  SELECT
    salesperson_id AS SALESPERSON_ID,
    AVG(sale_price) AS AVG_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  "_S1".AVG_SALE_PRICE AS ASP
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_S1" "_S1"
  ON SALESPERSONS."_id" = "_S1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
