WITH "_s3" AS (
  SELECT
    WRITES.AID,
    COUNT(DISTINCT PUBLICATION.PID) AS NDISTINCT_PUBLICATION_ID
  FROM MAIN.WRITES WRITES
  JOIN MAIN.PUBLICATION PUBLICATION
    ON PUBLICATION.PID = WRITES.PID AND PUBLICATION.YEAR = 2021
  GROUP BY
    WRITES.AID
)
SELECT
  AUTHOR.NAME AS name,
  "_s3".NDISTINCT_PUBLICATION_ID AS count_publication
FROM MAIN.AUTHOR AUTHOR
JOIN "_s3" "_s3"
  ON AUTHOR.AID = "_s3".AID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
