WITH "_s0" AS (
  SELECT
    MIN(SNAPSHOT_DATE) AS MIN_SNAPSHOT_DATE
  FROM MAIN.USER_SETTING_SNAPSHOT
  WHERE
    EXTRACT(YEAR FROM CAST(SNAPSHOT_DATE AS DATE)) = 2023
), "_s1" AS (
  SELECT
    SNAPSHOT_DATE,
    AVG(TX_LIMIT_DAILY) AS AVG_TX_LIMIT_DAILY,
    AVG(TX_LIMIT_MONTHLY) AS AVG_TX_LIMIT_MONTHLY
  FROM MAIN.USER_SETTING_SNAPSHOT
  WHERE
    EXTRACT(YEAR FROM CAST(SNAPSHOT_DATE AS DATE)) = 2023
  GROUP BY
    SNAPSHOT_DATE
)
SELECT
  "_s1".AVG_TX_LIMIT_DAILY AS avg_daily_limit,
  "_s1".AVG_TX_LIMIT_MONTHLY AS avg_monthly_limit
FROM "_s0" "_s0"
LEFT JOIN "_s1" "_s1"
  ON "_s0".MIN_SNAPSHOT_DATE = "_s1".SNAPSHOT_DATE
