SELECT
  CUSTOMERS.state,
  COUNT(DISTINCT SALES.customer_id) AS unique_customers,
  COALESCE(SUM(SALES.sale_price), 0) AS total_revenue
FROM MAIN.SALES SALES
JOIN MAIN.CUSTOMERS CUSTOMERS
  ON CUSTOMERS."_id" = SALES.customer_id
GROUP BY
  CUSTOMERS.state
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
