SELECT
  MIN(SBDAILYPRICE.sbdpclose) AS lowest_price
FROM MAIN.SBDAILYPRICE SBDAILYPRICE
JOIN MAIN.SBTICKER SBTICKER
  ON SBDAILYPRICE.sbdptickerid = SBTICKER.sbtickerid
  AND SBTICKER.sbtickersymbol = 'VTI'
WHERE
  DATEDIFF(CURRENT_TIMESTAMP, CAST(SBDAILYPRICE.sbdpdate AS DATETIME), DAY) <= 7
