SELECT
  WALLET_TRANSACTIONS_DAILY.SENDER_ID AS user_id,
  COUNT(*) AS total_transactions
FROM MAIN.USERS USERS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON USERS.UID = WALLET_TRANSACTIONS_DAILY.SENDER_ID
  AND WALLET_TRANSACTIONS_DAILY.SENDER_TYPE = 0
GROUP BY
  WALLET_TRANSACTIONS_DAILY.SENDER_ID
