WITH "_s1" AS (
  SELECT
    SBTXTICKERID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  WHERE
    SBTXDATETIME >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) - NUMTODSINTERVAL(10, 'day'), 'DD')
    AND SBTXTYPE = 'buy'
  GROUP BY
    SBTXTICKERID
)
SELECT
  SBTICKER.SBTICKERSYMBOL AS symbol,
  COALESCE("_s1".N_ROWS, 0) AS tx_count
FROM MAIN.SBTICKER SBTICKER
LEFT JOIN "_s1" "_s1"
  ON SBTICKER.SBTICKERID = "_s1".SBTXTICKERID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 2 ROWS ONLY
