WITH "_s1" AS (
  SELECT
    SBDPTICKERID,
    COUNT(SBDPCLOSE) AS COUNT_SBDPCLOSE,
    SUM(SBDPCLOSE) AS SUM_SBDPCLOSE
  FROM MAIN.SBDAILYPRICE
  WHERE
    (
      TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(SBDPDATE AS DATE) AS DATE), 'DD')
    ) <= 7
  GROUP BY
    SBDPTICKERID
)
SELECT
  SBTICKER.SBTICKERTYPE AS ticker_type,
  SUM("_s1".SUM_SBDPCLOSE) / SUM("_s1".COUNT_SBDPCLOSE) AS ACP
FROM MAIN.SBTICKER SBTICKER
JOIN "_s1" "_s1"
  ON SBTICKER.SBTICKERID = "_s1".SBDPTICKERID
GROUP BY
  SBTICKER.SBTICKERTYPE
