WITH _S1 AS (
  SELECT
    country AS COUNTRY,
    uid AS UID
  FROM MAIN.USERS
), _T1 AS (
  SELECT
    SUM(WALLET_TRANSACTIONS_DAILY.amount) AS AGG_0,
    COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.sender_id) AS AGG_1,
    _S1.COUNTRY
  FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
  LEFT JOIN _S1 AS _S1
    ON WALLET_TRANSACTIONS_DAILY.sender_id = _S1.UID
  WHERE
    WALLET_TRANSACTIONS_DAILY.sender_type = 0
  GROUP BY
    _S1.COUNTRY
)
SELECT
  COUNTRY AS country,
  AGG_1 AS user_count,
  COALESCE(AGG_0, 0) AS total_amount
FROM _T1
ORDER BY
  TOTAL_AMOUNT DESC NULLS LAST
LIMIT 5
