WITH _T1 AS (
  SELECT
    merchant_id AS MERCHANT_ID,
    start_date AS START_DATE
  FROM MAIN.COUPONS
), _S1 AS (
  SELECT
    MIN(START_DATE) AS MIN_START_DATE,
    MERCHANT_ID
  FROM _T1
  GROUP BY
    MERCHANT_ID
), _S3 AS (
  SELECT
    MIN(START_DATE) AS MIN_START_DATE,
    MERCHANT_ID
  FROM _T1
  GROUP BY
    MERCHANT_ID
), _S7 AS (
  SELECT
    MAX(COUPONS.cid) AS MAX_CID,
    MERCHANTS.mid AS MID
  FROM MAIN.MERCHANTS AS MERCHANTS
  LEFT JOIN _S3 AS _S3
    ON MERCHANTS.mid = _S3.MERCHANT_ID
  JOIN MAIN.COUPONS AS COUPONS
    ON COUPONS.merchant_id = MERCHANTS.mid AND COUPONS.start_date = _S3.MIN_START_DATE
  GROUP BY
    MERCHANTS.mid
)
SELECT
  MERCHANTS.mid AS merchants_id,
  MERCHANTS.created_at AS merchant_registration_date,
  _S1.MIN_START_DATE AS earliest_coupon_start_date,
  _S7.MAX_CID AS earliest_coupon_id
FROM MAIN.MERCHANTS AS MERCHANTS
LEFT JOIN _S1 AS _S1
  ON MERCHANTS.mid = _S1.MERCHANT_ID
LEFT JOIN _S7 AS _S7
  ON MERCHANTS.mid = _S7.MID
JOIN _T1 AS _S9
  ON MERCHANTS.mid = _S9.MERCHANT_ID
  AND _S9.START_DATE <= DATEADD(YEAR, 1, CAST(MERCHANTS.created_at AS TIMESTAMP))
