WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SBCUSTOMER.sbcustid AS SBCUSTID
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
  JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
    ON MONTH(SBCUSTOMER.sbcustjoindate) = MONTH(SBTRANSACTION.sbtxdatetime)
    AND SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
    AND YEAR(SBCUSTOMER.sbcustjoindate) = YEAR(SBTRANSACTION.sbtxdatetime)
  GROUP BY
    SBCUSTOMER.sbcustid
)
SELECT
  SBCUSTOMER.sbcustid AS _id,
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S3.N_ROWS, 0) AS num_transactions
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S3 AS _S3
  ON SBCUSTOMER.sbcustid = _S3.SBCUSTID
ORDER BY
  COALESCE(_S3.N_ROWS, 0) DESC NULLS LAST
LIMIT 1
