SELECT
  COUPONS.cid AS coupon_id,
  NVL(SUM(WALLET_TRANSACTIONS_DAILY.amount), 0) AS total_discount
FROM MAIN.COUPONS COUPONS
LEFT JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON COUPONS.cid = WALLET_TRANSACTIONS_DAILY.coupon_id
WHERE
  COUPONS.merchant_id = '1'
GROUP BY
  COUPONS.cid
