SELECT
  PAYMENT_METHOD AS payment_method,
  COUNT(*) AS total_payments,
  COALESCE(SUM(PAYMENT_AMOUNT), 0) AS total_amount
FROM MAIN.PAYMENTS_RECEIVED
GROUP BY
  PAYMENT_METHOD
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
