SELECT
  AVG(BALANCE) AS AMB
FROM MAIN.WALLET_USER_BALANCE_DAILY
WHERE
  (
    TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(UPDATED_AT AS DATE) AS DATE), 'DD')
  ) <= 7
