WITH _S1 AS (
  SELECT
    COUNT(*) AS NUM_SALES,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    DATEDIFF(DAY, CAST(sale_date AS DATETIME), CURRENT_TIMESTAMP()) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS._id,
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  _S1.NUM_SALES AS num_sales
FROM MAIN.SALESPERSONS AS SALESPERSONS
JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  NUM_SALES DESC NULLS LAST
