WITH "_s1" AS (
  SELECT
    EXTRACT(MONTH FROM CAST(SBTXDATETIME AS DATE)) AS MONTH_SBTXDATETIME,
    EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)) AS YEAR_SBTXDATETIME,
    SBTXCUSTID,
    COUNT(*) AS N_ROWS
  FROM MAIN.SBTRANSACTION
  GROUP BY
    EXTRACT(MONTH FROM CAST(SBTXDATETIME AS DATE)),
    EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)),
    SBTXCUSTID
)
SELECT
  SBCUSTOMER.SBCUSTID AS "_id",
  SBCUSTOMER.SBCUSTNAME AS name,
  COALESCE("_s1".N_ROWS, 0) AS num_transactions
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_s1" "_s1"
  ON SBCUSTOMER.SBCUSTID = "_s1".SBTXCUSTID
  AND "_s1".MONTH_SBTXDATETIME = EXTRACT(MONTH FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE))
  AND "_s1".YEAR_SBTXDATETIME = EXTRACT(YEAR FROM CAST(SBCUSTOMER.SBCUSTJOINDATE AS DATE))
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
