WITH _S1 AS (
  SELECT
    sbtxcustid AS SBTXCUSTID,
    COUNT(*) AS N_ROWS,
    SUM(sbtxamount) AS SUM_SBTXAMOUNT
  FROM MAIN.SBTRANSACTION
  WHERE
    sbtxdatetime >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 30, DAY), 'DAY')
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustcountry AS country,
  NVL(SUM(_S1.N_ROWS), 0) AS num_transactions,
  NVL(SUM(_S1.SUM_SBTXAMOUNT), 0) AS total_amount
FROM MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN _S1 _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
GROUP BY
  SBCUSTOMER.sbcustcountry
