WITH _t0 AS (
  SELECT
    DATE_TRUNC('MONTH', CAST(start_dt AS TIMESTAMP)) AS start_month,
    COUNT(*) AS n_rows,
    COUNT(DISTINCT diag_id) AS ndistinct_diag_id
  FROM main.treatments
  WHERE
    DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) - INTERVAL '12' MONTH <= DATE_TRUNC('MONTH', CAST(start_dt AS TIMESTAMP))
    AND DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)) > DATE_TRUNC('MONTH', CAST(start_dt AS TIMESTAMP))
  GROUP BY
    1
)
SELECT
  CONCAT_WS(
    '-',
    EXTRACT(YEAR FROM CAST(start_month AS TIMESTAMP)),
    CASE
      WHEN LENGTH(CAST(EXTRACT(MONTH FROM CAST(start_month AS TIMESTAMP)) AS TEXT)) >= 2
      THEN SUBSTRING(CAST(EXTRACT(MONTH FROM CAST(start_month AS TIMESTAMP)) AS TEXT), 1, 2)
      ELSE SUBSTRING(CONCAT('00', CAST(EXTRACT(MONTH FROM CAST(start_month AS TIMESTAMP)) AS TEXT)), -2)
    END
  ) AS start_month,
  ndistinct_diag_id AS PMPD,
  n_rows AS PMTC
FROM _t0
ORDER BY
  1 DESC
