WITH "_S3" AS (
  SELECT
    WRITES.aid AS AID,
    SUM(PUBLICATION.citation_num) AS SUM_CITATION_NUM
  FROM MAIN.WRITES WRITES
  JOIN MAIN.PUBLICATION PUBLICATION
    ON PUBLICATION.pid = WRITES.pid
  GROUP BY
    WRITES.aid
)
SELECT
  AUTHOR.name,
  NVL("_S3".SUM_CITATION_NUM, 0) AS total_citations
FROM MAIN.AUTHOR AUTHOR
JOIN "_S3" "_S3"
  ON AUTHOR.aid = "_S3".AID
