WITH _T1 AS (
  SELECT
    ANY_VALUE(SALES.car_id) AS ANYTHING_CAR_ID,
    ANY_VALUE(CARS.make) AS ANYTHING_MAKE,
    ANY_VALUE(CARS.model) AS ANYTHING_MODEL,
    ANY_VALUE(SALES.sale_price) AS ANYTHING_SALE_PRICE,
    CARS._id AS _ID_1
  FROM MAIN.SALES AS SALES
  JOIN MAIN.CARS AS CARS
    ON CARS._id = SALES.car_id
  JOIN MAIN.INVENTORY_SNAPSHOTS AS INVENTORY_SNAPSHOTS
    ON CARS._id = INVENTORY_SNAPSHOTS.car_id
    AND INVENTORY_SNAPSHOTS.is_in_inventory = 0
    AND INVENTORY_SNAPSHOTS.snapshot_date = SALES.sale_date
  GROUP BY
    SALES._id,
    5
)
SELECT
  ANYTHING_MAKE AS make,
  ANYTHING_MODEL AS model,
  ANYTHING_SALE_PRICE AS sale_price
FROM _T1
WHERE
  ANYTHING_CAR_ID = _ID_1
ORDER BY
  3 DESC NULLS LAST
LIMIT 1
