WITH "_s1" AS (
  SELECT
    DID,
    COUNT(DISTINCT AID) AS NDISTINCT_AID
  FROM MAIN.DOMAIN_AUTHOR
  GROUP BY
    DID
)
SELECT
  DOMAIN.NAME AS name,
  COALESCE("_s1".NDISTINCT_AID, 0) AS author_count
FROM MAIN.DOMAIN DOMAIN
LEFT JOIN "_s1" "_s1"
  ON DOMAIN.DID = "_s1".DID
ORDER BY
  2 DESC NULLS LAST,
  1 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
