SELECT
  COUNT(*) AS num_transactions,
  CASE
    WHEN COUNT(*) <> 0
    THEN COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0)
    ELSE NULL
  END AS total_amount
FROM MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
JOIN MAIN.USERS USERS
  ON USERS.COUNTRY = 'US' AND USERS.UID = WALLET_TRANSACTIONS_DAILY.SENDER_ID
WHERE
  (
    TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(WALLET_TRANSACTIONS_DAILY.CREATED_AT AS DATE) AS DATE), 'DD')
  ) <= 7
