WITH _S1 AS (
  SELECT
    car_id AS CAR_ID,
    COUNT(*) AS N_ROWS,
    SUM(sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    car_id
)
SELECT
  CARS.make,
  CARS.model,
  NVL(_S1.N_ROWS, 0) AS total_sales,
  NVL(_S1.SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.CARS CARS
LEFT JOIN _S1 _S1
  ON CARS._id = _S1.CAR_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
