WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS_1,
    SUM(sale_price) AS SUM_SALE_PRICE,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    DATEDIFF(DAY, CAST(sale_date AS DATETIME), CURRENT_TIMESTAMP()) <= 30
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  _S1.N_ROWS_1 AS total_sales,
  COALESCE(_S1.SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.SALESPERSONS AS SALESPERSONS
JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  _S1.N_ROWS_1 DESC NULLS LAST
LIMIT 5
