WITH _S1 AS (
  SELECT
    SUM(sbtxamount) AS SUM_SBTXAMOUNT,
    sbtxcustid AS SBTXCUSTID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  COALESCE(_S1.SUM_SBTXAMOUNT, 0) AS total_amount
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
ORDER BY
  COALESCE(_S1.SUM_SBTXAMOUNT, 0) DESC NULLS LAST
LIMIT 5
