SELECT
  COUNT(*) AS num_treatments
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.PATIENTS PATIENTS
  ON LOWER(PATIENTS.first_name) = 'alice'
  AND PATIENTS.patient_id = TREATMENTS.patient_id
WHERE
  TREATMENTS.start_dt < TRUNC(CURRENT_TIMESTAMP, 'MONTH')
  AND TREATMENTS.start_dt >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'MONTH'), 6, MONTH)
