WITH _u_0 AS (
  SELECT
    SBCUSTOMER.sbcustid AS _ID,
    SBCUSTOMER.sbcustemail AS EMAIL
  FROM MAIN.SBCUSTOMER AS SBCUSTOMER
), _S2 AS (
  SELECT
    _T1._ID AS _ID
  FROM _T1 AS _T1
  WHERE
    ENDSWITH(_T1.EMAIL, '.com')
), _S0 AS (
  SELECT
    SBTRANSACTION.sbtxcustid AS CUSTOMER_ID,
    SBTRANSACTION.sbtxtickerid AS TICKER_ID
  FROM MAIN.SBTRANSACTION AS SBTRANSACTION
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
    AND SBTICKER.sbtickersymbol IN ('AMZN', 'AAPL', 'GOOGL', 'META', 'NFLX')
  GROUP BY
    SBTRANSACTION.sbtxcustid
)
SELECT
  COUNT(*) AS n_customers
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _u_0 AS _u_0
  ON SBCUSTOMER.sbcustid = _u_0._u_1
WHERE
  NOT _u_0._u_1 IS NULL AND SBCUSTOMER.sbcustemail LIKE '%.com'
