WITH _u_0 AS (
  SELECT
    customer_id AS _u_1
  FROM MAIN.SALES
  GROUP BY
    1
)
SELECT
  CUSTOMERS._id
FROM MAIN.CUSTOMERS AS CUSTOMERS
LEFT JOIN _u_0 AS _u_0
  ON CUSTOMERS._id = _u_0._u_1
WHERE
  NOT _u_0._u_1 IS NULL
