WITH _T0 AS (
  SELECT
    WALLET_TRANSACTIONS_DAILY.receiver_id AS RECEIVER_ID,
    WALLET_TRANSACTIONS_DAILY.receiver_type AS RECEIVER_TYPE
  FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
), _S1 AS (
  SELECT
    _T0.RECEIVER_ID AS RECEIVER_ID
  FROM _T0 AS _T0
  WHERE
    _T0.RECEIVER_TYPE = 1
), _S0 AS (
  SELECT
    MERCHANTS.mid AS MERCHANT,
    MERCHANTS.mid AS MID
  FROM MAIN.MERCHANTS AS MERCHANTS
)
SELECT
  _S0.MERCHANT AS merchant
FROM _S0 AS _S0
WHERE
  EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0.MID = _S1.RECEIVER_ID
  )
