SELECT
  DATE_TRUNC('MONTH', CAST(created_at AS TIMESTAMP)) AS year_month,
  COUNT(DISTINCT sender_id) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY
WHERE
  created_at < DATE_TRUNC('MONTH', CURRENT_TIMESTAMP())
  AND created_at >= DATEADD(MONTH, -2, DATE_TRUNC('MONTH', CURRENT_TIMESTAMP()))
  AND sender_type = 0
GROUP BY
  1
