WITH _T0 AS (
  SELECT
    COUNT(*) AS AGG_0,
    COUNT_IF((
      (
        DAYOFWEEK(SBTRANSACTION.sbtxdatetime) + 6
      ) % 7
    ) IN (5, 6)) AS AGG_1,
    DATE_TRUNC('WEEK', CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS WEEK
  FROM MAIN.SBTRANSACTION AS SBTRANSACTION
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
    AND SBTICKER.sbtickertype = 'stock'
  WHERE
    SBTRANSACTION.sbtxdatetime < DATE_TRUNC('WEEK', CURRENT_TIMESTAMP())
    AND SBTRANSACTION.sbtxdatetime >= DATEADD(WEEK, -8, DATE_TRUNC('WEEK', CURRENT_TIMESTAMP()))
  GROUP BY
    DATE_TRUNC('WEEK', CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP))
)
SELECT
  WEEK AS week,
  AGG_0 AS num_transactions,
  COALESCE(AGG_1, 0) AS weekend_transactions
FROM _T0
