WITH "_T1" AS (
  SELECT
    ANY_VALUE(CARS.make) AS ANYTHING_MAKE,
    ANY_VALUE(CARS.model) AS ANYTHING_MODEL,
    COUNT(SALES.car_id) AS COUNT_CAR_ID
  FROM MAIN.CARS CARS
  LEFT JOIN MAIN.SALES SALES
    ON CARS."_id" = SALES.car_id
  WHERE
    LOWER(CARS.vin_number) LIKE '%m5%'
  GROUP BY
    CARS."_id"
)
SELECT
  ANYTHING_MAKE AS make,
  ANYTHING_MODEL AS model,
  NVL(SUM(COUNT_CAR_ID), 0) AS num_sales
FROM "_T1"
GROUP BY
  ANYTHING_MAKE,
  ANYTHING_MODEL
