SELECT
  NULLIF(COUNT(*), 0) AS n_transactions,
  COALESCE(SUM(SBTRANSACTION.SBTXAMOUNT), 0) AS total_amount
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBCUSTOMER SBCUSTOMER
  ON LOWER(SBCUSTOMER.SBCUSTCOUNTRY) = 'usa'
  AND SBCUSTOMER.SBCUSTID = SBTRANSACTION.SBTXCUSTID
WHERE
  SBTRANSACTION.SBTXDATETIME < TRUNC(
    SYS_EXTRACT_UTC(SYSTIMESTAMP) - MOD((
      TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'D') + 5
    ), 7),
    'DD'
  )
  AND SBTRANSACTION.SBTXDATETIME >= (
    TRUNC(
      SYS_EXTRACT_UTC(SYSTIMESTAMP) - MOD((
        TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'D') + 5
      ), 7),
      'DD'
    ) - NUMTODSINTERVAL(7, 'DAY')
  )
