WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    merchant_id AS MERCHANT_ID
  FROM MAIN.COUPONS
  GROUP BY
    2
)
SELECT
  MERCHANTS.name AS merchant_name,
  _S1.N_ROWS AS total_coupons
FROM MAIN.MERCHANTS AS MERCHANTS
JOIN _S1 AS _S1
  ON MERCHANTS.mid = _S1.MERCHANT_ID
WHERE
  CONTAINS(LOWER(MERCHANTS.category), 'retail') AND MERCHANTS.status = 'active'
