WITH "_s1" AS (
  SELECT
    JID,
    COUNT(*) AS N_ROWS
  FROM MAIN.PUBLICATION
  GROUP BY
    JID
)
SELECT
  JOURNAL.NAME AS name,
  JOURNAL.JID AS journal_id,
  COALESCE("_s1".N_ROWS, 0) AS num_publications
FROM MAIN.JOURNAL JOURNAL
LEFT JOIN "_s1" "_s1"
  ON JOURNAL.JID = "_s1".JID
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
