SELECT
  FIRST_NAME AS first_name,
  LAST_NAME AS last_name,
  PHONE AS phone,
  TRUNC(CAST(CAST(TERMINATION_DATE AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(HIRE_DATE AS DATE) AS DATE), 'DD') AS days_employed
FROM MAIN.SALESPERSONS
WHERE
  NOT TERMINATION_DATE IS NULL
ORDER BY
  4 NULLS FIRST
FETCH FIRST 1 ROWS ONLY
