WITH _S1 AS (
  SELECT
    COUNT(txid) AS AGG_0,
    SUM(amount) AS AGG_1,
    coupon_id AS COUPON_ID
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  GROUP BY
    coupon_id
)
SELECT
  COUPONS.code AS coupon_code,
  COALESCE(_S1.AGG_0, 0) AS redemption_count,
  COALESCE(_S1.AGG_1, 0) AS total_discount
FROM MAIN.COUPONS AS COUPONS
LEFT JOIN _S1 AS _S1
  ON COUPONS.cid = _S1.COUPON_ID
ORDER BY
  REDEMPTION_COUNT DESC NULLS LAST
LIMIT 3
