SELECT
  CARS.MAKE AS make,
  CARS.MODEL AS model,
  SALES.SALE_PRICE AS sale_price
FROM MAIN.SALES SALES
JOIN MAIN.CARS CARS
  ON CARS."_id" = SALES.CAR_ID
JOIN MAIN.INVENTORY_SNAPSHOTS INVENTORY_SNAPSHOTS
  ON CARS."_id" = INVENTORY_SNAPSHOTS.CAR_ID
  AND INVENTORY_SNAPSHOTS.SNAPSHOT_DATE = SALES.SALE_DATE
  AND NOT INVENTORY_SNAPSHOTS.IS_IN_INVENTORY
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
