SELECT
  TRUNC(CAST(SBTXDATETIME AS DATE), 'MONTH') AS month,
  AVG(SBTXPRICE) AS avg_price
FROM MAIN.SBTRANSACTION
WHERE
  EXTRACT(MONTH FROM CAST(SBTXDATETIME AS DATE)) IN (1, 2, 3)
  AND EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)) = 2023
  AND SBTXSTATUS = 'success'
GROUP BY
  TRUNC(CAST(SBTXDATETIME AS DATE), 'MONTH')
ORDER BY
  1 NULLS FIRST
