SELECT
  AVG(balance) AS AMB
FROM MAIN.WALLET_USER_BALANCE_DAILY
WHERE
  (
    TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(updated_at AS DATE) AS DATE), 'DD')
  ) <= 7
