WITH "_s0" AS (
  SELECT
    CITY_NAME,
    COUNT(*) AS N_ROWS
  FROM MAIN.RESTAURANT
  WHERE
    LOWER(FOOD_TYPE) = 'italian'
  GROUP BY
    CITY_NAME
)
SELECT
  GEOGRAPHIC.REGION AS rest_region,
  SUM("_s0".N_ROWS) AS n_restaurants
FROM "_s0" "_s0"
JOIN MAIN.GEOGRAPHIC GEOGRAPHIC
  ON GEOGRAPHIC.CITY_NAME = "_s0".CITY_NAME
GROUP BY
  GEOGRAPHIC.REGION
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
