WITH "_u_0" AS (
  SELECT
    OID AS "_u_1"
  FROM MAIN.ORGANIZATION
  GROUP BY
    OID
)
SELECT
  AUTHOR.NAME AS name,
  AUTHOR.AID AS author_id
FROM MAIN.AUTHOR AUTHOR
LEFT JOIN "_u_0" "_u_0"
  ON AUTHOR.OID = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
