WITH "_s1" AS (
  SELECT
    SALESPERSON_ID,
    COUNT(*) AS N_ROWS,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    (
      TRUNC(CAST(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(SALE_DATE AS DATE) AS DATE), 'DD')
    ) <= 30
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name,
  "_s1".N_ROWS AS total_sales,
  COALESCE("_s1".SUM_SALE_PRICE, 0) AS total_revenue
FROM MAIN.SALESPERSONS SALESPERSONS
JOIN "_s1" "_s1"
  ON SALESPERSONS."_id" = "_s1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
