WITH "_s1" AS (
  SELECT
    SALESPERSON_ID,
    AVG(SALE_PRICE) AS AVG_SALE_PRICE
  FROM MAIN.SALES
  GROUP BY
    SALESPERSON_ID
)
SELECT
  SALESPERSONS.FIRST_NAME AS first_name,
  SALESPERSONS.LAST_NAME AS last_name,
  "_s1".AVG_SALE_PRICE AS ASP
FROM MAIN.SALESPERSONS SALESPERSONS
LEFT JOIN "_s1" "_s1"
  ON SALESPERSONS."_id" = "_s1".SALESPERSON_ID
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
