WITH _T0 AS (
  SELECT
    WRITES.aid AS AID,
    COUNT(DISTINCT DOMAIN_PUBLICATION.did) AS NDISTINCT_DID
  FROM MAIN.WRITES WRITES
  JOIN MAIN.DOMAIN_PUBLICATION DOMAIN_PUBLICATION
    ON DOMAIN_PUBLICATION.pid = WRITES.pid
  JOIN MAIN.DOMAIN DOMAIN
    ON DOMAIN.did = DOMAIN_PUBLICATION.did
    AND DOMAIN.name IN ('Data Science', 'Machine Learning')
  GROUP BY
    WRITES.aid
)
SELECT
  AUTHOR.name
FROM MAIN.AUTHOR AUTHOR
JOIN _T0 _T0
  ON AUTHOR.aid = _T0.AID AND _T0.NDISTINCT_DID = 2
