SELECT
  COUNT(*) AS num_treatments
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.DIAGNOSES DIAGNOSES
  ON DIAGNOSES.diag_id = TREATMENTS.diag_id
  AND LOWER(DIAGNOSES.diag_name) LIKE '%psoriasis%'
JOIN MAIN.DRUGS DRUGS
  ON DRUGS.drug_id = TREATMENTS.drug_id AND NOT DRUGS.fda_appr_dt IS NULL
WHERE
  NOT TREATMENTS.end_dt IS NULL
  AND TREATMENTS.end_dt >= TRUNC(DATE_SUB(CURRENT_TIMESTAMP, 6, MONTH), 'DAY')
