SELECT
  SBTICKER.sbtickertype AS ticker_type,
  AVG(SBDAILYPRICE.sbdpclose) AS ACP
FROM MAIN.SBTICKER AS SBTICKER
JOIN MAIN.SBDAILYPRICE AS SBDAILYPRICE
  ON DATEDIFF(DAY, SBDAILYPRICE.sbdpdate, CURRENT_TIMESTAMP()) <= 7
  AND SBDAILYPRICE.sbdptickerid = SBTICKER.sbtickerid
GROUP BY
  SBTICKER.sbtickertype
