SELECT
  COUNT(*) AS TUC
FROM MAIN.USER_SESSIONS
WHERE
  SESSION_END_TS >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -1), 'DD')
  OR SESSION_START_TS >= TRUNC(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -1), 'DD')
