WITH "_t" AS (
  SELECT
    MARKETING_OPT_IN,
    USER_ID,
    ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY CREATED_AT DESC) AS "_w"
  FROM MAIN.USER_SETTING_SNAPSHOT
)
SELECT
  USERS.UID AS uid,
  "_t".MARKETING_OPT_IN AS marketing_opt_in
FROM MAIN.USERS USERS
JOIN "_t" "_t"
  ON USERS.UID = "_t".USER_ID AND "_t"."_w" = 1
