SELECT
  COALESCE(SUM(status = 'success'), 0) / NULLIF(COUNT(*), 0) AS "_expr0"
FROM MAIN.WALLET_TRANSACTIONS_DAILY
WHERE
  (
    (
      EXTRACT(YEAR FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(YEAR FROM CAST(created_at AS DATE))
    ) * 12 + (
      EXTRACT(MONTH FROM CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)) - EXTRACT(MONTH FROM CAST(created_at AS DATE))
    )
  ) = 1
