SELECT
  WALLET_TRANSACTIONS_DAILY.sender_id AS user_id,
  COUNT(*) AS total_transactions
FROM MAIN.USERS USERS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
  AND WALLET_TRANSACTIONS_DAILY.sender_type = 0
GROUP BY
  WALLET_TRANSACTIONS_DAILY.sender_id
