WITH "_S3" AS (
  SELECT
    TRUNC(CAST(SALES.sale_date AS DATE), 'MONTH') AS SALE_MONTH,
    COUNT(*) AS N_ROWS,
    SUM(SALES.sale_price) AS SUM_SALE_PRICE
  FROM MAIN.SALES SALES
  JOIN MAIN.SALESPERSONS SALESPERSONS
    ON EXTRACT(YEAR FROM CAST(SALESPERSONS.hire_date AS DATE)) <= 2023
    AND EXTRACT(YEAR FROM CAST(SALESPERSONS.hire_date AS DATE)) >= 2022
    AND SALES.salesperson_id = SALESPERSONS."_id"
  GROUP BY
    TRUNC(CAST(SALES.sale_date AS DATE), 'MONTH')
)
SELECT
  TO_CHAR(TRUNC(CAST(MONTHS_RANGE.DT AS DATE), 'MONTH'), 'YYYY-MM-DD') AS month,
  COALESCE("_S3".N_ROWS, 0) AS PMSPS,
  COALESCE("_S3".SUM_SALE_PRICE, 0) AS PMSR
FROM (VALUES
  (TO_TIMESTAMP('2025-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
  (TO_TIMESTAMP('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
  (TO_TIMESTAMP('2025-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
  (TO_TIMESTAMP('2025-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
  (TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
  (TO_TIMESTAMP('2026-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))) AS MONTHS_RANGE(DT)
LEFT JOIN "_S3" "_S3"
  ON "_S3".SALE_MONTH = TRUNC(CAST(MONTHS_RANGE.DT AS DATE), 'MONTH')
ORDER BY
  TRUNC(CAST(MONTHS_RANGE.DT AS DATE), 'MONTH') NULLS FIRST
