SELECT
  COUNT(*) AS num_treatments
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.PATIENTS PATIENTS
  ON LOWER(PATIENTS.FIRST_NAME) = 'alice'
  AND PATIENTS.PATIENT_ID = TREATMENTS.PATIENT_ID
WHERE
  TREATMENTS.START_DT < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
  AND TREATMENTS.START_DT >= ADD_MONTHS(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), -6)
