WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(sbtxamount) AS SUM_SBTXAMOUNT,
    sbtxcustid AS SBTXCUSTID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    3
)
SELECT
  SBCUSTOMER.sbcustname AS name,
  _S1.N_ROWS AS num_tx,
  COALESCE(_S1.SUM_SBTXAMOUNT, 0) AS total_amount,
  RANK() OVER (ORDER BY COALESCE(_S1.SUM_SBTXAMOUNT, 0) DESC) AS cust_rank
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
