SELECT
  COUNT(*) AS num_treatments
FROM MAIN.TREATMENTS TREATMENTS
JOIN MAIN.PATIENTS PATIENTS
  ON LOWER(PATIENTS.first_name) = 'alice'
  AND PATIENTS.patient_id = TREATMENTS.patient_id
WHERE
  TREATMENTS.start_dt < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
  AND TREATMENTS.start_dt >= (
    TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH') + NUMTOYMINTERVAL(6, 'month')
  )
