SELECT
  MIN(SBDAILYPRICE.sbdpclose) AS lowest_price
FROM MAIN.SBDAILYPRICE SBDAILYPRICE
JOIN MAIN.SBTICKER SBTICKER
  ON SBDAILYPRICE.sbdptickerid = SBTICKER.sbtickerid
  AND SBTICKER.sbtickersymbol = 'VTI'
WHERE
  (
    CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - CAST(SBDAILYPRICE.sbdpdate AS DATE)
  ) <= 7
