WITH _T0 AS (
  SELECT
    COUNT(*) AS AGG_0,
    SUM(WALLET_TRANSACTIONS_DAILY.amount) AS AGG_1
  FROM MAIN.WALLET_TRANSACTIONS_DAILY AS WALLET_TRANSACTIONS_DAILY
  JOIN MAIN.USERS AS USERS
    ON USERS.country = 'US' AND USERS.uid = WALLET_TRANSACTIONS_DAILY.sender_id
  WHERE
    DATEDIFF(DAY, WALLET_TRANSACTIONS_DAILY.created_at, CURRENT_TIMESTAMP()) <= 7
)
SELECT
  AGG_0 AS num_transactions,
  CASE WHEN AGG_0 > 0 THEN COALESCE(AGG_1, 0) ELSE NULL END AS total_amount
FROM _T0
