WITH "_s0" AS (
  SELECT
    CAR_ID,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    EXTRACT(YEAR FROM CAST(SALE_DATE AS DATE)) = 2023
  GROUP BY
    CAR_ID
)
SELECT
  (
    (
      COALESCE(SUM("_s0".SUM_SALE_PRICE), 0) - COALESCE(SUM(CARS.COST), 0)
    ) / NULLIF(SUM(CARS.COST), 0)
  ) * 100 AS GPM
FROM "_s0" "_s0"
JOIN MAIN.CARS CARS
  ON CARS."_id" = "_s0".CAR_ID
