WITH _T0 AS (
  SELECT
    ANY_VALUE(CARS.make) AS MAKE,
    ANY_VALUE(CARS.model) AS MODEL,
    ANY_VALUE(SALES.sale_price) AS SALE_PRICE
  FROM MAIN.SALES AS SALES
  JOIN MAIN.CARS AS CARS
    ON CARS._id = SALES.car_id
  JOIN MAIN.INVENTORY_SNAPSHOTS AS INVENTORY_SNAPSHOTS
    ON CARS._id = INVENTORY_SNAPSHOTS.car_id
    AND INVENTORY_SNAPSHOTS.is_in_inventory = 0
    AND INVENTORY_SNAPSHOTS.snapshot_date = SALES.sale_date
  GROUP BY
    SALES._id,
    CARS._id
)
SELECT
  MAKE AS make,
  MODEL AS model,
  SALE_PRICE AS sale_price
FROM _T0
ORDER BY
  SALE_PRICE DESC NULLS LAST
LIMIT 1
