WITH "_t" AS (
  SELECT
    DOC_ID,
    START_DT,
    TREATMENT_ID,
    ROW_NUMBER() OVER (PARTITION BY DOC_ID ORDER BY START_DT) AS "_w"
  FROM MAIN.TREATMENTS
), "_s1" AS (
  SELECT
    DOC_ID,
    START_DT,
    TREATMENT_ID
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  DOCTORS.LAST_NAME AS last_name,
  DOCTORS.YEAR_REG AS year_reg,
  "_s1".START_DT AS first_treatment_date,
  "_s1".TREATMENT_ID AS first_treatment_id
FROM MAIN.DOCTORS DOCTORS
LEFT JOIN "_s1" "_s1"
  ON DOCTORS.DOC_ID = "_s1".DOC_ID
WHERE
  DOCTORS.YEAR_REG = EXTRACT(YEAR FROM CAST(ADD_MONTHS(SYS_EXTRACT_UTC(SYSTIMESTAMP), -24) AS DATE))
