SELECT
  SBTXTYPE AS transaction_type,
  COUNT(DISTINCT SBTXCUSTID) AS num_customers,
  AVG(SBTXSHARES) AS avg_shares
FROM MAIN.SBTRANSACTION
WHERE
  SBTXDATETIME <= TO_DATE('2023-03-31', 'YYYY-MM-DD')
  AND SBTXDATETIME >= TO_DATE('2023-01-01', 'YYYY-MM-DD')
GROUP BY
  SBTXTYPE
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
