SELECT
  ADVERSE_EVENTS.TREATMENT_ID AS treatment_id,
  TREATMENTS.START_DT AS treatment_start_date,
  ADVERSE_EVENTS.REPORTED_DT AS adverse_event_date,
  ADVERSE_EVENTS.DESCRIPTION AS description
FROM MAIN.ADVERSE_EVENTS ADVERSE_EVENTS
JOIN MAIN.TREATMENTS TREATMENTS
  ON (
    TRUNC(CAST(CAST(ADVERSE_EVENTS.REPORTED_DT AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST(TREATMENTS.START_DT AS DATE) AS DATE), 'DD')
  ) <= 10
  AND ADVERSE_EVENTS.TREATMENT_ID = TREATMENTS.TREATMENT_ID
