SELECT
  TRUNC(CAST(CREATED_AT AS DATE), 'MONTH') AS year_month,
  COUNT(DISTINCT SENDER_ID) AS active_users
FROM MAIN.WALLET_TRANSACTIONS_DAILY
WHERE
  CREATED_AT < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
  AND CREATED_AT >= ADD_MONTHS(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), -2)
  AND SENDER_TYPE = 0
GROUP BY
  TRUNC(CAST(CREATED_AT AS DATE), 'MONTH')
