SELECT
  ANY_VALUE(MERCHANTS.name) AS name,
  COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.coupon_id) / COUNT(DISTINCT WALLET_TRANSACTIONS_DAILY.txid) AS CPUR
FROM MAIN.MERCHANTS MERCHANTS
JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON MERCHANTS.mid = WALLET_TRANSACTIONS_DAILY.receiver_id
  AND WALLET_TRANSACTIONS_DAILY.status = 'success'
GROUP BY
  WALLET_TRANSACTIONS_DAILY.receiver_id
