WITH _S0 AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.RESTAURANT
  WHERE
    rating > 4.5
), _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.RESTAURANT
)
SELECT
  _S0.N_ROWS / _S1.N_ROWS AS ratio
FROM _S0 _S0
CROSS JOIN _S1 _S1
