WITH "_s1" AS (
  SELECT
    SBDPTICKERID,
    MAX(SBDPHIGH) AS MAX_SBDPHIGH,
    MIN(SBDPLOW) AS MIN_SBDPLOW
  FROM MAIN.SBDAILYPRICE
  WHERE
    SBDPDATE <= TO_DATE('2023-04-04', 'YYYY-MM-DD')
    AND SBDPDATE >= TO_DATE('2023-04-01', 'YYYY-MM-DD')
  GROUP BY
    SBDPTICKERID
)
SELECT
  SBTICKER.SBTICKERSYMBOL AS symbol,
  "_s1".MAX_SBDPHIGH - "_s1".MIN_SBDPLOW AS price_change
FROM MAIN.SBTICKER SBTICKER
LEFT JOIN "_s1" "_s1"
  ON SBTICKER.SBTICKERID = "_s1".SBDPTICKERID
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY
