WITH "_u_0" AS (
  SELECT
    USER_ID AS "_u_1"
  FROM MAIN.NOTIFICATIONS
  WHERE
    TYPE = 'transaction'
  GROUP BY
    USER_ID
)
SELECT
  USERS.UID AS user_id
FROM MAIN.USERS USERS
LEFT JOIN "_u_0" "_u_0"
  ON USERS.UID = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
