WITH _S1 AS (
  SELECT
    COUPONS.merchant_id AS MERCHANT_ID
  FROM MAIN.COUPONS AS COUPONS
), _S0 AS (
  SELECT
    MERCHANTS.mid AS MERCHANT_ID,
    MERCHANTS.name AS MERCHANT_NAME,
    MERCHANTS.mid AS MID
  FROM MAIN.MERCHANTS AS MERCHANTS
)
SELECT
  _S0.MERCHANT_ID AS merchant_id,
  _S0.MERCHANT_NAME AS merchant_name
FROM _S0 AS _S0
WHERE
  NOT EXISTS(
    SELECT
      1 AS "1"
    FROM _S1 AS _S1
    WHERE
      _S0.MID = _S1.MERCHANT_ID
  )
