WITH _S1 AS (
  SELECT
    MIN(sbtxdatetime) AS MIN_SBTXDATETIME,
    sbtxcustid AS SBTXCUSTID
  FROM MAIN.SBTRANSACTION
  GROUP BY
    sbtxcustid
)
SELECT
  SBCUSTOMER.sbcustid AS cust_id,
  DATEDIFF(
    SECOND,
    CAST(SBCUSTOMER.sbcustjoindate AS DATETIME),
    CAST(_S1.MIN_SBTXDATETIME AS DATETIME)
  ) / 86400.0 AS DaysFromJoinToFirstTransaction
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
JOIN _S1 AS _S1
  ON SBCUSTOMER.sbcustid = _S1.SBTXCUSTID
