SELECT
  COUPONS.CID AS coupon_id,
  COALESCE(SUM(WALLET_TRANSACTIONS_DAILY.AMOUNT), 0) AS total_discount
FROM MAIN.COUPONS COUPONS
LEFT JOIN MAIN.WALLET_TRANSACTIONS_DAILY WALLET_TRANSACTIONS_DAILY
  ON COUPONS.CID = WALLET_TRANSACTIONS_DAILY.COUPON_ID
WHERE
  COUPONS.MERCHANT_ID = 1
GROUP BY
  COUPONS.CID
