WITH "_s0" AS (
  SELECT
    TRUNC(CAST(CAST(SALE_DATE AS DATE) AS DATE), 'Q') AS QUARTER,
    CUSTOMER_ID,
    SUM(SALE_PRICE) AS SUM_SALE_PRICE
  FROM MAIN.SALES
  WHERE
    EXTRACT(YEAR FROM CAST(SALE_DATE AS DATE)) = 2023
  GROUP BY
    TRUNC(CAST(CAST(SALE_DATE AS DATE) AS DATE), 'Q'),
    CUSTOMER_ID
), "_t1" AS (
  SELECT
    "_s0".QUARTER,
    CUSTOMERS.STATE,
    SUM("_s0".SUM_SALE_PRICE) AS SUM_SUM_SALE_PRICE
  FROM "_s0" "_s0"
  JOIN MAIN.CUSTOMERS CUSTOMERS
    ON CUSTOMERS."_id" = "_s0".CUSTOMER_ID
  GROUP BY
    "_s0".QUARTER,
    CUSTOMERS.STATE
)
SELECT
  QUARTER AS quarter,
  STATE AS customer_state,
  SUM_SUM_SALE_PRICE AS total_sales
FROM "_t1"
WHERE
  NOT SUM_SUM_SALE_PRICE IS NULL AND SUM_SUM_SALE_PRICE > 0
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
