SELECT
  TRUNC(CAST(NOTIFICATIONS.created_at AS TIMESTAMP), 'WEEK') AS week,
  COUNT(*) AS num_notifs,
  NVL(
    SUM((
      MOD((
        DAY_OF_WEEK(NOTIFICATIONS.created_at) + 6
      ), 7)
    ) IN (5, 6)),
    0
  ) AS weekend_notifs
FROM MAIN.NOTIFICATIONS NOTIFICATIONS
JOIN MAIN.USERS USERS
  ON NOTIFICATIONS.user_id = USERS.uid AND USERS.country IN ('US', 'CA')
WHERE
  NOTIFICATIONS.created_at < TRUNC(CURRENT_TIMESTAMP, 'WEEK')
  AND NOTIFICATIONS.created_at >= DATE_SUB(TRUNC(CURRENT_TIMESTAMP, 'WEEK'), 3, WEEK)
GROUP BY
  TRUNC(CAST(NOTIFICATIONS.created_at AS TIMESTAMP), 'WEEK')
