WITH "_S1" AS (
  SELECT
    amount AS AMOUNT,
    receiver_id AS RECEIVER_ID
  FROM MAIN.WALLET_TRANSACTIONS_DAILY
  WHERE
    created_at >= TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP) + NUMTODSINTERVAL(150, 'day'), 'DAY')
    AND receiver_type = 1
)
SELECT
  ANY_VALUE(MERCHANTS.name) AS merchant_name,
  COUNT("_S1".RECEIVER_ID) AS total_transactions,
  COALESCE(SUM("_S1".AMOUNT), 0) AS total_amount
FROM MAIN.MERCHANTS MERCHANTS
LEFT JOIN "_S1" "_S1"
  ON MERCHANTS.mid = "_S1".RECEIVER_ID
GROUP BY
  MERCHANTS.mid
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 2 ROWS ONLY
