WITH "_s2" AS (
  SELECT
    NVL(EXTRACT(YEAR FROM CAST(START_DT AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(START_DT AS DATE)), 2, '0'), '') AS TREATMENT_MONTH,
    COUNT(DISTINCT PATIENT_ID) AS NDISTINCT_PATIENT_ID
  FROM MAIN.TREATMENTS
  WHERE
    START_DT < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
    AND START_DT >= ADD_MONTHS(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), -3)
  GROUP BY
    NVL(EXTRACT(YEAR FROM CAST(START_DT AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(START_DT AS DATE)), 2, '0'), '')
), "_s3" AS (
  SELECT
    NVL(EXTRACT(YEAR FROM CAST(TREATMENTS.START_DT AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(TREATMENTS.START_DT AS DATE)), 2, '0'), '') AS TREATMENT_MONTH,
    COUNT(DISTINCT TREATMENTS.PATIENT_ID) AS NDISTINCT_PATIENT_ID
  FROM MAIN.TREATMENTS TREATMENTS
  JOIN MAIN.DRUGS DRUGS
    ON DRUGS.DRUG_ID = TREATMENTS.DRUG_ID AND DRUGS.DRUG_TYPE = 'biologic'
  WHERE
    TREATMENTS.START_DT < TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH')
    AND TREATMENTS.START_DT >= ADD_MONTHS(TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'MONTH'), -3)
  GROUP BY
    NVL(EXTRACT(YEAR FROM CAST(TREATMENTS.START_DT AS DATE)), '') || '-' || NVL(LPAD(EXTRACT(MONTH FROM CAST(TREATMENTS.START_DT AS DATE)), 2, '0'), '')
)
SELECT
  "_s2".TREATMENT_MONTH AS month,
  "_s2".NDISTINCT_PATIENT_ID AS patient_count,
  COALESCE("_s3".NDISTINCT_PATIENT_ID, 0) AS biologic_treatment_count
FROM "_s2" "_s2"
LEFT JOIN "_s3" "_s3"
  ON "_s2".TREATMENT_MONTH = "_s3".TREATMENT_MONTH
ORDER BY
  1 DESC NULLS LAST
