WITH _S1 AS (
  SELECT
    SUM(sale_price) AS AGG_0,
    COUNT(*) AS AGG_1,
    salesperson_id AS SALESPERSON_ID
  FROM MAIN.SALES
  WHERE
    sale_date >= DATEADD(MONTH, -3, CURRENT_TIMESTAMP())
  GROUP BY
    salesperson_id
)
SELECT
  SALESPERSONS.first_name,
  SALESPERSONS.last_name,
  COALESCE(_S1.AGG_1, 0) AS total_sales,
  COALESCE(_S1.AGG_0, 0) AS total_revenue
FROM MAIN.SALESPERSONS AS SALESPERSONS
LEFT JOIN _S1 AS _S1
  ON SALESPERSONS._id = _S1.SALESPERSON_ID
ORDER BY
  TOTAL_REVENUE DESC NULLS LAST
LIMIT 3
