SELECT
  (
    L_EXTENDEDPRICE + L_TAX
  ) / CASE WHEN (
    L_DISCOUNT * 2
  ) <> 0 THEN L_DISCOUNT * 2 ELSE NULL END AS computed_value
FROM TPCH.LINEITEM
ORDER BY
  L_DISCOUNT NULLS FIRST
FETCH FIRST 1 ROWS ONLY
