SELECT
  CASE
    WHEN CASE WHEN L_DISCOUNT > 0 THEN 1 ELSE L_DISCOUNT END = 0
    THEN 0
    ELSE L_EXTENDEDPRICE / CASE WHEN L_DISCOUNT > 0 THEN 1 ELSE L_DISCOUNT END
  END AS computed_value
FROM TPCH.LINEITEM
ORDER BY
  L_DISCOUNT NULLS FIRST
FETCH FIRST 1 ROWS ONLY
