SELECT
  L_QUANTITY * CASE WHEN L_DISCOUNT = 0 THEN 0 ELSE L_EXTENDEDPRICE / L_DISCOUNT END + L_TAX AS computed_value
FROM TPCH.LINEITEM
ORDER BY
  L_DISCOUNT NULLS FIRST,
  L_TAX NULLS FIRST
FETCH FIRST 1 ROWS ONLY
