SELECT
  CASE
    WHEN CASE WHEN L_DISCOUNT > 0.05 THEN L_DISCOUNT ELSE NULL END = 0
    THEN 0
    ELSE L_EXTENDEDPRICE / CASE WHEN L_DISCOUNT > 0.05 THEN L_DISCOUNT ELSE NULL END
  END AS computed_value
FROM TPCH.LINEITEM
ORDER BY
  L_DISCOUNT NULLS FIRST
FETCH FIRST 1 ROWS ONLY
