SELECT
  CASE
    WHEN (
      L_DISCOUNT * 2
    ) = 0
    THEN 0
    ELSE (
      L_EXTENDEDPRICE + L_TAX
    ) / (
      L_DISCOUNT * 2
    )
  END AS computed_value
FROM TPCH.LINEITEM
ORDER BY
  L_DISCOUNT NULLS FIRST
FETCH FIRST 1 ROWS ONLY
