WITH "_T3" AS (
  SELECT
    o_orderdate AS O_ORDERDATE
  FROM TPCH.ORDERS
), "_S0" AS (
  SELECT
    MIN(O_ORDERDATE) AS MIN_O_ORDERDATE
  FROM "_T3"
), "_S2" AS (
  SELECT
    DATEDIFF(CAST(ORDERS.o_orderdate AS DATETIME), CAST("_S0".MIN_O_ORDERDATE AS DATETIME), WEEK) AS ORD_WK,
    COUNT(*) AS N_ROWS
  FROM "_S0" "_S0"
  JOIN TPCH.ORDERS ORDERS
    ON DATEDIFF(CAST(ORDERS.o_orderdate AS DATETIME), CAST("_S0".MIN_O_ORDERDATE AS DATETIME), WEEK) < 10
    AND ORDERS.o_orderpriority = '1-URGENT'
    AND ORDERS.o_orderstatus = 'F'
  GROUP BY
    DATEDIFF(CAST(ORDERS.o_orderdate AS DATETIME), CAST("_S0".MIN_O_ORDERDATE AS DATETIME), WEEK)
), "_S3" AS (
  SELECT
    MIN(O_ORDERDATE) AS MIN_O_ORDERDATE
  FROM "_T3"
), "_T0" AS (
  SELECT
    DATEDIFF(
      CAST(LINEITEM.l_receiptdate AS DATETIME),
      CAST("_S3".MIN_O_ORDERDATE AS DATETIME),
      WEEK
    ) AS LINE_WK,
    "_S2".ORD_WK,
    ANY_VALUE("_S2".N_ROWS) AS ANYTHING_N_ROWS,
    COUNT(*) AS N_ROWS
  FROM "_S2" "_S2"
  CROSS JOIN "_S3" "_S3"
  JOIN TPCH.LINEITEM LINEITEM
    ON DATEDIFF(
      CAST(LINEITEM.l_receiptdate AS DATETIME),
      CAST("_S3".MIN_O_ORDERDATE AS DATETIME),
      WEEK
    ) < 10
    AND EXTRACT(YEAR FROM CAST(LINEITEM.l_receiptdate AS DATETIME)) = 1992
    AND LINEITEM.l_returnflag = 'R'
    AND LINEITEM.l_shipmode = 'RAIL'
    AND "_S2".ORD_WK = DATEDIFF(
      CAST(LINEITEM.l_receiptdate AS DATETIME),
      CAST("_S3".MIN_O_ORDERDATE AS DATETIME),
      WEEK
    )
  GROUP BY
    DATEDIFF(
      CAST(LINEITEM.l_receiptdate AS DATETIME),
      CAST("_S3".MIN_O_ORDERDATE AS DATETIME),
      WEEK
    ),
    "_S2".ORD_WK
)
SELECT
  ORD_WK AS wk,
  N_ROWS AS n_lines,
  ANYTHING_N_ROWS AS n_orders,
  ROUND(
    SUM(N_ROWS) OVER (ORDER BY LINE_WK ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(ANYTHING_N_ROWS) OVER (ORDER BY ORD_WK ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    4
  ) AS lpo
FROM "_T0"
ORDER BY
  1 NULLS FIRST
