WITH "_T0" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) AS YEAR_O_ORDERDATE,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    EXTRACT(MONTH FROM CAST(o_orderdate AS DATE)),
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATE))
)
SELECT
  YEAR_O_ORDERDATE AS year,
  MAX(N_ROWS) AS best_month
FROM "_T0"
GROUP BY
  YEAR_O_ORDERDATE
