WITH "_t0" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)),
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE))
)
SELECT
  YEAR_O_ORDERDATE AS year,
  MAX(N_ROWS) AS best_month
FROM "_t0"
GROUP BY
  YEAR_O_ORDERDATE
