WITH "_s0" AS (
  SELECT
    N_NAME,
    N_REGIONKEY
  FROM TPCH.NATION
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 2 ROWS ONLY
), "_s1" AS (
  SELECT
    R_NAME,
    R_REGIONKEY,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (PARTITION BY R_REGIONKEY ORDER BY R_REGIONKEY DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(R_REGIONKEY) OVER (PARTITION BY R_REGIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN R_REGIONKEY
      ELSE NULL
    END AS AVG_EXPR
  FROM TPCH.REGION
)
SELECT
  "_s0".N_NAME AS nation_name,
  "_s1".R_NAME AS a1,
  "_s1".R_NAME AS a2,
  "_s1".R_REGIONKEY AS a3,
  CASE
    WHEN NOT CASE WHEN "_s1".R_NAME <> 'AMERICA' THEN "_s1".R_REGIONKEY ELSE NULL END IS NULL
    THEN 1
    ELSE 0
  END AS a4,
  1 AS a5,
  "_s1".R_REGIONKEY AS a6,
  "_s1".R_NAME AS a7,
  "_s1".AVG_EXPR AS a8
FROM "_s0" "_s0"
JOIN "_s1" "_s1"
  ON "_s0".N_REGIONKEY = "_s1".R_REGIONKEY
ORDER BY
  1 NULLS FIRST
