SELECT
  EVENTS.ev_typ AS event_type,
  COUNT(*) AS n_events
FROM EVENTS EVENTS
JOIN SEASONS SEASONS
  ON (
    SEASONS.s_month1 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATE))
    OR SEASONS.s_month2 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATE))
    OR SEASONS.s_month3 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATE))
  )
  AND SEASONS.s_name = 'Summer'
GROUP BY
  EVENTS.ev_typ
ORDER BY
  1 NULLS FIRST
