WITH "_s0" AS (
  SELECT
    USER_ID,
    USER_NAME
  FROM USERS
), "_s1" AS (
  SELECT
    SEARCH_STRING,
    SEARCH_USER_ID
  FROM SEARCHES
)
SELECT
  ANY_VALUE("_s0".USER_NAME) AS user_name,
  COUNT(DISTINCT "_s7".USER_ID) AS n_other_users
FROM "_s0" "_s0"
JOIN "_s1" "_s1"
  ON "_s0".USER_ID = "_s1".SEARCH_USER_ID
JOIN EVENTS EVENTS
  ON LOWER("_s1".SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
JOIN "_s1" "_s5"
  ON LOWER("_s5".SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
JOIN "_s0" "_s7"
  ON "_s0".USER_NAME <> "_s7".USER_NAME AND "_s5".SEARCH_USER_ID = "_s7".USER_ID
GROUP BY
  "_s0".USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 7 ROWS ONLY
