WITH _T0 AS (
  SELECT
    ANY_VALUE(TIMES.t_start_hour) AS ANYTHING_T_START_HOUR,
    COUNT(*) AS N_ROWS,
    TIMES.t_name AS T_NAME
  FROM TIMES AS TIMES
  JOIN SEARCHES AS SEARCHES
    ON TIMES.t_end_hour > HOUR(CAST(SEARCHES.search_ts AS TIMESTAMP))
    AND TIMES.t_start_hour <= HOUR(CAST(SEARCHES.search_ts AS TIMESTAMP))
  GROUP BY
    3
)
SELECT
  T_NAME AS tod,
  ROUND((
    100.0 * N_ROWS
  ) / SUM(N_ROWS) OVER (), 2) AS pct_searches
FROM _T0
ORDER BY
  ANYTHING_T_START_HOUR NULLS FIRST
