WITH _S0 AS (
  SELECT
    user_id AS USER_ID,
    user_name AS USER_NAME
  FROM USERS
), _S1 AS (
  SELECT
    search_string AS SEARCH_STRING,
    search_user_id AS SEARCH_USER_ID
  FROM SEARCHES
)
SELECT
  ANY_VALUE(_S0.USER_NAME) AS user_name,
  COUNT(DISTINCT _S7.USER_ID) AS n_other_users
FROM _S0 AS _S0
JOIN _S1 AS _S1
  ON _S0.USER_ID = _S1.SEARCH_USER_ID
JOIN EVENTS AS EVENTS
  ON CONTAINS(LOWER(_S1.SEARCH_STRING), LOWER(EVENTS.ev_name))
JOIN _S1 AS _S5
  ON CONTAINS(LOWER(_S5.SEARCH_STRING), LOWER(EVENTS.ev_name))
JOIN _S0 AS _S7
  ON _S0.USER_NAME <> _S7.USER_NAME AND _S5.SEARCH_USER_ID = _S7.USER_ID
GROUP BY
  _S0.USER_ID
ORDER BY
  N_OTHER_USERS DESC NULLS LAST,
  ANY_VALUE(_S0.USER_NAME) NULLS FIRST
LIMIT 7
