WITH _T1 AS (
  SELECT
    COUNT(*) AS N_SEARCHES,
    SEARCHES.search_engine AS SEARCH_ENGINE,
    TIMES.t_name AS TOD
  FROM TIMES AS TIMES
  JOIN SEARCHES AS SEARCHES
    ON TIMES.t_end_hour > HOUR(SEARCHES.search_ts)
    AND TIMES.t_start_hour <= HOUR(SEARCHES.search_ts)
  GROUP BY
    SEARCHES.search_engine,
    TIMES.t_name
), _T0 AS (
  SELECT
    N_SEARCHES,
    SEARCH_ENGINE,
    TOD
  FROM _T1
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY TOD ORDER BY N_SEARCHES DESC, SEARCH_ENGINE) = 1
)
SELECT
  TOD AS tod,
  SEARCH_ENGINE AS search_engine,
  N_SEARCHES AS n_searches
FROM _T0
ORDER BY
  TOD NULLS FIRST
