WITH "_s0" AS (
  SELECT DISTINCT
    SEARCH_ENGINE
  FROM SEARCHES
), "_s1" AS (
  SELECT
    SEARCH_ENGINE,
    COUNT(DISTINCT SEARCH_USER_ID) AS NDISTINCT_SEARCH_USER_ID
  FROM SEARCHES
  WHERE
    EXTRACT(YEAR FROM CAST(SEARCH_TS AS DATE)) <= 2019
    AND EXTRACT(YEAR FROM CAST(SEARCH_TS AS DATE)) >= 2010
  GROUP BY
    SEARCH_ENGINE
)
SELECT
  "_s0".SEARCH_ENGINE AS engine,
  COALESCE("_s1".NDISTINCT_SEARCH_USER_ID, 0) AS n_users
FROM "_s0" "_s0"
LEFT JOIN "_s1" "_s1"
  ON "_s0".SEARCH_ENGINE = "_s1".SEARCH_ENGINE
ORDER BY
  1 NULLS FIRST
