WITH "_s0" AS (
  SELECT
    S_MONTH1,
    S_MONTH2,
    S_MONTH3,
    S_NAME
  FROM SEASONS
), "_s5" AS (
  SELECT
    EV_DT,
    EV_NAME
  FROM EVENTS
), "_s9" AS (
  SELECT
    "_s2".S_NAME,
    SEARCHES.SEARCH_ID
  FROM "_s0" "_s2"
  JOIN SEARCHES SEARCHES
    ON "_s2".S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s2".S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s2".S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
  JOIN "_s5" "_s5"
    ON LOWER(SEARCHES.SEARCH_STRING) LIKE CONCAT('%', LOWER("_s5".EV_NAME), '%')
  JOIN "_s0" "_s7"
    ON "_s2".S_NAME = "_s7".S_NAME
    AND (
      "_s7".S_MONTH1 = EXTRACT(MONTH FROM CAST("_s5".EV_DT AS DATE))
      OR "_s7".S_MONTH2 = EXTRACT(MONTH FROM CAST("_s5".EV_DT AS DATE))
      OR "_s7".S_MONTH3 = EXTRACT(MONTH FROM CAST("_s5".EV_DT AS DATE))
    )
), "_t1" AS (
  SELECT
    "_s0".S_NAME,
    COUNT("_s9".SEARCH_ID) AS COUNT_SEARCH_ID
  FROM "_s0" "_s0"
  JOIN SEARCHES SEARCHES
    ON "_s0".S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s0".S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s0".S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
  LEFT JOIN "_s9" "_s9"
    ON SEARCHES.SEARCH_ID = "_s9".SEARCH_ID AND "_s0".S_NAME = "_s9".S_NAME
  GROUP BY
    "_s0".S_NAME,
    SEARCHES.SEARCH_ID
), "_s16" AS (
  SELECT
    S_NAME,
    COUNT(*) AS N_ROWS,
    SUM((
      NOT NULLIF(COUNT_SEARCH_ID, 0) IS NULL AND NULLIF(COUNT_SEARCH_ID, 0) > 0
    )) AS SUM_IS_INTRA_SEASON
  FROM "_t1"
  GROUP BY
    S_NAME
), "_s17" AS (
  SELECT
    "_s10".S_NAME,
    COUNT(*) AS N_ROWS,
    SUM("_s15".S_NAME = "_s10".S_NAME) AS SUM_IS_INTRA_SEASON
  FROM "_s0" "_s10"
  JOIN "_s5" "_s11"
    ON "_s10".S_MONTH1 = EXTRACT(MONTH FROM CAST("_s11".EV_DT AS DATE))
    OR "_s10".S_MONTH2 = EXTRACT(MONTH FROM CAST("_s11".EV_DT AS DATE))
    OR "_s10".S_MONTH3 = EXTRACT(MONTH FROM CAST("_s11".EV_DT AS DATE))
  JOIN SEARCHES SEARCHES
    ON LOWER(SEARCHES.SEARCH_STRING) LIKE CONCAT('%', LOWER("_s11".EV_NAME), '%')
  JOIN "_s0" "_s15"
    ON "_s15".S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s15".S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
    OR "_s15".S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.SEARCH_TS AS DATE))
  GROUP BY
    "_s10".S_NAME
)
SELECT
  "_s16".S_NAME AS season_name,
  ROUND((
    100.0 * COALESCE("_s16".SUM_IS_INTRA_SEASON, 0)
  ) / "_s16".N_ROWS, 2) AS pct_season_searches,
  ROUND(
    (
      100.0 * COALESCE("_s17".SUM_IS_INTRA_SEASON, 0)
    ) / COALESCE("_s17".N_ROWS, 0),
    2
  ) AS pct_event_searches
FROM "_s16" "_s16"
LEFT JOIN "_s17" "_s17"
  ON "_s16".S_NAME = "_s17".S_NAME
ORDER BY
  1 NULLS FIRST
