WITH _S0 AS (
  SELECT
    user_id AS USER_ID,
    user_name AS USER_NAME
  FROM USERS
), _T2 AS (
  SELECT
    ANY_VALUE(SEARCHES.search_user_id) AS ANYTHING_SEARCH_USER_ID,
    ANY_VALUE(_S0.USER_NAME) AS ANYTHING_USER_NAME,
    _S0.USER_ID
  FROM _S0 AS _S0
  JOIN SEARCHES AS SEARCHES
    ON SEARCHES.search_user_id = _S0.USER_ID
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN SEARCHES AS SEARCHES_2
    ON CONTAINS(LOWER(SEARCHES_2.search_string), LOWER(EVENTS.ev_name))
  JOIN _S0 AS _S7
    ON SEARCHES_2.search_user_id = _S7.USER_ID AND _S0.USER_NAME <> _S7.USER_NAME
  GROUP BY
    SEARCHES.search_id,
    3
)
SELECT
  ANY_VALUE(ANYTHING_USER_NAME) AS user_name,
  COUNT(*) AS n_searches
FROM _T2
WHERE
  ANYTHING_SEARCH_USER_ID = USER_ID
GROUP BY
  USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
LIMIT 4
