WITH _S2 AS (
  SELECT
    ev_dt AS EV_DT,
    ev_key AS EV_KEY
  FROM EVENTS
)
SELECT
  EVENTS.ev_name AS event_name,
  ERAS.er_name AS era_name,
  EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME)) AS event_year,
  SEASONS.s_name AS season_name,
  TIMES.t_name AS tod
FROM EVENTS EVENTS
JOIN ERAS ERAS
  ON ERAS.er_end_year > EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
  AND ERAS.er_start_year <= EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
JOIN _S2 _S2
  ON EVENTS.ev_key = _S2.EV_KEY
JOIN SEASONS SEASONS
  ON SEASONS.s_month1 = EXTRACT(MONTH FROM CAST(_S2.EV_DT AS DATETIME))
  OR SEASONS.s_month2 = EXTRACT(MONTH FROM CAST(_S2.EV_DT AS DATETIME))
  OR SEASONS.s_month3 = EXTRACT(MONTH FROM CAST(_S2.EV_DT AS DATETIME))
JOIN _S2 _S6
  ON EVENTS.ev_key = _S6.EV_KEY
JOIN TIMES TIMES
  ON TIMES.t_end_hour > EXTRACT(HOUR FROM CAST(_S6.EV_DT AS DATETIME))
  AND TIMES.t_start_hour <= EXTRACT(HOUR FROM CAST(_S6.EV_DT AS DATETIME))
WHERE
  EVENTS.ev_typ = 'culture'
ORDER BY
  EVENTS.ev_dt NULLS FIRST
FETCH FIRST 6 ROWS ONLY
