WITH "_T2" AS (
  SELECT
    ERAS.er_end_year AS ER_END_YEAR,
    ERAS.er_name AS ER_NAME,
    ERAS.er_start_year AS ER_START_YEAR,
    EVENTS.ev_dt AS EV_DT,
    DATEDIFF(
      CAST(EVENTS.ev_dt AS DATETIME),
      CAST(LAG(EVENTS.ev_dt, 1) OVER (PARTITION BY ERAS.er_name, ERAS.er_name ORDER BY EVENTS.ev_dt) AS DATETIME),
      DAY
    ) AS DAY_GAP
  FROM ERAS ERAS
  JOIN EVENTS EVENTS
    ON ERAS.er_end_year > EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
    AND ERAS.er_start_year <= EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
)
SELECT
  ER_NAME AS era_name,
  AVG(DAY_GAP) AS avg_event_gap
FROM "_T2"
WHERE
  ER_END_YEAR > EXTRACT(YEAR FROM CAST(EV_DT AS DATETIME))
  AND ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EV_DT AS DATETIME))
GROUP BY
  ER_NAME
ORDER BY
  ANY_VALUE(ER_START_YEAR) NULLS FIRST
