WITH _S0 AS (
  SELECT
    user_id AS USER_ID,
    user_name AS USER_NAME
  FROM USERS
), _T2 AS (
  SELECT
    ANY_VALUE(_S0.USER_ID) AS ANYTHING_USER_ID,
    ANY_VALUE(_S0.USER_NAME) AS ANYTHING_USER_NAME,
    COUNT(*) AS N_ROWS
  FROM _S0 AS _S0
  JOIN SEARCHES AS SEARCHES
    ON SEARCHES.search_user_id = _S0.USER_ID
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN SEARCHES AS SEARCHES_2
    ON CONTAINS(LOWER(SEARCHES_2.search_string), LOWER(EVENTS.ev_name))
  JOIN USERS AS USERS_2
    ON SEARCHES_2.search_user_id = USERS_2.user_id
  WHERE
    USERS.user_name <> USERS_2.user_name
  GROUP BY
    SEARCHES.search_id,
    _S0.USER_ID
)
SELECT
  ANY_VALUE(ANYTHING_USER_NAME) AS user_name,
  COUNT(*) AS n_searches
FROM _T2
WHERE
  N_ROWS > 0
GROUP BY
  ANYTHING_USER_ID
ORDER BY
  N_SEARCHES DESC NULLS LAST,
  ANY_VALUE(ANYTHING_USER_NAME) NULLS FIRST
LIMIT 4
