WITH _T1 AS (
  SELECT
    ERAS.er_name AS ER_NAME,
    ERAS.er_start_year AS ER_START_YEAR,
    EVENTS.ev_name AS EV_NAME
  FROM ERAS AS ERAS
  JOIN EVENTS AS EVENTS
    ON ERAS.er_end_year > YEAR(EVENTS.ev_dt)
    AND ERAS.er_start_year <= YEAR(EVENTS.ev_dt)
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY ERAS.er_name ORDER BY EVENTS.ev_dt) = 1
)
SELECT
  ER_NAME AS era_name,
  EV_NAME AS event_name
FROM _T1
ORDER BY
  ER_START_YEAR NULLS FIRST
