SELECT
  EVENTS.ev_typ AS event_type,
  COUNT(*) AS n_events
FROM EVENTS AS EVENTS
JOIN SEASONS AS SEASONS
  ON (
    SEASONS.s_month1 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
    OR SEASONS.s_month2 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
    OR SEASONS.s_month3 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
  )
  AND SEASONS.s_name = 'Summer'
GROUP BY
  1
ORDER BY
  1 COLLATE utf8mb4_bin
