WITH "_s0" AS (
  SELECT
    USER_ID,
    USER_NAME
  FROM USERS
), "_t2" AS (
  SELECT
    "_s0".USER_ID,
    ANY_VALUE(SEARCHES.SEARCH_USER_ID) AS ANYTHING_SEARCH_USER_ID,
    ANY_VALUE("_s0".USER_NAME) AS ANYTHING_USER_NAME
  FROM "_s0" "_s0"
  JOIN SEARCHES SEARCHES
    ON SEARCHES.SEARCH_USER_ID = "_s0".USER_ID
  JOIN EVENTS EVENTS
    ON LOWER(SEARCHES.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
  JOIN SEARCHES SEARCHES_2
    ON LOWER(SEARCHES_2.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
  JOIN "_s0" "_s7"
    ON SEARCHES_2.SEARCH_USER_ID = "_s7".USER_ID AND "_s0".USER_NAME <> "_s7".USER_NAME
  GROUP BY
    SEARCHES.SEARCH_ID,
    "_s0".USER_ID
)
SELECT
  ANY_VALUE(ANYTHING_USER_NAME) AS user_name,
  COUNT(*) AS n_searches
FROM "_t2"
WHERE
  ANYTHING_SEARCH_USER_ID = USER_ID
GROUP BY
  USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 4 ROWS ONLY
