SELECT
  EVENTS.EV_TYP AS event_type,
  COUNT(*) AS n_events
FROM EVENTS EVENTS
JOIN SEASONS SEASONS
  ON (
    SEASONS.S_MONTH1 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
    OR SEASONS.S_MONTH2 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
    OR SEASONS.S_MONTH3 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
  )
  AND SEASONS.S_NAME = 'Summer'
GROUP BY
  EVENTS.EV_TYP
ORDER BY
  1 NULLS FIRST
