WITH "_t1" AS (
  SELECT
    EVENTS.EV_TYP,
    USERS.USER_REGION,
    COUNT(DISTINCT SEARCHES.SEARCH_ID) AS NDISTINCT_SEARCH_ID
  FROM EVENTS EVENTS
  JOIN SEARCHES SEARCHES
    ON LOWER(SEARCHES.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
  JOIN USERS USERS
    ON SEARCHES.SEARCH_USER_ID = USERS.USER_ID
  GROUP BY
    EVENTS.EV_TYP,
    USERS.USER_REGION
), "_t" AS (
  SELECT
    EV_TYP,
    USER_REGION,
    NDISTINCT_SEARCH_ID,
    ROW_NUMBER() OVER (PARTITION BY USER_REGION ORDER BY NDISTINCT_SEARCH_ID DESC) AS "_w"
  FROM "_t1"
)
SELECT
  USER_REGION AS region,
  EV_TYP AS event_type,
  NDISTINCT_SEARCH_ID AS n_searches
FROM "_t"
WHERE
  "_w" = 1
