SELECT
  ANY_VALUE(SEASONS.s_name) AS season_name,
  COUNT(*) AS n_events
FROM SEASONS AS SEASONS
JOIN EVENTS AS EVENTS
  ON SEASONS.s_month1 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
  OR SEASONS.s_month2 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
  OR SEASONS.s_month3 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
GROUP BY
  SEASONS.s_name
ORDER BY
  N_EVENTS DESC NULLS LAST,
  SEASON_NAME NULLS FIRST
