WITH _S0 AS (
  SELECT
    s_month1 AS FIRST_MONTH,
    s_name AS NAME,
    s_name AS SEASON_NAME,
    s_month2 AS SECOND_MONTH,
    s_month3 AS THIRD_MONTH
  FROM SEASONS
), _S7 AS (
  SELECT
    s_month1 AS FIRST_MONTH,
    s_name AS NAME,
    s_month2 AS SECOND_MONTH,
    s_month3 AS THIRD_MONTH
  FROM SEASONS
), _S9 AS (
  SELECT
    COUNT(*) AS AGG_0,
    _S2.NAME,
    SEARCHES.search_id AS SEARCH_ID
  FROM _S0 AS _S2
  JOIN SEARCHES AS SEARCHES
    ON _S2.FIRST_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S2.SECOND_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S2.THIRD_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
  JOIN EVENTS AS EVENTS
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN _S7 AS _S7
    ON _S2.SEASON_NAME = _S7.NAME
    AND (
      _S7.FIRST_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
      OR _S7.SECOND_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
      OR _S7.THIRD_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
    )
  GROUP BY
    _S2.NAME,
    SEARCHES.search_id
), _S16 AS (
  SELECT
    ANY_VALUE(_S0.NAME) AS AGG_1,
    COUNT_IF((
      NOT _S9.AGG_0 IS NULL AND _S9.AGG_0 > 0
    )) AS AGG_2,
    COUNT(*) AS AGG_3,
    ANY_VALUE(_S0.SEASON_NAME) AS AGG_4
  FROM _S0 AS _S0
  JOIN SEARCHES AS SEARCHES
    ON _S0.FIRST_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S0.SECOND_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S0.THIRD_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
  LEFT JOIN _S9 AS _S9
    ON SEARCHES.search_id = _S9.SEARCH_ID AND _S0.NAME = _S9.NAME
  GROUP BY
    _S0.NAME
), _S17 AS (
  SELECT
    COUNT_IF(_S10.SEASON_NAME = _S15.NAME) AS AGG_0,
    COUNT(*) AS AGG_1,
    _S10.NAME
  FROM _S0 AS _S10
  JOIN EVENTS AS EVENTS
    ON _S10.FIRST_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
    OR _S10.SECOND_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
    OR _S10.THIRD_MONTH = DATE_PART(MONTH, EVENTS.ev_dt)
  JOIN SEARCHES AS SEARCHES
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN _S7 AS _S15
    ON _S15.FIRST_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S15.SECOND_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
    OR _S15.THIRD_MONTH = DATE_PART(MONTH, SEARCHES.search_ts)
  GROUP BY
    _S10.NAME
)
SELECT
  _S16.AGG_4 AS season_name,
  ROUND((
    100.0 * COALESCE(_S16.AGG_2, 0)
  ) / _S16.AGG_3, 2) AS pct_season_searches,
  ROUND((
    100.0 * COALESCE(_S17.AGG_0, 0)
  ) / COALESCE(_S17.AGG_1, 0), 2) AS pct_event_searches
FROM _S16 AS _S16
LEFT JOIN _S17 AS _S17
  ON _S16.AGG_1 = _S17.NAME
ORDER BY
  SEASON_NAME NULLS FIRST
