SELECT
  EVENTS.ev_typ AS event_type,
  COUNT(*) AS n_events
FROM EVENTS AS EVENTS
JOIN SEASONS AS SEASONS
  ON (
    SEASONS.s_month1 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
    OR SEASONS.s_month2 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
    OR SEASONS.s_month3 = MONTH(CAST(EVENTS.ev_dt AS TIMESTAMP))
  )
  AND SEASONS.s_name = 'Summer'
GROUP BY
  1
ORDER BY
  1 NULLS FIRST
