WITH _T1 AS (
  SELECT
    COUNT(DISTINCT SEARCHES.search_id) AS N_SEARCHES,
    EVENTS.ev_typ AS EVENT_TYPE,
    USERS.user_region AS REGION
  FROM EVENTS AS EVENTS
  JOIN SEARCHES AS SEARCHES
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN USERS AS USERS
    ON SEARCHES.search_user_id = USERS.user_id
  GROUP BY
    EVENTS.ev_typ,
    USERS.user_region
), _T0 AS (
  SELECT
    N_SEARCHES,
    EVENT_TYPE,
    REGION
  FROM _T1
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY REGION ORDER BY N_SEARCHES DESC) = 1
)
SELECT
  REGION AS region,
  EVENT_TYPE AS event_type,
  N_SEARCHES AS n_searches
FROM _T0
