WITH _S0 AS (
  SELECT
    s_month1 AS S_MONTH1,
    s_month2 AS S_MONTH2,
    s_month3 AS S_MONTH3,
    s_name AS S_NAME
  FROM SEASONS
), _S5 AS (
  SELECT
    ev_dt AS EV_DT,
    ev_name AS EV_NAME
  FROM EVENTS
), _S9 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _S2.S_NAME,
    SEARCHES.search_id AS SEARCH_ID
  FROM _S0 AS _S2
  JOIN SEARCHES AS SEARCHES
    ON _S2.FIRST_MONTH = MONTH(SEARCHES.search_ts)
    OR _S2.SECOND_MONTH = MONTH(SEARCHES.search_ts)
    OR _S2.THIRD_MONTH = MONTH(SEARCHES.search_ts)
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN _S7 AS _S7
    ON _S2.SEASON_NAME = _S7.NAME
    AND (
      _S7.FIRST_MONTH = MONTH(EVENTS.ev_dt)
      OR _S7.SECOND_MONTH = MONTH(EVENTS.ev_dt)
      OR _S7.THIRD_MONTH = MONTH(EVENTS.ev_dt)
    )
  GROUP BY
    _S2.S_NAME,
    SEARCHES.search_id
), _S16 AS (
  SELECT
    ANY_VALUE(_S0.S_NAME) AS ANYTHING_S_NAME,
    COUNT(*) AS N_ROWS,
    COUNT_IF((
      NOT _S9.N_ROWS IS NULL AND _S9.N_ROWS > 0
    )) AS SUM_IS_INTRA_SEASON
  FROM _S0 AS _S0
  JOIN SEARCHES AS SEARCHES
    ON _S0.FIRST_MONTH = MONTH(SEARCHES.search_ts)
    OR _S0.SECOND_MONTH = MONTH(SEARCHES.search_ts)
    OR _S0.THIRD_MONTH = MONTH(SEARCHES.search_ts)
  LEFT JOIN _S9 AS _S9
    ON SEARCHES.search_id = _S9.SEARCH_ID AND _S0.S_NAME = _S9.S_NAME
  GROUP BY
    _S0.S_NAME
), _S17 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    COUNT_IF(_S15.S_NAME = _S10.S_NAME) AS SUM_IS_INTRA_SEASON,
    _S10.S_NAME
  FROM _S0 AS _S10
  JOIN EVENTS AS EVENTS
    ON _S10.FIRST_MONTH = MONTH(EVENTS.ev_dt)
    OR _S10.SECOND_MONTH = MONTH(EVENTS.ev_dt)
    OR _S10.THIRD_MONTH = MONTH(EVENTS.ev_dt)
  JOIN SEARCHES AS SEARCHES
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN _S7 AS _S15
    ON _S15.FIRST_MONTH = MONTH(SEARCHES.search_ts)
    OR _S15.SECOND_MONTH = MONTH(SEARCHES.search_ts)
    OR _S15.THIRD_MONTH = MONTH(SEARCHES.search_ts)
  GROUP BY
    _S10.S_NAME
)
SELECT
  _S16.ANYTHING_S_NAME AS season_name,
  ROUND((
    100.0 * COALESCE(_S16.SUM_IS_INTRA_SEASON, 0)
  ) / _S16.N_ROWS, 2) AS pct_season_searches,
  ROUND((
    100.0 * COALESCE(_S17.SUM_IS_INTRA_SEASON, 0)
  ) / COALESCE(_S17.N_ROWS, 0), 2) AS pct_event_searches
FROM _S16 AS _S16
LEFT JOIN _S17 AS _S17
  ON _S16.ANYTHING_S_NAME = _S17.S_NAME
ORDER BY
  _S16.ANYTHING_S_NAME NULLS FIRST
