WITH _S0 AS (
  SELECT
    s_month1 AS S_MONTH1,
    s_month2 AS S_MONTH2,
    s_month3 AS S_MONTH3,
    s_name AS S_NAME
  FROM SEASONS
), _S5 AS (
  SELECT
    ev_dt AS EV_DT,
    ev_name AS EV_NAME
  FROM EVENTS
), _S9 AS (
  SELECT
    _S2.S_NAME,
    SEARCHES.search_id AS SEARCH_ID
  FROM _S0 _S2
  JOIN SEARCHES SEARCHES
    ON _S2.S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S2.S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S2.S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
  JOIN _S5 _S5
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(_S5.EV_NAME), '%')
  JOIN _S0 _S7
    ON _S2.S_NAME = _S7.S_NAME
    AND (
      _S7.S_MONTH1 = EXTRACT(MONTH FROM CAST(_S5.EV_DT AS DATETIME))
      OR _S7.S_MONTH2 = EXTRACT(MONTH FROM CAST(_S5.EV_DT AS DATETIME))
      OR _S7.S_MONTH3 = EXTRACT(MONTH FROM CAST(_S5.EV_DT AS DATETIME))
    )
), _T1 AS (
  SELECT
    _S0.S_NAME,
    COUNT(_S9.SEARCH_ID) AS COUNT_SEARCH_ID
  FROM _S0 _S0
  JOIN SEARCHES SEARCHES
    ON _S0.S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S0.S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S0.S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
  LEFT JOIN _S9 _S9
    ON SEARCHES.search_id = _S9.SEARCH_ID AND _S0.S_NAME = _S9.S_NAME
  GROUP BY
    SEARCHES.search_id,
    _S0.S_NAME
), _S16 AS (
  SELECT
    S_NAME,
    COUNT(*) AS N_ROWS,
    SUM((
      NOT NULLIF(COUNT_SEARCH_ID, 0) IS NULL AND NULLIF(COUNT_SEARCH_ID, 0) > 0
    )) AS SUM_IS_INTRA_SEASON
  FROM _T1
  GROUP BY
    S_NAME
), _S17 AS (
  SELECT
    _S10.S_NAME,
    COUNT(*) AS N_ROWS,
    SUM(_S15.S_NAME = _S10.S_NAME) AS SUM_IS_INTRA_SEASON
  FROM _S0 _S10
  JOIN _S5 _S11
    ON _S10.S_MONTH1 = EXTRACT(MONTH FROM CAST(_S11.EV_DT AS DATETIME))
    OR _S10.S_MONTH2 = EXTRACT(MONTH FROM CAST(_S11.EV_DT AS DATETIME))
    OR _S10.S_MONTH3 = EXTRACT(MONTH FROM CAST(_S11.EV_DT AS DATETIME))
  JOIN SEARCHES SEARCHES
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(_S11.EV_NAME), '%')
  JOIN _S0 _S15
    ON _S15.S_MONTH1 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S15.S_MONTH2 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
    OR _S15.S_MONTH3 = EXTRACT(MONTH FROM CAST(SEARCHES.search_ts AS DATETIME))
  GROUP BY
    _S10.S_NAME
)
SELECT
  _S16.S_NAME AS season_name,
  ROUND((
    100.0 * NVL(_S16.SUM_IS_INTRA_SEASON, 0)
  ) / _S16.N_ROWS, 2) AS pct_season_searches,
  ROUND((
    100.0 * NVL(_S17.SUM_IS_INTRA_SEASON, 0)
  ) / NVL(_S17.N_ROWS, 0), 2) AS pct_event_searches
FROM _S16 _S16
LEFT JOIN _S17 _S17
  ON _S16.S_NAME = _S17.S_NAME
ORDER BY
  1 NULLS FIRST
