WITH _T0 AS (
  SELECT
    ANY_VALUE(SEARCHES.search_user_id) AS AGG_5
  FROM SEARCHES AS SEARCHES
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN ERAS AS ERAS
    ON ERAS.er_end_year > YEAR(EVENTS.ev_dt)
    AND ERAS.er_name = 'Cold War'
    AND ERAS.er_start_year <= YEAR(EVENTS.ev_dt)
  GROUP BY
    SEARCHES.search_id
), _S5 AS (
  SELECT
    COUNT(*) AS N_COLD_WAR_SEARCHES,
    AGG_5
  FROM _T0
  GROUP BY
    AGG_5
)
SELECT
  USERS.user_name,
  _S5.N_COLD_WAR_SEARCHES AS n_cold_war_searches
FROM USERS AS USERS
JOIN _S5 AS _S5
  ON USERS.user_id = _S5.AGG_5
ORDER BY
  N_COLD_WAR_SEARCHES DESC NULLS LAST,
  USER_NAME NULLS FIRST
LIMIT 3
