WITH "_t0" AS (
  SELECT
    TIMES.T_NAME,
    ANY_VALUE(TIMES.T_START_HOUR) AS ANYTHING_T_START_HOUR,
    COUNT(*) AS N_ROWS
  FROM TIMES TIMES
  JOIN SEARCHES SEARCHES
    ON TIMES.T_END_HOUR > EXTRACT(HOUR FROM CAST(SEARCHES.SEARCH_TS AS TIMESTAMP))
    AND TIMES.T_START_HOUR <= EXTRACT(HOUR FROM CAST(SEARCHES.SEARCH_TS AS TIMESTAMP))
  GROUP BY
    TIMES.T_NAME
)
SELECT
  T_NAME AS tod,
  ROUND((
    100.0 * N_ROWS
  ) / SUM(N_ROWS) OVER (), 2) AS pct_searches
FROM "_t0"
ORDER BY
  ANYTHING_T_START_HOUR NULLS FIRST
