WITH _T0 AS (
  SELECT
    TIMES.t_name AS T_NAME,
    ANY_VALUE(TIMES.t_start_hour) AS ANYTHING_T_START_HOUR,
    COUNT(*) AS N_ROWS
  FROM TIMES TIMES
  JOIN SEARCHES SEARCHES
    ON TIMES.t_end_hour > EXTRACT(HOUR FROM CAST(SEARCHES.search_ts AS DATETIME))
    AND TIMES.t_start_hour <= EXTRACT(HOUR FROM CAST(SEARCHES.search_ts AS DATETIME))
  GROUP BY
    TIMES.t_name
)
SELECT
  T_NAME AS tod,
  ROUND((
    100.0 * N_ROWS
  ) / SUM(N_ROWS) OVER (), 2) AS pct_searches
FROM _T0
ORDER BY
  ANYTHING_T_START_HOUR NULLS FIRST
