WITH "_t2" AS (
  SELECT
    SEARCHES.SEARCH_ENGINE,
    TIMES.T_NAME,
    COUNT(*) AS N_ROWS
  FROM TIMES TIMES
  JOIN SEARCHES SEARCHES
    ON TIMES.T_END_HOUR > EXTRACT(HOUR FROM CAST(SEARCHES.SEARCH_TS AS TIMESTAMP))
    AND TIMES.T_START_HOUR <= EXTRACT(HOUR FROM CAST(SEARCHES.SEARCH_TS AS TIMESTAMP))
  GROUP BY
    SEARCHES.SEARCH_ENGINE,
    TIMES.T_NAME
), "_t" AS (
  SELECT
    SEARCH_ENGINE,
    T_NAME,
    N_ROWS,
    ROW_NUMBER() OVER (PARTITION BY T_NAME ORDER BY N_ROWS DESC, SEARCH_ENGINE) AS "_w"
  FROM "_t2"
)
SELECT
  T_NAME AS tod,
  SEARCH_ENGINE AS search_engine,
  N_ROWS AS n_searches
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
