WITH _S1 AS (
  SELECT
    search_string AS SEARCH_STRING,
    search_user_id AS USER_ID
  FROM SEARCHES
), _T0 AS (
  SELECT
    ANY_VALUE(USERS.user_name) AS AGG_2,
    COUNT(DISTINCT USERS_2.user_id) AS N_OTHER_USERS,
    ANY_VALUE(USERS.user_name) AS USER_NAME
  FROM USERS AS USERS
  JOIN _S1 AS _S1
    ON USERS.user_id = _S1.USER_ID
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(_S1.SEARCH_STRING), LOWER(EVENTS.ev_name))
  JOIN _S1 AS _S5
    ON CONTAINS(LOWER(_S5.SEARCH_STRING), LOWER(EVENTS.ev_name))
  JOIN USERS AS USERS_2
    ON USERS_2.user_id = _S5.USER_ID
  WHERE
    USERS.user_name <> USERS_2.user_name
  GROUP BY
    USERS.user_id
)
SELECT
  USER_NAME AS user_name,
  N_OTHER_USERS AS n_other_users
FROM _T0
ORDER BY
  N_OTHER_USERS DESC NULLS LAST,
  AGG_2 NULLS FIRST
LIMIT 7
