WITH "_t1" AS (
  SELECT
    ANY_VALUE(SEARCHES.SEARCH_USER_ID) AS ANYTHING_SEARCH_USER_ID
  FROM SEARCHES SEARCHES
  JOIN EVENTS EVENTS
    ON LOWER(SEARCHES.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.EV_NAME), '%')
  JOIN ERAS ERAS
    ON ERAS.ER_END_YEAR > EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
    AND ERAS.ER_NAME = 'Cold War'
    AND ERAS.ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
  GROUP BY
    SEARCHES.SEARCH_ID
), "_s5" AS (
  SELECT
    ANYTHING_SEARCH_USER_ID,
    COUNT(*) AS N_ROWS
  FROM "_t1"
  GROUP BY
    ANYTHING_SEARCH_USER_ID
)
SELECT
  USERS.USER_NAME AS user_name,
  "_s5".N_ROWS AS n_cold_war_searches
FROM USERS USERS
JOIN "_s5" "_s5"
  ON USERS.USER_ID = "_s5".ANYTHING_SEARCH_USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
