WITH "_T1" AS (
  SELECT
    ANY_VALUE(SEARCHES.search_user_id) AS ANYTHING_SEARCH_USER_ID
  FROM SEARCHES SEARCHES
  JOIN EVENTS EVENTS
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN ERAS ERAS
    ON ERAS.er_end_year > EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
    AND ERAS.er_name = 'Cold War'
    AND ERAS.er_start_year <= EXTRACT(YEAR FROM CAST(EVENTS.ev_dt AS DATETIME))
  GROUP BY
    SEARCHES.search_id
), "_S5" AS (
  SELECT
    ANYTHING_SEARCH_USER_ID,
    COUNT(*) AS N_ROWS
  FROM "_T1"
  GROUP BY
    ANYTHING_SEARCH_USER_ID
)
SELECT
  USERS.user_name,
  "_S5".N_ROWS AS n_cold_war_searches
FROM USERS USERS
JOIN "_S5" "_S5"
  ON USERS.user_id = "_S5".ANYTHING_SEARCH_USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
