WITH "_t2" AS (
  SELECT
    ERAS.ER_END_YEAR,
    ERAS.ER_NAME,
    ERAS.ER_START_YEAR,
    EVENTS.EV_DT,
    TRUNC(CAST(CAST(EVENTS.EV_DT AS DATE) AS DATE), 'DD') - TRUNC(
      CAST(CAST(LAG(EVENTS.EV_DT, 1) OVER (PARTITION BY ERAS.ER_NAME, ERAS.ER_NAME ORDER BY EVENTS.EV_DT) AS DATE) AS DATE),
      'DD'
    ) AS DAY_GAP
  FROM ERAS ERAS
  JOIN EVENTS EVENTS
    ON ERAS.ER_END_YEAR > EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
    AND ERAS.ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
)
SELECT
  ER_NAME AS era_name,
  AVG(DAY_GAP) AS avg_event_gap
FROM "_t2"
WHERE
  ER_END_YEAR > EXTRACT(YEAR FROM CAST(EV_DT AS DATE))
  AND ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EV_DT AS DATE))
GROUP BY
  ER_NAME
ORDER BY
  ANY_VALUE(ER_START_YEAR) NULLS FIRST
