WITH _T0 AS (
  SELECT
    COUNT(*) AS N_EVENTS,
    ANY_VALUE(SEASONS.s_name) AS SEASON_NAME
  FROM SEASONS AS SEASONS
  JOIN EVENTS AS EVENTS
    ON SEASONS.s_month1 = MONTH(EVENTS.ev_dt)
    OR SEASONS.s_month2 = MONTH(EVENTS.ev_dt)
    OR SEASONS.s_month3 = MONTH(EVENTS.ev_dt)
  GROUP BY
    SEASONS.s_name
)
SELECT
  ANY_VALUE(SEASONS.s_name) AS season_name,
  COUNT(*) AS n_events
FROM SEASONS AS SEASONS
JOIN EVENTS AS EVENTS
  ON SEASONS.s_month1 = DATE_PART(MONTH, CAST(EVENTS.ev_dt AS DATETIME))
  OR SEASONS.s_month2 = DATE_PART(MONTH, CAST(EVENTS.ev_dt AS DATETIME))
  OR SEASONS.s_month3 = DATE_PART(MONTH, CAST(EVENTS.ev_dt AS DATETIME))
GROUP BY
  SEASONS.s_name
ORDER BY
  N_EVENTS DESC NULLS LAST,
  SEASON_NAME NULLS FIRST
