WITH _T0 AS (
  SELECT
    COUNT(*) AS N_EVENTS,
    ANY_VALUE(SEASONS.s_name) AS SEASON_NAME
  FROM SEASONS AS SEASONS
  JOIN EVENTS AS EVENTS
    ON SEASONS.s_month1 = MONTH(EVENTS.ev_dt)
    OR SEASONS.s_month2 = MONTH(EVENTS.ev_dt)
    OR SEASONS.s_month3 = MONTH(EVENTS.ev_dt)
  GROUP BY
    SEASONS.s_name
)
SELECT
  SEASON_NAME AS season_name,
  N_EVENTS AS n_events
FROM _T0
ORDER BY
  N_EVENTS DESC NULLS LAST,
  SEASON_NAME NULLS FIRST
