WITH _T1 AS (
  SELECT
    EVENTS.ev_typ AS EV_TYP,
    USERS.user_region AS USER_REGION,
    COUNT(DISTINCT SEARCHES.search_id) AS NDISTINCT_SEARCH_ID
  FROM EVENTS EVENTS
  JOIN SEARCHES SEARCHES
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN USERS USERS
    ON SEARCHES.search_user_id = USERS.user_id
  GROUP BY
    EVENTS.ev_typ,
    USERS.user_region
), _T AS (
  SELECT
    EV_TYP,
    USER_REGION,
    NDISTINCT_SEARCH_ID,
    ROW_NUMBER() OVER (PARTITION BY USER_REGION ORDER BY NDISTINCT_SEARCH_ID DESC) AS _W
  FROM _T1
)
SELECT
  USER_REGION AS region,
  EV_TYP AS event_type,
  NDISTINCT_SEARCH_ID AS n_searches
FROM _T
WHERE
  _W = 1
