WITH _S0 AS (
  SELECT
    user_id AS USER_ID,
    user_name AS USER_NAME
  FROM USERS
), _S1 AS (
  SELECT
    search_string AS SEARCH_STRING,
    search_user_id AS SEARCH_USER_ID
  FROM SEARCHES
), _T0 AS (
  SELECT
    ANY_VALUE(USERS.user_name) AS AGG_2,
    COUNT(DISTINCT USERS_2.user_id) AS N_OTHER_USERS,
    ANY_VALUE(USERS.user_name) AS USER_NAME
  FROM USERS AS USERS
  JOIN _S1 AS _S1
    ON USERS.user_id = _S1.USER_ID
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(_S1.SEARCH_STRING), LOWER(EVENTS.ev_name))
  JOIN _S1 AS _S5
    ON CONTAINS(LOWER(_S5.SEARCH_STRING), LOWER(EVENTS.ev_name))
  JOIN USERS AS USERS_2
    ON USERS_2.user_id = _S5.USER_ID
  WHERE
    USERS.user_name <> USERS_2.user_name
  GROUP BY
    USERS.user_id
)
SELECT
  ANY_VALUE(_S0.USER_NAME) AS user_name,
  COUNT(DISTINCT _S7.USER_ID) AS n_other_users
FROM _S0 AS _S0
JOIN _S1 AS _S1
  ON _S0.USER_ID = _S1.SEARCH_USER_ID
JOIN EVENTS AS EVENTS
  ON LOWER(_S1.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
JOIN _S1 AS _S5
  ON LOWER(_S5.SEARCH_STRING) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
JOIN _S0 AS _S7
  ON _S0.USER_NAME <> _S7.USER_NAME AND _S5.SEARCH_USER_ID = _S7.USER_ID
GROUP BY
  _S0.USER_ID
ORDER BY
  N_OTHER_USERS DESC NULLS LAST,
  ANY_VALUE(_S0.USER_NAME) NULLS FIRST
LIMIT 7
