WITH _S2 AS (
  SELECT DISTINCT
    search_engine AS SEARCH_ENGINE
  FROM SEARCHES
), _S3 AS (
  SELECT
    COUNT(DISTINCT USERS.user_id) AS NDISTINCT_USER_ID,
    SEARCHES.search_engine AS SEARCH_ENGINE
  FROM SEARCHES AS SEARCHES
  JOIN USERS AS USERS
    ON SEARCHES.search_user_id = USERS.user_id
  WHERE
    YEAR(CAST(SEARCHES.search_ts AS TIMESTAMP)) <= 2019
    AND YEAR(CAST(SEARCHES.search_ts AS TIMESTAMP)) >= 2010
  GROUP BY
    2
)
SELECT
  _S2.SEARCH_ENGINE AS engine,
  COALESCE(_S3.NDISTINCT_USER_ID, 0) AS n_users
FROM _S2 AS _S2
LEFT JOIN _S3 AS _S3
  ON _S2.SEARCH_ENGINE = _S3.SEARCH_ENGINE
ORDER BY
  1 NULLS FIRST
