WITH _S0 AS (
  SELECT
    ev_dt AS EV_DT,
    ev_key AS EV_KEY
  FROM EVENTS
)
SELECT
  COUNT(DISTINCT _S0.EV_KEY) AS n_events
FROM _S0 _S0
JOIN TIMES TIMES
  ON TIMES.t_end_hour > EXTRACT(HOUR FROM CAST(_S0.EV_DT AS DATETIME))
  AND TIMES.t_name = 'Pre-Dawn'
  AND TIMES.t_start_hour <= EXTRACT(HOUR FROM CAST(_S0.EV_DT AS DATETIME))
JOIN _S0 _S2
  ON _S0.EV_KEY = _S2.EV_KEY
JOIN ERAS ERAS
  ON ERAS.er_end_year > EXTRACT(YEAR FROM CAST(_S2.EV_DT AS DATETIME))
  AND ERAS.er_name = 'Cold War'
  AND ERAS.er_start_year <= EXTRACT(YEAR FROM CAST(_S2.EV_DT AS DATETIME))
