SELECT
  SEASONS.S_NAME AS season_name,
  COUNT(*) AS n_events
FROM SEASONS SEASONS
JOIN EVENTS EVENTS
  ON SEASONS.S_MONTH1 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
  OR SEASONS.S_MONTH2 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
  OR SEASONS.S_MONTH3 = EXTRACT(MONTH FROM CAST(EVENTS.EV_DT AS DATE))
GROUP BY
  SEASONS.S_NAME
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
