WITH _T1 AS (
  SELECT
    ANY_VALUE(TIMES.t_name) AS ANYTHING_T_NAME,
    ANY_VALUE(TIMES.t_start_hour) AS ANYTHING_T_START_HOUR,
    COUNT(*) AS N_ROWS
  FROM TIMES AS TIMES
  JOIN SEARCHES AS SEARCHES
    ON TIMES.t_end_hour > HOUR(SEARCHES.search_ts)
    AND TIMES.t_start_hour <= HOUR(SEARCHES.search_ts)
  GROUP BY
    TIMES.t_name
), _T0 AS (
  SELECT
    ROUND((
      100.0 * N_ROWS
    ) / SUM(N_ROWS) OVER (), 2) AS PCT_SEARCHES,
    ANYTHING_T_NAME,
    ANYTHING_T_START_HOUR
  FROM _T1
)
SELECT
  ANYTHING_T_NAME AS tod,
  PCT_SEARCHES AS pct_searches
FROM _T0
ORDER BY
  ANYTHING_T_START_HOUR NULLS FIRST
