WITH _T0 AS (
  SELECT
    COUNT(DISTINCT SEARCHES.search_id) AS N_SEARCHES,
    EVENTS.ev_typ AS EV_TYP,
    USERS.user_region AS USER_REGION
  FROM EVENTS AS EVENTS
  JOIN SEARCHES AS SEARCHES
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN USERS AS USERS
    ON SEARCHES.search_user_id = USERS.user_id
  GROUP BY
    EVENTS.ev_typ,
    USERS.user_region
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY USERS.user_region ORDER BY COUNT(DISTINCT SEARCHES.search_id) DESC) = 1
)
SELECT
  USER_REGION AS region,
  EV_TYP AS event_type,
  N_SEARCHES AS n_searches
FROM _T0
