WITH _S0 AS (
  SELECT
    user_id AS USER_ID,
    user_name AS USER_NAME
  FROM USERS
), _T2 AS (
  SELECT
    _S0.USER_ID,
    ANY_VALUE(SEARCHES.search_user_id) AS ANYTHING_SEARCH_USER_ID,
    ANY_VALUE(_S0.USER_NAME) AS ANYTHING_USER_NAME
  FROM _S0 _S0
  JOIN SEARCHES SEARCHES
    ON SEARCHES.search_user_id = _S0.USER_ID
  JOIN EVENTS EVENTS
    ON LOWER(SEARCHES.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN SEARCHES SEARCHES_2
    ON LOWER(SEARCHES_2.search_string) LIKE CONCAT('%', LOWER(EVENTS.ev_name), '%')
  JOIN _S0 _S7
    ON SEARCHES_2.search_user_id = _S7.USER_ID AND _S0.USER_NAME <> _S7.USER_NAME
  GROUP BY
    SEARCHES.search_id,
    _S0.USER_ID
)
SELECT
  ANY_VALUE(ANYTHING_USER_NAME) AS user_name,
  COUNT(*) AS n_searches
FROM _T2
WHERE
  ANYTHING_SEARCH_USER_ID = USER_ID
GROUP BY
  USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 4 ROWS ONLY
