WITH _S4 AS (
  SELECT
    USERS.user_id AS USER_ID,
    USERS.user_name AS USER_NAME
  FROM USERS AS USERS
), _S0 AS (
  SELECT
    SEARCHES.search_string AS SEARCH_STRING,
    SEARCHES.search_user_id AS USER_ID
  FROM SEARCHES AS SEARCHES
), _S1 AS (
  SELECT
    EVENTS.ev_dt AS DATE_TIME,
    EVENTS.ev_name AS NAME
  FROM EVENTS AS EVENTS
), _T1 AS (
  SELECT
    ERAS.er_end_year AS END_YEAR,
    ERAS.er_name AS NAME,
    ERAS.er_start_year AS START_YEAR
  FROM ERAS AS ERAS
), _S2 AS (
  SELECT
    _T1.END_YEAR AS END_YEAR,
    _T1.START_YEAR AS START_YEAR
  FROM _T1 AS _T1
  WHERE
    _T1.NAME = 'Cold War'
), _S3 AS (
  SELECT
    _S1.NAME AS NAME
  FROM _S1 AS _S1
  JOIN _S2 AS _S2
    ON _S2.END_YEAR > DATE_PART(YEAR, _S1.DATE_TIME)
    AND _S2.START_YEAR <= DATE_PART(YEAR, _S1.DATE_TIME)
), _T0 AS (
  SELECT
    _S0.USER_ID AS USER_ID
  FROM _S0 AS _S0
  WHERE
    EXISTS(
      SELECT
        1 AS "1"
      FROM _S3 AS _S3
      WHERE
        LOWER(_S0.SEARCH_STRING) LIKE CONCAT('%', LOWER(_S3.NAME), '%')
    )
), _S5 AS (
  SELECT
    COUNT(*) AS N_COLD_WAR_SEARCHES,
    _T0.USER_ID AS USER_ID_3_0_1
  FROM _T0 AS _T0
  GROUP BY
    _T0.USER_ID
)
SELECT
  _S4.USER_NAME AS user_name,
  _S5.N_COLD_WAR_SEARCHES AS n_cold_war_searches
FROM _S4 AS _S4
JOIN _S5 AS _S5
  ON _S4.USER_ID = _S5.USER_ID_3_0_1
ORDER BY
  N_COLD_WAR_SEARCHES DESC NULLS LAST,
  USER_NAME NULLS FIRST
LIMIT 3
