WITH "_S0" AS (
  SELECT DISTINCT
    search_engine AS SEARCH_ENGINE
  FROM SEARCHES
), "_S1" AS (
  SELECT
    search_engine AS SEARCH_ENGINE,
    COUNT(DISTINCT search_user_id) AS NDISTINCT_SEARCH_USER_ID
  FROM SEARCHES
  WHERE
    EXTRACT(YEAR FROM CAST(search_ts AS DATE)) <= 2019
    AND EXTRACT(YEAR FROM CAST(search_ts AS DATE)) >= 2010
  GROUP BY
    search_engine
)
SELECT
  "_S0".SEARCH_ENGINE AS engine,
  COALESCE("_S1".NDISTINCT_SEARCH_USER_ID, 0) AS n_users
FROM "_S0" "_S0"
LEFT JOIN "_S1" "_S1"
  ON "_S0".SEARCH_ENGINE = "_S1".SEARCH_ENGINE
ORDER BY
  1 NULLS FIRST
