WITH _T0 AS (
  SELECT
    ANY_VALUE(SEARCHES.search_user_id) AS ANYTHING_SEARCH_USER_ID
  FROM SEARCHES AS SEARCHES
  JOIN EVENTS AS EVENTS
    ON CONTAINS(LOWER(SEARCHES.search_string), LOWER(EVENTS.ev_name))
  JOIN ERAS AS ERAS
    ON ERAS.er_end_year > YEAR(CAST(EVENTS.ev_dt AS TIMESTAMP))
    AND ERAS.er_name = 'Cold War'
    AND ERAS.er_start_year <= YEAR(CAST(EVENTS.ev_dt AS TIMESTAMP))
  GROUP BY
    SEARCHES.search_id
), _S5 AS (
  SELECT
    COUNT(*) AS N_COLD_WAR_SEARCHES,
    ANYTHING_SEARCH_USER_ID
  FROM _T0
  GROUP BY
    2
)
SELECT
  USERS.user_name,
  _S5.N_COLD_WAR_SEARCHES AS n_cold_war_searches
FROM USERS AS USERS
JOIN _S5 AS _S5
  ON USERS.user_id = _S5.ANYTHING_SEARCH_USER_ID
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
LIMIT 3
