SELECT
  SEASONS.s_name AS season_name,
  COUNT(*) AS n_events
FROM SEASONS AS SEASONS
JOIN EVENTS AS EVENTS
  ON SEASONS.s_month1 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
  OR SEASONS.s_month2 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
  OR SEASONS.s_month3 = EXTRACT(MONTH FROM CAST(EVENTS.ev_dt AS DATETIME))
GROUP BY
  SEASONS.s_name
ORDER BY
  n_events DESC,
  SEASONS.s_name COLLATE utf8mb4_bin
