WITH "_t" AS (
  SELECT
    ERAS.ER_NAME,
    ERAS.ER_START_YEAR,
    EVENTS.EV_NAME,
    ROW_NUMBER() OVER (PARTITION BY ERAS.ER_NAME ORDER BY EVENTS.EV_DT) AS "_w"
  FROM ERAS ERAS
  JOIN EVENTS EVENTS
    ON ERAS.ER_END_YEAR > EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
    AND ERAS.ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
)
SELECT
  ER_NAME AS era_name,
  EV_NAME AS event_name
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  ER_START_YEAR NULLS FIRST
