WITH "_s2" AS (
  SELECT
    EV_DT,
    EV_KEY
  FROM EVENTS
)
SELECT
  EVENTS.EV_NAME AS event_name,
  ERAS.ER_NAME AS era_name,
  EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE)) AS event_year,
  SEASONS.S_NAME AS season_name,
  TIMES.T_NAME AS tod
FROM EVENTS EVENTS
JOIN ERAS ERAS
  ON ERAS.ER_END_YEAR > EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
  AND ERAS.ER_START_YEAR <= EXTRACT(YEAR FROM CAST(EVENTS.EV_DT AS DATE))
JOIN "_s2" "_s2"
  ON EVENTS.EV_KEY = "_s2".EV_KEY
JOIN SEASONS SEASONS
  ON SEASONS.S_MONTH1 = EXTRACT(MONTH FROM CAST("_s2".EV_DT AS DATE))
  OR SEASONS.S_MONTH2 = EXTRACT(MONTH FROM CAST("_s2".EV_DT AS DATE))
  OR SEASONS.S_MONTH3 = EXTRACT(MONTH FROM CAST("_s2".EV_DT AS DATE))
JOIN "_s2" "_s6"
  ON EVENTS.EV_KEY = "_s6".EV_KEY
JOIN TIMES TIMES
  ON TIMES.T_END_HOUR > EXTRACT(HOUR FROM CAST("_s6".EV_DT AS TIMESTAMP))
  AND TIMES.T_START_HOUR <= EXTRACT(HOUR FROM CAST("_s6".EV_DT AS TIMESTAMP))
WHERE
  EVENTS.EV_TYP = 'culture'
ORDER BY
  EVENTS.EV_DT NULLS FIRST
FETCH FIRST 6 ROWS ONLY
