WITH "_t" AS (
  SELECT
    O_ORDERDATE,
    O_ORDERKEY,
    LAG(O_ORDERDATE, 1) OVER (ORDER BY O_ORDERDATE, O_ORDERKEY) AS "_w",
    LAG(O_ORDERDATE, 1) OVER (ORDER BY O_ORDERDATE, O_ORDERKEY) AS "_w_2"
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) = 1
)
SELECT
  O_ORDERDATE AS order_date,
  O_ORDERKEY AS "key"
FROM "_t"
WHERE
  EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) <> EXTRACT(YEAR FROM CAST("_w_2" AS DATE))
  OR "_w" IS NULL
ORDER BY
  1 NULLS FIRST
