WITH "_t" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE,
    O_TOTALPRICE,
    ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE, O_ORDERKEY) AS "_w"
  FROM TPCH.ORDERS
)
SELECT
  CUSTOMER.C_NAME AS name,
  "_t".O_ORDERDATE AS first_order_date,
  "_t".O_TOTALPRICE AS first_order_price
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_t" "_t"
  ON CUSTOMER.C_CUSTKEY = "_t".O_CUSTKEY AND "_t"."_w" = 1
WHERE
  CUSTOMER.C_ACCTBAL >= 9000.0
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
