SELECT
  CAST(5.6 AS INTEGER) - CAST(CAST(5.6 AS INTEGER) > 5.6 AS INTEGER) AS floor_frac,
  CAST(5.4 AS INTEGER) + CAST(CAST(5.4 AS INTEGER) < 5.4 AS INTEGER) AS ceil_frac,
  CAST(-5.4 AS INTEGER) - CAST(-5.4 < CAST(-5.4 AS INTEGER) AS INTEGER) AS floor_frac_neg,
  CAST(-5.6 AS INTEGER) + CAST(-5.6 > CAST(-5.6 AS INTEGER) AS INTEGER) AS ceil_frac_neg,
  CAST(6 AS INTEGER) - CAST(FALSE AS INTEGER) AS floor_int,
  CAST(6 AS INTEGER) + CAST(FALSE AS INTEGER) AS ceil_int,
  CAST(-6 AS INTEGER) - CAST(FALSE AS INTEGER) AS floor_int_neg,
  CAST(-6 AS INTEGER) + CAST(FALSE AS INTEGER) AS ceil_int_neg
FROM (VALUES
  (NULL)) AS _q_0
