SELECT
  PS_SUPPKEY AS supplier_key,
  PS_PARTKEY AS part_key,
  FLOOR(PS_AVAILQTY) AS complete_parts,
  CEIL(PS_SUPPLYCOST * FLOOR(PS_AVAILQTY)) AS total_cost
FROM TPCH.PARTSUPP
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
