SELECT
  NVL(REGION.R_NAME, '') || '-' || NVL(NATION.N_NAME, '') || '-' || NVL(SUBSTR(CUSTOMER.C_NAME, 17), '') AS a,
  ROUND(CUSTOMER.C_ACCTBAL, 1) AS b,
  CASE WHEN SUBSTR(CUSTOMER.C_PHONE, 1, 1) = '3' THEN CUSTOMER.C_NAME ELSE NULL END AS c,
  NOT CASE
    WHEN SUBSTR(CUSTOMER.C_PHONE, 2, GREATEST(1, 0)) = '1'
    THEN CUSTOMER.C_NAME
    ELSE NULL
  END IS NULL AS d,
  CASE WHEN SUBSTR(CUSTOMER.C_PHONE, 15) = '7' THEN CUSTOMER.C_NAME ELSE NULL END IS NULL AS e,
  ROUND(CUSTOMER.C_ACCTBAL, 0) AS f
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_ACCTBAL <= 100.0
  AND CUSTOMER.C_ACCTBAL >= 0.0
  AND CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
ORDER BY
  CUSTOMER.C_ADDRESS NULLS FIRST
FETCH FIRST 10 ROWS ONLY
