WITH "_s2" AS (
  SELECT
    AVG(C_ACCTBAL) AS AVG_C_ACCTBAL
  FROM TPCH.CUSTOMER
), "_s0" AS (
  SELECT
    C_MKTSEGMENT,
    C_NATIONKEY,
    COUNT(C_ACCTBAL) AS COUNT_C_ACCTBAL,
    SUM(C_ACCTBAL) AS SUM_C_ACCTBAL
  FROM TPCH.CUSTOMER
  GROUP BY
    C_MKTSEGMENT,
    C_NATIONKEY
), "_s3" AS (
  SELECT
    "_s0".C_MKTSEGMENT,
    SUM("_s0".COUNT_C_ACCTBAL) AS SUM_COUNT_C_ACCTBAL,
    SUM("_s0".SUM_C_ACCTBAL) AS SUM_SUM_C_ACCTBAL
  FROM "_s0" "_s0"
  JOIN TPCH.NATION NATION
    ON NATION.N_NATIONKEY = "_s0".C_NATIONKEY
  GROUP BY
    "_s0".C_MKTSEGMENT,
    NATION.N_NAME
)
SELECT
  "_s3".C_MKTSEGMENT AS market_segment,
  ROUND(
    MAX(
      (
        100.0 * (
          (
            "_s3".SUM_SUM_C_ACCTBAL / "_s3".SUM_COUNT_C_ACCTBAL
          ) - "_s2".AVG_C_ACCTBAL
        )
      ) / "_s2".AVG_C_ACCTBAL
    ),
    2
  ) AS max_nation_pct_diff
FROM "_s2" "_s2"
CROSS JOIN "_s3" "_s3"
GROUP BY
  "_s3".C_MKTSEGMENT
