WITH "_s0" AS (
  SELECT
    AVG(C_ACCTBAL) AS AVG_C_ACCTBAL
  FROM TPCH.CUSTOMER
), "_s2" AS (
  SELECT
    CUSTOMER.C_MKTSEGMENT,
    CUSTOMER.C_NATIONKEY,
    ANY_VALUE("_s0".AVG_C_ACCTBAL) AS ANYTHING_AVG_C_ACCTBAL,
    MAX(
      (
        100.0 * (
          CUSTOMER.C_ACCTBAL - "_s0".AVG_C_ACCTBAL
        )
      ) / "_s0".AVG_C_ACCTBAL
    ) AS MAX_PCT_DIFF
  FROM "_s0" "_s0"
  CROSS JOIN TPCH.CUSTOMER CUSTOMER
  GROUP BY
    CUSTOMER.C_MKTSEGMENT,
    CUSTOMER.C_NATIONKEY
), "_t1" AS (
  SELECT
    "_s2".C_MKTSEGMENT,
    ANY_VALUE("_s2".ANYTHING_AVG_C_ACCTBAL) AS ANYTHING_ANYTHING_AVG_C_ACCTBAL,
    MAX("_s2".MAX_PCT_DIFF) AS MAX_MAX_PCT_DIFF
  FROM "_s2" "_s2"
  JOIN TPCH.NATION NATION
    ON NATION.N_NATIONKEY = "_s2".C_NATIONKEY
  GROUP BY
    "_s2".C_MKTSEGMENT,
    NATION.N_NAME
)
SELECT
  C_MKTSEGMENT AS market_segment,
  ROUND(AVG(MAX_MAX_PCT_DIFF), 2) AS avg_max_pct_diff,
  ROUND(ANY_VALUE(ANYTHING_ANYTHING_AVG_C_ACCTBAL), 2) AS avg_bal
FROM "_t1"
GROUP BY
  C_MKTSEGMENT
