WITH "_u_0" AS (
  SELECT
    N_NATIONKEY AS "_u_1"
  FROM TPCH.NATION
  GROUP BY
    N_NATIONKEY
)
SELECT
  COUNT(*) AS n
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_u_0" "_u_0"
  ON CUSTOMER.C_NATIONKEY = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
