WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  WHERE
    O_ORDERPRIORITY = '1-URGENT'
  GROUP BY
    O_CUSTKEY
)
SELECT
  COUNT(*) AS n
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
WHERE
  "_s1".N_ROWS = 0 OR "_s1".N_ROWS IS NULL
