WITH "_t3" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    O_ORDERPRIORITY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)),
    O_ORDERPRIORITY
), "_t2" AS (
  SELECT
    O_ORDERPRIORITY,
    YEAR_O_ORDERDATE,
    (
      100.0 * N_ROWS
    ) / SUM(N_ROWS) OVER (PARTITION BY YEAR_O_ORDERDATE) AS PRIORITY_PCT
  FROM "_t3"
), "_t" AS (
  SELECT
    O_ORDERPRIORITY,
    YEAR_O_ORDERDATE,
    PRIORITY_PCT,
    ROW_NUMBER() OVER (PARTITION BY YEAR_O_ORDERDATE ORDER BY PRIORITY_PCT DESC) AS "_w"
  FROM "_t2"
)
SELECT
  YEAR_O_ORDERDATE AS order_year,
  O_ORDERPRIORITY AS highest_priority,
  PRIORITY_PCT AS priority_pct
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
