WITH "_T3" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)) AS YEAR_O_ORDERDATE,
    o_orderpriority AS O_ORDERPRIORITY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATE)),
    o_orderpriority
), "_T2" AS (
  SELECT
    O_ORDERPRIORITY,
    YEAR_O_ORDERDATE,
    (
      100.0 * N_ROWS
    ) / SUM(N_ROWS) OVER (PARTITION BY YEAR_O_ORDERDATE) AS PRIORITY_PCT
  FROM "_T3"
), "_T" AS (
  SELECT
    O_ORDERPRIORITY,
    YEAR_O_ORDERDATE,
    PRIORITY_PCT,
    ROW_NUMBER() OVER (PARTITION BY YEAR_O_ORDERDATE ORDER BY PRIORITY_PCT DESC) AS "_W"
  FROM "_T2"
)
SELECT
  YEAR_O_ORDERDATE AS order_year,
  O_ORDERPRIORITY AS highest_priority,
  PRIORITY_PCT AS priority_pct
FROM "_T"
WHERE
  "_W" = 1
ORDER BY
  1 NULLS FIRST
