SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  HOUR(SBTRANSACTION.sbtxdatetime) AS _expr0,
  MINUTE(SBTRANSACTION.sbtxdatetime) AS _expr1,
  SECOND(SBTRANSACTION.sbtxdatetime) AS _expr2
FROM MAIN.SBTRANSACTION AS SBTRANSACTION
JOIN MAIN.SBTICKER AS SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  AND SBTICKER.sbtickersymbol IN ('AAPL', 'GOOGL', 'NFLX')
ORDER BY
  SBTRANSACTION.sbtxid NULLS FIRST
