SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  DATE_PART(HOUR, CAST(SBTRANSACTION.sbtxdatetime AS DATETIME)) AS _expr0,
  DATE_PART(MINUTE, CAST(SBTRANSACTION.sbtxdatetime AS DATETIME)) AS _expr1,
  DATE_PART(SECOND, CAST(SBTRANSACTION.sbtxdatetime AS DATETIME)) AS _expr2
FROM MAIN.SBTRANSACTION AS SBTRANSACTION
JOIN MAIN.SBTICKER AS SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  AND SBTICKER.sbtickersymbol IN ('AAPL', 'GOOGL', 'NFLX')
ORDER BY
  SBTRANSACTION.sbtxid NULLS FIRST
