SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  HOUR(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS _expr0,
  MINUTE(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS _expr1,
  SECOND(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS _expr2
FROM MAIN.SBTRANSACTION AS SBTRANSACTION
JOIN MAIN.SBTICKER AS SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  AND SBTICKER.sbtickersymbol IN ('AAPL', 'GOOGL', 'NFLX')
ORDER BY
  SBTRANSACTION.sbtxid NULLS FIRST
