SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  EXTRACT(HOUR FROM CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS "_expr0",
  EXTRACT(MINUTE FROM CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS "_expr1",
  EXTRACT(SECOND FROM CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) AS "_expr2"
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBTICKER SBTICKER
  ON SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  AND SBTICKER.sbtickersymbol IN ('AAPL', 'GOOGL', 'NFLX')
WHERE
  EXTRACT(YEAR FROM CAST(SBTRANSACTION.sbtxdatetime AS DATE)) = 2023
ORDER BY
  1 NULLS FIRST
