SELECT
  SBTRANSACTION.SBTXID AS transaction_id,
  EXTRACT(HOUR FROM CAST(SBTRANSACTION.SBTXDATETIME AS TIMESTAMP)) AS "_expr0",
  EXTRACT(MINUTE FROM CAST(SBTRANSACTION.SBTXDATETIME AS TIMESTAMP)) AS "_expr1",
  EXTRACT(SECOND FROM CAST(SBTRANSACTION.SBTXDATETIME AS TIMESTAMP)) AS "_expr2"
FROM MAIN.SBTRANSACTION SBTRANSACTION
JOIN MAIN.SBTICKER SBTICKER
  ON SBTICKER.SBTICKERID = SBTRANSACTION.SBTXTICKERID
  AND SBTICKER.SBTICKERSYMBOL IN ('AAPL', 'GOOGL', 'NFLX')
WHERE
  EXTRACT(YEAR FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE)) = 2023
ORDER BY
  1 NULLS FIRST
