SELECT
  "QUOTED TABLE_NAME"."`cast`" AS "cast_",
  "QUOTED TABLE_NAME"."`name""[" AS "name",
  "QUOTED TABLE_NAME"."= ""QUOTE""" AS "quote_",
  "LOWERCASE_DETAIL"."0 = 0 and '" AS "_0_0_and",
  "LOWERCASE_DETAIL"."as" AS "as_"
FROM KEYWORDS."""QUOTED TABLE_NAME""" "QUOTED TABLE_NAME"
JOIN KEYWORDS."lowercase_detail" "LOWERCASE_DETAIL"
  ON "LOWERCASE_DETAIL".ID = "QUOTED TABLE_NAME"."`name""["
WHERE
  "QUOTED TABLE_NAME"."= ""QUOTE""" = 4 AND "QUOTED TABLE_NAME"."`name""[" = 7
