SELECT
  NVL("WHERE".default_to, "WHERE".".CALCULATE") AS calculate2,
  CALCULATE.".WHERE" AS "_where",
  CALCULATE."LIKE" AS "_like",
  CALCULATE.datetime,
  "WHERE".abs,
  "WHERE".has
FROM KEYWORDS."WHERE" "WHERE"
JOIN KEYWORDS.CALCULATE CALCULATE
  ON "WHERE".".CALCULATE" = CALCULATE.".WHERE"
WHERE
  "WHERE".".CALCULATE" = 4 AND "WHERE".present IS NULL
