SELECT
  "CAST".ID2 AS id1,
  "CAST".ID AS id2,
  "LOWERCASE_DETAIL"."select" AS "fk1_select",
  "LOWERCASE_DETAIL"."as" AS "fk1_as",
  LOWERCASE_DETAIL_2."two words" AS "fk2_two_words"
FROM KEYWORDS."CAST" "CAST"
JOIN KEYWORDS."lowercase_detail" "LOWERCASE_DETAIL"
  ON "CAST".ID2 = "LOWERCASE_DETAIL".ID
  AND "LOWERCASE_DETAIL"."0 = 0 and '" = '2 "0 = 0 and ''" field name'
JOIN KEYWORDS."lowercase_detail" LOWERCASE_DETAIL_2
  ON "CAST".ID = LOWERCASE_DETAIL_2.ID AND LOWERCASE_DETAIL_2.ID = 1
