SELECT
  COALESCE("WHERE".DEFAULT_TO, "WHERE".".CALCULATE") AS calculate2,
  CALCULATE.".WHERE" AS "_where",
  CALCULATE."LIKE" AS "_like",
  CALCULATE.DATETIME AS datetime,
  "WHERE".ABS AS abs,
  "WHERE".HAS AS has
FROM KEYWORDS."WHERE" "WHERE"
JOIN KEYWORDS.CALCULATE CALCULATE
  ON "WHERE".".CALCULATE" = CALCULATE.".WHERE"
WHERE
  "WHERE".".CALCULATE" = 4 AND "WHERE".PRESENT IS NULL
