WITH _s0 AS (
  SELECT
    MAX(`INTEGER`) AS max_INTEGER
  FROM keywords.`PARTITION`
)
SELECT
  CALCULATE.`.WHERE` AS `key`,
  CALCULATE.`LENGTH` AS len
FROM _s0 AS _s0
JOIN keywords.CALCULATE AS CALCULATE
  ON CALCULATE.`.WHERE` = _s0.max_INTEGER
