WITH "_S2" AS (
  SELECT
    DEVICES.de_product_id AS DE_PRODUCT_ID,
    ANY_VALUE(PRODUCTS.pr_name) AS ANYTHING_PR_NAME,
    COUNT(*) AS N_ROWS
  FROM MAIN.PRODUCTS PRODUCTS
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.de_product_id = PRODUCTS.pr_id
  WHERE
    PRODUCTS.pr_id IN (618070, 960138, 143712)
  GROUP BY
    DEVICES.de_product_id
), "_S3" AS (
  SELECT
    in_product_id AS IN_PRODUCT_ID,
    COUNT(DISTINCT in_device_id) AS NDISTINCT_IN_DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_product_id
)
SELECT
  "_S2".ANYTHING_PR_NAME AS product_name,
  ROUND(COALESCE("_S3".NDISTINCT_IN_DEVICE_ID, 0) / "_S2".N_ROWS, 2) AS lifetime_ir
FROM "_S2" "_S2"
LEFT JOIN "_S3" "_S3"
  ON "_S2".DE_PRODUCT_ID = "_S3".IN_PRODUCT_ID
ORDER BY
  1 NULLS FIRST
