WITH "_S1" AS (
  SELECT
    n_nationkey AS N_NATIONKEY,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
)
SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN "_S1" "_S1"
  ON SUPPLIER.s_nationkey = "_S1".N_NATIONKEY
JOIN "_S1" "_S3"
  ON "_S1".N_REGIONKEY = "_S3".N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_custkey = SUPPLIER.s_suppkey
  AND CUSTOMER.c_nationkey = "_S3".N_NATIONKEY
WHERE
  SUPPLIER.s_nationkey = 4
