SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY AND NATION.N_REGIONKEY = 0
JOIN TPCH.NATION NATION_2
  ON NATION.N_REGIONKEY = NATION_2.N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = SUPPLIER.S_SUPPKEY
  AND CUSTOMER.C_NATIONKEY = NATION_2.N_NATIONKEY
