SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = SUPPLIER.S_SUPPKEY
  AND CUSTOMER.C_NATIONKEY = 3
  AND CUSTOMER.C_NATIONKEY = SUPPLIER.S_NATIONKEY
