WITH "_s1" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
)
SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN "_s1" "_s1"
  ON SUPPLIER.S_NATIONKEY = "_s1".N_NATIONKEY
JOIN "_s1" "_s3"
  ON "_s1".N_REGIONKEY = "_s3".N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = SUPPLIER.S_SUPPKEY
  AND CUSTOMER.C_NATIONKEY = 7
  AND CUSTOMER.C_NATIONKEY = "_s3".N_NATIONKEY
