SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY AND NATION.N_REGIONKEY < 3
JOIN TPCH.NATION NATION_2
  ON NATION.N_REGIONKEY = NATION_2.N_REGIONKEY AND NATION_2.N_REGIONKEY > 0
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = SUPPLIER.S_SUPPKEY
  AND CUSTOMER.C_NATIONKEY = NATION_2.N_NATIONKEY
  AND NOT CUSTOMER.C_NATIONKEY IN (1, 4, 7, 10, 13, 16, 19, 22)
WHERE
  NOT SUPPLIER.S_NATIONKEY IN (0, 3, 6, 9, 12, 15, 18, 21, 24)
