WITH "_s3" AS (
  SELECT
    1 AS N_ROWS,
    ID
  FROM MAIN.DISH
  WHERE
    LOWER(NAME) = 'baked apples with cream'
), "_t1" AS (
  SELECT
    MENUPAGE.MENU_ID,
    MAX(MENUITEM.PRICE) AS MAX_PRICE,
    SUM("_s3".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.MENUPAGE MENUPAGE
  JOIN MAIN.MENUITEM MENUITEM
    ON MENUITEM.MENU_PAGE_ID = MENUPAGE.ID
  LEFT JOIN "_s3" "_s3"
    ON MENUITEM.DISH_ID = "_s3".ID
  GROUP BY
    MENUPAGE.MENU_ID
)
SELECT
  MENU.SPONSOR AS sponsor
FROM MAIN.MENU MENU
JOIN "_t1" "_t1"
  ON MENU.ID = "_t1".MENU_ID AND "_t1".SUM_N_ROWS <> 0
ORDER BY
  "_t1".MAX_PRICE DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
