WITH _S3 AS (
  SELECT
    1 AS N_ROWS,
    id AS ID
  FROM MAIN.DISH
  WHERE
    LOWER(name) = 'baked apples with cream'
), _T1 AS (
  SELECT
    MENUPAGE.menu_id AS MENU_ID,
    MAX(MENUITEM.price) AS MAX_PRICE,
    SUM(_S3.N_ROWS) AS SUM_N_ROWS
  FROM MAIN.MENUPAGE MENUPAGE
  JOIN MAIN.MENUITEM MENUITEM
    ON MENUITEM.menu_page_id = MENUPAGE.id
  LEFT JOIN _S3 _S3
    ON MENUITEM.dish_id = _S3.ID
  GROUP BY
    MENUPAGE.menu_id
)
SELECT
  MENU.sponsor
FROM MAIN.MENU MENU
JOIN _T1 _T1
  ON MENU.id = _T1.MENU_ID AND _T1.SUM_N_ROWS <> 0
ORDER BY
  _T1.MAX_PRICE DESC NULLS LAST
FETCH FIRST 1 ROWS ONLY
