SELECT
  O_ORDERDATE AS order_date,
  TO_CHAR(TO_DATE('1995-10-26', 'YYYY-MM-DD'), 'Mon') AS month_name_str,
  TO_CHAR(O_ORDERDATE, 'Mon') AS month_name_col,
  TO_CHAR(ADD_MONTHS(CAST(O_ORDERDATE AS DATE), 3), 'Mon') AS month_col_added,
  TO_CHAR(TO_DATE('1995-05-26', 'YYYY-MM-DD'), 'Mon') AS month_str_subs,
  TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Mon') AS month_now
FROM TPCH.ORDERS
WHERE
  EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) = 1998
ORDER BY
  O_CUSTKEY NULLS FIRST
FETCH FIRST 5 ROWS ONLY
