SELECT
  o_orderdate AS order_date,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-10-26' AS TIMESTAMP)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS month_name_str,
  CASE
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS month_name_col,
  CASE
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM DATE_ADD(CAST(o_orderdate AS TIMESTAMP), 3, 'MONTH')) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS month_col_added,
  CASE
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CAST('1995-05-26' AS DATE)) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS month_str_subs,
  CASE
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 1
    THEN 'Jan'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 2
    THEN 'Feb'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 3
    THEN 'Mar'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 4
    THEN 'Apr'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 5
    THEN 'May'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 6
    THEN 'Jun'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 7
    THEN 'Jul'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 8
    THEN 'Aug'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 9
    THEN 'Sep'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 10
    THEN 'Oct'
    WHEN EXTRACT(MONTH FROM CURRENT_TIMESTAMP()) = 11
    THEN 'Nov'
    ELSE 'Dec'
  END AS month_now
FROM tpch.orders
WHERE
  EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME)) = 1998
ORDER BY
  o_custkey
LIMIT 5
