WITH _T7 AS (
  SELECT
    o_orderdate AS O_ORDERDATE,
    o_orderpriority AS O_ORDERPRIORITY,
    o_totalprice AS O_TOTALPRICE
  FROM TPCH.ORDERS
  WHERE
    o_orderpriority = '1-URGENT'
), _T5 AS (
  SELECT
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATETIME)) AS YEAR_O_ORDERDATE,
    SUM(O_TOTALPRICE) AS SUM_O_TOTALPRICE
  FROM _T7
  GROUP BY
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATETIME))
), _T4 AS (
  SELECT
    SUM_O_TOTALPRICE,
    YEAR_O_ORDERDATE,
    LEAD(NVL(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE) AS NEXT_YEAR_TOTAL_SPENT
  FROM _T5
), _T2 AS (
  SELECT
    EXTRACT(MONTH FROM CAST(_T8.O_ORDERDATE AS DATETIME)) AS MONTH_O_ORDERDATE,
    EXTRACT(YEAR FROM CAST(_T8.O_ORDERDATE AS DATETIME)) AS YEAR_O_ORDERDATE,
    SUM(_T8.O_TOTALPRICE) AS SUM_O_TOTALPRICE
  FROM _T4 _T4
  JOIN _T7 _T8
    ON _T4.YEAR_O_ORDERDATE = EXTRACT(YEAR FROM CAST(_T8.O_ORDERDATE AS DATETIME))
  WHERE
    _T4.NEXT_YEAR_TOTAL_SPENT < NVL(_T4.SUM_O_TOTALPRICE, 0)
  GROUP BY
    EXTRACT(MONTH FROM CAST(_T8.O_ORDERDATE AS DATETIME)),
    EXTRACT(YEAR FROM CAST(_T8.O_ORDERDATE AS DATETIME))
), _T AS (
  SELECT
    MONTH_O_ORDERDATE,
    YEAR_O_ORDERDATE,
    SUM_O_TOTALPRICE,
    LEAD(NVL(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE, MONTH_O_ORDERDATE) AS _W,
    LAG(NVL(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE, MONTH_O_ORDERDATE) AS _W_2
  FROM _T2
)
SELECT
  YEAR_O_ORDERDATE AS year,
  MONTH_O_ORDERDATE AS month
FROM _T
WHERE
  _W < NVL(SUM_O_TOTALPRICE, 0) AND _W_2 < NVL(SUM_O_TOTALPRICE, 0)
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
