WITH "_t7" AS (
  SELECT
    O_ORDERDATE,
    O_ORDERPRIORITY,
    O_TOTALPRICE
  FROM TPCH.ORDERS
  WHERE
    O_ORDERPRIORITY = '1-URGENT'
), "_t5" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    SUM(O_TOTALPRICE) AS SUM_O_TOTALPRICE
  FROM "_t7"
  GROUP BY
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE))
), "_t4" AS (
  SELECT
    SUM_O_TOTALPRICE,
    YEAR_O_ORDERDATE,
    LEAD(COALESCE(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE) AS NEXT_YEAR_TOTAL_SPENT
  FROM "_t5"
), "_t2" AS (
  SELECT
    EXTRACT(MONTH FROM CAST("_t8".O_ORDERDATE AS DATE)) AS MONTH_O_ORDERDATE,
    EXTRACT(YEAR FROM CAST("_t8".O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    SUM("_t8".O_TOTALPRICE) AS SUM_O_TOTALPRICE
  FROM "_t4" "_t4"
  JOIN "_t7" "_t8"
    ON "_t4".YEAR_O_ORDERDATE = EXTRACT(YEAR FROM CAST("_t8".O_ORDERDATE AS DATE))
  WHERE
    "_t4".NEXT_YEAR_TOTAL_SPENT < COALESCE("_t4".SUM_O_TOTALPRICE, 0)
  GROUP BY
    EXTRACT(MONTH FROM CAST("_t8".O_ORDERDATE AS DATE)),
    EXTRACT(YEAR FROM CAST("_t8".O_ORDERDATE AS DATE))
), "_t" AS (
  SELECT
    MONTH_O_ORDERDATE,
    YEAR_O_ORDERDATE,
    SUM_O_TOTALPRICE,
    LEAD(COALESCE(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE, MONTH_O_ORDERDATE) AS "_w",
    LAG(COALESCE(SUM_O_TOTALPRICE, 0), 1, 0.0) OVER (ORDER BY YEAR_O_ORDERDATE, MONTH_O_ORDERDATE) AS "_w_2"
  FROM "_t2"
)
SELECT
  YEAR_O_ORDERDATE AS year,
  MONTH_O_ORDERDATE AS month
FROM "_t"
WHERE
  "_w" < COALESCE(SUM_O_TOTALPRICE, 0) AND "_w_2" < COALESCE(SUM_O_TOTALPRICE, 0)
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
