WITH "_t3" AS (
  SELECT
    CUSTOMER.C_NAME,
    CUSTOMER.C_NATIONKEY,
    ORDERS.O_ORDERKEY,
    ORDERS.O_TOTALPRICE,
    (
      100.0 * ORDERS.O_TOTALPRICE
    ) / SUM(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY) AS VALUE_PERCENTAGE
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1998
), "_t" AS (
  SELECT
    C_NAME,
    C_NATIONKEY,
    O_ORDERKEY,
    O_TOTALPRICE,
    VALUE_PERCENTAGE,
    ROW_NUMBER() OVER (PARTITION BY C_NATIONKEY ORDER BY O_TOTALPRICE DESC) AS "_w"
  FROM "_t3"
)
SELECT
  NATION.N_NAME AS nation_name,
  "_t".C_NAME AS customer_name,
  "_t".O_ORDERKEY AS order_key,
  "_t".O_TOTALPRICE AS order_value,
  "_t".VALUE_PERCENTAGE AS value_percentage
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'ASIA'
JOIN "_t" "_t"
  ON NATION.N_NATIONKEY = "_t".C_NATIONKEY AND "_t"."_w" = 1
ORDER BY
  1 NULLS FIRST
