WITH "_s3" AS (
  SELECT
    C_ACCTBAL,
    C_NATIONKEY,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (
            PARTITION BY C_NATIONKEY
            ORDER BY CASE WHEN C_ACCTBAL >= 0 THEN C_ACCTBAL ELSE NULL END DESC NULLS LAST
          ) - 1.0
        ) - (
          (
            COUNT(CASE WHEN C_ACCTBAL >= 0 THEN C_ACCTBAL ELSE NULL END) OVER (PARTITION BY C_NATIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CASE WHEN C_ACCTBAL >= 0 THEN C_ACCTBAL ELSE NULL END
      ELSE NULL
    END AS EXPR_5,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (PARTITION BY C_NATIONKEY ORDER BY C_ACCTBAL DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(C_ACCTBAL) OVER (PARTITION BY C_NATIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN C_ACCTBAL
      ELSE NULL
    END AS EXPR_6,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (
            PARTITION BY C_NATIONKEY
            ORDER BY CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END DESC NULLS LAST
          ) - 1.0
        ) - (
          (
            COUNT(CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END) OVER (PARTITION BY C_NATIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END
      ELSE NULL
    END AS EXPR_7
  FROM TPCH.CUSTOMER
)
SELECT
  ANY_VALUE(NATION.N_NAME) AS nation_name,
  COUNT(CASE WHEN "_s3".C_ACCTBAL < 0 THEN "_s3".C_ACCTBAL ELSE NULL END) AS n_red_acctbal,
  COUNT(CASE WHEN "_s3".C_ACCTBAL >= 0 THEN "_s3".C_ACCTBAL ELSE NULL END) AS n_black_acctbal,
  AVG("_s3".EXPR_7) AS median_red_acctbal,
  AVG("_s3".EXPR_5) AS median_black_acctbal,
  AVG("_s3".EXPR_6) AS median_overall_acctbal
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AMERICA'
JOIN "_s3" "_s3"
  ON NATION.N_NATIONKEY = "_s3".C_NATIONKEY
GROUP BY
  "_s3".C_NATIONKEY
ORDER BY
  1 NULLS FIRST
