SELECT
  N_NAME AS nation_name,
  SUM(N_NATIONKEY) OVER () AS key_sum,
  AVG(CAST(N_NATIONKEY AS DOUBLE PRECISION)) OVER () AS key_avg,
  COUNT(CASE WHEN LENGTH(N_COMMENT) < 75 THEN N_COMMENT ELSE NULL END) OVER () AS n_short_comment,
  COUNT(*) OVER () AS n_nations
FROM TPCH.NATION
WHERE
  NOT SUBSTR(N_NAME, 1, 1) IN ('A', 'E', 'I', 'O', 'U')
ORDER BY
  N_REGIONKEY NULLS FIRST,
  1 NULLS FIRST
