SELECT
  AVG(
    TRUNC(
      CAST(CAST(LEAST(LINEITEM.L_COMMITDATE, LINEITEM.L_RECEIPTDATE) AS DATE) AS DATE),
      'DD'
    ) - TRUNC(CAST(CAST(ORDERS.O_ORDERDATE AS DATE) AS DATE), 'DD')
  ) AS avg_gap
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.ORDERS ORDERS
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
WHERE
  LINEITEM.L_SHIPMODE = 'RAIL'
