WITH "_s4" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE,
    O_ORDERKEY
  FROM TPCH.ORDERS
), "_t" AS (
  SELECT
    CUSTOMER.C_CUSTKEY,
    CUSTOMER.C_NAME,
    "_s3".O_ORDERDATE,
    ROW_NUMBER() OVER (PARTITION BY "_s3".O_CUSTKEY ORDER BY "_s3".O_ORDERDATE, "_s3".O_ORDERKEY) AS "_w"
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'VIETNAM'
  JOIN "_s4" "_s3"
    ON CUSTOMER.C_CUSTKEY = "_s3".O_CUSTKEY
), "_s5" AS (
  SELECT
    C_CUSTKEY,
    C_NAME,
    O_ORDERDATE
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  "_s5".C_NAME AS customer_name,
  "_s4".O_ORDERKEY AS order_key,
  TRUNC(CAST(CAST("_s4".O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(CAST(CAST("_s5".O_ORDERDATE AS DATE) AS DATE), 'DD') AS days_since_first_order
FROM "_s4" "_s4"
LEFT JOIN "_s5" "_s5"
  ON "_s4".O_CUSTKEY = "_s5".C_CUSTKEY
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
