WITH "_S4" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    o_orderdate AS O_ORDERDATE,
    o_orderkey AS O_ORDERKEY
  FROM TPCH.ORDERS
), "_T" AS (
  SELECT
    CUSTOMER.c_custkey AS C_CUSTKEY,
    CUSTOMER.c_name AS C_NAME,
    "_S3".O_ORDERDATE,
    ROW_NUMBER() OVER (PARTITION BY "_S3".O_CUSTKEY ORDER BY "_S3".O_ORDERDATE, "_S3".O_ORDERKEY) AS "_W"
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'VIETNAM'
  JOIN "_S4" "_S3"
    ON CUSTOMER.c_custkey = "_S3".O_CUSTKEY
), "_S5" AS (
  SELECT
    C_CUSTKEY,
    C_NAME,
    O_ORDERDATE
  FROM "_T"
  WHERE
    "_W" = 1
)
SELECT
  "_S5".C_NAME AS customer_name,
  "_S4".O_ORDERKEY AS order_key,
  CAST("_S4".O_ORDERDATE AS DATE) - CAST("_S5".O_ORDERDATE AS DATE) AS days_since_first_order
FROM "_S4" "_S4"
LEFT JOIN "_S5" "_S5"
  ON "_S4".O_CUSTKEY = "_S5".C_CUSTKEY
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
