WITH "_t" AS (
  SELECT
    O_ORDERKEY,
    O_ORDERPRIORITY,
    O_TOTALPRICE,
    ROW_NUMBER() OVER (PARTITION BY O_ORDERPRIORITY ORDER BY O_TOTALPRICE DESC) AS "_w"
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) = 1992
)
SELECT
  O_ORDERPRIORITY AS order_priority,
  O_ORDERKEY AS order_key,
  O_TOTALPRICE AS order_total_price
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
