WITH "_s0" AS (
  SELECT DISTINCT
    SBTICKEREXCHANGE
  FROM MAIN.SBTICKER
), "_s9" AS (
  SELECT
    SBCUSTOMER.SBCUSTID,
    "_s2".SBTICKEREXCHANGE,
    COUNT(*) AS N_ROWS
  FROM "_s0" "_s2"
  CROSS JOIN MAIN.SBCUSTOMER SBCUSTOMER
  JOIN MAIN.SBTRANSACTION SBTRANSACTION
    ON SBCUSTOMER.SBCUSTID = SBTRANSACTION.SBTXCUSTID
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.SBTICKEREXCHANGE = "_s2".SBTICKEREXCHANGE
    AND SBTICKER.SBTICKERID = SBTRANSACTION.SBTXTICKERID
  GROUP BY
    SBCUSTOMER.SBCUSTID,
    "_s2".SBTICKEREXCHANGE
)
SELECT
  SBCUSTOMER.SBCUSTSTATE AS state,
  "_s0".SBTICKEREXCHANGE AS exchange,
  COALESCE(SUM("_s9".N_ROWS), 0) AS n
FROM "_s0" "_s0"
CROSS JOIN MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_s9" "_s9"
  ON SBCUSTOMER.SBCUSTID = "_s9".SBCUSTID
  AND "_s0".SBTICKEREXCHANGE = "_s9".SBTICKEREXCHANGE
GROUP BY
  SBCUSTOMER.SBCUSTSTATE,
  "_s0".SBTICKEREXCHANGE
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
