WITH "_S0" AS (
  SELECT
    c_mktsegment AS C_MKTSEGMENT,
    c_nationkey AS C_NATIONKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.CUSTOMER
  GROUP BY
    c_mktsegment,
    c_nationkey
), "_S4" AS (
  SELECT
    "_S0".C_MKTSEGMENT,
    NATION.n_name AS N_NAME,
    SUM("_S0".N_ROWS) AS SUM_N_ROWS
  FROM "_S0" "_S0"
  JOIN TPCH.NATION NATION
    ON NATION.n_nationkey = "_S0".C_NATIONKEY
  GROUP BY
    "_S0".C_MKTSEGMENT,
    NATION.n_name
), "_S5" AS (
  SELECT
    CUSTOMER.c_mktsegment AS C_MKTSEGMENT,
    CUSTOMER.c_name AS C_NAME,
    NATION.n_name AS N_NAME,
    NATION.n_regionkey AS N_REGIONKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
)
SELECT
  REGION.r_name,
  "_S4".N_NAME AS n_name,
  "_S5".C_MKTSEGMENT AS c_industry,
  "_S5".C_NAME AS c_name,
  "_S4".SUM_N_ROWS AS n
FROM "_S4" "_S4"
JOIN "_S5" "_S5"
  ON "_S4".C_MKTSEGMENT = "_S5".C_MKTSEGMENT AND "_S4".N_NAME = "_S5".N_NAME
JOIN TPCH.REGION REGION
  ON REGION.r_regionkey = "_S5".N_REGIONKEY
ORDER BY
  5 DESC NULLS LAST,
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST,
  4 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
