WITH "_t4" AS (
  SELECT
    L_ORDERKEY,
    L_PARTKEY,
    L_QUANTITY,
    L_SHIPMODE
  FROM TPCH.LINEITEM
  WHERE
    L_SHIPMODE = 'RAIL'
), "_s6" AS (
  SELECT
    "_t4".L_PARTKEY,
    ANY_VALUE(PART.P_NAME) AS ANYTHING_P_NAME,
    SUM("_t4".L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.PART PART
  JOIN "_t4" "_t4"
    ON PART.P_PARTKEY = "_t4".L_PARTKEY
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1995
    AND ORDERS.O_ORDERKEY = "_t4".L_ORDERKEY
  WHERE
    PART.P_CONTAINER LIKE 'SM%'
  GROUP BY
    "_t4".L_PARTKEY
)
SELECT
  ANY_VALUE("_s6".ANYTHING_P_NAME) AS name,
  COALESCE(ANY_VALUE("_s6".SUM_L_QUANTITY), 0) AS qty_95,
  COALESCE(SUM("_t6".L_QUANTITY), 0) AS qty_96
FROM "_s6" "_s6"
JOIN "_t4" "_t6"
  ON "_s6".L_PARTKEY = "_t6".L_PARTKEY
JOIN TPCH.ORDERS ORDERS
  ON EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1996
  AND ORDERS.O_ORDERKEY = "_t6".L_ORDERKEY
GROUP BY
  "_t6".L_PARTKEY
ORDER BY
  COALESCE(SUM("_t6".L_QUANTITY), 0) - COALESCE(ANY_VALUE("_s6".SUM_L_QUANTITY), 0) DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
