WITH "_s0" AS (
  SELECT
    P_PARTKEY,
    P_RETAILPRICE,
    P_SIZE
  FROM TPCH.PART
  ORDER BY
    TRUNC(CAST(P_RETAILPRICE AS DOUBLE PRECISION), 0) NULLS FIRST
  FETCH FIRST 2 ROWS ONLY
)
SELECT
  CAST("_s0".P_SIZE / 2.5 AS DOUBLE PRECISION) AS reduced_size,
  TRUNC(CAST("_s0".P_RETAILPRICE AS DOUBLE PRECISION), 0) AS retail_price_int,
  'old size: ' || NVL(TO_CHAR("_s0".P_SIZE), '') AS message,
  LINEITEM.L_DISCOUNT AS discount,
  TO_CHAR(LINEITEM.L_RECEIPTDATE, 'DD-MM-YYYY') AS date_dmy,
  TO_CHAR(LINEITEM.L_RECEIPTDATE, 'MM/DD') AS date_md,
  TO_CHAR(LINEITEM.L_RECEIPTDATE, 'HH24:MIAM') AS am_pm
FROM "_s0" "_s0"
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.L_PARTKEY = "_s0".P_PARTKEY
ORDER BY
  4 DESC NULLS LAST,
  5 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
