WITH _S0 AS (
  SELECT DISTINCT
    sbcuststate AS SBCUSTSTATE
  FROM MAIN.SBCUSTOMER
), _T2 AS (
  SELECT
    sbtxdatetime AS SBTXDATETIME
  FROM MAIN.SBTRANSACTION
  WHERE
    YEAR(CAST(sbtxdatetime AS TIMESTAMP)) = 2023
), _S1 AS (
  SELECT DISTINCT
    DATE_TRUNC('MONTH', CAST(SBTXDATETIME AS TIMESTAMP)) AS MONTH
  FROM _T2
), _S3 AS (
  SELECT DISTINCT
    DATE_TRUNC('MONTH', CAST(SBTXDATETIME AS TIMESTAMP)) AS MONTH
  FROM _T2
), _S9 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _S3.MONTH,
    _S2.SBCUSTSTATE
  FROM _S0 AS _S2
  CROSS JOIN _S3 AS _S3
  JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
    ON YEAR(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP)) = 2023
    AND _S3.MONTH = DATE_TRUNC('MONTH', CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP))
  JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
    ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
    AND SBCUSTOMER.sbcuststate = _S2.SBCUSTSTATE
  GROUP BY
    2,
    3
)
SELECT
  _S0.SBCUSTSTATE AS state,
  _S1.MONTH AS month_of_year,
  SUM(COALESCE(_S9.N_ROWS, 0)) OVER (PARTITION BY _S0.SBCUSTSTATE ORDER BY _S1.MONTH ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS n
FROM _S0 AS _S0
CROSS JOIN _S1 AS _S1
LEFT JOIN _S9 AS _S9
  ON _S0.SBCUSTSTATE = _S9.SBCUSTSTATE AND _S1.MONTH = _S9.MONTH
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
