WITH _S0 AS (
  SELECT DISTINCT
    sbcuststate AS SBCUSTSTATE
  FROM MAIN.SBCUSTOMER
), _T2 AS (
  SELECT
    sbtxdatetime AS SBTXDATETIME
  FROM MAIN.SBTRANSACTION
  WHERE
    EXTRACT(YEAR FROM CAST(sbtxdatetime AS DATETIME)) = 2023
), _S1 AS (
  SELECT DISTINCT
    TRUNC(CAST(SBTXDATETIME AS TIMESTAMP), 'MONTH') AS MONTH
  FROM _T2
), _S3 AS (
  SELECT DISTINCT
    TRUNC(CAST(SBTXDATETIME AS TIMESTAMP), 'MONTH') AS MONTH
  FROM _T2
), _S9 AS (
  SELECT
    _S3.MONTH,
    _S2.SBCUSTSTATE,
    COUNT(*) AS N_ROWS
  FROM _S0 _S2
  CROSS JOIN _S3 _S3
  JOIN MAIN.SBTRANSACTION SBTRANSACTION
    ON EXTRACT(YEAR FROM CAST(SBTRANSACTION.sbtxdatetime AS DATETIME)) = 2023
    AND _S3.MONTH = TRUNC(CAST(SBTRANSACTION.sbtxdatetime AS TIMESTAMP), 'MONTH')
  JOIN MAIN.SBCUSTOMER SBCUSTOMER
    ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
    AND SBCUSTOMER.sbcuststate = _S2.SBCUSTSTATE
  GROUP BY
    _S3.MONTH,
    _S2.SBCUSTSTATE
)
SELECT
  _S0.SBCUSTSTATE AS state,
  MAX(NVL(_S9.N_ROWS, 0)) AS max_n
FROM _S0 _S0
CROSS JOIN _S1 _S1
LEFT JOIN _S9 _S9
  ON _S0.SBCUSTSTATE = _S9.SBCUSTSTATE AND _S1.MONTH = _S9.MONTH
GROUP BY
  _S0.SBCUSTSTATE
