WITH _S0 AS (
  SELECT DISTINCT
    sbtickerexchange AS SBTICKEREXCHANGE
  FROM MAIN.SBTICKER
), _S9 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SBCUSTOMER.sbcustid AS SBCUSTID,
    _S2.SBTICKEREXCHANGE
  FROM _S0 AS _S2
  CROSS JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
  JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
    ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  JOIN MAIN.SBTICKER AS SBTICKER
    ON SBTICKER.sbtickerexchange = _S2.SBTICKEREXCHANGE
    AND SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  GROUP BY
    2,
    3
)
SELECT
  SBCUSTOMER.sbcuststate AS state,
  _S0.SBTICKEREXCHANGE AS exchange,
  COALESCE(SUM(_S9.N_ROWS), 0) AS n
FROM _S0 AS _S0
CROSS JOIN MAIN.SBCUSTOMER AS SBCUSTOMER
LEFT JOIN _S9 AS _S9
  ON SBCUSTOMER.sbcustid = _S9.SBCUSTID
  AND _S0.SBTICKEREXCHANGE = _S9.SBTICKEREXCHANGE
GROUP BY
  1,
  2
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
