WITH "_S0" AS (
  SELECT DISTINCT
    sbtickerexchange AS SBTICKEREXCHANGE
  FROM MAIN.SBTICKER
), "_S9" AS (
  SELECT
    SBCUSTOMER.sbcustid AS SBCUSTID,
    "_S2".SBTICKEREXCHANGE,
    COUNT(*) AS N_ROWS
  FROM "_S0" "_S2"
  CROSS JOIN MAIN.SBCUSTOMER SBCUSTOMER
  JOIN MAIN.SBTRANSACTION SBTRANSACTION
    ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
  JOIN MAIN.SBTICKER SBTICKER
    ON SBTICKER.sbtickerexchange = "_S2".SBTICKEREXCHANGE
    AND SBTICKER.sbtickerid = SBTRANSACTION.sbtxtickerid
  GROUP BY
    SBCUSTOMER.sbcustid,
    "_S2".SBTICKEREXCHANGE
)
SELECT
  SBCUSTOMER.sbcuststate AS state,
  "_S0".SBTICKEREXCHANGE AS exchange,
  COALESCE(SUM("_S9".N_ROWS), 0) AS n
FROM "_S0" "_S0"
CROSS JOIN MAIN.SBCUSTOMER SBCUSTOMER
LEFT JOIN "_S9" "_S9"
  ON SBCUSTOMER.sbcustid = "_S9".SBCUSTID
  AND "_S0".SBTICKEREXCHANGE = "_S9".SBTICKEREXCHANGE
GROUP BY
  SBCUSTOMER.sbcuststate,
  "_S0".SBTICKEREXCHANGE
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
