WITH _T4 AS (
  SELECT
    l_orderkey AS L_ORDERKEY,
    l_partkey AS L_PARTKEY,
    l_quantity AS L_QUANTITY,
    l_shipmode AS L_SHIPMODE
  FROM TPCH.LINEITEM
  WHERE
    l_shipmode = 'RAIL'
), _S6 AS (
  SELECT
    _T4.L_PARTKEY,
    ANY_VALUE(PART.p_name) AS ANYTHING_P_NAME,
    SUM(_T4.L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.PART PART
  JOIN _T4 _T4
    ON PART.p_partkey = _T4.L_PARTKEY
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1995
    AND ORDERS.o_orderkey = _T4.L_ORDERKEY
  WHERE
    PART.p_container LIKE 'SM%'
  GROUP BY
    _T4.L_PARTKEY
)
SELECT
  ANY_VALUE(_S6.ANYTHING_P_NAME) AS name,
  NVL(ANY_VALUE(_S6.SUM_L_QUANTITY), 0) AS qty_95,
  NVL(SUM(_T6.L_QUANTITY), 0) AS qty_96
FROM _S6 _S6
JOIN _T4 _T6
  ON _S6.L_PARTKEY = _T6.L_PARTKEY
JOIN TPCH.ORDERS ORDERS
  ON EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1996
  AND ORDERS.o_orderkey = _T6.L_ORDERKEY
GROUP BY
  _T6.L_PARTKEY
ORDER BY
  NVL(SUM(_T6.L_QUANTITY), 0) - NVL(ANY_VALUE(_S6.SUM_L_QUANTITY), 0) DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
