WITH "_s0" AS (
  SELECT DISTINCT
    SBCUSTSTATE
  FROM MAIN.SBCUSTOMER
), "_t2" AS (
  SELECT
    SBTXDATETIME
  FROM MAIN.SBTRANSACTION
  WHERE
    EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)) = 2023
), "_s1" AS (
  SELECT DISTINCT
    TRUNC(CAST(SBTXDATETIME AS DATE), 'MONTH') AS MONTH
  FROM "_t2"
), "_s3" AS (
  SELECT DISTINCT
    TRUNC(CAST(SBTXDATETIME AS DATE), 'MONTH') AS MONTH
  FROM "_t2"
), "_s9" AS (
  SELECT
    "_s3".MONTH,
    "_s2".SBCUSTSTATE,
    COUNT(*) AS N_ROWS
  FROM "_s0" "_s2"
  CROSS JOIN "_s3" "_s3"
  JOIN MAIN.SBTRANSACTION SBTRANSACTION
    ON EXTRACT(YEAR FROM CAST(SBTRANSACTION.SBTXDATETIME AS DATE)) = 2023
    AND "_s3".MONTH = TRUNC(CAST(SBTRANSACTION.SBTXDATETIME AS DATE), 'MONTH')
  JOIN MAIN.SBCUSTOMER SBCUSTOMER
    ON SBCUSTOMER.SBCUSTID = SBTRANSACTION.SBTXCUSTID
    AND SBCUSTOMER.SBCUSTSTATE = "_s2".SBCUSTSTATE
  GROUP BY
    "_s3".MONTH,
    "_s2".SBCUSTSTATE
)
SELECT
  "_s0".SBCUSTSTATE AS state,
  "_s1".MONTH AS month_of_year,
  SUM(COALESCE("_s9".N_ROWS, 0)) OVER (
    PARTITION BY "_s0".SBCUSTSTATE
    ORDER BY "_s1".MONTH
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS n
FROM "_s0" "_s0"
CROSS JOIN "_s1" "_s1"
LEFT JOIN "_s9" "_s9"
  ON "_s0".SBCUSTSTATE = "_s9".SBCUSTSTATE AND "_s1".MONTH = "_s9".MONTH
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
