WITH "_t1" AS (
  SELECT
    N_NAME,
    N_NATIONKEY
  FROM TPCH.NATION
  WHERE
    N_NAME IN ('CANADA', 'ARGENTINA')
), "_s6" AS (
  SELECT DISTINCT
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    "_t1".N_NAME
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
  JOIN "_t1" "_t1"
    ON CUSTOMER.C_NATIONKEY = "_t1".N_NATIONKEY
), "_s7" AS (
  SELECT DISTINCT
    "_t3".N_NAME
  FROM TPCH.SUPPLIER SUPPLIER
  JOIN "_t1" "_t3"
    ON SUPPLIER.S_NATIONKEY = "_t3".N_NATIONKEY
)
SELECT
  "_s6".N_NAME AS c_nation,
  "_s6".YEAR_O_ORDERDATE AS o_year
FROM "_s6" "_s6"
JOIN "_s7" "_s7"
  ON "_s6".N_NAME = "_s7".N_NAME
