WITH "_s3" AS (
  SELECT
    ANY_VALUE(CUSTOMER.SUPPORTREPID) AS ANYTHING_SUPPORTREPID,
    SUM(INVOICE.TOTAL) AS SUM_TOTAL
  FROM MAIN.CUSTOMER CUSTOMER
  LEFT JOIN MAIN.INVOICE INVOICE
    ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
  GROUP BY
    CUSTOMER.CUSTOMERID
)
SELECT
  "_s3".ANYTHING_SUPPORTREPID AS employee_id,
  COALESCE(SUM("_s3".SUM_TOTAL), 0) AS total_invoice
FROM MAIN.EMPLOYEE EMPLOYEE
JOIN "_s3" "_s3"
  ON EMPLOYEE.EMPLOYEEID = "_s3".ANYTHING_SUPPORTREPID
GROUP BY
  "_s3".ANYTHING_SUPPORTREPID
ORDER BY
  1 NULLS FIRST
