WITH "_T1" AS (
  SELECT
    ANY_VALUE(CUSTOMER.supportrepid) AS ANYTHING_SUPPORTREPID,
    SUM(INVOICE.total) AS SUM_TOTAL
  FROM MAIN.CUSTOMER CUSTOMER
  LEFT JOIN MAIN.INVOICE INVOICE
    ON CUSTOMER.customerid = INVOICE.customerid
  GROUP BY
    CUSTOMER.customerid
), "_S3" AS (
  SELECT
    ANYTHING_SUPPORTREPID,
    SUM(SUM_TOTAL) AS SUM_SUM_TOTAL
  FROM "_T1"
  GROUP BY
    ANYTHING_SUPPORTREPID
)
SELECT
  EMPLOYEE.employeeid AS employee_id,
  COALESCE("_S3".SUM_SUM_TOTAL, 0) AS total_invoice
FROM MAIN.EMPLOYEE EMPLOYEE
JOIN "_S3" "_S3"
  ON EMPLOYEE.employeeid = "_S3".ANYTHING_SUPPORTREPID
ORDER BY
  1 NULLS FIRST
