WITH "_S3" AS (
  SELECT
    ANY_VALUE(CUSTOMER.supportrepid) AS ANYTHING_SUPPORTREPID,
    SUM(INVOICE.total) AS SUM_TOTAL
  FROM MAIN.CUSTOMER CUSTOMER
  LEFT JOIN MAIN.INVOICE INVOICE
    ON CUSTOMER.customerid = INVOICE.customerid
  GROUP BY
    CUSTOMER.customerid
)
SELECT
  "_S3".ANYTHING_SUPPORTREPID AS employee_id,
  COALESCE(SUM("_S3".SUM_TOTAL), 0) AS total_invoice
FROM MAIN.EMPLOYEE EMPLOYEE
JOIN "_S3" "_S3"
  ON EMPLOYEE.employeeid = "_S3".ANYTHING_SUPPORTREPID
GROUP BY
  "_S3".ANYTHING_SUPPORTREPID
ORDER BY
  1 NULLS FIRST
