WITH "_t" AS (
  SELECT
    CUSTOMER.C_NAME,
    CUSTOMER.C_PHONE,
    NTILE(100) OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY CUSTOMER.C_ACCTBAL) AS "_w"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
)
SELECT
  C_NAME AS name
FROM "_t"
WHERE
  C_PHONE LIKE '%00' AND "_w" = 95
ORDER BY
  1 NULLS FIRST
