WITH "_T" AS (
  SELECT
    CUSTOMER.c_name AS C_NAME,
    CUSTOMER.c_phone AS C_PHONE,
    NTILE(100) OVER (PARTITION BY NATION.n_regionkey ORDER BY CUSTOMER.c_acctbal) AS "_W"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
)
SELECT
  C_NAME AS name
FROM "_T"
WHERE
  C_PHONE LIKE '%00' AND "_W" = 95
ORDER BY
  1 NULLS FIRST
