WITH "_S0" AS (
  SELECT
    n_name AS N_NAME,
    n_nationkey AS N_NATIONKEY,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 5 ROWS ONLY
), "_S5" AS (
  SELECT
    CUSTOMER.c_nationkey AS C_NATIONKEY,
    ORDERS.o_totalprice AS O_TOTALPRICE
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
    AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1998
), "_T1" AS (
  SELECT
    "_S0".N_NAME,
    "_S0".N_NATIONKEY,
    "_S5".O_TOTALPRICE,
    REGION.r_name AS R_NAME,
    CASE
      WHEN FLOOR(0.99 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_10,
    CASE
      WHEN FLOOR(0.75 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_11,
    CASE
      WHEN FLOOR(0.25 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_12,
    CASE
      WHEN FLOOR(0.1 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_13,
    CASE
      WHEN FLOOR(0.01 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_14,
    CASE
      WHEN FLOOR(0.5 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_15,
    CASE
      WHEN FLOOR(0.9 * COUNT("_S5".O_TOTALPRICE) OVER (PARTITION BY "_S5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_S5".C_NATIONKEY ORDER BY "_S5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_S5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_9
  FROM "_S0" "_S0"
  JOIN TPCH.REGION REGION
    ON REGION.r_regionkey = "_S0".N_REGIONKEY
  LEFT JOIN "_S5" "_S5"
    ON "_S0".N_NATIONKEY = "_S5".C_NATIONKEY
)
SELECT
  ANY_VALUE(R_NAME) AS region_name,
  ANY_VALUE(N_NAME) AS nation_name,
  MIN(O_TOTALPRICE) AS orders_min,
  MAX(EXPR_10) AS orders_1_percent,
  MAX(EXPR_9) AS orders_10_percent,
  MAX(EXPR_11) AS orders_25_percent,
  MAX(EXPR_15) AS orders_median,
  MAX(EXPR_12) AS orders_75_percent,
  MAX(EXPR_13) AS orders_90_percent,
  MAX(EXPR_14) AS orders_99_percent,
  MAX(O_TOTALPRICE) AS orders_max
FROM "_T1"
GROUP BY
  N_NATIONKEY
ORDER BY
  2 NULLS FIRST
