SELECT
  PERCENTILE_DISC(0.7) WITHIN GROUP (ORDER BY
    ORDERS.o_totalprice) AS seventieth_order_price
FROM TPCH.CUSTOMER AS CUSTOMER
JOIN TPCH.ORDERS AS ORDERS
  ON CUSTOMER.c_custkey = ORDERS.o_custkey
  AND YEAR(CAST(ORDERS.o_orderdate AS TIMESTAMP)) = 1998
