WITH "_t0" AS (
  SELECT
    CASE
      WHEN FLOOR(0.3 * COUNT(O_TOTALPRICE) OVER ()) < ROW_NUMBER() OVER (ORDER BY O_TOTALPRICE DESC NULLS LAST)
      THEN O_TOTALPRICE
      ELSE NULL
    END AS EXPR_1
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) = 1998
)
SELECT
  MAX(EXPR_1) AS seventieth_order_price
FROM "_t0"
