WITH _T0 AS (
  SELECT
    CASE
      WHEN CAST(0.30000000000000004 * COUNT(ORDERS.o_totalprice) OVER () AS BIGINT) < ROW_NUMBER() OVER (ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_1
  FROM TPCH.CUSTOMER AS CUSTOMER
  JOIN TPCH.ORDERS AS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
    AND DATE_PART(YEAR, CAST(ORDERS.o_orderdate AS DATETIME)) = 1998
)
SELECT
  MAX(EXPR_1) AS seventieth_order_price
FROM _T0
