WITH "_s0" AS (
  SELECT
    N_NAME,
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 5 ROWS ONLY
), "_s5" AS (
  SELECT
    CUSTOMER.C_NATIONKEY,
    ORDERS.O_TOTALPRICE,
    CASE
      WHEN FLOOR(0.99 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_10,
    CASE
      WHEN FLOOR(0.75 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_11,
    CASE
      WHEN FLOOR(0.25 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_12,
    CASE
      WHEN FLOOR(0.1 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_13,
    CASE
      WHEN FLOOR(0.01 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_14,
    CASE
      WHEN FLOOR(0.5 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_15,
    CASE
      WHEN FLOOR(0.9 * COUNT(ORDERS.O_TOTALPRICE) OVER (PARTITION BY CUSTOMER.C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY ORDERS.O_TOTALPRICE DESC NULLS LAST)
      THEN ORDERS.O_TOTALPRICE
      ELSE NULL
    END AS EXPR_9
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1998
)
SELECT
  ANY_VALUE(REGION.R_NAME) AS region_name,
  ANY_VALUE("_s0".N_NAME) AS nation_name,
  MIN("_s5".O_TOTALPRICE) AS orders_min,
  MAX("_s5".EXPR_10) AS orders_1_percent,
  MAX("_s5".EXPR_9) AS orders_10_percent,
  MAX("_s5".EXPR_11) AS orders_25_percent,
  MAX("_s5".EXPR_15) AS orders_median,
  MAX("_s5".EXPR_12) AS orders_75_percent,
  MAX("_s5".EXPR_13) AS orders_90_percent,
  MAX("_s5".EXPR_14) AS orders_99_percent,
  MAX("_s5".O_TOTALPRICE) AS orders_max
FROM "_s0" "_s0"
JOIN TPCH.REGION REGION
  ON REGION.R_REGIONKEY = "_s0".N_REGIONKEY
LEFT JOIN "_s5" "_s5"
  ON "_s0".N_NATIONKEY = "_s5".C_NATIONKEY
GROUP BY
  "_s0".N_NATIONKEY
ORDER BY
  2 NULLS FIRST
