WITH "_s0" AS (
  SELECT
    N_NAME,
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 5 ROWS ONLY
), "_s5" AS (
  SELECT
<<<<<<< HEAD
    CUSTOMER.C_NATIONKEY,
    ORDERS.O_TOTALPRICE
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1998
), "_t1" AS (
  SELECT
    "_s0".N_NAME,
    "_s0".N_NATIONKEY,
    "_s5".O_TOTALPRICE,
    REGION.R_NAME,
    CASE
      WHEN FLOOR(0.99 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_10,
    CASE
      WHEN FLOOR(0.75 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_11,
    CASE
      WHEN FLOOR(0.25 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_12,
    CASE
      WHEN FLOOR(0.1 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_13,
    CASE
      WHEN FLOOR(0.01 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_14,
    CASE
      WHEN FLOOR(0.5 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_15,
    CASE
      WHEN FLOOR(0.9 * COUNT("_s5".O_TOTALPRICE) OVER (PARTITION BY "_s5".C_NATIONKEY)) < ROW_NUMBER() OVER (PARTITION BY "_s5".C_NATIONKEY ORDER BY "_s5".O_TOTALPRICE DESC NULLS LAST)
      THEN "_s5".O_TOTALPRICE
      ELSE NULL
    END AS EXPR_9
  FROM "_s0" "_s0"
  JOIN TPCH.REGION REGION
    ON REGION.R_REGIONKEY = "_s0".N_REGIONKEY
  LEFT JOIN "_s5" "_s5"
    ON "_s0".N_NATIONKEY = "_s5".C_NATIONKEY
)
SELECT
  ANY_VALUE(R_NAME) AS region_name,
  ANY_VALUE(N_NAME) AS nation_name,
  MIN(O_TOTALPRICE) AS orders_min,
  MAX(EXPR_10) AS orders_1_percent,
  MAX(EXPR_9) AS orders_10_percent,
  MAX(EXPR_11) AS orders_25_percent,
  MAX(EXPR_15) AS orders_median,
  MAX(EXPR_12) AS orders_75_percent,
  MAX(EXPR_13) AS orders_90_percent,
  MAX(EXPR_14) AS orders_99_percent,
  MAX(O_TOTALPRICE) AS orders_max
FROM "_t1"
=======
    CUSTOMER.c_nationkey AS C_NATIONKEY,
    ORDERS.o_totalprice AS O_TOTALPRICE,
    CASE
      WHEN FLOOR(0.99 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_10,
    CASE
      WHEN FLOOR(0.75 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_11,
    CASE
      WHEN FLOOR(0.25 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_12,
    CASE
      WHEN FLOOR(0.1 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_13,
    CASE
      WHEN FLOOR(0.01 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_14,
    CASE
      WHEN FLOOR(0.5 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_15,
    CASE
      WHEN FLOOR(0.9 * COUNT(ORDERS.o_totalprice) OVER (PARTITION BY CUSTOMER.c_nationkey)) < ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY ORDERS.o_totalprice DESC NULLS LAST)
      THEN ORDERS.o_totalprice
      ELSE NULL
    END AS EXPR_9
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
    AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1998
)
SELECT
  ANY_VALUE(REGION.r_name) AS region_name,
  ANY_VALUE("_S0".N_NAME) AS nation_name,
  MIN("_S5".O_TOTALPRICE) AS orders_min,
  MAX("_S5".EXPR_10) AS orders_1_percent,
  MAX("_S5".EXPR_9) AS orders_10_percent,
  MAX("_S5".EXPR_11) AS orders_25_percent,
  MAX("_S5".EXPR_15) AS orders_median,
  MAX("_S5".EXPR_12) AS orders_75_percent,
  MAX("_S5".EXPR_13) AS orders_90_percent,
  MAX("_S5".EXPR_14) AS orders_99_percent,
  MAX("_S5".O_TOTALPRICE) AS orders_max
FROM "_S0" "_S0"
JOIN TPCH.REGION REGION
  ON REGION.r_regionkey = "_S0".N_REGIONKEY
LEFT JOIN "_S5" "_S5"
  ON "_S0".N_NATIONKEY = "_S5".C_NATIONKEY
>>>>>>> 4867111585f8e9dcf48b9d829dc38efab694d6a8
GROUP BY
  "_S0".N_NATIONKEY
ORDER BY
  2 NULLS FIRST
