WITH "_t2" AS (
  SELECT
    PR_NAME,
    PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_s1" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_s7" AS (
  SELECT
    "_s3".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_t2" "_t4"
  JOIN "_s1" "_s3"
    ON "_s3".CA_DT < TRUNC(ADD_MONTHS(CAST("_t4".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s3".CA_DT >= "_t4".PR_RELEASE
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_PRODUCT_ID = 800544
    AND "_s3".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  GROUP BY
    "_s3".CA_DT
), "_s22" AS (
  SELECT
    TRUNC(CAST(CAST("_s1".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    SUM("_s7".N_ROWS) AS SUM_N_ROWS
  FROM "_t2" "_t2"
  JOIN "_s1" "_s1"
    ON "_s1".CA_DT < TRUNC(ADD_MONTHS(CAST("_t2".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s1".CA_DT >= "_t2".PR_RELEASE
  LEFT JOIN "_s7" "_s7"
    ON "_s1".CA_DT = "_s7".CA_DT
  GROUP BY
    TRUNC(CAST(CAST("_s1".CA_DT AS DATE) AS DATE), 'Q')
), "_s13" AS (
  SELECT DISTINCT
    TRUNC(CAST(CAST("_s11".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER
  FROM "_t2" "_t10"
  JOIN "_s1" "_s11"
    ON "_s11".CA_DT < TRUNC(ADD_MONTHS(CAST("_t10".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s11".CA_DT >= "_t10".PR_RELEASE
), "_s17" AS (
  SELECT
    "_s15".CA_DT
  FROM "_t2" "_t11"
  JOIN "_s1" "_s15"
    ON "_s15".CA_DT < TRUNC(ADD_MONTHS(CAST("_t11".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s15".CA_DT >= "_t11".PR_RELEASE
), "_s23" AS (
  SELECT
    "_s13".QUARTER,
    COUNT(DISTINCT INCIDENTS.IN_DEVICE_ID) AS NDISTINCT_IN_DEVICE_ID
  FROM MAIN.PRODUCTS PRODUCTS
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.CO_NAME = 'CN'
  CROSS JOIN "_s13" "_s13"
  JOIN "_s17" "_s17"
    ON "_s13".QUARTER = TRUNC(CAST(CAST("_s17".CA_DT AS DATE) AS DATE), 'Q')
  JOIN MAIN.INCIDENTS INCIDENTS
    ON COUNTRIES.CO_ID = INCIDENTS.IN_REPAIR_COUNTRY_ID
    AND "_s17".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID AND DEVICES.DE_PRODUCT_ID = 800544
  WHERE
    PRODUCTS.PR_NAME = 'RubyCopper-Star'
  GROUP BY
    "_s13".QUARTER
)
SELECT
  "_s22".QUARTER AS quarter,
  COALESCE("_s23".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  COALESCE("_s22".SUM_N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(COALESCE("_s23".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_s22".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_s22".SUM_N_ROWS, 0)) OVER (ORDER BY "_s22".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_s22" "_s22"
LEFT JOIN "_s23" "_s23"
  ON "_s22".QUARTER = "_s23".QUARTER
ORDER BY
  1 NULLS FIRST
