WITH "_T2" AS (
  SELECT
    pr_name AS PR_NAME,
    pr_release AS PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'RubyCopper-Star'
), "_S1" AS (
  SELECT
    ca_dt AS CA_DT
  FROM MAIN.CALENDAR
), "_S7" AS (
  SELECT
    "_S3".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_T2" "_T4"
  JOIN "_S1" "_S3"
    ON "_S3".CA_DT < TRUNC(DATE_ADD(CAST("_T4".PR_RELEASE AS TIMESTAMP), 2, 'YEAR'), 'QUARTER')
    AND "_S3".CA_DT >= "_T4".PR_RELEASE
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.de_product_id = 800544
    AND "_S3".CA_DT = TRUNC(CAST(DEVICES.de_purchase_ts AS TIMESTAMP), 'DAY')
  GROUP BY
    "_S3".CA_DT
), "_S22" AS (
  SELECT
    TRUNC(CAST("_S1".CA_DT AS TIMESTAMP), 'QUARTER') AS QUARTER,
    SUM("_S7".N_ROWS) AS SUM_N_ROWS
  FROM "_T2" "_T2"
  JOIN "_S1" "_S1"
    ON "_S1".CA_DT < TRUNC(DATE_ADD(CAST("_T2".PR_RELEASE AS TIMESTAMP), 2, 'YEAR'), 'QUARTER')
    AND "_S1".CA_DT >= "_T2".PR_RELEASE
  LEFT JOIN "_S7" "_S7"
    ON "_S1".CA_DT = "_S7".CA_DT
  GROUP BY
    TRUNC(CAST("_S1".CA_DT AS TIMESTAMP), 'QUARTER')
), "_S13" AS (
  SELECT DISTINCT
    TRUNC(CAST("_S11".CA_DT AS TIMESTAMP), 'QUARTER') AS QUARTER
  FROM "_T2" "_T10"
  JOIN "_S1" "_S11"
    ON "_S11".CA_DT < TRUNC(DATE_ADD(CAST("_T10".PR_RELEASE AS TIMESTAMP), 2, 'YEAR'), 'QUARTER')
    AND "_S11".CA_DT >= "_T10".PR_RELEASE
), "_S17" AS (
  SELECT
    "_S15".CA_DT
  FROM "_T2" "_T11"
  JOIN "_S1" "_S15"
    ON "_S15".CA_DT < TRUNC(DATE_ADD(CAST("_T11".PR_RELEASE AS TIMESTAMP), 2, 'YEAR'), 'QUARTER')
    AND "_S15".CA_DT >= "_T11".PR_RELEASE
), "_S23" AS (
  SELECT
    "_S13".QUARTER,
    COUNT(DISTINCT INCIDENTS.in_device_id) AS NDISTINCT_IN_DEVICE_ID
  FROM MAIN.PRODUCTS PRODUCTS
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.co_name = 'CN'
  CROSS JOIN "_S13" "_S13"
  JOIN "_S17" "_S17"
    ON "_S13".QUARTER = TRUNC(CAST("_S17".CA_DT AS TIMESTAMP), 'QUARTER')
  JOIN MAIN.INCIDENTS INCIDENTS
    ON COUNTRIES.co_id = INCIDENTS.in_repair_country_id
    AND "_S17".CA_DT = TRUNC(CAST(INCIDENTS.in_error_report_ts AS TIMESTAMP), 'DAY')
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id AND DEVICES.de_product_id = 800544
  WHERE
    PRODUCTS.pr_name = 'RubyCopper-Star'
  GROUP BY
    "_S13".QUARTER
)
SELECT
  "_S22".QUARTER AS quarter,
  NVL("_S23".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  NVL("_S22".SUM_N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(NVL("_S23".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_S22".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(NVL("_S22".SUM_N_ROWS, 0)) OVER (ORDER BY "_S22".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_S22" "_S22"
LEFT JOIN "_S23" "_S23"
  ON "_S22".QUARTER = "_S23".QUARTER
ORDER BY
  1 NULLS FIRST
