WITH "_t1" AS (
  SELECT
    PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_t2" AS (
  SELECT
    CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    CO_NAME = 'CN'
), "_t4" AS (
  SELECT
    PR_NAME,
    PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'RubyCopper-Star'
), "_s5" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_s13" AS (
  SELECT
    "_s9".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_t4" "_t7"
  CROSS JOIN "_t2" "_t8"
  JOIN "_s5" "_s9"
    ON "_s9".CA_DT < TRUNC(ADD_MONTHS(CAST("_t7".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s9".CA_DT >= "_t7".PR_RELEASE
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_PRODUCT_ID = 800544
    AND "_s9".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  GROUP BY
    "_s9".CA_DT
), "_s15" AS (
  SELECT
    TRUNC(CAST(CAST("_s5".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER,
    SUM("_s13".N_ROWS) AS SUM_N_ROWS
  FROM "_t4" "_t4"
  CROSS JOIN "_t2" "_t5"
  JOIN "_s5" "_s5"
    ON "_s5".CA_DT < TRUNC(ADD_MONTHS(CAST("_t4".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s5".CA_DT >= "_t4".PR_RELEASE
  LEFT JOIN "_s13" "_s13"
    ON "_s13".CA_DT = "_s5".CA_DT
  GROUP BY
    TRUNC(CAST(CAST("_s5".CA_DT AS DATE) AS DATE), 'Q')
), "_s23" AS (
  SELECT DISTINCT
    TRUNC(CAST(CAST("_s21".CA_DT AS DATE) AS DATE), 'Q') AS QUARTER
  FROM "_t4" "_t14"
  CROSS JOIN "_t2" "_t15"
  JOIN "_s5" "_s21"
    ON "_s21".CA_DT < TRUNC(ADD_MONTHS(CAST("_t14".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s21".CA_DT >= "_t14".PR_RELEASE
), "_s29" AS (
  SELECT
    "_s27".CA_DT
  FROM "_t4" "_t16"
  CROSS JOIN "_t2" "_t17"
  JOIN "_s5" "_s27"
    ON "_s27".CA_DT < TRUNC(ADD_MONTHS(CAST("_t16".PR_RELEASE AS DATE), 24), 'Q')
    AND "_s27".CA_DT >= "_t16".PR_RELEASE
), "_s35" AS (
  SELECT
    "_s23".QUARTER,
    COUNT(DISTINCT INCIDENTS.IN_DEVICE_ID) AS NDISTINCT_IN_DEVICE_ID
  FROM "_t1" "_t11"
  JOIN MAIN.COUNTRIES COUNTRIES
    ON COUNTRIES.CO_NAME = 'CN'
  CROSS JOIN "_s23" "_s23"
  JOIN "_s29" "_s29"
    ON "_s23".QUARTER = TRUNC(CAST(CAST("_s29".CA_DT AS DATE) AS DATE), 'Q')
  JOIN MAIN.INCIDENTS INCIDENTS
    ON COUNTRIES.CO_ID = INCIDENTS.IN_REPAIR_COUNTRY_ID
    AND "_s29".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID AND DEVICES.DE_PRODUCT_ID = 800544
  GROUP BY
    "_s23".QUARTER
)
SELECT
  "_s15".QUARTER AS quarter,
  COALESCE("_s35".NDISTINCT_IN_DEVICE_ID, 0) AS n_incidents,
  COALESCE("_s15".SUM_N_ROWS, 0) AS n_sold,
  ROUND(
    SUM(COALESCE("_s35".NDISTINCT_IN_DEVICE_ID, 0)) OVER (ORDER BY "_s15".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_s15".SUM_N_ROWS, 0)) OVER (ORDER BY "_s15".QUARTER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS quarter_cum
FROM "_t1" "_t1"
CROSS JOIN "_t2" "_t2"
CROSS JOIN "_s15" "_s15"
LEFT JOIN "_s35" "_s35"
  ON "_s15".QUARTER = "_s35".QUARTER
ORDER BY
  1 NULLS FIRST
