WITH "_s0" AS (
  SELECT DISTINCT
    P_SIZE
  FROM TPCH.PART
  ORDER BY
    1 DESC NULLS LAST
  FETCH FIRST 5 ROWS ONLY
), "_t" AS (
  SELECT
    PART.P_SIZE AS SIZE_1,
    PART.P_NAME,
    ROW_NUMBER() OVER (PARTITION BY "_s0".P_SIZE ORDER BY PART.P_RETAILPRICE DESC, PART.P_PARTKEY) AS "_w"
  FROM "_s0" "_s0"
  JOIN TPCH.PART PART
    ON PART.P_SIZE = "_s0".P_SIZE
)
SELECT
  P_NAME AS pname,
  SIZE_1 AS psize
FROM "_t"
WHERE
  "_w" = 1
