SELECT
  PART.P_PARTKEY AS "key",
  REGION.R_NAME AS region,
  DENSE_RANK() OVER (
    PARTITION BY NATION.N_REGIONKEY
    ORDER BY PART.P_SIZE DESC, PART.P_CONTAINER DESC, PART.P_TYPE DESC
  ) AS rank
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
JOIN TPCH.SUPPLIER SUPPLIER
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN TPCH.PARTSUPP PARTSUPP
  ON PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN TPCH.PART PART
  ON PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 15 ROWS ONLY
