WITH "_s1" AS (
  SELECT
    C_NATIONKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.CUSTOMER
  GROUP BY
    C_NATIONKEY
)
SELECT
  NATION.N_NAME AS nation_name,
  ROW_NUMBER() OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY "_s1".N_ROWS DESC, NATION.N_NAME) AS rank
FROM TPCH.NATION NATION
JOIN "_s1" "_s1"
  ON NATION.N_NATIONKEY = "_s1".C_NATIONKEY
ORDER BY
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
