SELECT
  PART.p_partkey AS key,
  REGION.r_name AS region,
  DENSE_RANK() OVER (PARTITION BY NATION.n_regionkey ORDER BY PART.p_size DESC, PART.p_container DESC, PART.p_type DESC) AS rank
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.n_regionkey = REGION.r_regionkey
JOIN TPCH.SUPPLIER SUPPLIER
  ON NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN TPCH.PARTSUPP PARTSUPP
  ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
JOIN TPCH.PART PART
  ON PART.p_partkey = PARTSUPP.ps_partkey
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 15 ROWS ONLY
