WITH "_t0" AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY C_ACCTBAL DESC, C_NAME) AS R,
    C_NAME
  FROM TPCH.CUSTOMER
)
SELECT
  C_NAME AS n,
  R AS r
FROM "_t0"
WHERE
  C_NAME LIKE '%0' AND R <= 30
