WITH "_u_0" AS (
  SELECT
    NATION.N_NATIONKEY AS "_u_1"
  FROM TPCH.NATION NATION
  JOIN TPCH.REGION REGION
    ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AFRICA'
  GROUP BY
    NATION.N_NATIONKEY
)
SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
LEFT JOIN "_u_0" "_u_0"
  ON SUPPLIER.S_NATIONKEY = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
