SELECT
  COUNT(*) AS n
FROM TPCH.CUSTOMER CUSTOMER
JOIN TPCH.NATION NATION
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'ASIA'
