SELECT
  COUNT(*) AS n
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN TPCH.REGION REGION
  ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'EUROPE'
