WITH _S3 AS (
  SELECT
    MEDIAN(CASE WHEN CUSTOMER.c_acctbal >= 0 THEN CUSTOMER.c_acctbal ELSE NULL END) AS MEDIAN_BLACK_ACCTBAL,
    MEDIAN(CUSTOMER.c_acctbal) AS MEDIAN_OVERALL_ACCTBAL,
    MEDIAN(CASE WHEN CUSTOMER.c_acctbal < 0 THEN CUSTOMER.c_acctbal ELSE NULL END) AS MEDIAN_RED_ACCTBAL,
    COUNT(CASE WHEN CUSTOMER.c_acctbal >= 0 THEN CUSTOMER.c_acctbal ELSE NULL END) AS N_BLACK_ACCTBAL,
    COUNT(CASE WHEN CUSTOMER.c_acctbal < 0 THEN CUSTOMER.c_acctbal ELSE NULL END) AS N_RED_ACCTBAL,
    NATION.n_regionkey AS REGION_KEY
  FROM TPCH.NATION AS NATION
  JOIN TPCH.CUSTOMER AS CUSTOMER
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
  GROUP BY
    NATION.n_regionkey
)
SELECT
  REGION.r_name AS region_name,
  _S3.N_RED_ACCTBAL AS n_red_acctbal,
  _S3.N_BLACK_ACCTBAL AS n_black_acctbal,
  _S3.MEDIAN_RED_ACCTBAL AS median_red_acctbal,
  _S3.MEDIAN_BLACK_ACCTBAL AS median_black_acctbal,
  _S3.MEDIAN_OVERALL_ACCTBAL AS median_overall_acctbal
FROM TPCH.REGION AS REGION
JOIN _S3 AS _S3
  ON REGION.r_regionkey = _S3.N_REGIONKEY
ORDER BY
  REGION.r_name NULLS FIRST
