WITH "_t" AS (
  SELECT
    CUSTOMER.C_CUSTKEY,
    NATION.N_REGIONKEY,
    ROW_NUMBER() OVER (
      PARTITION BY CUSTOMER.C_NATIONKEY
      ORDER BY CUSTOMER.C_ACCTBAL DESC, CUSTOMER.C_NAME
    ) AS "_w"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
), "_s3" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
), "_s5" AS (
  SELECT
    "_t".N_REGIONKEY,
    SUM("_s3".N_ROWS) AS SUM_N_ROWS
  FROM "_t" "_t"
  JOIN "_s3" "_s3"
    ON "_s3".O_CUSTKEY = "_t".C_CUSTKEY
  WHERE
    "_t"."_w" = 1
  GROUP BY
    "_t".N_REGIONKEY
)
SELECT
  REGION.R_NAME AS region_name,
  COALESCE("_s5".SUM_N_ROWS, 0) AS n_orders
FROM TPCH.REGION REGION
LEFT JOIN "_s5" "_s5"
  ON REGION.R_REGIONKEY = "_s5".N_REGIONKEY
ORDER BY
  1 NULLS FIRST
