WITH "_t" AS (
  SELECT
    NATION.N_REGIONKEY,
    ORDERS.O_ORDERKEY,
    ROW_NUMBER() OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY ORDERS.O_ORDERDATE, ORDERS.O_ORDERKEY) AS "_w"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1992
), "_t_2" AS (
  SELECT
    LINEITEM.L_PARTKEY,
    "_t".N_REGIONKEY,
    ROW_NUMBER() OVER (
      PARTITION BY "_t".N_REGIONKEY
      ORDER BY LINEITEM.L_QUANTITY DESC, LINEITEM.L_LINENUMBER
    ) AS "_w"
  FROM "_t" "_t"
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1992
    AND LINEITEM.L_ORDERKEY = "_t".O_ORDERKEY
  WHERE
    "_t"."_w" = 1
), "_s9" AS (
  SELECT
    "_t".N_REGIONKEY,
    PART.P_NAME
  FROM "_t_2" "_t"
  JOIN TPCH.PART PART
    ON PART.P_PARTKEY = "_t".L_PARTKEY
  WHERE
    "_t"."_w" = 1
)
SELECT
  REGION.R_NAME AS region_name,
  "_s9".P_NAME AS part_name
FROM TPCH.REGION REGION
LEFT JOIN "_s9" "_s9"
  ON REGION.R_REGIONKEY = "_s9".N_REGIONKEY
ORDER BY
  1 NULLS FIRST
