WITH "_t1" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    NATION.N_REGIONKEY,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (
            PARTITION BY NATION.N_REGIONKEY
            ORDER BY CASE WHEN CUSTOMER.C_ACCTBAL >= 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END DESC NULLS LAST
          ) - 1.0
        ) - (
          (
            COUNT(CASE WHEN CUSTOMER.C_ACCTBAL >= 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END) OVER (PARTITION BY NATION.N_REGIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CASE WHEN CUSTOMER.C_ACCTBAL >= 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END
      ELSE NULL
    END AS EXPR_5,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY CUSTOMER.C_ACCTBAL DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(CUSTOMER.C_ACCTBAL) OVER (PARTITION BY NATION.N_REGIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CUSTOMER.C_ACCTBAL
      ELSE NULL
    END AS EXPR_6,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (
            PARTITION BY NATION.N_REGIONKEY
            ORDER BY CASE WHEN CUSTOMER.C_ACCTBAL < 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END DESC NULLS LAST
          ) - 1.0
        ) - (
          (
            COUNT(CASE WHEN CUSTOMER.C_ACCTBAL < 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END) OVER (PARTITION BY NATION.N_REGIONKEY) - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN CASE WHEN CUSTOMER.C_ACCTBAL < 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END
      ELSE NULL
    END AS EXPR_7
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
), "_s3" AS (
  SELECT
    N_REGIONKEY,
    AVG(EXPR_5) AS AVG_EXPR_5,
    AVG(EXPR_6) AS AVG_EXPR_6,
    AVG(EXPR_7) AS AVG_EXPR_7,
    COUNT(CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END) AS COUNT_NEGATIVE_ACCTBAL,
    COUNT(CASE WHEN C_ACCTBAL >= 0 THEN C_ACCTBAL ELSE NULL END) AS COUNT_NON_NEGATIVE_ACCTBAL
  FROM "_t1"
  GROUP BY
    N_REGIONKEY
)
SELECT
  REGION.R_NAME AS region_name,
  "_s3".COUNT_NEGATIVE_ACCTBAL AS n_red_acctbal,
  "_s3".COUNT_NON_NEGATIVE_ACCTBAL AS n_black_acctbal,
  "_s3".AVG_EXPR_7 AS median_red_acctbal,
  "_s3".AVG_EXPR_5 AS median_black_acctbal,
  "_s3".AVG_EXPR_6 AS median_overall_acctbal
FROM TPCH.REGION REGION
JOIN "_s3" "_s3"
  ON REGION.R_REGIONKEY = "_s3".N_REGIONKEY
ORDER BY
  1 NULLS FIRST
