WITH "_s3" AS (
  SELECT
    PS_SUPPKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.PARTSUPP
  GROUP BY
    PS_SUPPKEY
), "_t" AS (
  SELECT
    SUPPLIER.S_NAME,
    NTILE(1000) OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY "_s3".N_ROWS, SUPPLIER.S_NAME) AS "_w"
  FROM TPCH.NATION NATION
  JOIN TPCH.SUPPLIER SUPPLIER
    ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
  JOIN "_s3" "_s3"
    ON SUPPLIER.S_SUPPKEY = "_s3".PS_SUPPKEY
)
SELECT
  S_NAME AS name
FROM "_t"
WHERE
  "_w" = 1000
