SELECT
  COUNT(*) AS n
FROM tpch.CUSTOMER AS CUSTOMER
JOIN tpch.NATION AS NATION
  ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'CHINA'
JOIN tpch.REGION AS REGION
  ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'ASIA'
