SELECT
  COUNT(DISTINCT NATION.n_nationkey) AS n
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'ASIA'
WHERE
  NATION.n_name = 'CHINA'
