SELECT
  COUNT(*) AS n
FROM tpch.ORDERS AS ORDERS
JOIN tpch.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey AND CUSTOMER.c_mktsegment = 'AUTOMOBILE'
WHERE
  ORDERS.o_orderstatus = 'F'
