WITH "_t0" AS (
  SELECT
    O_CUSTKEY AS C_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) = 1994
    AND O_ORDERPRIORITY = '1-URGENT'
  GROUP BY
    O_CUSTKEY
)
SELECT
  MIN(C_CUSTKEY) AS min_k,
  MAX(C_CUSTKEY) AS max_k,
  SUM(N_ROWS) AS n
FROM "_t0"
