WITH "_u_0" AS (
  SELECT
    C_NATIONKEY AS "_u_1"
  FROM TPCH.CUSTOMER
  WHERE
    C_MKTSEGMENT = 'BUILDING'
  GROUP BY
    C_NATIONKEY
)
SELECT
  COUNT(*) AS n
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'EUROPE'
LEFT JOIN "_u_0" "_u_0"
  ON NATION.N_NATIONKEY = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
