WITH "_u_0" AS (
  SELECT
    O_CUSTKEY AS "_u_1"
  FROM TPCH.ORDERS
  WHERE
    O_CLERK = 'Clerk#000000470' AND O_TOTALPRICE = 252004.18
  GROUP BY
    O_CUSTKEY
)
SELECT
  ANY_VALUE(CUSTOMER.C_NAME) AS any_customer
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_u_0" "_u_0"
  ON CUSTOMER.C_CUSTKEY = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
