WITH "_t" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    CUSTOMER.C_NAME,
    NATION.N_NAME,
    REGION.R_NAME,
    ROW_NUMBER() OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY CUSTOMER.C_ACCTBAL DESC, CUSTOMER.C_NAME) AS "_w"
  FROM TPCH.REGION REGION
  JOIN TPCH.NATION NATION
    ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
)
SELECT
  R_NAME AS region_name,
  N_NAME AS nation_name,
  C_NAME AS customer_name,
  C_ACCTBAL AS balance
FROM "_t"
WHERE
  "_w" = 1
