WITH "_t" AS (
  SELECT
    CUSTOMER.C_CUSTKEY,
    ROW_NUMBER() OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY CUSTOMER.C_ACCTBAL DESC) AS "_w"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
)
SELECT
  C_CUSTKEY AS "key"
FROM "_t"
WHERE
  "_w" = 1
