WITH "_T" AS (
  SELECT
    CUSTOMER.c_custkey AS C_CUSTKEY,
    ROW_NUMBER() OVER (PARTITION BY NATION.n_regionkey ORDER BY CUSTOMER.c_acctbal DESC) AS "_W"
  FROM TPCH.NATION NATION
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
)
SELECT
  C_CUSTKEY AS key
FROM "_T"
WHERE
  "_W" = 1
