WITH "_S3" AS (
  SELECT
    CUSTOMER.c_custkey AS C_CUSTKEY,
    MAX(CUSTOMER.c_phone) AS MAX_C_PHONE
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
  GROUP BY
    CUSTOMER.c_custkey
)
SELECT
  ORDERS.o_orderkey AS "key",
  "_S3".MAX_C_PHONE AS x
FROM TPCH.ORDERS ORDERS
LEFT JOIN "_S3" "_S3"
  ON ORDERS.o_custkey = "_S3".C_CUSTKEY
ORDER BY
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
