SELECT
  ANY_VALUE(NATION.N_NAME) AS name,
  VAR_POP(SUPPLIER.S_ACCTBAL) AS var,
  STDDEV_POP(SUPPLIER.S_ACCTBAL) AS std,
  CASE
    WHEN COUNT(SUPPLIER.S_ACCTBAL) < 2
    THEN NULL
    ELSE VARIANCE(SUPPLIER.S_ACCTBAL)
  END AS sample_var,
  CASE
    WHEN COUNT(SUPPLIER.S_ACCTBAL) < 2
    THEN NULL
    ELSE STDDEV(SUPPLIER.S_ACCTBAL)
  END AS sample_std,
  VAR_POP(SUPPLIER.S_ACCTBAL) AS pop_var,
  STDDEV_POP(SUPPLIER.S_ACCTBAL) AS pop_std
FROM TPCH.NATION NATION
JOIN TPCH.SUPPLIER SUPPLIER
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
WHERE
  NATION.N_NAME IN ('ALGERIA', 'ARGENTINA')
GROUP BY
  SUPPLIER.S_NATIONKEY
