WITH "_t1" AS (
  SELECT
    C_ACCTBAL,
    C_CUSTKEY,
    C_MKTSEGMENT,
    C_NATIONKEY
  FROM TPCH.CUSTOMER
  WHERE
    C_ACCTBAL > 9990
)
SELECT
  COUNT(*) AS n_pairs
FROM "_t1" "_t1"
JOIN "_t1" "_t2"
  ON "_t1".C_CUSTKEY < "_t2".C_CUSTKEY
  AND "_t1".C_MKTSEGMENT = "_t2".C_MKTSEGMENT
  AND "_t1".C_NATIONKEY = "_t2".C_NATIONKEY
