WITH "_s3" AS (
  SELECT
    PART.P_PARTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.PART PART
  JOIN TPCH.PART PART_2
    ON ABS(PART_2.P_RETAILPRICE - PART.P_RETAILPRICE) < 5.0
    AND PART.P_BRAND = PART_2.P_BRAND
    AND PART.P_MFGR = PART_2.P_MFGR
    AND PART.P_PARTKEY < PART_2.P_PARTKEY
    AND PART_2.P_NAME LIKE '%tomato%'
  WHERE
    PART.P_BRAND = 'Brand#35'
    AND PART.P_MFGR = 'Manufacturer#3'
    AND PART.P_NAME LIKE '%tomato%'
  GROUP BY
    PART.P_PARTKEY
)
SELECT
  PART.P_PARTKEY AS original_part_key,
  COALESCE("_s3".N_ROWS, 0) AS n_other_parts
FROM TPCH.PART PART
LEFT JOIN "_s3" "_s3"
  ON PART.P_PARTKEY = "_s3".P_PARTKEY
WHERE
  PART.P_BRAND = 'Brand#35'
  AND PART.P_MFGR = 'Manufacturer#3'
  AND PART.P_NAME LIKE '%tomato%'
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
