WITH "_s0" AS (
  SELECT
    O_ORDERDATE
  FROM TPCH.ORDERS
), "_s1" AS (
  SELECT
    MIN(O_ORDERDATE) AS MIN_O_ORDERDATE
  FROM "_s0"
)
SELECT
  COUNT(*) AS n
FROM "_s0" "_s0"
JOIN "_s1" "_s1"
  ON "_s0".O_ORDERDATE = "_s1".MIN_O_ORDERDATE
