WITH "_t1" AS (
  SELECT
    R_NAME
  FROM TPCH.REGION
), "_s0" AS (
  SELECT DISTINCT
    CASE WHEN R_NAME LIKE '%A%' THEN 'A' ELSE '*' END AS A
  FROM "_t1"
), "_s1" AS (
  SELECT DISTINCT
    CASE WHEN R_NAME LIKE '%E%' THEN 'E' ELSE '*' END AS E
  FROM "_t1"
), "_s3" AS (
  SELECT DISTINCT
    CASE WHEN R_NAME LIKE '%I%' THEN 'I' ELSE '*' END AS I
  FROM "_t1"
), "_s5" AS (
  SELECT DISTINCT
    CASE WHEN R_NAME LIKE '%O%' THEN 'O' ELSE '*' END AS O
  FROM "_t1"
)
SELECT
  "_s0".A AS a,
  "_s1".E AS e,
  "_s3".I AS i,
  "_s5".O AS o
FROM "_s0" "_s0"
CROSS JOIN "_s1" "_s1"
CROSS JOIN "_s3" "_s3"
CROSS JOIN "_s5" "_s5"
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST,
  4 NULLS FIRST
