WITH _S0 AS (
  SELECT
    o_orderdate AS O_ORDERDATE
  FROM TPCH.ORDERS
), _S1 AS (
  SELECT
    MIN(O_ORDERDATE) AS MIN_O_ORDERDATE
  FROM _S0
)
SELECT
  COUNT(*) AS n
FROM _S0 _S0
JOIN _S1 _S1
  ON _S0.O_ORDERDATE = _S1.MIN_O_ORDERDATE
