WITH "_S0" AS (
  SELECT
    r_name AS R_NAME,
    r_regionkey AS R_REGIONKEY
  FROM TPCH.REGION
), "_S1" AS (
  SELECT
    n_name AS N_NAME,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
)
SELECT
  "_S1".N_NAME AS n1,
  "_S5".N_NAME AS n2
FROM "_S0" "_S0"
JOIN "_S1" "_S1"
  ON "_S0".R_REGIONKEY = "_S1".N_REGIONKEY
JOIN "_S0" "_S3"
  ON "_S0".R_NAME = "_S3".R_NAME
JOIN "_S1" "_S5"
  ON "_S1".N_NAME <> "_S5".N_NAME AND "_S3".R_REGIONKEY = "_S5".N_REGIONKEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
