WITH "_s4" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s5" AS (
  SELECT
    "_s0".R_REGIONKEY,
    COUNT(*) AS N_ROWS
  FROM "_s4" "_s0"
  JOIN "_s4" "_s1"
    ON "_s0".R_NAME <> "_s1".R_NAME
  JOIN TPCH.NATION NATION
    ON NATION.N_REGIONKEY = "_s1".R_REGIONKEY
    AND SUBSTR(NATION.N_NAME, 1, 1) = SUBSTR("_s0".R_NAME, 1, 1)
  GROUP BY
    "_s0".R_REGIONKEY
)
SELECT
  "_s4".R_NAME AS region_name,
  COALESCE("_s5".N_ROWS, 0) AS n_other_nations
FROM "_s4" "_s4"
LEFT JOIN "_s5" "_s5"
  ON "_s4".R_REGIONKEY = "_s5".R_REGIONKEY
ORDER BY
  1 NULLS FIRST
