WITH "_S0" AS (
  SELECT
    r_name AS R_NAME,
    r_regionkey AS R_REGIONKEY
  FROM TPCH.REGION
), "_S3" AS (
  SELECT
    n_nationkey AS N_NATIONKEY,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
), "_S15" AS (
  SELECT
    "_S13".R_NAME,
    SUPPLIER.s_suppkey AS S_SUPPKEY
  FROM TPCH.SUPPLIER SUPPLIER
  JOIN "_S3" "_S11"
    ON SUPPLIER.s_nationkey = "_S11".N_NATIONKEY
  JOIN "_S0" "_S13"
    ON "_S11".N_REGIONKEY = "_S13".R_REGIONKEY
  WHERE
    SUPPLIER.s_acctbal < 0
)
SELECT
  ANY_VALUE("_S0".R_NAME) AS supplier_region,
  ANY_VALUE("_S1".R_NAME) AS customer_region,
  COUNT(*) AS region_combinations
FROM "_S0" "_S0"
CROSS JOIN "_S0" "_S1"
JOIN "_S3" "_S3"
  ON "_S1".R_REGIONKEY = "_S3".N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_mktsegment = 'AUTOMOBILE' AND CUSTOMER.c_nationkey = "_S3".N_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.c_custkey = ORDERS.o_custkey AND ORDERS.o_clerk = 'Clerk#000000007'
JOIN TPCH.LINEITEM LINEITEM
  ON EXTRACT(MONTH FROM CAST(LINEITEM.l_shipdate AS DATETIME)) = 3
  AND EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATETIME)) = 1998
  AND LINEITEM.l_orderkey = ORDERS.o_orderkey
JOIN "_S15" "_S15"
  ON LINEITEM.l_suppkey = "_S15".S_SUPPKEY AND "_S0".R_NAME = "_S15".R_NAME
GROUP BY
  "_S1".R_REGIONKEY,
  "_S0".R_REGIONKEY
