WITH _T1 AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY sbcustname) AS RANK,
    AVG(ABS(COALESCE(CAST(sbcustpostalcode AS BIGINT), 0))) OVER () AS RAVG1,
    COALESCE(
      AVG(ABS(COALESCE(CAST(sbcustpostalcode AS BIGINT), 0))) OVER (ORDER BY sbcustname ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),
      0.1
    ) AS RAVG2,
    COUNT(CAST(sbcustpostalcode AS BIGINT)) OVER () AS RCNT1,
    COALESCE(
      COUNT(CAST(sbcustpostalcode AS BIGINT)) OVER (ORDER BY sbcustname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
      0.1
    ) AS RCNT2,
    COUNT(*) OVER () AS RSIZ1,
    COALESCE(
      COUNT(*) OVER (ORDER BY sbcustname ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING),
      0.1
    ) AS RSIZ2,
    SUM(ABS(COALESCE(CAST(sbcustpostalcode AS BIGINT), 0))) OVER () AS RSUM1,
    COALESCE(
      SUM(ABS(COALESCE(CAST(sbcustpostalcode AS BIGINT), 0))) OVER (ORDER BY sbcustname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
      0.1
    ) AS RSUM2,
    sbcustpostalcode AS SBCUSTPOSTALCODE
  FROM MAIN.SBCUSTOMER
)
SELECT
  TRUE AS s00,
  TRUE AS s01,
  FALSE AS s02,
  FALSE AS s03,
  FALSE AS s04,
  FALSE AS s05,
  COUNT(*) >= 3 AS s06,
  FALSE AS s07,
  COUNT(*) <= 6 AS s08,
  FALSE AS s09,
  91 AS s10,
  0 AS s11,
  50 AS s12,
  35 AS s13,
  25.0 AS s14,
  ABS(COUNT(*) * -0.75) AS s15,
  10 AS s16,
  COUNT(*) AS s17,
  COUNT(*) AS s18,
  FALSE AS s19,
  TRUE AS s20,
  FALSE AS s21,
  TRUE AS s22,
  FALSE AS s23,
  TRUE AS s24,
  PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY
    ABS(CAST(SBCUSTPOSTALCODE AS BIGINT))) AS s25,
  MEDIAN(ABS(CAST(SBCUSTPOSTALCODE AS BIGINT))) AS s26,
  MIN(RANK) AS s27,
  MAX(RANK) AS s28,
  ANY_VALUE(RSUM1) AS s29,
  ROUND(SUM(RSUM2), 2) AS s30,
  ANY_VALUE(RAVG1) AS s31,
  ROUND(SUM(RAVG2), 2) AS s32,
  ANY_VALUE(RCNT1) AS s33,
  ROUND(SUM(RCNT2), 2) AS s34,
  ANY_VALUE(RSIZ1) AS s35,
  ROUND(SUM(RSIZ2), 2) AS s36
FROM _T1
