WITH _t1 AS (
  SELECT
    sbtxdatetime
  FROM main.sbtransaction
  WHERE
    EXTRACT(YEAR FROM CAST(sbtxdatetime AS DATETIME)) = 2023
  QUALIFY
    ROW_NUMBER() OVER (ORDER BY sbtxdatetime DESC NULLS FIRST) = 1
    OR ROW_NUMBER() OVER (ORDER BY sbtxdatetime NULLS LAST) = 1
)
SELECT
  sbtxdatetime AS date_time,
  DATE_ADD(DATE_TRUNC('WEEK', CAST(sbtxdatetime AS TIMESTAMP)), -8, 'WEEK') AS s00,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s01,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (1, 2, 3) AS s02,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (4, 5, 6) AS s03,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (7, 8, 9) AS s04,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (10, 11, 12) AS s05,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s06,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s07,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) < 4 AS s08,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) < 7 AS s09,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) < 10 AS s10,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s11,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s12,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) <= 3 AS s13,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) <= 6 AS s14,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) <= 9 AS s15,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s16,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s17,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) > 3 AS s18,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) > 6 AS s19,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) > 9 AS s20,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s21,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s22,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) >= 4 AS s23,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) >= 7 AS s24,
  EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) >= 10 AS s25,
  CASE WHEN NOT sbtxdatetime IS NULL THEN FALSE ELSE NULL END AS s26,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s27,
  NOT EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (1, 2, 3) AS s28,
  NOT EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (4, 5, 6) AS s29,
  NOT EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (7, 8, 9) AS s30,
  NOT EXTRACT(MONTH FROM CAST(sbtxdatetime AS DATETIME)) IN (10, 11, 12) AS s31,
  CASE WHEN NOT sbtxdatetime IS NULL THEN TRUE ELSE NULL END AS s32
FROM _t1
