WITH "_s0" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s3" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
), "_s15" AS (
  SELECT
    "_s13".R_NAME,
    SUPPLIER.S_SUPPKEY
  FROM TPCH.SUPPLIER SUPPLIER
  JOIN "_s3" "_s11"
    ON SUPPLIER.S_NATIONKEY = "_s11".N_NATIONKEY
  JOIN "_s0" "_s13"
    ON "_s11".N_REGIONKEY = "_s13".R_REGIONKEY
  WHERE
    SUPPLIER.S_ACCTBAL < 0
)
SELECT
  ANY_VALUE("_s0".R_NAME) AS supplier_region,
  ANY_VALUE("_s1".R_NAME) AS customer_region,
  COUNT(*) AS region_combinations
FROM "_s0" "_s0"
CROSS JOIN "_s0" "_s1"
JOIN "_s3" "_s3"
  ON "_s1".R_REGIONKEY = "_s3".N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_MKTSEGMENT = 'AUTOMOBILE' AND CUSTOMER.C_NATIONKEY = "_s3".N_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND ORDERS.O_CLERK = 'Clerk#000000007'
JOIN TPCH.LINEITEM LINEITEM
  ON EXTRACT(MONTH FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 3
  AND EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1998
  AND LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN "_s15" "_s15"
  ON LINEITEM.L_SUPPKEY = "_s15".S_SUPPKEY AND "_s0".R_NAME = "_s15".R_NAME
GROUP BY
  "_s1".R_REGIONKEY,
  "_s0".R_REGIONKEY
