WITH "_T1" AS (
  SELECT
    p_container AS P_CONTAINER,
    p_size AS P_SIZE
  FROM TPCH.PART
  WHERE
    p_container LIKE 'LG%'
), "_S6" AS (
  SELECT DISTINCT
    P_SIZE
  FROM "_T1"
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
), "_S0" AS (
  SELECT DISTINCT
    P_SIZE
  FROM "_T1"
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
), "_T4" AS (
  SELECT
    ORDERS.o_orderpriority AS O_ORDERPRIORITY,
    "_S0".P_SIZE,
    SUM(LINEITEM.l_quantity) AS SUM_L_QUANTITY
  FROM "_S0" "_S0"
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(MONTH FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1
    AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1998
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.l_discount = 0
    AND LINEITEM.l_orderkey = ORDERS.o_orderkey
    AND LINEITEM.l_shipmode = 'SHIP'
    AND LINEITEM.l_tax = 0
  JOIN TPCH.PART PART
    ON LINEITEM.l_partkey = PART.p_partkey
    AND PART.p_container LIKE 'LG%'
    AND PART.p_size = "_S0".P_SIZE
  GROUP BY
    ORDERS.o_orderpriority,
    "_S0".P_SIZE
), "_T" AS (
  SELECT
    O_ORDERPRIORITY,
    P_SIZE,
    SUM_L_QUANTITY,
    ROW_NUMBER() OVER (PARTITION BY P_SIZE ORDER BY CASE
      WHEN (
        NOT SUM_L_QUANTITY IS NULL AND SUM_L_QUANTITY > 0
      )
      THEN NVL(SUM_L_QUANTITY, 0)
      ELSE NULL
    END DESC) AS "_W"
  FROM "_T4"
), "_S7" AS (
  SELECT
    CASE
      WHEN (
        NOT SUM_L_QUANTITY IS NULL AND SUM_L_QUANTITY > 0
      )
      THEN NVL(SUM_L_QUANTITY, 0)
      ELSE NULL
    END AS TOTAL_QTY,
    O_ORDERPRIORITY,
    P_SIZE
  FROM "_T"
  WHERE
    "_W" = 1
)
SELECT
  "_S6".P_SIZE AS part_size,
  "_S7".O_ORDERPRIORITY AS best_order_priority,
  "_S7".TOTAL_QTY AS best_order_priority_qty
FROM "_S6" "_S6"
LEFT JOIN "_S7" "_S7"
  ON "_S6".P_SIZE = "_S7".P_SIZE
ORDER BY
  1 NULLS FIRST
