WITH "_s1" AS (
  SELECT
    N_NAME,
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
)
SELECT
  ANY_VALUE("_s1".N_NAME) AS supplier_nation,
  ANY_VALUE("_s5".N_NAME) AS customer_nation,
  COUNT(*) AS nation_combinations
FROM TPCH.REGION REGION
JOIN "_s1" "_s1"
  ON REGION.R_REGIONKEY = "_s1".N_REGIONKEY
JOIN TPCH.REGION REGION_2
  ON REGION_2.R_NAME = 'AMERICA'
JOIN "_s1" "_s5"
  ON REGION_2.R_REGIONKEY = "_s5".N_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_ACCTBAL < 0 AND CUSTOMER.C_NATIONKEY = "_s5".N_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
  AND EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 4
  AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1992
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY AND LINEITEM.L_SHIPMODE = 'SHIP'
JOIN TPCH.SUPPLIER SUPPLIER
  ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
  AND SUPPLIER.S_NATIONKEY = "_s1".N_NATIONKEY
WHERE
  REGION.R_NAME = 'ASIA'
GROUP BY
  REGION_2.R_REGIONKEY,
  "_s5".N_NATIONKEY,
  "_s1".N_NATIONKEY,
  REGION.R_REGIONKEY
