WITH "_S5" AS (
  SELECT
    NATION.n_regionkey AS N_REGIONKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.NATION NATION
  CROSS JOIN (VALUES
    (NULL)) AS "_Q_1"("_COL_0")
  WHERE
    SUBSTR(NATION.n_name, 1, 1) IN ('A', 'B', 'C')
  GROUP BY
    NATION.n_regionkey
)
SELECT
  REGION.r_name AS region_name,
  'foo' AS x,
  COALESCE("_S5".N_ROWS, 0) AS n
FROM TPCH.REGION REGION
CROSS JOIN (VALUES
  (NULL)) AS "_Q_0"("_COL_0")
LEFT JOIN "_S5" "_S5"
  ON REGION.r_regionkey = "_S5".N_REGIONKEY
ORDER BY
  1 NULLS FIRST
