WITH "_s0" AS (
  SELECT
    R_NAME
  FROM TPCH.REGION
)
SELECT
  "_s0".R_NAME AS r1,
  "_s1".R_NAME AS r2
FROM "_s0" "_s0"
JOIN "_s0" "_s1"
  ON "_s0".R_NAME <> "_s1".R_NAME
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
