WITH "_s0" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s1" AS (
  SELECT
    N_NAME,
    N_REGIONKEY
  FROM TPCH.NATION
)
SELECT
  "_s1".N_NAME AS n1,
  "_s5".N_NAME AS n2
FROM "_s0" "_s0"
JOIN "_s1" "_s1"
  ON "_s0".R_REGIONKEY = "_s1".N_REGIONKEY
JOIN "_s0" "_s3"
  ON "_s0".R_NAME = "_s3".R_NAME
JOIN "_s1" "_s5"
  ON "_s1".N_NAME <> "_s5".N_NAME AND "_s3".R_REGIONKEY = "_s5".N_REGIONKEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
