WITH "_t1" AS (
  SELECT
    P_CONTAINER,
    P_SIZE
  FROM TPCH.PART
  WHERE
    P_CONTAINER LIKE 'LG%'
), "_s6" AS (
  SELECT DISTINCT
    P_SIZE
  FROM "_t1"
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
), "_s0" AS (
  SELECT DISTINCT
    P_SIZE
  FROM "_t1"
  ORDER BY
    1 NULLS FIRST
  FETCH FIRST 10 ROWS ONLY
), "_t4" AS (
  SELECT
    ORDERS.O_ORDERPRIORITY,
    "_s0".P_SIZE,
    SUM(LINEITEM.L_QUANTITY) AS SUM_L_QUANTITY
  FROM "_s0" "_s0"
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1998
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_DISCOUNT = 0
    AND LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
    AND LINEITEM.L_SHIPMODE = 'SHIP'
    AND LINEITEM.L_TAX = 0
  JOIN TPCH.PART PART
    ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
    AND PART.P_CONTAINER LIKE 'LG%'
    AND PART.P_SIZE = "_s0".P_SIZE
  GROUP BY
    ORDERS.O_ORDERPRIORITY,
    "_s0".P_SIZE
), "_t" AS (
  SELECT
    O_ORDERPRIORITY,
    P_SIZE,
    SUM_L_QUANTITY,
    ROW_NUMBER() OVER (
      PARTITION BY P_SIZE
      ORDER BY CASE
        WHEN COALESCE(SUM_L_QUANTITY, 0) > 0
        THEN COALESCE(SUM_L_QUANTITY, 0)
        ELSE NULL
      END DESC
    ) AS "_w"
  FROM "_t4"
), "_s7" AS (
  SELECT
    CASE
      WHEN (
        NOT SUM_L_QUANTITY IS NULL AND SUM_L_QUANTITY > 0
      )
      THEN COALESCE(SUM_L_QUANTITY, 0)
      ELSE NULL
    END AS TOTAL_QTY,
    O_ORDERPRIORITY,
    P_SIZE
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  "_s6".P_SIZE AS part_size,
  "_s7".O_ORDERPRIORITY AS best_order_priority,
  "_s7".TOTAL_QTY AS best_order_priority_qty
FROM "_s6" "_s6"
LEFT JOIN "_s7" "_s7"
  ON "_s6".P_SIZE = "_s7".P_SIZE
ORDER BY
  1 NULLS FIRST
