WITH "_s5" AS (
  SELECT
    NATION.N_REGIONKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.NATION NATION
  CROSS JOIN (VALUES
    (NULL)) AS "_1"("_COL_0")
  WHERE
    SUBSTR(NATION.N_NAME, 1, 1) IN ('A', 'B', 'C')
  GROUP BY
    NATION.N_REGIONKEY
)
SELECT
  REGION.R_NAME AS region_name,
  'foo' AS x,
  COALESCE("_s5".N_ROWS, 0) AS n
FROM TPCH.REGION REGION
CROSS JOIN (VALUES
  (NULL)) AS "_0"("_COL_0")
LEFT JOIN "_s5" "_s5"
  ON REGION.R_REGIONKEY = "_s5".N_REGIONKEY
ORDER BY
  1 NULLS FIRST
