SELECT
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE VARIANCE(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END)
  END AS var_samp_0_nnull,
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE VARIANCE(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END)
  END AS var_samp_1_nnull,
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE VARIANCE(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END)
  END AS var_samp_2_nnull,
  VAR_POP(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END) AS var_pop_0_nnull,
  VAR_POP(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END) AS var_pop_1_nnull,
  VAR_POP(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END) AS var_pop_2_nnull,
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE STDDEV(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END)
  END AS std_samp_0_nnull,
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE STDDEV(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END)
  END AS std_samp_1_nnull,
  CASE
    WHEN COUNT(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END) < 2
    THEN NULL
    ELSE STDDEV(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END)
  END AS std_samp_2_nnull,
  STDDEV_POP(CASE WHEN C_CUSTKEY > 3 THEN C_ACCTBAL ELSE NULL END) AS std_pop_0_nnull,
  STDDEV_POP(CASE WHEN C_CUSTKEY > 2 THEN C_ACCTBAL ELSE NULL END) AS std_pop_1_nnull,
  STDDEV_POP(CASE WHEN C_CUSTKEY > 1 THEN C_ACCTBAL ELSE NULL END) AS std_pop_2_nnull
FROM TPCH.CUSTOMER
WHERE
  C_CUSTKEY IN (1, 2, 3)
