WITH "_s2" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s3" AS (
  SELECT
    "_s0".R_REGIONKEY,
    COUNT(*) AS N_ROWS
  FROM "_s2" "_s0"
  JOIN TPCH.REGION REGION
    ON REGION.R_NAME <> "_s0".R_NAME
    AND SUBSTR(REGION.R_NAME, 1, 1) = SUBSTR("_s0".R_NAME, 1, 1)
  GROUP BY
    "_s0".R_REGIONKEY
)
SELECT
  "_s2".R_NAME AS region_name,
  COALESCE("_s3".N_ROWS, 0) AS n_other_regions
FROM "_s2" "_s2"
LEFT JOIN "_s3" "_s3"
  ON "_s2".R_REGIONKEY = "_s3".R_REGIONKEY
ORDER BY
  1 NULLS FIRST
