WITH "_s0" AS (
  SELECT DISTINCT
    O_ORDERPRIORITY
  FROM TPCH.ORDERS
), "_s1" AS (
  SELECT DISTINCT
    C_MKTSEGMENT
  FROM TPCH.CUSTOMER
)
SELECT
  "_s0".O_ORDERPRIORITY AS order_priority,
  "_s1".C_MKTSEGMENT AS market_segment
FROM "_s0" "_s0"
CROSS JOIN "_s1" "_s1"
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
