WITH "_S3" AS (
  SELECT
    l_partkey AS L_PARTKEY,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(l_shipdate AS DATE)) = 1994
), "_T4" AS (
  SELECT
    PARTSUPP.ps_suppkey AS PS_SUPPKEY,
    ANY_VALUE(PART.p_name) AS ANYTHING_P_NAME,
    COUNT("_S3".L_SUPPKEY) AS COUNT_L_SUPPKEY
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN TPCH.PART PART
    ON PART.p_brand = 'Brand#13' AND PART.p_partkey = PARTSUPP.ps_partkey
  LEFT JOIN "_S3" "_S3"
    ON PARTSUPP.ps_partkey = "_S3".L_PARTKEY AND PARTSUPP.ps_suppkey = "_S3".L_SUPPKEY
  GROUP BY
    PARTSUPP.ps_partkey,
    PARTSUPP.ps_suppkey
), "_T" AS (
  SELECT
    PS_SUPPKEY,
    ANYTHING_P_NAME,
    COUNT_L_SUPPKEY,
    ROW_NUMBER() OVER (PARTITION BY PS_SUPPKEY ORDER BY COALESCE(COUNT_L_SUPPKEY, 0) DESC, ANYTHING_P_NAME) AS "_W"
  FROM "_T4"
), "_S5" AS (
  SELECT
    COALESCE(COUNT_L_SUPPKEY, 0) AS N_ORDERS,
    ANYTHING_P_NAME,
    PS_SUPPKEY
  FROM "_T"
  WHERE
    "_W" = 1
)
SELECT
  SUPPLIER.s_name AS supplier_name,
  "_S5".ANYTHING_P_NAME AS part_name,
  "_S5".N_ORDERS AS n_orders
FROM TPCH.SUPPLIER SUPPLIER
LEFT JOIN "_S5" "_S5"
  ON SUPPLIER.s_suppkey = "_S5".PS_SUPPKEY
WHERE
  SUPPLIER.s_nationkey = 20
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
