WITH "_t3" AS (
  SELECT
    P_BRAND,
    P_CONTAINER,
    P_PARTKEY
  FROM TPCH.PART
  WHERE
    P_BRAND = 'Brand#13'
), "_t" AS (
  SELECT
    LINEITEM.L_SHIPDATE,
    "_t7".P_PARTKEY,
    ROW_NUMBER() OVER (
      PARTITION BY "_t7".P_CONTAINER
      ORDER BY LINEITEM.L_EXTENDEDPRICE DESC, LINEITEM.L_SHIPDATE
    ) AS "_w"
  FROM "_t3" "_t7"
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_PARTKEY = "_t7".P_PARTKEY
    AND LINEITEM.L_SHIPMODE = 'RAIL'
    AND LINEITEM.L_TAX = 0
), "_s3" AS (
  SELECT
    P_PARTKEY,
    ANY_VALUE(L_SHIPDATE) AS ANYTHING_L_SHIPDATE,
    COUNT(*) AS N_ROWS
  FROM "_t"
  WHERE
    "_w" = 1
  GROUP BY
    P_PARTKEY
), "_t1" AS (
  SELECT
    "_t3".P_CONTAINER,
    MAX("_s3".ANYTHING_L_SHIPDATE) AS MAX_ANYTHING_L_SHIPDATE,
    SUM("_s3".N_ROWS) AS SUM_N_ROWS
  FROM "_t3" "_t3"
  LEFT JOIN "_s3" "_s3"
    ON "_s3".P_PARTKEY = "_t3".P_PARTKEY
  GROUP BY
    "_t3".P_CONTAINER
)
SELECT
  P_CONTAINER AS container,
  MAX_ANYTHING_L_SHIPDATE AS highest_price_ship_date
FROM "_t1"
WHERE
  SUM_N_ROWS <> 0
ORDER BY
  2 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
