WITH "_s3" AS (
  SELECT
    CUSTOMER.C_NATIONKEY,
    ORDERS.O_ORDERKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND ORDERS.O_ORDERKEY = 454791
  WHERE
    CUSTOMER.C_CUSTKEY = 1
)
SELECT
  NATION.N_NAME AS name,
  "_s3".O_ORDERKEY AS okey
FROM TPCH.NATION NATION
LEFT JOIN "_s3" "_s3"
  ON NATION.N_NATIONKEY = "_s3".C_NATIONKEY
