WITH "_s1" AS (
  SELECT
    N_NAME,
    N_REGIONKEY
  FROM TPCH.NATION
  WHERE
    N_NATIONKEY = 4
)
SELECT
  REGION.R_NAME AS name,
  "_s1".N_NAME AS nation_4_name
FROM TPCH.REGION REGION
LEFT JOIN "_s1" "_s1"
  ON REGION.R_REGIONKEY = "_s1".N_REGIONKEY
