WITH "_t" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE,
    ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_TOTALPRICE DESC) AS "_w"
  FROM TPCH.ORDERS
  WHERE
    O_ORDERPRIORITY = '1-URGENT'
), "_s1" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  CUSTOMER.C_NAME AS name
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
WHERE
  CUSTOMER.C_NATIONKEY = 6
ORDER BY
  COALESCE("_s1".O_ORDERDATE, TO_DATE('2000-01-01', 'YYYY-MM-DD'))
FETCH FIRST 5 ROWS ONLY
