WITH "_s0" AS (
  SELECT
    C_CUSTKEY,
    C_NAME
  FROM TPCH.CUSTOMER
  ORDER BY
    2 NULLS FIRST
  FETCH FIRST 5 ROWS ONLY
), "_t" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE,
    ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_TOTALPRICE DESC) AS "_w"
  FROM TPCH.ORDERS
), "_s1" AS (
  SELECT
    O_CUSTKEY,
    O_ORDERDATE
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  "_s0".C_NAME AS name
FROM "_s0" "_s0"
LEFT JOIN "_s1" "_s1"
  ON "_s0".C_CUSTKEY = "_s1".O_CUSTKEY
ORDER BY
  "_s1".O_ORDERDATE
