WITH "_s3" AS (
  SELECT
    L_PARTKEY,
    L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(L_SHIPDATE AS DATE)) = 1994
), "_t4" AS (
  SELECT
    PARTSUPP.PS_SUPPKEY,
    ANY_VALUE(PART.P_NAME) AS ANYTHING_P_NAME,
    COUNT("_s3".L_SUPPKEY) AS COUNT_L_SUPPKEY
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN TPCH.PART PART
    ON PART.P_BRAND = 'Brand#13' AND PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
  LEFT JOIN "_s3" "_s3"
    ON PARTSUPP.PS_PARTKEY = "_s3".L_PARTKEY AND PARTSUPP.PS_SUPPKEY = "_s3".L_SUPPKEY
  GROUP BY
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY
), "_t" AS (
  SELECT
    PS_SUPPKEY,
    ANYTHING_P_NAME,
    COUNT_L_SUPPKEY,
    ROW_NUMBER() OVER (
      PARTITION BY PS_SUPPKEY
      ORDER BY COALESCE(CASE WHEN COUNT_L_SUPPKEY <> 0 THEN COUNT_L_SUPPKEY ELSE NULL END, 0) DESC, ANYTHING_P_NAME
    ) AS "_w"
  FROM "_t4"
), "_s5" AS (
  SELECT
    COALESCE(COUNT_L_SUPPKEY, 0) AS N_ORDERS,
    ANYTHING_P_NAME,
    PS_SUPPKEY
  FROM "_t"
  WHERE
    "_w" = 1
)
SELECT
  SUPPLIER.S_NAME AS supplier_name,
  "_s5".ANYTHING_P_NAME AS part_name,
  "_s5".N_ORDERS AS n_orders
FROM TPCH.SUPPLIER SUPPLIER
LEFT JOIN "_s5" "_s5"
  ON SUPPLIER.S_SUPPKEY = "_s5".PS_SUPPKEY
WHERE
  SUPPLIER.S_NATIONKEY = 20
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
