WITH "_S3" AS (
  SELECT
    CUSTOMER.c_nationkey AS C_NATIONKEY,
    ORDERS.o_orderkey AS O_ORDERKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey AND ORDERS.o_orderkey = 454791
  WHERE
    CUSTOMER.c_custkey = 1
)
SELECT
  NATION.n_name AS name,
  "_S3".O_ORDERKEY AS okey
FROM TPCH.NATION NATION
LEFT JOIN "_S3" "_S3"
  ON NATION.n_nationkey = "_S3".C_NATIONKEY
