WITH "_t" AS (
  SELECT
    LINEITEM.L_RECEIPTDATE,
    LINEITEM.L_SUPPKEY,
    ORDERS.O_CUSTKEY,
    ROW_NUMBER() OVER (
      PARTITION BY ORDERS.O_CUSTKEY
      ORDER BY LINEITEM.L_RECEIPTDATE, LINEITEM.L_EXTENDEDPRICE * (
        1 - LINEITEM.L_DISCOUNT
      ) DESC
    ) AS "_w"
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
  WHERE
    ORDERS.O_CLERK = 'Clerk#000000017'
)
SELECT
  CUSTOMER.C_NAME AS name,
  "_t".L_RECEIPTDATE AS receipt_date,
  NATION.N_NAME AS nation_name
FROM TPCH.CUSTOMER CUSTOMER
JOIN "_t" "_t"
  ON CUSTOMER.C_CUSTKEY = "_t".O_CUSTKEY AND "_t"."_w" = 1
JOIN TPCH.SUPPLIER SUPPLIER
  ON SUPPLIER.S_SUPPKEY = "_t".L_SUPPKEY
JOIN TPCH.NATION NATION
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
WHERE
  CUSTOMER.C_NATIONKEY = 4
ORDER BY
  2 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
