SELECT
  O_ORDERKEY AS "key",
  NVL(EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)), '') || '_' || NVL(FLOOR((
    EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) - 1
  ) / 3) + 1, '') || '_' || NVL(EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)), '') || '_' || NVL(EXTRACT(DAY FROM CAST(O_ORDERDATE AS DATE)), '') AS a,
  NVL(
    CASE
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 1
      THEN 'Sunday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 2
      THEN 'Monday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 3
      THEN 'Tuesday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 4
      THEN 'Wednesday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 5
      THEN 'Thursday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 6
      THEN 'Friday'
      WHEN TO_CHAR(O_ORDERDATE, 'D') = 7
      THEN 'Saturday'
    END,
    ''
  ) || ':' || NVL((
    MOD((
      TO_CHAR(O_ORDERDATE, 'D') + -1
    ), 7)
  ), '') AS b,
  ADD_MONTHS(TRUNC(CAST(O_ORDERDATE AS DATE), 'YEAR'), 6) - NUMTODSINTERVAL(13, 'day') AS c,
  ADD_MONTHS(TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'Q'), 12) + NUMTODSINTERVAL(25, 'hour') AS d,
  TO_DATE('2025-01-01 12:35:00', 'YYYY-MM-DD HH24:MI:SS') AS e,
  TO_DATE('2025-07-22 12:00:00', 'YYYY-MM-DD HH24:MI:SS') AS f,
  TO_DATE('2025-01-01', 'YYYY-MM-DD') AS g,
  12 || ';' || 20 || ';' || 6 AS h,
  EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(YEAR FROM TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS')) AS i,
  (
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(YEAR FROM TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS'))
  ) * 4 + (
    FLOOR((
      EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) - 1
    ) / 3) - FLOOR(
      (
        EXTRACT(MONTH FROM TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS')) - 1
      ) / 3
    )
  ) AS j,
  (
    EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(YEAR FROM TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS'))
  ) * 12 + (
    EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) - EXTRACT(MONTH FROM TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS'))
  ) AS k,
  FLOOR(
    (
      TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(CAST(TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS') AS DATE), 'DD') + (
        MOD(
          (
            TO_CHAR(TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS'), 'D') + -1
          ),
          7
        )
      ) - (
        MOD((
          TO_CHAR(CAST(O_ORDERDATE AS DATE), 'D') + -1
        ), 7)
      )
    ) / 7
  ) AS l,
  TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'DD') - TRUNC(CAST(TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS') AS DATE), 'DD') AS m,
  (
    TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'HH24') - TRUNC(CAST(TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS') AS DATE), 'HH24')
  ) * 24 AS n,
  (
    TRUNC(CAST(CAST(O_ORDERDATE AS DATE) AS DATE), 'MI') - TRUNC(CAST(TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS') AS DATE), 'MI')
  ) * 1440 AS o,
  (
    CAST(O_ORDERDATE AS DATE) - TO_DATE('1993-05-25 12:45:36', 'YYYY-MM-DD HH24:MI:SS')
  ) * 86400 AS p,
  TRUNC(
    CAST(CAST(O_ORDERDATE AS DATE) - MOD((
      TO_CHAR(CAST(O_ORDERDATE AS DATE), 'D') + -1
    ), 7) AS DATE),
    'DD'
  ) AS q,
  NVL(TO_CHAR(O_ORDERDATE, 'Mon'), '') || ':' || NVL(TO_CHAR(ADD_MONTHS(CAST(O_ORDERDATE AS DATE), 3), 'Mon'), '') || ':' || NVL(TO_CHAR(ADD_MONTHS(CAST(O_ORDERDATE AS DATE), -2), 'Mon'), '') AS r
FROM TPCH.ORDERS
WHERE
  O_CLERK LIKE '%5' AND O_COMMENT LIKE '%fo%' AND O_ORDERPRIORITY LIKE '3%'
ORDER BY
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
