WITH "_t1" AS (
  SELECT
    C_ACCTBAL,
    C_MKTSEGMENT,
    C_NAME,
    CASE
      WHEN FLOOR(0.8 * COUNT(C_ACCTBAL) OVER ()) < ROW_NUMBER() OVER (ORDER BY C_ACCTBAL DESC NULLS LAST)
      THEN C_ACCTBAL
      ELSE NULL
    END AS EXPR_30,
    CASE
      WHEN ABS(
        (
          ROW_NUMBER() OVER (ORDER BY C_ACCTBAL DESC NULLS LAST) - 1.0
        ) - (
          (
            COUNT(C_ACCTBAL) OVER () - 1.0
          ) / 2.0
        )
      ) < 1.0
      THEN C_ACCTBAL
      ELSE NULL
    END AS EXPR_31
  FROM TPCH.CUSTOMER
)
SELECT
  COUNT(*) AS a,
  COALESCE(SUM(FLOOR(C_ACCTBAL)), 0) AS b,
  COALESCE(SUM(CEIL(C_ACCTBAL)), 0) AS c,
  COUNT(DISTINCT C_MKTSEGMENT) AS d,
  ROUND(AVG(ABS(C_ACCTBAL)), 4) AS e,
  MIN(C_ACCTBAL) AS f,
  MAX(C_ACCTBAL) AS g,
  ANY_VALUE(SUBSTR(C_NAME, 1, 1)) AS h,
  COUNT(CASE WHEN C_ACCTBAL > 0 THEN C_ACCTBAL ELSE NULL END) AS i,
  CEIL(VAR_POP(CASE WHEN C_ACCTBAL > 0 THEN C_ACCTBAL ELSE NULL END)) AS j,
  ROUND(
    CASE
      WHEN COUNT(CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END) < 2
      THEN NULL
      ELSE VARIANCE(CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END)
    END,
    4
  ) AS k,
  FLOOR(STDDEV_POP(CASE WHEN C_ACCTBAL < 0 THEN C_ACCTBAL ELSE NULL END)) AS l,
  ROUND(
    CASE
      WHEN COUNT(CASE WHEN C_ACCTBAL > 0 THEN C_ACCTBAL ELSE NULL END) < 2
      THEN NULL
      ELSE STDDEV(CASE WHEN C_ACCTBAL > 0 THEN C_ACCTBAL ELSE NULL END)
    END,
    4
  ) AS m,
  ROUND(AVG(COALESCE(CASE WHEN C_ACCTBAL > 0 THEN C_ACCTBAL ELSE NULL END, 0)), 2) AS n,
  SUM(NOT CASE WHEN C_ACCTBAL > 1000 THEN C_ACCTBAL ELSE NULL END IS NULL) AS o,
  SUM(CASE WHEN C_ACCTBAL > 1000 THEN C_ACCTBAL ELSE NULL END IS NULL) AS p,
  MAX(EXPR_30) AS q,
  AVG(EXPR_31) AS r
FROM "_t1"
