SELECT
  o_orderkey AS key,
  CONCAT_WS(
    '_',
    EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(QUARTER FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(DAY FROM CAST(o_orderdate AS TIMESTAMP))
  ) AS a,
  CONCAT_WS(
    ':',
    CASE
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 0
      THEN 'Sunday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 1
      THEN 'Monday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 2
      THEN 'Tuesday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 3
      THEN 'Wednesday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 4
      THEN 'Thursday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 5
      THEN 'Friday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 6
      THEN 'Saturday'
    END,
    EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP))
  ) AS b,
  DATE_TRUNC('YEAR', CAST(o_orderdate AS TIMESTAMP)) + INTERVAL '6 MONTH' - INTERVAL '13 DAY' AS c,
  DATE_TRUNC('QUARTER', CAST(o_orderdate AS TIMESTAMP)) + INTERVAL '1 YEAR' + INTERVAL '25 HOUR' AS d,
  CAST('2025-01-01 12:35:00' AS TIMESTAMP) AS e,
  CAST('2025-07-22 12:00:00' AS TIMESTAMP) AS f,
  CAST('2025-01-01' AS DATE) AS g,
  CONCAT_WS(';', 12, 20, 6) AS h,
  EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)) - EXTRACT(YEAR FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP)) AS i,
  (
    EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)) - EXTRACT(YEAR FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  ) * 4 + (
    EXTRACT(QUARTER FROM CAST(o_orderdate AS TIMESTAMP)) - EXTRACT(QUARTER FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  ) AS j,
  (
    EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)) - EXTRACT(YEAR FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  ) * 12 + (
    EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)) - EXTRACT(MONTH FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  ) AS k,
  CAST(CAST((
    CAST(o_orderdate AS DATE) - CAST(CAST('1993-05-25 12:45:36' AS TIMESTAMP) AS DATE) + EXTRACT(DOW FROM CAST('1993-05-25 12:45:36' AS TIMESTAMP)) - EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP))
  ) AS DOUBLE PRECISION) / 7 AS BIGINT) AS l,
  CAST(o_orderdate AS DATE) - CAST(CAST('1993-05-25 12:45:36' AS TIMESTAMP) AS DATE) AS m,
  CAST(CAST(EXTRACT(EPOCH FROM (
    DATE_TRUNC('HOUR', o_orderdate) - DATE_TRUNC('HOUR', CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  )) AS DOUBLE PRECISION) / 3600 AS BIGINT) AS n,
  CAST(CAST(EXTRACT(EPOCH FROM (
    DATE_TRUNC('MINUTE', o_orderdate) - DATE_TRUNC('MINUTE', CAST('1993-05-25 12:45:36' AS TIMESTAMP))
  )) AS DOUBLE PRECISION) / 60 AS BIGINT) AS o,
  EXTRACT(EPOCH FROM (
    CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)
  )) AS p,
  DATE_TRUNC(
    'DAY',
    CAST(o_orderdate AS TIMESTAMP) - CAST(EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) || ' days' AS INTERVAL)
  ) AS q
FROM tpch.orders
WHERE
  o_clerk LIKE '%5' AND o_comment LIKE '%fo%' AND o_orderpriority LIKE '3%'
ORDER BY
  1 NULLS FIRST
LIMIT 5
