SELECT
  CUSTOMER.c_custkey AS `key`,
  ROW_NUMBER() OVER (ORDER BY CASE WHEN CUSTOMER.c_acctbal IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_acctbal, CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS a,
  ROW_NUMBER() OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CASE WHEN CUSTOMER.c_acctbal IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_acctbal, CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS b,
  RANK() OVER (ORDER BY CASE WHEN CUSTOMER.c_mktsegment COLLATE utf8mb4_bin IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_mktsegment COLLATE utf8mb4_bin) AS c,
  DENSE_RANK() OVER (ORDER BY CASE WHEN CUSTOMER.c_mktsegment COLLATE utf8mb4_bin IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_mktsegment COLLATE utf8mb4_bin) AS d,
  NTILE(100) OVER (ORDER BY CASE WHEN CUSTOMER.c_acctbal IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_acctbal, CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS e,
  NTILE(12) OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CASE WHEN CUSTOMER.c_acctbal IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_acctbal, CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS f,
  LAG(CUSTOMER.c_custkey, 1) OVER (ORDER BY CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS g,
  LAG(CUSTOMER.c_custkey, 2, -1) OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS h,
  LEAD(CUSTOMER.c_custkey, 1) OVER (ORDER BY CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS i,
  LEAD(CUSTOMER.c_custkey, 6000) OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CASE WHEN CUSTOMER.c_custkey IS NULL THEN 1 ELSE 0 END, CUSTOMER.c_custkey) AS j,
  SUM(CUSTOMER.c_acctbal) OVER (PARTITION BY CUSTOMER.c_nationkey) AS k,
  SUM(CUSTOMER.c_acctbal) OVER (ORDER BY CUSTOMER.c_custkey ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS l,
  ROUND(AVG(CUSTOMER.c_acctbal) OVER (), 2) AS m,
  ROUND(
    AVG(CUSTOMER.c_acctbal) OVER (PARTITION BY CUSTOMER.c_nationkey ORDER BY CUSTOMER.c_custkey ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),
    2
  ) AS n,
  COUNT(CASE WHEN CUSTOMER.c_acctbal > 0 THEN CUSTOMER.c_acctbal ELSE NULL END) OVER () AS o,
  COUNT(*) OVER () AS p
FROM tpch.NATION AS NATION
JOIN tpch.REGION AS REGION
  ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'ASIA'
JOIN tpch.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_nationkey = NATION.n_nationkey
ORDER BY
  CUSTOMER.c_custkey
LIMIT 10
