SELECT
  CUSTOMER.C_CUSTKEY AS "key",
  ROW_NUMBER() OVER (ORDER BY CUSTOMER.C_ACCTBAL, CUSTOMER.C_CUSTKEY) AS a,
  ROW_NUMBER() OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY CUSTOMER.C_ACCTBAL, CUSTOMER.C_CUSTKEY) AS b,
  RANK() OVER (ORDER BY CUSTOMER.C_MKTSEGMENT) AS c,
  DENSE_RANK() OVER (ORDER BY CUSTOMER.C_MKTSEGMENT) AS d,
  NTILE(100) OVER (ORDER BY CUSTOMER.C_ACCTBAL, CUSTOMER.C_CUSTKEY) AS e,
  NTILE(12) OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY CUSTOMER.C_ACCTBAL, CUSTOMER.C_CUSTKEY) AS f,
  LAG(CUSTOMER.C_CUSTKEY, 1) OVER (ORDER BY CUSTOMER.C_CUSTKEY) AS g,
  LAG(CUSTOMER.C_CUSTKEY, 2, 42) OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY CUSTOMER.C_CUSTKEY) AS h,
  LEAD(CUSTOMER.C_CUSTKEY, 1) OVER (ORDER BY CUSTOMER.C_CUSTKEY) AS i,
  LEAD(CUSTOMER.C_CUSTKEY, 6000) OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY CUSTOMER.C_CUSTKEY) AS j,
  SUM(CUSTOMER.C_ACCTBAL) OVER (PARTITION BY CUSTOMER.C_NATIONKEY) AS k,
  SUM(CUSTOMER.C_ACCTBAL) OVER (ORDER BY CUSTOMER.C_CUSTKEY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS l,
  ROUND(AVG(CAST(CUSTOMER.C_ACCTBAL AS DOUBLE PRECISION)) OVER (), 2) AS m,
  ROUND(
    AVG(CAST(CUSTOMER.C_ACCTBAL AS DOUBLE PRECISION)) OVER (
      PARTITION BY CUSTOMER.C_NATIONKEY
      ORDER BY CUSTOMER.C_CUSTKEY
      ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
    ),
    2
  ) AS n,
  COUNT(CASE WHEN CUSTOMER.C_ACCTBAL > 0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END) OVER () AS o,
  COUNT(*) OVER () AS p
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'ASIA'
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
ORDER BY
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
