SELECT
  o_orderkey AS key,
  CONCAT_WS(
    '_',
    EXTRACT(YEAR FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(QUARTER FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(MONTH FROM CAST(o_orderdate AS TIMESTAMP)),
    EXTRACT(DAY FROM CAST(o_orderdate AS TIMESTAMP))
  ) AS a,
  CONCAT_WS(
    ':',
    CASE
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 0
      THEN 'Sunday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 1
      THEN 'Monday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 2
      THEN 'Tuesday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 3
      THEN 'Wednesday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 4
      THEN 'Thursday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 5
      THEN 'Friday'
      WHEN EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP)) = 6
      THEN 'Saturday'
    END,
    EXTRACT(DOW FROM CAST(o_orderdate AS TIMESTAMP))
  ) AS b,
  DATE_TRUNC('YEAR', CAST(o_orderdate AS TIMESTAMP)) + INTERVAL '6 MONTH' - INTERVAL '13 DAY' AS c,
  DATE_TRUNC('QUARTER', CAST(o_orderdate AS TIMESTAMP)) + INTERVAL '1 YEAR' + INTERVAL '25 HOUR' AS d,
  DATE_TRUNC('MINUTE', CAST('2025-01-01 12:35:13' AS TIMESTAMP)) AS e,
  DATE_TRUNC('HOUR', CAST('2025-01-01 12:35:13' AS TIMESTAMP)) + INTERVAL '6 MONTH' + INTERVAL '3 WEEK' AS f,
  DATE_TRUNC('DAY', CAST('2025-01-01 12:35:13' AS TIMESTAMP)) AS g,
  CONCAT_WS(
    ';',
    EXTRACT(HOUR FROM CAST('2025-01-01 12:35:13' AS TIMESTAMP)),
    EXTRACT(MINUTE FROM CAST('2025-01-01 13:20:13' AS TIMESTAMP)),
    CAST(EXTRACT(SECOND FROM CAST('2025-01-01 12:35:06' AS TIMESTAMP)) AS BIGINT)
  ) AS h,
  CAST(EXTRACT(YEAR FROM AGE(CAST(o_orderdate AS TIMESTAMP), CAST('1993-05-25 12:45:36' AS TIMESTAMP))) AS BIGINT) AS i,
  EXTRACT(YEAR FROM AGE(CAST(o_orderdate AS TIMESTAMP), CAST('1993-05-25 12:45:36' AS TIMESTAMP))) * 4 + EXTRACT(MONTH FROM AGE(CAST(o_orderdate AS TIMESTAMP), CAST('1993-05-25 12:45:36' AS TIMESTAMP))) / 3 AS j,
  CAST(EXTRACT(YEAR FROM AGE(CAST(o_orderdate AS TIMESTAMP), CAST('1993-05-25 12:45:36' AS TIMESTAMP))) * 12 + EXTRACT(MONTH FROM AGE(CAST(o_orderdate AS TIMESTAMP), CAST('1993-05-25 12:45:36' AS TIMESTAMP))) AS BIGINT) AS k,
  EXTRACT(DAYS FROM (
    CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)
  )) / 7 AS l,
  EXTRACT(EPOCH FROM CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)) / 86400 AS m,
  EXTRACT(EPOCH FROM CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)) / 3600 AS n,
  EXTRACT(EPOCH FROM CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)) / 60 AS o,
  CAST(EXTRACT(EPOCH FROM CAST(o_orderdate AS TIMESTAMP) - CAST('1993-05-25 12:45:36' AS TIMESTAMP)) AS BIGINT) AS p,
  DATE_TRUNC('WEEK', CAST(o_orderdate AS TIMESTAMP)) AS q
FROM tpch.orders
WHERE
  o_clerk LIKE '%5' AND o_comment LIKE '%fo%' AND o_orderpriority LIKE '3%'
ORDER BY
  1 NULLS FIRST
LIMIT 5
