SELECT
  sbtxdatetime AS x,
  CAST('2025-05-02 11:00:00' AS TIMESTAMP) AS y1,
  CAST('2023-04-03 13:16:30' AS TIMESTAMP) AS y,
  DATE_DIFF(
    'YEAR',
    CAST(DATE_TRUNC('YEAR', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('YEAR', CAST('2025-05-02 11:00:00' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS years_diff,
  DATE_DIFF(
    'MONTH',
    CAST(DATE_TRUNC('MONTH', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('MONTH', CAST('2025-05-02 11:00:00' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS months_diff,
  DATE_DIFF(
    'DAY',
    CAST(DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('DAY', CAST('2025-05-02 11:00:00' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS days_diff,
  DATE_DIFF(
    'HOUR',
    CAST(DATE_TRUNC('HOUR', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('HOUR', CAST('2025-05-02 11:00:00' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS hours_diff,
  DATE_DIFF(
    'MINUTE',
    CAST(DATE_TRUNC('MINUTE', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('MINUTE', CAST('2023-04-03 13:16:30' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS minutes_diff,
  DATE_DIFF(
    'SECOND',
    CAST(DATE_TRUNC('SECOND', CAST(sbtxdatetime AS TIMESTAMP)) AS TIMESTAMP),
    CAST(DATE_TRUNC('SECOND', CAST('2023-04-03 13:16:30' AS TIMESTAMP)) AS TIMESTAMP)
  ) AS seconds_diff
FROM main.sbtransaction
WHERE
  YEAR(CAST(sbtxdatetime AS TIMESTAMP)) < 2025
ORDER BY
  4 NULLS FIRST
LIMIT 30
