SELECT
  SBTXDATETIME AS date_time,
  TRUNC(
    CAST(CAST(SBTXDATETIME AS DATE) - MOD((
      TO_CHAR(CAST(SBTXDATETIME AS DATE), 'D') + 3
    ), 7) AS DATE),
    'DD'
  ) AS sow,
  CASE
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 1
    THEN 'Sunday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 2
    THEN 'Monday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 3
    THEN 'Tuesday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 4
    THEN 'Wednesday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 5
    THEN 'Thursday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 6
    THEN 'Friday'
    WHEN TO_CHAR(SBTXDATETIME, 'D') = 7
    THEN 'Saturday'
  END AS dayname,
  (
    MOD((
      TO_CHAR(SBTXDATETIME, 'D') + 3
    ), 7)
  ) + 1 AS dayofweek
FROM MAIN.SBTRANSACTION
WHERE
  EXTRACT(DAY FROM CAST(SBTXDATETIME AS DATE)) > 1
  AND EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)) < 2025
