SELECT
  r_name AS name,
  GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS c1,
  GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS c2,
  GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS c3
FROM tpch.region
ORDER BY
  r_name
