WITH _t0 AS (
  SELECT
    GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS c1,
    GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS c2,
    GROUP_CONCAT(r_name, '-') OVER (ORDER BY r_name ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS c3,
    r_name
  FROM tpch.region
)
SELECT
  r_name AS name,
  c1,
  c2,
  c3
FROM _t0
ORDER BY
  r_name
