SELECT
  SUPPLIER.S_NAME AS name,
  REGION.R_NAME AS region_name,
  SUPPLIER.S_ACCTBAL - LAG(SUPPLIER.S_ACCTBAL, 1) OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY SUPPLIER.S_ACCTBAL) AS acctbal_delta
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
JOIN TPCH.SUPPLIER SUPPLIER
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
