WITH "_s7" AS (
  SELECT
    LINEITEM.L_QUANTITY,
    LINEITEM.L_SUPPKEY
  FROM TPCH.LINEITEM LINEITEM
  JOIN TPCH.PART PART
    ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
    AND PART.P_CONTAINER LIKE 'LG%'
    AND PART.P_NAME LIKE '%tomato%'
  WHERE
    EXTRACT(MONTH FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) < 7
    AND EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1995
    AND LINEITEM.L_SHIPMODE = 'SHIP'
), "_t0" AS (
  SELECT
    ANY_VALUE(NATION.N_NAME) AS ANYTHING_N_NAME,
    ANY_VALUE(SUPPLIER.S_NAME) AS ANYTHING_S_NAME,
    ANY_VALUE(SUPPLIER.S_NATIONKEY) AS ANYTHING_S_NATIONKEY,
    SUM("_s7".L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.NATION NATION
  JOIN TPCH.REGION REGION
    ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AFRICA'
  JOIN TPCH.SUPPLIER SUPPLIER
    ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
    AND SUPPLIER.S_ACCTBAL >= 8000.0
    AND SUPPLIER.S_COMMENT LIKE '%careful%'
  LEFT JOIN "_s7" "_s7"
    ON SUPPLIER.S_SUPPKEY = "_s7".L_SUPPKEY
  GROUP BY
    SUPPLIER.S_SUPPKEY
)
SELECT
  ANYTHING_S_NAME AS supplier_name,
  ANYTHING_N_NAME AS nation_name,
  COALESCE(SUM_L_QUANTITY, 0) AS supplier_quantity,
  (
    100.0 * COALESCE(SUM_L_QUANTITY, 0)
  ) / CASE
    WHEN SUM(COALESCE(SUM_L_QUANTITY, 0)) OVER (PARTITION BY ANYTHING_S_NATIONKEY) > 0
    THEN SUM(COALESCE(SUM_L_QUANTITY, 0)) OVER (PARTITION BY ANYTHING_S_NATIONKEY)
    ELSE NULL
  END AS national_qty_pct
FROM "_t0"
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
