WITH _S7 AS (
  SELECT
    LINEITEM.l_quantity AS L_QUANTITY,
    LINEITEM.l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM LINEITEM
  JOIN TPCH.PART PART
    ON LINEITEM.l_partkey = PART.p_partkey
    AND PART.p_container LIKE 'LG%'
    AND PART.p_name LIKE '%tomato%'
  WHERE
    EXTRACT(MONTH FROM CAST(LINEITEM.l_shipdate AS DATETIME)) < 7
    AND EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATETIME)) = 1995
    AND LINEITEM.l_shipmode = 'SHIP'
), _T0 AS (
  SELECT
    ANY_VALUE(NATION.n_name) AS ANYTHING_N_NAME,
    ANY_VALUE(SUPPLIER.s_name) AS ANYTHING_S_NAME,
    ANY_VALUE(SUPPLIER.s_nationkey) AS ANYTHING_S_NATIONKEY,
    SUM(_S7.L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.NATION NATION
  JOIN TPCH.REGION REGION
    ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'AFRICA'
  JOIN TPCH.SUPPLIER SUPPLIER
    ON NATION.n_nationkey = SUPPLIER.s_nationkey
    AND SUPPLIER.s_acctbal >= 8000.0
    AND SUPPLIER.s_comment LIKE '%careful%'
  LEFT JOIN _S7 _S7
    ON SUPPLIER.s_suppkey = _S7.L_SUPPKEY
  GROUP BY
    SUPPLIER.s_suppkey
)
SELECT
  ANYTHING_S_NAME AS supplier_name,
  ANYTHING_N_NAME AS nation_name,
  NVL(SUM_L_QUANTITY, 0) AS supplier_quantity,
  (
    100.0 * NVL(SUM_L_QUANTITY, 0)
  ) / CASE
    WHEN SUM(NVL(SUM_L_QUANTITY, 0)) OVER (PARTITION BY ANYTHING_S_NATIONKEY) > 0
    THEN SUM(NVL(SUM_L_QUANTITY, 0)) OVER (PARTITION BY ANYTHING_S_NATIONKEY)
    ELSE NULL
  END AS national_qty_pct
FROM _T0
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
