WITH "_s2" AS (
  SELECT
    L_PARTKEY,
    L_SUPPKEY,
    COUNT(*) AS N_ROWS,
    SUM(L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.LINEITEM
  WHERE
    EXTRACT(YEAR FROM CAST(L_SHIPDATE AS DATE)) = 1994 AND L_TAX = 0
  GROUP BY
    L_PARTKEY,
    L_SUPPKEY
), "_t" AS (
  SELECT
    "_s2".L_SUPPKEY,
    "_s2".N_ROWS,
    PART.P_NAME,
    "_s2".SUM_L_QUANTITY,
    ROW_NUMBER() OVER (PARTITION BY "_s2".L_SUPPKEY ORDER BY COALESCE("_s2".SUM_L_QUANTITY, 0) DESC) AS "_w"
  FROM "_s2" "_s2"
  JOIN TPCH.PART PART
    ON PART.P_PARTKEY = "_s2".L_PARTKEY
)
SELECT
  SUPPLIER.S_NAME AS supplier_name,
  "_t".P_NAME AS part_name,
  COALESCE("_t".SUM_L_QUANTITY, 0) AS total_quantity,
  "_t".N_ROWS AS n_shipments
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.N_NAME = 'FRANCE' AND NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN "_t" "_t"
  ON SUPPLIER.S_SUPPKEY = "_t".L_SUPPKEY AND "_t"."_w" = 1
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 3 ROWS ONLY
