SELECT
  CONDITIONS.DESCRIPTION AS condition_description
FROM MAIN.PATIENTS PATIENTS
JOIN MAIN.CONDITIONS CONDITIONS
  ON CONDITIONS.PATIENT = PATIENTS.PATIENT
WHERE
  PATIENTS.ETHNICITY = 'italian' AND PATIENTS.GENDER = 'F'
GROUP BY
  CONDITIONS.DESCRIPTION
ORDER BY
  COUNT(*) DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 1 ROWS ONLY
