SELECT
  CONDITIONS.description AS condition_description
FROM MAIN.PATIENTS PATIENTS
JOIN MAIN.CONDITIONS CONDITIONS
  ON CONDITIONS.patient = PATIENTS.patient
WHERE
  PATIENTS.ethnicity = 'italian' AND PATIENTS.gender = 'F'
GROUP BY
  CONDITIONS.description
ORDER BY
  COUNT(*) DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 1 ROWS ONLY
