WITH _S3 AS (
  SELECT
    COUNT(*) AS AGG_0,
    in_device_id AS DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
), _T0 AS (
  SELECT
    SUM(COALESCE(_S3.AGG_0, 0)) AS AGG_0,
    COUNT(*) AS AGG_1,
    PRODUCTS.pr_brand AS BRAND
  FROM MAIN.DEVICES AS DEVICES
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id
  LEFT JOIN _S3 AS _S3
    ON DEVICES.de_id = _S3.DEVICE_ID
  GROUP BY
    PRODUCTS.pr_brand
)
SELECT
  BRAND AS brand,
  ROUND(COALESCE(AGG_0, 0) / AGG_1, 2) AS ir
FROM _T0
ORDER BY
  BRAND NULLS FIRST
