WITH _S5 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    INCIDENTS.in_error_id AS IN_ERROR_ID
  FROM MAIN.INCIDENTS AS INCIDENTS
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id AND PRODUCTS.pr_name = 'Sun-Set'
  GROUP BY
    2
)
SELECT
  ERRORS.er_name AS error,
  ROUND((
    100.0 * COALESCE(_S5.N_ROWS, 0)
  ) / SUM(COALESCE(_S5.N_ROWS, 0)) OVER (), 2) AS pct
FROM MAIN.ERRORS AS ERRORS
LEFT JOIN _S5 AS _S5
  ON ERRORS.er_id = _S5.IN_ERROR_ID
ORDER BY
  2 DESC NULLS LAST
