WITH "_T2" AS (
  SELECT
    in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS
), "_S1" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM "_T2"
  GROUP BY
    IN_DEVICE_ID
), "_S3" AS (
  SELECT
    DEVICES.de_production_country_id AS DE_PRODUCTION_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM("_S1".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.DEVICES DEVICES
  LEFT JOIN "_S1" "_S1"
    ON DEVICES.de_id = "_S1".IN_DEVICE_ID
  GROUP BY
    DEVICES.de_production_country_id
), "_S5" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM "_T2"
  GROUP BY
    IN_DEVICE_ID
), "_S7" AS (
  SELECT
    DEVICES.de_purchase_country_id AS DE_PURCHASE_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM("_S5".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.DEVICES DEVICES
  LEFT JOIN "_S5" "_S5"
    ON DEVICES.de_id = "_S5".IN_DEVICE_ID
  GROUP BY
    DEVICES.de_purchase_country_id
), "_T5" AS (
  SELECT
    ANY_VALUE(USERS.us_country_id) AS ANYTHING_US_COUNTRY_ID,
    COUNT("_S11".IN_DEVICE_ID) AS COUNT_IN_DEVICE_ID
  FROM MAIN.USERS USERS
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.de_owner_id = USERS.us_id
  LEFT JOIN "_T2" "_S11"
    ON DEVICES.de_id = "_S11".IN_DEVICE_ID
  GROUP BY
    DEVICES.de_id
), "_S13" AS (
  SELECT
    ANYTHING_US_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM(COUNT_IN_DEVICE_ID) AS SUM_N_ROWS
  FROM "_T5"
  GROUP BY
    ANYTHING_US_COUNTRY_ID
)
SELECT
  COUNTRIES.co_name AS country_name,
  ROUND(COALESCE("_S3".SUM_N_ROWS, 0) / "_S3".N_ROWS, 2) AS made_ir,
  ROUND(COALESCE("_S7".SUM_N_ROWS, 0) / "_S7".N_ROWS, 2) AS sold_ir,
  ROUND(COALESCE("_S13".SUM_N_ROWS, 0) / COALESCE("_S13".N_ROWS, 0), 2) AS user_ir
FROM MAIN.COUNTRIES COUNTRIES
JOIN "_S3" "_S3"
  ON COUNTRIES.co_id = "_S3".DE_PRODUCTION_COUNTRY_ID
JOIN "_S7" "_S7"
  ON COUNTRIES.co_id = "_S7".DE_PURCHASE_COUNTRY_ID
LEFT JOIN "_S13" "_S13"
  ON COUNTRIES.co_id = "_S13".ANYTHING_US_COUNTRY_ID
ORDER BY
  1 NULLS FIRST
