WITH "_s1" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.COUNTRIES
)
SELECT
  COUNTRIES.CO_NAME AS name,
  "_s1".N_ROWS AS n_other_countries
FROM MAIN.COUNTRIES COUNTRIES
CROSS JOIN "_s1" "_s1"
ORDER BY
  1 NULLS FIRST
