WITH _S1 AS (
  SELECT
    COUNT(*) AS N_OTHER_COUNTRIES
  FROM MAIN.COUNTRIES
)
SELECT
  COUNTRIES.co_name AS name,
  _S1.N_OTHER_COUNTRIES AS n_other_countries
FROM MAIN.COUNTRIES AS COUNTRIES
CROSS JOIN _S1 AS _S1
ORDER BY
  COUNTRIES.co_name NULLS FIRST
