WITH _S0 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    de_product_id AS DE_PRODUCT_ID
  FROM MAIN.DEVICES
  GROUP BY
    de_product_id
), _S1 AS (
  SELECT
    pr_id AS PR_ID,
    pr_release AS PR_RELEASE
  FROM MAIN.PRODUCTS
), _S6 AS (
  SELECT
    YEAR(CAST(_S1.PR_RELEASE AS TIMESTAMP)) AS RELEASE_YEAR,
    SUM(_S0.N_ROWS) AS SUM_N_ROWS
  FROM _S0 AS _S0
  JOIN _S1 AS _S1
    ON _S0.DE_PRODUCT_ID = _S1.PR_ID
  GROUP BY
    YEAR(CAST(_S1.PR_RELEASE AS TIMESTAMP))
), _S7 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    YEAR(CAST(_S3.PR_RELEASE AS TIMESTAMP)) AS RELEASE_YEAR
  FROM MAIN.DEVICES AS DEVICES
  JOIN _S1 AS _S3
    ON DEVICES.de_product_id = _S3.PR_ID
  JOIN MAIN.INCIDENTS AS INCIDENTS
    ON DEVICES.de_id = INCIDENTS.in_device_id
  GROUP BY
    YEAR(CAST(_S3.PR_RELEASE AS TIMESTAMP))
)
SELECT
  _S6.RELEASE_YEAR AS year,
  ROUND(COALESCE(_S7.N_ROWS, 0) / _S6.SUM_N_ROWS, 2) AS ir
FROM _S6 AS _S6
LEFT JOIN _S7 AS _S7
  ON _S6.RELEASE_YEAR = _S7.RELEASE_YEAR
ORDER BY
  _S6.RELEASE_YEAR NULLS FIRST
