WITH "_s0" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS
), "_s1" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES
)
SELECT
  ROUND("_s0".N_ROWS / "_s1".N_ROWS, 2) AS ir
FROM "_s0" "_s0"
CROSS JOIN "_s1" "_s1"
