WITH "_t2" AS (
  SELECT
    IN_DEVICE_ID
  FROM MAIN.INCIDENTS
), "_s1" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM "_t2"
  GROUP BY
    IN_DEVICE_ID
), "_s3" AS (
  SELECT
    DEVICES.DE_PRODUCTION_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM("_s1".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.DEVICES DEVICES
  LEFT JOIN "_s1" "_s1"
    ON DEVICES.DE_ID = "_s1".IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_PRODUCTION_COUNTRY_ID
), "_s5" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM "_t2"
  GROUP BY
    IN_DEVICE_ID
), "_s7" AS (
  SELECT
    DEVICES.DE_PURCHASE_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM("_s5".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.DEVICES DEVICES
  LEFT JOIN "_s5" "_s5"
    ON DEVICES.DE_ID = "_s5".IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_PURCHASE_COUNTRY_ID
), "_t5" AS (
  SELECT
    ANY_VALUE(USERS.US_COUNTRY_ID) AS ANYTHING_US_COUNTRY_ID,
    COUNT("_s11".IN_DEVICE_ID) AS COUNT_IN_DEVICE_ID
  FROM MAIN.USERS USERS
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_OWNER_ID = USERS.US_ID
  LEFT JOIN "_t2" "_s11"
    ON DEVICES.DE_ID = "_s11".IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_ID
), "_s13" AS (
  SELECT
    ANYTHING_US_COUNTRY_ID,
    COUNT(*) AS N_ROWS,
    SUM(COUNT_IN_DEVICE_ID) AS SUM_N_ROWS
  FROM "_t5"
  GROUP BY
    ANYTHING_US_COUNTRY_ID
)
SELECT
  COUNTRIES.CO_NAME AS country_name,
  ROUND(COALESCE("_s3".SUM_N_ROWS, 0) / "_s3".N_ROWS, 2) AS made_ir,
  ROUND(COALESCE("_s7".SUM_N_ROWS, 0) / "_s7".N_ROWS, 2) AS sold_ir,
  ROUND(COALESCE("_s13".SUM_N_ROWS, 0) / COALESCE("_s13".N_ROWS, 0), 2) AS user_ir
FROM MAIN.COUNTRIES COUNTRIES
JOIN "_s3" "_s3"
  ON COUNTRIES.CO_ID = "_s3".DE_PRODUCTION_COUNTRY_ID
JOIN "_s7" "_s7"
  ON COUNTRIES.CO_ID = "_s7".DE_PURCHASE_COUNTRY_ID
LEFT JOIN "_s13" "_s13"
  ON COUNTRIES.CO_ID = "_s13".ANYTHING_US_COUNTRY_ID
ORDER BY
  1 NULLS FIRST
