WITH _S0 AS (
  SELECT
    COUNT(*) AS AGG_0
  FROM MAIN.INCIDENTS
), _S1 AS (
  SELECT
    COUNT(*) AS AGG_1
  FROM MAIN.DEVICES
)
SELECT
  ROUND(_S0.AGG_0 / _S1.AGG_1, 2) AS ir
FROM _S0 AS _S0
CROSS JOIN _S1 AS _S1
