WITH "_s1" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS
  GROUP BY
    IN_DEVICE_ID
), "_s3" AS (
  SELECT
    DEVICES.DE_PRODUCT_ID,
    COUNT(*) AS N_ROWS,
    SUM("_s1".N_ROWS) AS SUM_N_ROWS
  FROM MAIN.DEVICES DEVICES
  LEFT JOIN "_s1" "_s1"
    ON DEVICES.DE_ID = "_s1".IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_PRODUCT_ID
)
SELECT
  PRODUCTS.PR_NAME AS product,
  PRODUCTS.PR_BRAND AS product_brand,
  PRODUCTS.PR_TYPE AS product_type,
  ROUND(COALESCE("_s3".SUM_N_ROWS, 0) / "_s3".N_ROWS, 2) AS ir
FROM MAIN.PRODUCTS PRODUCTS
JOIN "_s3" "_s3"
  ON PRODUCTS.PR_ID = "_s3".DE_PRODUCT_ID
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
