WITH _S7 AS (
  SELECT
    COUNT(*) AS AGG_0,
    INCIDENTS.in_device_id AS DEVICE_ID
  FROM MAIN.INCIDENTS AS INCIDENTS
  JOIN MAIN.ERRORS AS ERRORS
    ON ERRORS.er_id = INCIDENTS.in_error_id AND ERRORS.er_name = 'Battery Failure'
  GROUP BY
    INCIDENTS.in_device_id
), _T1 AS (
  SELECT
    SUM(COALESCE(_S7.AGG_0, 0)) AS AGG_0,
    COUNT(*) AS AGG_1,
    COUNTRIES.co_name AS COUNTRY_NAME,
    PRODUCTS.pr_name AS PRODUCT_NAME
  FROM MAIN.COUNTRIES AS COUNTRIES
  JOIN MAIN.DEVICES AS DEVICES
    ON COUNTRIES.co_id = DEVICES.de_production_country_id
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id
  LEFT JOIN _S7 AS _S7
    ON DEVICES.de_id = _S7.DEVICE_ID
  GROUP BY
    COUNTRIES.co_name,
    PRODUCTS.pr_name
)
SELECT
  COUNTRY_NAME AS country_name,
  PRODUCT_NAME AS product_name,
  ROUND(COALESCE(AGG_0, 0) / AGG_1, 2) AS ir
FROM _T1
ORDER BY
  IR DESC NULLS LAST,
  PRODUCT_NAME NULLS FIRST,
  COUNTRY_NAME NULLS FIRST
LIMIT 5
