WITH _T3 AS (
  SELECT
    in_device_id AS DEVICE_ID
  FROM MAIN.INCIDENTS
), _S1 AS (
  SELECT
    COUNT(*) AS AGG_9,
    DEVICE_ID
  FROM _T3
  GROUP BY
    DEVICE_ID
), _S3 AS (
  SELECT
    COUNT(*) AS AGG_1,
    SUM(_S1.AGG_9) AS AGG_11,
    DEVICES.de_production_country_id AS FACTORY_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  LEFT JOIN _S1 AS _S1
    ON DEVICES.de_id = _S1.DEVICE_ID
  GROUP BY
    DEVICES.de_production_country_id
), _S5 AS (
  SELECT
    COUNT(*) AS AGG_12,
    DEVICE_ID
  FROM _T3
  GROUP BY
    DEVICE_ID
), _S7 AS (
  SELECT
    SUM(_S5.AGG_12) AS AGG_14,
    COUNT(*) AS AGG_3,
    DEVICES.de_purchase_country_id AS STORE_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  LEFT JOIN _S5 AS _S5
    ON DEVICES.de_id = _S5.DEVICE_ID
  GROUP BY
    DEVICES.de_purchase_country_id
), _S11 AS (
  SELECT
    COUNT(*) AS AGG_6,
    DEVICE_ID
  FROM _T3
  GROUP BY
    DEVICE_ID
), _S13 AS (
  SELECT
    COUNT(*) AS AGG_5,
    SUM(_S11.AGG_6) AS AGG_8,
    USERS.us_country_id AS COUNTRY_ID
  FROM MAIN.USERS AS USERS
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_owner_id = USERS.us_id
  LEFT JOIN _S11 AS _S11
    ON DEVICES.de_id = _S11.DEVICE_ID
  GROUP BY
    USERS.us_country_id
)
SELECT
  COUNTRIES.co_name AS country_name,
  ROUND(COALESCE(_S3.AGG_11, 0) / _S3.AGG_1, 2) AS made_ir,
  ROUND(COALESCE(_S7.AGG_14, 0) / _S7.AGG_3, 2) AS sold_ir,
  ROUND(COALESCE(_S13.AGG_8, 0) / COALESCE(_S13.AGG_5, 0), 2) AS user_ir
FROM MAIN.COUNTRIES AS COUNTRIES
JOIN _S3 AS _S3
  ON COUNTRIES.co_id = _S3.FACTORY_COUNTRY_ID
JOIN _S7 AS _S7
  ON COUNTRIES.co_id = _S7.STORE_COUNTRY_ID
LEFT JOIN _S13 AS _S13
  ON COUNTRIES.co_id = _S13.COUNTRY_ID
ORDER BY
  COUNTRY_NAME NULLS FIRST
