WITH "_t2" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
  WHERE
    EXTRACT(YEAR FROM CAST(CA_DT AS DATE)) IN (2020, 2021)
), "_t5" AS (
  SELECT
    CO_ID,
    CO_NAME
  FROM MAIN.COUNTRIES
  WHERE
    CO_NAME = 'CN'
), "_s7" AS (
  SELECT
    "_t4".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_t2" "_t4"
  JOIN MAIN.CALENDAR CALENDAR
    ON CALENDAR.CA_DT >= ADD_MONTHS(CAST("_t4".CA_DT AS DATE), -6)
  JOIN MAIN.DEVICES DEVICES
    ON CALENDAR.CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  JOIN "_t5" "_t5"
    ON DEVICES.DE_PRODUCTION_COUNTRY_ID = "_t5".CO_ID
  GROUP BY
    "_t4".CA_DT
), "_s15" AS (
  SELECT
    "_t7".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_t2" "_t7"
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_t7".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  JOIN "_t5" "_t8"
    ON DEVICES.DE_PRODUCTION_COUNTRY_ID = "_t8".CO_ID
  GROUP BY
    "_t7".CA_DT
), "_t0" AS (
  SELECT
    EXTRACT(MONTH FROM CAST("_t2".CA_DT AS DATE)) AS MONTH_CA_DT,
    EXTRACT(YEAR FROM CAST("_t2".CA_DT AS DATE)) AS YEAR_CA_DT,
    SUM("_s7".N_ROWS) AS SUM_EXPR_3,
    SUM("_s15".N_ROWS) AS SUM_N_ROWS
  FROM "_t2" "_t2"
  LEFT JOIN "_s7" "_s7"
    ON "_s7".CA_DT = "_t2".CA_DT
  LEFT JOIN "_s15" "_s15"
    ON "_s15".CA_DT = "_t2".CA_DT
  GROUP BY
    EXTRACT(MONTH FROM CAST("_t2".CA_DT AS DATE)),
    EXTRACT(YEAR FROM CAST("_t2".CA_DT AS DATE))
)
SELECT
  NVL(YEAR_CA_DT, '') || '-' || NVL(LPAD(MONTH_CA_DT, 2, '0'), '') AS month,
  ROUND((
    1000000.0 * COALESCE(SUM_N_ROWS, 0)
  ) / COALESCE(SUM_EXPR_3, 0), 2) AS ir
FROM "_t0"
ORDER BY
  MONTH_CA_DT NULLS FIRST
