WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    2
)
SELECT
  PRODUCTS.pr_brand AS brand,
  ROUND(COALESCE(SUM(_S3.N_ROWS), 0) / COUNT(*), 2) AS ir
FROM MAIN.DEVICES AS DEVICES
JOIN MAIN.PRODUCTS AS PRODUCTS
  ON DEVICES.de_product_id = PRODUCTS.pr_id
LEFT JOIN _S3 AS _S3
  ON DEVICES.de_id = _S3.IN_DEVICE_ID
GROUP BY
  1
ORDER BY
  1 NULLS FIRST
