WITH _S5 AS (
  SELECT
    COUNT(*) AS AGG_0,
    INCIDENTS.in_error_id AS ERROR_ID
  FROM MAIN.INCIDENTS AS INCIDENTS
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id AND PRODUCTS.pr_name = 'Sun-Set'
  GROUP BY
    INCIDENTS.in_error_id
), _T0 AS (
  SELECT
    ERRORS.er_name AS ERROR,
    ROUND((
      100.0 * COALESCE(_S5.AGG_0, 0)
    ) / SUM(COALESCE(_S5.AGG_0, 0)) OVER (), 2) AS PCT
  FROM MAIN.ERRORS AS ERRORS
  LEFT JOIN _S5 AS _S5
    ON ERRORS.er_id = _S5.ERROR_ID
)
SELECT
  ERROR AS error,
  PCT AS pct
FROM _T0
ORDER BY
  PCT DESC NULLS LAST
