SELECT
  ANY_VALUE(CALENDAR.ca_dt) AS start_of_period,
  COUNT(*) AS n_purchases
FROM main.CALENDAR AS CALENDAR
JOIN main.CALENDAR AS CALENDAR_2
  ON CALENDAR.ca_dt <= CALENDAR_2.ca_dt
  AND CALENDAR_2.ca_dt < DATE_ADD(CAST(CALENDAR.ca_dt AS DATETIME), INTERVAL '5' DAY)
JOIN main.DEVICES AS DEVICES
  ON CALENDAR_2.ca_dt = DATE(CAST(DEVICES.de_purchase_ts AS DATETIME))
WHERE
  YEAR(CALENDAR.ca_dt) = 2024
GROUP BY
  CALENDAR.ca_dt
ORDER BY
  n_purchases DESC,
  start_of_period
LIMIT 1
