WITH _S14 AS (
  SELECT
    ANY_VALUE(pr_release) AS RELEASE_DATE
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'GoldCopper-Star'
), _T6 AS (
  SELECT
    ca_dt AS CALENDAR_DAY
  FROM MAIN.CALENDAR
), _T8 AS (
  SELECT
    pr_id AS _ID,
    pr_name AS NAME
  FROM MAIN.PRODUCTS
), _S7 AS (
  SELECT
    COUNT(*) AS AGG_3,
    _S0.CALENDAR_DAY
  FROM _T6 AS _S0
  JOIN MAIN.INCIDENTS AS INCIDENTS
    ON _S0.CALENDAR_DAY = DATE_TRUNC('DAY', CAST(INCIDENTS.in_error_report_ts AS TIMESTAMP))
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id
  JOIN _T8 AS _T8
    ON DEVICES.de_product_id = _T8._ID AND _T8.NAME = 'GoldCopper-Star'
  GROUP BY
    _S0.CALENDAR_DAY
), _S13 AS (
  SELECT
    COUNT(*) AS AGG_6,
    _S8.CALENDAR_DAY
  FROM _T6 AS _S8
  JOIN MAIN.DEVICES AS DEVICES
    ON _S8.CALENDAR_DAY = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
  JOIN _T8 AS _T10
    ON DEVICES.de_product_id = _T10._ID AND _T10.NAME = 'GoldCopper-Star'
  GROUP BY
    _S8.CALENDAR_DAY
), _S15 AS (
  SELECT
    SUM(_S7.AGG_3) AS AGG_5,
    SUM(_S13.AGG_6) AS AGG_8,
    YEAR(_T6.CALENDAR_DAY) AS YEAR
  FROM _T6 AS _T6
  LEFT JOIN _S7 AS _S7
    ON _S7.CALENDAR_DAY = _T6.CALENDAR_DAY
  LEFT JOIN _S13 AS _S13
    ON _S13.CALENDAR_DAY = _T6.CALENDAR_DAY
  GROUP BY
    YEAR(_T6.CALENDAR_DAY)
), _T0 AS (
  SELECT
    COALESCE(_S15.AGG_8, 0) AS BOUGHT,
    ROUND(
      SUM(COALESCE(_S15.AGG_5, 0)) OVER (ORDER BY _S15.YEAR ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE(_S15.AGG_8, 0)) OVER (ORDER BY _S15.YEAR ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
      2
    ) AS CUM_IR,
    COALESCE(_S15.AGG_5, 0) AS INCIDENTS,
    ROUND(
      (
        100.0 * (
          COALESCE(_S15.AGG_8, 0) - LAG(COALESCE(_S15.AGG_8, 0), 1) OVER (ORDER BY _S15.YEAR)
        )
      ) / LAG(COALESCE(_S15.AGG_8, 0), 1) OVER (ORDER BY _S15.YEAR),
      2
    ) AS PCT_BOUGHT_CHANGE,
    ROUND(
      (
        100.0 * (
          COALESCE(_S15.AGG_5, 0) - LAG(COALESCE(_S15.AGG_5, 0), 1) OVER (ORDER BY _S15.YEAR)
        )
      ) / LAG(COALESCE(_S15.AGG_5, 0), 1) OVER (ORDER BY _S15.YEAR),
      2
    ) AS PCT_INCIDENT_CHANGE,
    _S15.YEAR - YEAR(_S14.RELEASE_DATE) AS YEARS_SINCE_RELEASE
  FROM _S14 AS _S14
  CROSS JOIN _S15 AS _S15
  WHERE
    _S15.YEAR >= YEAR(_S14.RELEASE_DATE)
)
SELECT
  YEARS_SINCE_RELEASE AS years_since_release,
  CUM_IR AS cum_ir,
  PCT_BOUGHT_CHANGE AS pct_bought_change,
  PCT_INCIDENT_CHANGE AS pct_incident_change,
  BOUGHT AS bought,
  INCIDENTS AS incidents
FROM _T0
ORDER BY
  YEARS_SINCE_RELEASE NULLS FIRST
