WITH "_S1" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.COUNTRIES
)
SELECT
  COUNTRIES.co_name AS name,
  "_S1".N_ROWS AS n_other_countries
FROM MAIN.COUNTRIES COUNTRIES
CROSS JOIN "_S1" "_S1"
ORDER BY
  1 NULLS FIRST
