WITH _T4 AS (
  SELECT
    ca_dt AS CALENDAR_DAY
  FROM MAIN.CALENDAR
), _T8 AS (
  SELECT
    co_id AS _ID,
    co_name AS NAME
  FROM MAIN.COUNTRIES
), _S7 AS (
  SELECT
    COUNT(*) AS AGG_2,
    _T7.CALENDAR_DAY
  FROM _T4 AS _T7
  JOIN MAIN.CALENDAR AS CALENDAR
    ON CALENDAR.ca_dt >= DATEADD(MONTH, -6, CAST(_T7.CALENDAR_DAY AS TIMESTAMP))
  JOIN MAIN.DEVICES AS DEVICES
    ON CALENDAR.ca_dt = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
  JOIN _T8 AS _T8
    ON DEVICES.de_production_country_id = _T8._ID AND _T8.NAME = 'CN'
  WHERE
    YEAR(_T7.CALENDAR_DAY) IN (2020, 2021)
  GROUP BY
    _T7.CALENDAR_DAY
), _S15 AS (
  SELECT
    COUNT(*) AS AGG_5,
    _T11.CALENDAR_DAY
  FROM _T4 AS _T11
  JOIN MAIN.INCIDENTS AS INCIDENTS
    ON _T11.CALENDAR_DAY = DATE_TRUNC('DAY', CAST(INCIDENTS.in_error_report_ts AS TIMESTAMP))
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id
  JOIN _T8 AS _T12
    ON DEVICES.de_production_country_id = _T12._ID AND _T12.NAME = 'CN'
  WHERE
    YEAR(_T11.CALENDAR_DAY) IN (2020, 2021)
  GROUP BY
    _T11.CALENDAR_DAY
), _T1 AS (
  SELECT
    SUM(_S7.AGG_2) AS AGG_4,
    SUM(_S15.AGG_5) AS AGG_7,
    MONTH(_T4.CALENDAR_DAY) AS MONTH,
    YEAR(_T4.CALENDAR_DAY) AS YEAR
  FROM _T4 AS _T4
  LEFT JOIN _S7 AS _S7
    ON _S7.CALENDAR_DAY = _T4.CALENDAR_DAY
  LEFT JOIN _S15 AS _S15
    ON _S15.CALENDAR_DAY = _T4.CALENDAR_DAY
  WHERE
    YEAR(_T4.CALENDAR_DAY) IN (2020, 2021)
  GROUP BY
    MONTH(_T4.CALENDAR_DAY),
    YEAR(_T4.CALENDAR_DAY)
)
SELECT
  CONCAT_WS('-', YEAR, LPAD(MONTH, 2, '0')) AS month,
  ROUND((
    1000000.0 * COALESCE(AGG_7, 0)
  ) / COALESCE(AGG_4, 0), 2) AS ir
FROM _T1
ORDER BY
  MONTH NULLS FIRST
