WITH "_s14" AS (
  SELECT
    ANY_VALUE(PR_RELEASE) AS ANYTHING_PR_RELEASE
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'GoldCopper-Star'
), "_s6" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_t5" AS (
  SELECT
    PR_ID,
    PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    PR_NAME = 'GoldCopper-Star'
), "_s7" AS (
  SELECT
    "_s0".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_s6" "_s0"
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_s0".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  JOIN "_t5" "_t5"
    ON DEVICES.DE_PRODUCT_ID = "_t5".PR_ID
  GROUP BY
    "_s0".CA_DT
), "_s13" AS (
  SELECT
    "_s8".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_s6" "_s8"
  JOIN MAIN.DEVICES DEVICES
    ON "_s8".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  JOIN "_t5" "_t7"
    ON DEVICES.DE_PRODUCT_ID = "_t7".PR_ID
  GROUP BY
    "_s8".CA_DT
), "_s15" AS (
  SELECT
    EXTRACT(YEAR FROM CAST("_s6".CA_DT AS DATE)) AS YEAR_CA_DT,
    SUM("_s7".N_ROWS) AS SUM_EXPR_4,
    SUM("_s13".N_ROWS) AS SUM_N_ROWS
  FROM "_s6" "_s6"
  LEFT JOIN "_s7" "_s7"
    ON "_s6".CA_DT = "_s7".CA_DT
  LEFT JOIN "_s13" "_s13"
    ON "_s13".CA_DT = "_s6".CA_DT
  GROUP BY
    EXTRACT(YEAR FROM CAST("_s6".CA_DT AS DATE))
)
SELECT
  "_s15".YEAR_CA_DT - EXTRACT(YEAR FROM CAST("_s14".ANYTHING_PR_RELEASE AS DATE)) AS years_since_release,
  ROUND(
    SUM(COALESCE("_s15".SUM_EXPR_4, 0)) OVER (ORDER BY "_s15".YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE("_s15".SUM_N_ROWS, 0)) OVER (ORDER BY "_s15".YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS cum_ir,
  ROUND(
    (
      100.0 * (
        COALESCE("_s15".SUM_N_ROWS, 0) - LAG(COALESCE("_s15".SUM_N_ROWS, 0), 1) OVER (ORDER BY "_s15".YEAR_CA_DT)
      )
    ) / LAG(COALESCE("_s15".SUM_N_ROWS, 0), 1) OVER (ORDER BY "_s15".YEAR_CA_DT),
    2
  ) AS pct_bought_change,
  ROUND(
    (
      100.0 * (
        COALESCE("_s15".SUM_EXPR_4, 0) - LAG(COALESCE("_s15".SUM_EXPR_4, 0), 1) OVER (ORDER BY "_s15".YEAR_CA_DT)
      )
    ) / LAG(COALESCE("_s15".SUM_EXPR_4, 0), 1) OVER (ORDER BY "_s15".YEAR_CA_DT),
    2
  ) AS pct_incident_change,
  COALESCE("_s15".SUM_N_ROWS, 0) AS bought,
  COALESCE("_s15".SUM_EXPR_4, 0) AS incidents
FROM "_s14" "_s14"
JOIN "_s15" "_s15"
  ON "_s15".YEAR_CA_DT >= EXTRACT(YEAR FROM CAST("_s14".ANYTHING_PR_RELEASE AS DATE))
ORDER BY
  1 NULLS FIRST
