WITH _T3 AS (
  SELECT
    in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS
), _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    IN_DEVICE_ID
  FROM _T3
  GROUP BY
    IN_DEVICE_ID
), _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(_S1.N_ROWS) AS SUM_N_ROWS,
    DEVICES.de_production_country_id AS DE_PRODUCTION_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  LEFT JOIN _S1 AS _S1
    ON DEVICES.de_id = _S1.IN_DEVICE_ID
  GROUP BY
    DEVICES.de_production_country_id
), _S5 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    IN_DEVICE_ID
  FROM _T3
  GROUP BY
    IN_DEVICE_ID
), _S7 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(_S5.N_ROWS) AS SUM_N_ROWS,
    DEVICES.de_purchase_country_id AS DE_PURCHASE_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  LEFT JOIN _S5 AS _S5
    ON DEVICES.de_id = _S5.IN_DEVICE_ID
  GROUP BY
    DEVICES.de_purchase_country_id
), _S11 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    IN_DEVICE_ID
  FROM _T3
  GROUP BY
    IN_DEVICE_ID
), _S13 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(_S11.N_ROWS) AS SUM_N_ROWS,
    USERS.us_country_id AS US_COUNTRY_ID
  FROM MAIN.USERS AS USERS
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_owner_id = USERS.us_id
  LEFT JOIN _S11 AS _S11
    ON DEVICES.de_id = _S11.IN_DEVICE_ID
  GROUP BY
    USERS.us_country_id
)
SELECT
  COUNTRIES.co_name AS country_name,
  ROUND(COALESCE(_S3.SUM_N_ROWS, 0) / _S3.N_ROWS, 2) AS made_ir,
  ROUND(COALESCE(_S7.SUM_N_ROWS, 0) / _S7.N_ROWS, 2) AS sold_ir,
  ROUND(COALESCE(_S13.SUM_N_ROWS, 0) / COALESCE(_S13.N_ROWS, 0), 2) AS user_ir
FROM MAIN.COUNTRIES AS COUNTRIES
JOIN _S3 AS _S3
  ON COUNTRIES.co_id = _S3.DE_PRODUCTION_COUNTRY_ID
JOIN _S7 AS _S7
  ON COUNTRIES.co_id = _S7.DE_PURCHASE_COUNTRY_ID
LEFT JOIN _S13 AS _S13
  ON COUNTRIES.co_id = _S13.US_COUNTRY_ID
ORDER BY
  COUNTRIES.co_name NULLS FIRST
