WITH _S0 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    de_product_id AS DE_PRODUCT_ID
  FROM MAIN.DEVICES
  GROUP BY
    de_product_id
), _T4 AS (
  SELECT
    pr_id AS PR_ID,
    pr_release AS PR_RELEASE
  FROM MAIN.PRODUCTS
), _S6 AS (
  SELECT
    SUM(_S0.N_ROWS) AS SUM_N_ROWS,
    YEAR(_T4.PR_RELEASE) AS RELEASE_YEAR
  FROM _S0 AS _S0
  JOIN _T4 AS _T4
    ON _S0.DE_PRODUCT_ID = _T4.PR_ID
  GROUP BY
    YEAR(_T4.PR_RELEASE)
), _S7 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    YEAR(_T6.PR_RELEASE) AS RELEASE_YEAR
  FROM MAIN.DEVICES AS DEVICES
  JOIN _T4 AS _T6
    ON DEVICES.de_product_id = _T6.PR_ID
  JOIN MAIN.INCIDENTS AS INCIDENTS
    ON DEVICES.de_id = INCIDENTS.in_device_id
  GROUP BY
    YEAR(_T6.PR_RELEASE)
)
SELECT
  _S6.RELEASE_YEAR AS year,
  ROUND(COALESCE(_S7.N_ROWS, 0) / _S6.SUM_N_ROWS, 2) AS ir
FROM _S6 AS _S6
LEFT JOIN _S7 AS _S7
  ON _S6.RELEASE_YEAR = _S7.RELEASE_YEAR
ORDER BY
  _S6.RELEASE_YEAR NULLS FIRST
