SELECT
  CALENDAR.ca_dt AS start_of_period,
  COUNT(*) AS n_purchases
FROM main.CALENDAR AS CALENDAR
JOIN main.CALENDAR AS CALENDAR_2
  ON CALENDAR.ca_dt <= CALENDAR_2.ca_dt
  AND CALENDAR_2.ca_dt < DATE_ADD(CAST(CALENDAR.ca_dt AS DATETIME), INTERVAL '5' DAY)
JOIN main.DEVICES AS DEVICES
  ON CALENDAR_2.ca_dt = DATE(CAST(DEVICES.de_purchase_ts AS DATETIME))
WHERE
  EXTRACT(YEAR FROM CAST(CALENDAR.ca_dt AS DATETIME)) = 2024
GROUP BY
  1
ORDER BY
  n_purchases DESC,
  CALENDAR.ca_dt
LIMIT 1
