WITH "_t2" AS (
  SELECT
    ANY_VALUE(DEVICES.DE_PRODUCTION_COUNTRY_ID) AS ANYTHING_DE_PRODUCTION_COUNTRY_ID,
    COUNT(INCIDENTS.IN_DEVICE_ID) AS COUNT_IN_DEVICE_ID
  FROM MAIN.DEVICES DEVICES
  JOIN MAIN.PRODUCTS PRODUCTS
    ON DEVICES.DE_PRODUCT_ID = PRODUCTS.PR_ID AND PRODUCTS.PR_NAME = 'Sun-Set'
  LEFT JOIN MAIN.INCIDENTS INCIDENTS
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_ID
), "_s5" AS (
  SELECT
    COALESCE(SUM(COUNT_IN_DEVICE_ID), 0) AS SUM_N_INCIDENTS,
    ANYTHING_DE_PRODUCTION_COUNTRY_ID,
    COUNT(*) AS N_ROWS
  FROM "_t2"
  GROUP BY
    ANYTHING_DE_PRODUCTION_COUNTRY_ID
)
SELECT
  COUNTRIES.CO_NAME AS country,
  ROUND(COALESCE("_s5".SUM_N_INCIDENTS, 0) / COALESCE("_s5".N_ROWS, 0), 2) AS ir
FROM MAIN.COUNTRIES COUNTRIES
LEFT JOIN "_s5" "_s5"
  ON COUNTRIES.CO_ID = "_s5".ANYTHING_DE_PRODUCTION_COUNTRY_ID
ORDER BY
  1 NULLS FIRST
