WITH _S14 AS (
  SELECT
    ANY_VALUE(pr_release) AS RELEASE_DATE
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'GoldCopper-Star'
), _S6 AS (
  SELECT
    ca_dt AS CA_DT
  FROM MAIN.CALENDAR
), _T5 AS (
  SELECT
    pr_id AS PR_ID,
    pr_name AS PR_NAME
  FROM MAIN.PRODUCTS
  WHERE
    pr_name = 'GoldCopper-Star'
), _S7 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _S0.CA_DT
  FROM _S6 AS _S0
  JOIN MAIN.INCIDENTS AS INCIDENTS
    ON _S0.CA_DT = DATE_TRUNC('DAY', CAST(INCIDENTS.in_error_report_ts AS TIMESTAMP))
  JOIN MAIN.DEVICES AS DEVICES
    ON DEVICES.de_id = INCIDENTS.in_device_id
  JOIN _T5 AS _T5
    ON DEVICES.de_product_id = _T5.PR_ID
  GROUP BY
    2
), _S13 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _S8.CA_DT
  FROM _S6 AS _S8
  JOIN MAIN.DEVICES AS DEVICES
    ON _S8.CA_DT = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
  JOIN _T5 AS _T7
    ON DEVICES.de_product_id = _T7.PR_ID
  GROUP BY
    2
), _S15 AS (
  SELECT
    SUM(_S7.N_ROWS) AS SUM_EXPR_4,
    SUM(_S13.N_ROWS) AS SUM_N_ROWS,
    YEAR(CAST(_S6.CA_DT AS TIMESTAMP)) AS YEAR_1
  FROM _S6 AS _S6
  LEFT JOIN _S7 AS _S7
    ON _S6.CA_DT = _S7.CA_DT
  LEFT JOIN _S13 AS _S13
    ON _S13.CA_DT = _S6.CA_DT
  GROUP BY
    3
)
SELECT
  _S15.YEAR_1 - YEAR(CAST(_S14.RELEASE_DATE AS TIMESTAMP)) AS years_since_release,
  ROUND(
    SUM(COALESCE(_S15.SUM_EXPR_4, 0)) OVER (ORDER BY _S15.YEAR_1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(COALESCE(_S15.SUM_N_ROWS, 0)) OVER (ORDER BY _S15.YEAR_1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS cum_ir,
  ROUND(
    (
      100.0 * (
        COALESCE(_S15.SUM_N_ROWS, 0) - LAG(COALESCE(_S15.SUM_N_ROWS, 0), 1) OVER (ORDER BY _S15.YEAR_1)
      )
    ) / LAG(COALESCE(_S15.SUM_N_ROWS, 0), 1) OVER (ORDER BY _S15.YEAR_1),
    2
  ) AS pct_bought_change,
  ROUND(
    (
      100.0 * (
        COALESCE(_S15.SUM_EXPR_4, 0) - LAG(COALESCE(_S15.SUM_EXPR_4, 0), 1) OVER (ORDER BY _S15.YEAR_1)
      )
    ) / LAG(COALESCE(_S15.SUM_EXPR_4, 0), 1) OVER (ORDER BY _S15.YEAR_1),
    2
  ) AS pct_incident_change,
  COALESCE(_S15.SUM_N_ROWS, 0) AS bought,
  COALESCE(_S15.SUM_EXPR_4, 0) AS incidents
FROM _S14 AS _S14
JOIN _S15 AS _S15
  ON _S15.YEAR_1 >= YEAR(CAST(_S14.RELEASE_DATE AS TIMESTAMP))
ORDER BY
  1 NULLS FIRST
