WITH _S0 AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS
), _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES
)
SELECT
  ROUND(_S0.N_ROWS / _S1.N_ROWS, 2) AS ir
FROM _S0 AS _S0
CROSS JOIN _S1 AS _S1
