SELECT
  CALENDAR.CA_DT AS start_of_period,
  COUNT(*) AS n_purchases
FROM MAIN.CALENDAR CALENDAR
JOIN MAIN.CALENDAR CALENDAR_2
  ON CALENDAR.CA_DT <= CALENDAR_2.CA_DT
  AND CALENDAR_2.CA_DT < (
    CAST(CALENDAR.CA_DT AS DATE) + NUMTODSINTERVAL(5, 'day')
  )
JOIN MAIN.DEVICES DEVICES
  ON CALENDAR_2.CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
WHERE
  EXTRACT(YEAR FROM CAST(CALENDAR.CA_DT AS DATE)) = 2024
GROUP BY
  CALENDAR.CA_DT
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 1 ROWS ONLY
