WITH "_T2" AS (
  SELECT
    ANY_VALUE(DEVICES.de_production_country_id) AS ANYTHING_DE_PRODUCTION_COUNTRY_ID,
    COUNT(INCIDENTS.in_device_id) AS COUNT_IN_DEVICE_ID
  FROM MAIN.DEVICES DEVICES
  JOIN MAIN.PRODUCTS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id AND PRODUCTS.pr_name = 'Sun-Set'
  LEFT JOIN MAIN.INCIDENTS INCIDENTS
    ON DEVICES.de_id = INCIDENTS.in_device_id
  GROUP BY
    DEVICES.de_id
), "_S5" AS (
  SELECT
    NVL(SUM(COUNT_IN_DEVICE_ID), 0) AS SUM_N_INCIDENTS,
    ANYTHING_DE_PRODUCTION_COUNTRY_ID,
    COUNT(*) AS N_ROWS
  FROM "_T2"
  GROUP BY
    ANYTHING_DE_PRODUCTION_COUNTRY_ID
)
SELECT
  COUNTRIES.co_name AS country,
  ROUND(NVL("_S5".SUM_N_INCIDENTS, 0) / NVL("_S5".N_ROWS, 0), 2) AS ir
FROM MAIN.COUNTRIES COUNTRIES
LEFT JOIN "_S5" "_S5"
  ON COUNTRIES.co_id = "_S5".ANYTHING_DE_PRODUCTION_COUNTRY_ID
ORDER BY
  1 NULLS FIRST
