SELECT
  ANY_VALUE(CALENDAR.ca_dt) AS start_of_period,
  COUNT(*) AS n_purchases
FROM MAIN.CALENDAR AS CALENDAR
JOIN MAIN.CALENDAR AS CALENDAR_2
  ON CALENDAR.ca_dt <= CALENDAR_2.ca_dt
  AND CALENDAR_2.ca_dt < DATEADD(DAY, 5, CAST(CALENDAR.ca_dt AS TIMESTAMP))
JOIN MAIN.DEVICES AS DEVICES
  ON CALENDAR_2.ca_dt = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
WHERE
  YEAR(CALENDAR.ca_dt) = 2024
GROUP BY
  CALENDAR.ca_dt
ORDER BY
  N_PURCHASES DESC NULLS LAST,
  START_OF_PERIOD NULLS FIRST
LIMIT 1
