WITH "_s0" AS (
  SELECT
    CO_ID,
    CO_NAME
  FROM MAIN.COUNTRIES
), "_s2" AS (
  SELECT
    CO_ID
  FROM MAIN.COUNTRIES
), "_t1" AS (
  SELECT
    ANY_VALUE("_s3".CO_ID) AS ANYTHING__ID_3,
    ANY_VALUE("_s2".CO_ID) AS ANYTHING_CO_ID,
    COUNT(INCIDENTS.IN_DEVICE_ID) AS COUNT_IN_DEVICE_ID
  FROM "_s2" "_s2"
  CROSS JOIN "_s2" "_s3"
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_PRODUCTION_COUNTRY_ID = "_s2".CO_ID
    AND DEVICES.DE_PURCHASE_COUNTRY_ID = "_s3".CO_ID
  LEFT JOIN MAIN.INCIDENTS INCIDENTS
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  GROUP BY
    DEVICES.DE_ID
), "_s9" AS (
  SELECT
    ANYTHING__ID_3,
    ANYTHING_CO_ID,
    COUNT(*) AS N_ROWS,
    SUM(COUNT_IN_DEVICE_ID) AS SUM_N_ROWS
  FROM "_t1"
  GROUP BY
    ANYTHING__ID_3,
    ANYTHING_CO_ID
)
SELECT
  "_s0".CO_NAME AS factory_country,
  "_s1".CO_NAME AS purchase_country,
  ROUND(COALESCE("_s9".SUM_N_ROWS, 0) / COALESCE("_s9".N_ROWS, 0), 2) AS ir
FROM "_s0" "_s0"
CROSS JOIN "_s0" "_s1"
LEFT JOIN "_s9" "_s9"
  ON "_s0".CO_ID = "_s9".ANYTHING_CO_ID AND "_s1".CO_ID = "_s9".ANYTHING__ID_3
ORDER BY
  3 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
