WITH _S7 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    INCIDENTS.in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS AS INCIDENTS
  JOIN MAIN.ERRORS AS ERRORS
    ON ERRORS.er_id = INCIDENTS.in_error_id AND ERRORS.er_name = 'Battery Failure'
  GROUP BY
    INCIDENTS.in_device_id
)
SELECT
  COUNTRIES.co_name AS country_name,
  PRODUCTS.pr_name AS product_name,
  ROUND(COALESCE(SUM(_S7.N_ROWS), 0) / COUNT(*), 2) AS ir
FROM MAIN.COUNTRIES AS COUNTRIES
JOIN MAIN.DEVICES AS DEVICES
  ON COUNTRIES.co_id = DEVICES.de_production_country_id
JOIN MAIN.PRODUCTS AS PRODUCTS
  ON DEVICES.de_product_id = PRODUCTS.pr_id
LEFT JOIN _S7 AS _S7
  ON DEVICES.de_id = _S7.IN_DEVICE_ID
GROUP BY
  COUNTRIES.co_name,
  PRODUCTS.pr_name
ORDER BY
  ROUND(COALESCE(SUM(_S7.N_ROWS), 0) / COUNT(*), 2) DESC NULLS LAST,
  PRODUCTS.pr_name NULLS FIRST,
  COUNTRIES.co_name NULLS FIRST
LIMIT 5
