WITH "_s0" AS (
  SELECT
    DE_PRODUCT_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES
  GROUP BY
    DE_PRODUCT_ID
), "_s1" AS (
  SELECT
    PR_ID,
    PR_RELEASE
  FROM MAIN.PRODUCTS
), "_s6" AS (
  SELECT
    EXTRACT(YEAR FROM CAST("_s1".PR_RELEASE AS DATE)) AS YEAR_PR_RELEASE,
    SUM("_s0".N_ROWS) AS SUM_N_ROWS
  FROM "_s0" "_s0"
  JOIN "_s1" "_s1"
    ON "_s0".DE_PRODUCT_ID = "_s1".PR_ID
  GROUP BY
    EXTRACT(YEAR FROM CAST("_s1".PR_RELEASE AS DATE))
), "_s7" AS (
  SELECT
    EXTRACT(YEAR FROM CAST("_s3".PR_RELEASE AS DATE)) AS YEAR_PR_RELEASE,
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES DEVICES
  JOIN "_s1" "_s3"
    ON DEVICES.DE_PRODUCT_ID = "_s3".PR_ID
  JOIN MAIN.INCIDENTS INCIDENTS
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  GROUP BY
    EXTRACT(YEAR FROM CAST("_s3".PR_RELEASE AS DATE))
)
SELECT
  "_s6".YEAR_PR_RELEASE AS year,
  ROUND(COALESCE("_s7".N_ROWS, 0) / "_s6".SUM_N_ROWS, 2) AS ir
FROM "_s6" "_s6"
LEFT JOIN "_s7" "_s7"
  ON "_s6".YEAR_PR_RELEASE = "_s7".YEAR_PR_RELEASE
ORDER BY
  1 NULLS FIRST
