WITH "_s5" AS (
  SELECT
    INCIDENTS.IN_ERROR_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS INCIDENTS
  JOIN MAIN.DEVICES DEVICES
    ON DEVICES.DE_ID = INCIDENTS.IN_DEVICE_ID
  JOIN MAIN.PRODUCTS PRODUCTS
    ON DEVICES.DE_PRODUCT_ID = PRODUCTS.PR_ID AND PRODUCTS.PR_NAME = 'Sun-Set'
  GROUP BY
    INCIDENTS.IN_ERROR_ID
)
SELECT
  ERRORS.ER_NAME AS error,
  ROUND(
    (
      100.0 * COALESCE("_s5".N_ROWS, 0)
    ) / SUM(COALESCE("_s5".N_ROWS, 0)) OVER (),
    2
  ) AS pct
FROM MAIN.ERRORS ERRORS
LEFT JOIN "_s5" "_s5"
  ON ERRORS.ER_ID = "_s5".IN_ERROR_ID
ORDER BY
  2 DESC NULLS LAST
