WITH _S3 AS (
  SELECT
    COUNT(*) AS AGG_0,
    in_device_id AS DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
), _S5 AS (
  SELECT
    SUM(COALESCE(_S3.AGG_0, 0)) AS AGG_0,
    COUNT(*) AS AGG_1,
    DEVICES.de_production_country_id AS FACTORY_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id AND PRODUCTS.pr_name = 'Sun-Set'
  LEFT JOIN _S3 AS _S3
    ON DEVICES.de_id = _S3.DEVICE_ID
  GROUP BY
    DEVICES.de_production_country_id
)
SELECT
  COUNTRIES.co_name AS country,
  ROUND(COALESCE(_S5.AGG_0, 0) / COALESCE(_S5.AGG_1, 0), 2) AS ir
FROM MAIN.COUNTRIES AS COUNTRIES
LEFT JOIN _S5 AS _S5
  ON COUNTRIES.co_id = _S5.FACTORY_COUNTRY_ID
ORDER BY
  COUNTRY NULLS FIRST
