WITH _S7 AS (
  SELECT
    COUNT(*) AS AGG_2,
    in_device_id AS DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
), _S9 AS (
  SELECT
    COUNT(*) AS AGG_1,
    SUM(_S7.AGG_2) AS AGG_4,
    COUNTRIES.co_id AS _ID,
    COUNTRIES_2.co_id AS _ID_3
  FROM MAIN.COUNTRIES AS COUNTRIES
  CROSS JOIN MAIN.COUNTRIES AS COUNTRIES_2
  JOIN MAIN.DEVICES AS DEVICES
    ON COUNTRIES.co_id = DEVICES.de_production_country_id
    AND COUNTRIES_2.co_id = DEVICES.de_purchase_country_id
  LEFT JOIN _S7 AS _S7
    ON DEVICES.de_id = _S7.DEVICE_ID
  GROUP BY
    COUNTRIES.co_id,
    COUNTRIES_2.co_id
)
SELECT
  COUNTRIES.co_name AS factory_country,
  COUNTRIES_2.co_name AS purchase_country,
  ROUND((
    1.0 * COALESCE(_S9.AGG_4, 0)
  ) / COALESCE(_S9.AGG_1, 0), 2) AS ir
FROM MAIN.COUNTRIES AS COUNTRIES
CROSS JOIN MAIN.COUNTRIES AS COUNTRIES_2
LEFT JOIN _S9 AS _S9
  ON COUNTRIES.co_id = _S9._ID AND COUNTRIES_2.co_id = _S9._ID_3
ORDER BY
  IR DESC NULLS LAST
LIMIT 5
