WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
), _S5 AS (
  SELECT
    ROUND(COALESCE(SUM(COALESCE(_S3.N_ROWS, 0)), 0) / COUNT(*), 2) AS IR,
    DEVICES.de_product_id AS DE_PRODUCT_ID
  FROM MAIN.DEVICES AS DEVICES
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id
  LEFT JOIN _S3 AS _S3
    ON DEVICES.de_id = _S3.IN_DEVICE_ID
  GROUP BY
    DEVICES.de_product_id
)
SELECT
  PRODUCTS.pr_name AS product,
  PRODUCTS.pr_brand AS product_brand,
  PRODUCTS.pr_type AS product_type,
  _S5.IR AS ir
FROM MAIN.PRODUCTS AS PRODUCTS
JOIN _S5 AS _S5
  ON PRODUCTS.pr_id = _S5.DE_PRODUCT_ID
ORDER BY
  IR DESC NULLS LAST
LIMIT 5
