WITH _S0 AS (
  SELECT
    de_product_id AS DE_PRODUCT_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES
  GROUP BY
    de_product_id
), _S1 AS (
  SELECT
    pr_id AS PR_ID,
    pr_release AS PR_RELEASE
  FROM MAIN.PRODUCTS
), _S6 AS (
  SELECT
    EXTRACT(YEAR FROM CAST(_S1.PR_RELEASE AS DATETIME)) AS YEAR_PR_RELEASE,
    SUM(_S0.N_ROWS) AS SUM_N_ROWS
  FROM _S0 _S0
  JOIN _S1 _S1
    ON _S0.DE_PRODUCT_ID = _S1.PR_ID
  GROUP BY
    EXTRACT(YEAR FROM CAST(_S1.PR_RELEASE AS DATETIME))
), _S7 AS (
  SELECT
    EXTRACT(YEAR FROM CAST(_S3.PR_RELEASE AS DATETIME)) AS YEAR_PR_RELEASE,
    COUNT(*) AS N_ROWS
  FROM MAIN.DEVICES DEVICES
  JOIN _S1 _S3
    ON DEVICES.de_product_id = _S3.PR_ID
  JOIN MAIN.INCIDENTS INCIDENTS
    ON DEVICES.de_id = INCIDENTS.in_device_id
  GROUP BY
    EXTRACT(YEAR FROM CAST(_S3.PR_RELEASE AS DATETIME))
)
SELECT
  _S6.YEAR_PR_RELEASE AS year,
  ROUND(NVL(_S7.N_ROWS, 0) / _S6.SUM_N_ROWS, 2) AS ir
FROM _S6 _S6
LEFT JOIN _S7 _S7
  ON _S6.YEAR_PR_RELEASE = _S7.YEAR_PR_RELEASE
ORDER BY
  1 NULLS FIRST
