SELECT
  CALENDAR.ca_dt AS start_of_period,
  COUNT(*) AS n_purchases
FROM MAIN.CALENDAR CALENDAR
JOIN MAIN.CALENDAR CALENDAR_2
  ON CALENDAR.ca_dt <= CALENDAR_2.ca_dt
  AND CALENDAR_2.ca_dt < DATE_ADD(CAST(CALENDAR.ca_dt AS TIMESTAMP), 5, 'DAY')
JOIN MAIN.DEVICES DEVICES
  ON CALENDAR_2.ca_dt = TRUNC(CAST(DEVICES.de_purchase_ts AS TIMESTAMP), 'DAY')
WHERE
  EXTRACT(YEAR FROM CAST(CALENDAR.ca_dt AS DATETIME)) = 2024
GROUP BY
  CALENDAR.ca_dt
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 1 ROWS ONLY
