WITH "_s7" AS (
  SELECT
    INCIDENTS.IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS INCIDENTS
  JOIN MAIN.ERRORS ERRORS
    ON ERRORS.ER_ID = INCIDENTS.IN_ERROR_ID AND ERRORS.ER_NAME = 'Battery Failure'
  GROUP BY
    INCIDENTS.IN_DEVICE_ID
)
SELECT
  COUNTRIES.CO_NAME AS country_name,
  PRODUCTS.PR_NAME AS product_name,
  ROUND(COALESCE(SUM("_s7".N_ROWS), 0) / COUNT(*), 2) AS ir
FROM MAIN.COUNTRIES COUNTRIES
JOIN MAIN.DEVICES DEVICES
  ON COUNTRIES.CO_ID = DEVICES.DE_PRODUCTION_COUNTRY_ID
JOIN MAIN.PRODUCTS PRODUCTS
  ON DEVICES.DE_PRODUCT_ID = PRODUCTS.PR_ID
LEFT JOIN "_s7" "_s7"
  ON DEVICES.DE_ID = "_s7".IN_DEVICE_ID
GROUP BY
  COUNTRIES.CO_NAME,
  PRODUCTS.PR_NAME
ORDER BY
  3 DESC NULLS LAST,
  2 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
