WITH _S2 AS (
  SELECT
    ca_dt AS CA_DT
  FROM MAIN.CALENDAR
), _S3 AS (
  SELECT
    _S0.CA_DT,
    COUNT(*) AS N_ROWS
  FROM _S2 _S0
  JOIN MAIN.DEVICES DEVICES
    ON _S0.CA_DT = TRUNC(CAST(DEVICES.de_purchase_ts AS TIMESTAMP), 'DAY')
  GROUP BY
    _S0.CA_DT
), _S7 AS (
  SELECT
    _S4.CA_DT,
    COUNT(*) AS N_ROWS
  FROM _S2 _S4
  JOIN MAIN.INCIDENTS INCIDENTS
    ON _S4.CA_DT = TRUNC(CAST(INCIDENTS.in_error_report_ts AS TIMESTAMP), 'DAY')
  GROUP BY
    _S4.CA_DT
), _T1 AS (
  SELECT
    EXTRACT(YEAR FROM CAST(_S2.CA_DT AS DATETIME)) AS YEAR_CA_DT,
    SUM(_S3.N_ROWS) AS SUM_EXPR_3,
    SUM(_S7.N_ROWS) AS SUM_N_ROWS
  FROM _S2 _S2
  LEFT JOIN _S3 _S3
    ON _S2.CA_DT = _S3.CA_DT
  LEFT JOIN _S7 _S7
    ON _S2.CA_DT = _S7.CA_DT
  GROUP BY
    EXTRACT(YEAR FROM CAST(_S2.CA_DT AS DATETIME))
)
SELECT
  YEAR_CA_DT AS yr,
  ROUND(
    SUM(NVL(SUM_N_ROWS, 0)) OVER (ORDER BY YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(SUM_EXPR_3) OVER (ORDER BY YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS cum_ir,
  ROUND(
    (
      100.0 * (
        SUM_EXPR_3 - LAG(SUM_EXPR_3, 1) OVER (ORDER BY YEAR_CA_DT)
      )
    ) / LAG(SUM_EXPR_3, 1) OVER (ORDER BY YEAR_CA_DT),
    2
  ) AS pct_bought_change,
  ROUND(
    (
      100.0 * (
        NVL(SUM_N_ROWS, 0) - LAG(NVL(SUM_N_ROWS, 0), 1) OVER (ORDER BY YEAR_CA_DT)
      )
    ) / LAG(NVL(SUM_N_ROWS, 0), 1) OVER (ORDER BY YEAR_CA_DT),
    2
  ) AS pct_incident_change,
  SUM_EXPR_3 AS bought,
  NVL(SUM_N_ROWS, 0) AS incidents
FROM _T1
WHERE
  NOT SUM_EXPR_3 IS NULL AND SUM_EXPR_3 <> 0
ORDER BY
  1 NULLS FIRST
