WITH _T3 AS (
  SELECT
    ca_dt AS CALENDAR_DAY
  FROM MAIN.CALENDAR
), _T0 AS (
  SELECT
    COUNT(*) AS N_PURCHASES,
    ANY_VALUE(_T3.CALENDAR_DAY) AS START_OF_PERIOD
  FROM _T3 AS _T3
  CROSS JOIN _T3 AS _S1
  JOIN MAIN.DEVICES AS DEVICES
    ON _S1.CALENDAR_DAY = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
  WHERE
    YEAR(_T3.CALENDAR_DAY) = 2024
    AND _S1.CALENDAR_DAY < DATEADD(DAY, 5, CAST(_T3.CALENDAR_DAY AS TIMESTAMP))
    AND _S1.CALENDAR_DAY >= _T3.CALENDAR_DAY
  GROUP BY
    _T3.CALENDAR_DAY
)
SELECT
  ANY_VALUE(CALENDAR.ca_dt) AS start_of_period,
  COUNT(*) AS n_purchases
FROM MAIN.CALENDAR AS CALENDAR
JOIN MAIN.CALENDAR AS CALENDAR_2
  ON CALENDAR.ca_dt <= CALENDAR_2.ca_dt
  AND CALENDAR_2.ca_dt < DATEADD(DAY, 5, CAST(CALENDAR.ca_dt AS TIMESTAMP))
JOIN MAIN.DEVICES AS DEVICES
  ON CALENDAR_2.ca_dt = DATE_TRUNC('DAY', CAST(DEVICES.de_purchase_ts AS TIMESTAMP))
WHERE
  DATE_PART(YEAR, CAST(CALENDAR.ca_dt AS DATETIME)) = 2024
GROUP BY
  CALENDAR.ca_dt
ORDER BY
  N_PURCHASES DESC NULLS LAST,
  START_OF_PERIOD NULLS FIRST
LIMIT 1
