WITH "_s2" AS (
  SELECT
    CA_DT
  FROM MAIN.CALENDAR
), "_s3" AS (
  SELECT
    "_s0".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_s2" "_s0"
  JOIN MAIN.DEVICES DEVICES
    ON "_s0".CA_DT = TRUNC(CAST(CAST(DEVICES.DE_PURCHASE_TS AS DATE) AS DATE), 'DD')
  GROUP BY
    "_s0".CA_DT
), "_s7" AS (
  SELECT
    "_s4".CA_DT,
    COUNT(*) AS N_ROWS
  FROM "_s2" "_s4"
  JOIN MAIN.INCIDENTS INCIDENTS
    ON "_s4".CA_DT = TRUNC(CAST(CAST(INCIDENTS.IN_ERROR_REPORT_TS AS DATE) AS DATE), 'DD')
  GROUP BY
    "_s4".CA_DT
), "_t1" AS (
  SELECT
    EXTRACT(YEAR FROM CAST("_s2".CA_DT AS DATE)) AS YEAR_CA_DT,
    SUM("_s3".N_ROWS) AS SUM_EXPR_3,
    SUM("_s7".N_ROWS) AS SUM_N_ROWS
  FROM "_s2" "_s2"
  LEFT JOIN "_s3" "_s3"
    ON "_s2".CA_DT = "_s3".CA_DT
  LEFT JOIN "_s7" "_s7"
    ON "_s2".CA_DT = "_s7".CA_DT
  GROUP BY
    EXTRACT(YEAR FROM CAST("_s2".CA_DT AS DATE))
)
SELECT
  YEAR_CA_DT AS yr,
  ROUND(
    SUM(COALESCE(SUM_N_ROWS, 0)) OVER (ORDER BY YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(SUM_EXPR_3) OVER (ORDER BY YEAR_CA_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2
  ) AS cum_ir,
  ROUND(
    (
      100.0 * (
        SUM_EXPR_3 - LAG(SUM_EXPR_3, 1) OVER (ORDER BY YEAR_CA_DT)
      )
    ) / LAG(SUM_EXPR_3, 1) OVER (ORDER BY YEAR_CA_DT),
    2
  ) AS pct_bought_change,
  ROUND(
    (
      100.0 * (
        COALESCE(SUM_N_ROWS, 0) - LAG(COALESCE(SUM_N_ROWS, 0), 1) OVER (ORDER BY YEAR_CA_DT)
      )
    ) / LAG(COALESCE(SUM_N_ROWS, 0), 1) OVER (ORDER BY YEAR_CA_DT),
    2
  ) AS pct_incident_change,
  SUM_EXPR_3 AS bought,
  COALESCE(SUM_N_ROWS, 0) AS incidents
FROM "_t1"
WHERE
  NOT SUM_EXPR_3 IS NULL AND SUM_EXPR_3 <> 0
ORDER BY
  1 NULLS FIRST
