WITH _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    in_device_id AS IN_DEVICE_ID
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
), _S5 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    SUM(COALESCE(_S3.N_ROWS, 0)) AS SUM_N_INCIDENTS,
    DEVICES.de_production_country_id AS DE_PRODUCTION_COUNTRY_ID
  FROM MAIN.DEVICES AS DEVICES
  JOIN MAIN.PRODUCTS AS PRODUCTS
    ON DEVICES.de_product_id = PRODUCTS.pr_id AND PRODUCTS.pr_name = 'Sun-Set'
  LEFT JOIN _S3 AS _S3
    ON DEVICES.de_id = _S3.IN_DEVICE_ID
  GROUP BY
    DEVICES.de_production_country_id
)
SELECT
  COUNTRIES.co_name AS country,
  ROUND(COALESCE(_S5.SUM_N_INCIDENTS, 0) / COALESCE(_S5.N_ROWS, 0), 2) AS ir
FROM MAIN.COUNTRIES AS COUNTRIES
LEFT JOIN _S5 AS _S5
  ON COUNTRIES.co_id = _S5.DE_PRODUCTION_COUNTRY_ID
ORDER BY
  COUNTRIES.co_name NULLS FIRST
