WITH "_s3" AS (
  SELECT
    IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS
  GROUP BY
    IN_DEVICE_ID
)
SELECT
  PRODUCTS.PR_BRAND AS brand,
  ROUND(COALESCE(SUM("_s3".N_ROWS), 0) / COUNT(*), 2) AS ir
FROM MAIN.DEVICES DEVICES
JOIN MAIN.PRODUCTS PRODUCTS
  ON DEVICES.DE_PRODUCT_ID = PRODUCTS.PR_ID
LEFT JOIN "_s3" "_s3"
  ON DEVICES.DE_ID = "_s3".IN_DEVICE_ID
GROUP BY
  PRODUCTS.PR_BRAND
ORDER BY
  1 NULLS FIRST
