WITH "_S3" AS (
  SELECT
    in_device_id AS IN_DEVICE_ID,
    COUNT(*) AS N_ROWS
  FROM MAIN.INCIDENTS
  GROUP BY
    in_device_id
)
SELECT
  PRODUCTS.pr_brand AS brand,
  ROUND(COALESCE(SUM("_S3".N_ROWS), 0) / COUNT(*), 2) AS ir
FROM MAIN.DEVICES DEVICES
JOIN MAIN.PRODUCTS PRODUCTS
  ON DEVICES.de_product_id = PRODUCTS.pr_id
LEFT JOIN "_S3" "_S3"
  ON DEVICES.de_id = "_S3".IN_DEVICE_ID
GROUP BY
  PRODUCTS.pr_brand
ORDER BY
  1 NULLS FIRST
