WITH _T3 AS (
  SELECT
    (
      100.0 * SUM(sbtxshares) OVER (PARTITION BY DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP)) ORDER BY sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    ) / SUM(sbtxshares) OVER (PARTITION BY DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP))) AS PCT_OF_DAY,
    sbtxdatetime AS SBTXDATETIME
  FROM MAIN.SBTRANSACTION
  WHERE
    YEAR(CAST(sbtxdatetime AS TIMESTAMP)) = 2023
), _T1 AS (
  SELECT
    SBTXDATETIME
  FROM _T3
  WHERE
    PCT_OF_DAY >= 50.0
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('DAY', CAST(SBTXDATETIME AS TIMESTAMP)) ORDER BY PCT_OF_DAY) = 1
)
SELECT
  SBTXDATETIME AS date_time
FROM _T1
ORDER BY
  SBTXDATETIME NULLS FIRST
