WITH _T2 AS (
  SELECT
    (
      100.0 * SUM(sbtxshares) OVER (PARTITION BY DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP)) ORDER BY sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    ) / SUM(sbtxshares) OVER (PARTITION BY DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP))) AS PCT_OF_DAY,
    sbtxdatetime AS DATE_TIME,
    DATE_TRUNC('DAY', CAST(sbtxdatetime AS TIMESTAMP)) AS TXN_DAY
  FROM MAIN.SBTRANSACTION
  WHERE
    DATE_PART(YEAR, sbtxdatetime) = 2023
), _T0 AS (
  SELECT
    DATE_TIME
  FROM _T2
  WHERE
    PCT_OF_DAY >= 50.0
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY TXN_DAY ORDER BY PCT_OF_DAY) = 1
)
SELECT
  DATE_TIME AS date_time
FROM _T0
ORDER BY
  DATE_TIME NULLS FIRST
