WITH "_T3" AS (
  SELECT
    sbtxdatetime AS SBTXDATETIME,
    (
      100.0 * SUM(sbtxshares) OVER (PARTITION BY TRUNC(CAST(sbtxdatetime AS TIMESTAMP), 'DAY') ORDER BY sbtxdatetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    ) / SUM(sbtxshares) OVER (PARTITION BY TRUNC(CAST(sbtxdatetime AS TIMESTAMP), 'DAY')) AS PCT_OF_DAY
  FROM MAIN.SBTRANSACTION
  WHERE
    EXTRACT(YEAR FROM CAST(sbtxdatetime AS DATE)) = 2023
), "_T" AS (
  SELECT
    SBTXDATETIME,
    ROW_NUMBER() OVER (PARTITION BY TRUNC(CAST(SBTXDATETIME AS TIMESTAMP), 'DAY') ORDER BY PCT_OF_DAY) AS "_W"
  FROM "_T3"
  WHERE
    PCT_OF_DAY >= 50.0
)
SELECT
  SBTXDATETIME AS date_time
FROM "_T"
WHERE
  "_W" = 1
ORDER BY
  1 NULLS FIRST
