WITH "_t3" AS (
  SELECT
    SBTXDATETIME,
    (
      100.0 * SUM(SBTXSHARES) OVER (
        PARTITION BY TRUNC(CAST(CAST(SBTXDATETIME AS DATE) AS DATE), 'DD')
        ORDER BY SBTXDATETIME
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
      )
    ) / SUM(SBTXSHARES) OVER (PARTITION BY TRUNC(CAST(CAST(SBTXDATETIME AS DATE) AS DATE), 'DD')) AS PCT_OF_DAY
  FROM MAIN.SBTRANSACTION
  WHERE
    EXTRACT(YEAR FROM CAST(SBTXDATETIME AS DATE)) = 2023
), "_t" AS (
  SELECT
    SBTXDATETIME,
    ROW_NUMBER() OVER (
      PARTITION BY TRUNC(CAST(CAST(SBTXDATETIME AS DATE) AS DATE), 'DD')
      ORDER BY PCT_OF_DAY
    ) AS "_w"
  FROM "_t3"
  WHERE
    PCT_OF_DAY >= 50.0
)
SELECT
  SBTXDATETIME AS date_time
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
