SELECT
  ASIAN_NATIONS_T8.nation_name,
  ASIAN_CUSTS_T8.ckey
FROM ASIAN_NATIONS_T8 ASIAN_NATIONS_T8
JOIN ASIAN_CUSTS_T8 ASIAN_CUSTS_T8
  ON ASIAN_CUSTS_T8.nkey = ASIAN_NATIONS_T8.nation_key
ORDER BY
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
