SELECT
  EURO_REGIONS_T24.RKEY AS rkey,
  EURO_REGIONS_T24.RNAME AS rname,
  TIERS_T24.TIER_ID AS tier_id,
  TIERS_T24.TIER_LABEL AS tier_label
FROM EURO_REGIONS_T24 EURO_REGIONS_T24
CROSS JOIN TIERS_T24 TIERS_T24
ORDER BY
  3 NULLS FIRST
