WITH "_u_0" AS (
  SELECT
    NATION_KEY AS "_u_1"
  FROM ASIAN_NATIONS_T5
  GROUP BY
    NATION_KEY
)
SELECT
  CUSTOMER.C_NAME AS name
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_u_0" "_u_0"
  ON CUSTOMER.C_NATIONKEY = "_u_0"."_u_1"
WHERE
  NOT "_u_0"."_u_1" IS NULL
ORDER BY
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
