SELECT
  ASIAN_NATIONS_T7.nation_name,
  ASIAN_CUSTS_T7.ckey
FROM ASIAN_NATIONS_T7 ASIAN_NATIONS_T7
JOIN ASIAN_CUSTS_T7 ASIAN_CUSTS_t7
  ON ASIAN_CUSTS_T7.nkey = ASIAN_NATIONS_T7.nation_key
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
