SELECT
  ASIAN_NATIONS_T7.NATION_NAME AS nation_name,
  ASIAN_CUSTS_T7.CKEY AS ckey
FROM ASIAN_NATIONS_T7 ASIAN_NATIONS_T7
JOIN ASIAN_CUSTS_T7 ASIAN_CUSTS_T7
  ON ASIAN_CUSTS_T7.NKEY = ASIAN_NATIONS_T7.NATION_KEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
