SELECT
  ASIAN_NATIONS_T8.NATION_NAME AS nation_name,
  ASIAN_CUSTS_T8.CKEY AS ckey
FROM ASIAN_NATIONS_T8 ASIAN_NATIONS_T8
JOIN ASIAN_CUSTS_T8 ASIAN_CUSTS_T8
  ON ASIAN_CUSTS_T8.NKEY = ASIAN_NATIONS_T8.NATION_KEY
ORDER BY
  2 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
