WITH "_t" AS (
  SELECT
    NATION.N_NAME,
    NATION.N_NATIONKEY,
    REGIONS_T25.RKEY,
    REGIONS_T25.RNAME,
    ROW_NUMBER() OVER (PARTITION BY REGIONS_T25.RKEY ORDER BY NATION.N_NATIONKEY) AS "_w"
  FROM REGIONS_T25 REGIONS_T25
  JOIN TPCH.NATION NATION
    ON NATION.N_REGIONKEY = REGIONS_T25.RKEY
)
SELECT
  RKEY AS rkey,
  RNAME AS rname,
  N_NATIONKEY AS nkey,
  N_NAME AS nname
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
