SELECT
  ASIA_NATIONS_T23.NKEY AS nkey,
  ASIA_NATIONS_T23.NNAME AS nname,
  MULTS_T23.MULT AS mult
FROM ASIA_NATIONS_T23 ASIA_NATIONS_T23
CROSS JOIN MULTS_T23 MULTS_T23
ORDER BY
  1 NULLS FIRST,
  3 NULLS FIRST
