WITH "_s2" AS (
  SELECT
    L_LINENUMBER,
    L_ORDERKEY,
    L_PARTKEY,
    L_SUPPKEY
  FROM TPCH.LINEITEM
  ORDER BY
    2 NULLS FIRST,
    1 NULLS FIRST
  FETCH FIRST 7 ROWS ONLY
), "_s0" AS (
  SELECT
    PS_PARTKEY,
    PS_SUPPKEY
  FROM TPCH.PARTSUPP
)
SELECT
  "_s2".L_ORDERKEY AS order_key,
  "_s2".L_LINENUMBER AS line_number,
  PART.P_SIZE AS part_size,
  SUPPLIER.S_NATIONKEY AS supplier_nation
FROM "_s2" "_s2"
JOIN "_s0" "_s0"
  ON "_s0".PS_PARTKEY = "_s2".L_PARTKEY AND "_s0".PS_SUPPKEY = "_s2".L_SUPPKEY
JOIN TPCH.PART PART
  ON PART.P_PARTKEY = "_s0".PS_PARTKEY
JOIN "_s0" "_s4"
  ON "_s2".L_PARTKEY = "_s4".PS_PARTKEY AND "_s2".L_SUPPKEY = "_s4".PS_SUPPKEY
JOIN TPCH.SUPPLIER SUPPLIER
  ON SUPPLIER.S_SUPPKEY = "_s4".PS_SUPPKEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
