WITH "_S1" AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    o_custkey
)
SELECT
  CUSTOMER.c_custkey AS customer_key,
  COALESCE("_S1".N_ROWS, 0) AS n_orders
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_S1" "_S1"
  ON CUSTOMER.c_custkey = "_S1".O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
