WITH "_s1" AS (
  SELECT
    PS_PARTKEY,
    PS_SUPPKEY
  FROM TPCH.PARTSUPP
)
SELECT
  LINEITEM.L_ORDERKEY AS order_key,
  LINEITEM.L_LINENUMBER AS line_number,
  PART.P_SIZE AS part_size,
  NATION.N_NATIONKEY AS supplier_nation
FROM TPCH.PART PART
JOIN "_s1" "_s1"
  ON PART.P_PARTKEY = "_s1".PS_PARTKEY
CROSS JOIN TPCH.NATION NATION
JOIN TPCH.SUPPLIER SUPPLIER
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN "_s1" "_s7"
  ON SUPPLIER.S_SUPPKEY = "_s7".PS_SUPPKEY
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
  AND LINEITEM.L_PARTKEY = "_s7".PS_PARTKEY
  AND LINEITEM.L_SUPPKEY = "_s1".PS_SUPPKEY
  AND LINEITEM.L_SUPPKEY = "_s7".PS_SUPPKEY
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
FETCH FIRST 7 ROWS ONLY
