WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
)
SELECT
  CUSTOMER.C_CUSTKEY AS customer_key,
  COALESCE("_s1".N_ROWS, 0) AS n_orders
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 5 ROWS ONLY
