WITH "_S5" AS (
  SELECT
    LINEITEM.l_partkey AS L_PARTKEY,
    SUM(LINEITEM.l_quantity) AS SUM_L_QUANTITY
  FROM TPCH.PART PART
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATE)) = 1994
    AND LINEITEM.l_partkey = PART.p_partkey
  WHERE
    PART.p_name LIKE 'forest%'
  GROUP BY
    LINEITEM.l_partkey
)
SELECT
  ANY_VALUE(SUPPLIER.s_name) AS S_NAME,
  ANY_VALUE(SUPPLIER.s_address) AS S_ADDRESS
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.n_name = 'CANADA' AND NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN TPCH.PARTSUPP PARTSUPP
  ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
JOIN "_S5" "_S5"
  ON PARTSUPP.ps_availqty > (
    0.5 * COALESCE("_S5".SUM_L_QUANTITY, 0)
  )
  AND PARTSUPP.ps_partkey = "_S5".L_PARTKEY
GROUP BY
  PARTSUPP.ps_suppkey
ORDER BY
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
