WITH _T3 AS (
  SELECT
    l_discount AS L_DISCOUNT,
    l_extendedprice AS L_EXTENDEDPRICE,
    l_shipdate AS L_SHIPDATE,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    l_shipdate < TO_DATE('1996-04-01', 'YYYY-MM-DD')
    AND l_shipdate >= TO_DATE('1996-01-01', 'YYYY-MM-DD')
), _T1 AS (
  SELECT
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR
  FROM _T3
  GROUP BY
    L_SUPPKEY
), _S0 AS (
  SELECT
    MAX(NVL(SUM_EXPR, 0)) AS MAX_TOTAL_REVENUE
  FROM _T1
), _S3 AS (
  SELECT
    L_SUPPKEY,
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR
  FROM _T3
  GROUP BY
    L_SUPPKEY
)
SELECT
  SUPPLIER.s_suppkey AS S_SUPPKEY,
  SUPPLIER.s_name AS S_NAME,
  SUPPLIER.s_address AS S_ADDRESS,
  SUPPLIER.s_phone AS S_PHONE,
  NVL(_S3.SUM_EXPR, 0) AS TOTAL_REVENUE
FROM _S0 _S0
CROSS JOIN TPCH.SUPPLIER SUPPLIER
JOIN _S3 _S3
  ON SUPPLIER.s_suppkey = _S3.L_SUPPKEY
  AND _S0.MAX_TOTAL_REVENUE = NVL(_S3.SUM_EXPR, 0)
ORDER BY
  1 NULLS FIRST
