WITH _S0 AS (
  SELECT
    s_nationkey AS S_NATIONKEY,
    s_suppkey AS S_SUPPKEY
  FROM TPCH.SUPPLIER
), _T3 AS (
  SELECT
    n_name AS N_NAME,
    n_nationkey AS N_NATIONKEY
  FROM TPCH.NATION
  WHERE
    n_name = 'GERMANY'
), _S8 AS (
  SELECT
    SUM(PARTSUPP.ps_supplycost * PARTSUPP.ps_availqty) AS SUM_METRIC
  FROM TPCH.PARTSUPP AS PARTSUPP
  JOIN _S0 AS _S0
    ON PARTSUPP.ps_suppkey = _S0.S_SUPPKEY
  JOIN _T3 AS _T3
    ON _S0.S_NATIONKEY = _T3.N_NATIONKEY
), _S9 AS (
  SELECT
    SUM(PARTSUPP.ps_supplycost * PARTSUPP.ps_availqty) AS SUM_EXPR_2,
    PARTSUPP.ps_partkey AS PS_PARTKEY
  FROM TPCH.PARTSUPP AS PARTSUPP
  JOIN _S0 AS _S4
    ON PARTSUPP.ps_suppkey = _S4.S_SUPPKEY
  JOIN _T3 AS _T5
    ON _S4.S_NATIONKEY = _T5.N_NATIONKEY
  GROUP BY
    PARTSUPP.ps_partkey
)
SELECT
  _S9.PS_PARTKEY,
  COALESCE(_S9.SUM_EXPR_2, 0) AS VALUE
FROM _S8 AS _S8
JOIN _S9 AS _S9
  ON (
    COALESCE(_S8.SUM_METRIC, 0) * 0.0001
  ) < COALESCE(_S9.SUM_EXPR_2, 0)
ORDER BY
  COALESCE(_S9.SUM_EXPR_2, 0) DESC NULLS LAST
LIMIT 10
