WITH _u_0 AS (
  SELECT
    l_orderkey AS _u_1
  FROM TPCH.LINEITEM
  WHERE
    l_commitdate < l_receiptdate
  GROUP BY
    1
)
SELECT
  ORDERS.o_orderpriority AS O_ORDERPRIORITY,
  COUNT(*) AS ORDER_COUNT
FROM TPCH.ORDERS AS ORDERS
LEFT JOIN _u_0 AS _u_0
  ON ORDERS.o_orderkey = _u_0._u_1
WHERE
  NOT _u_0._u_1 IS NULL
  AND QUARTER(CAST(ORDERS.o_orderdate AS TIMESTAMP)) = 3
  AND YEAR(CAST(ORDERS.o_orderdate AS TIMESTAMP)) = 1993
GROUP BY
  1
ORDER BY
  1 NULLS FIRST
