WITH "_t5" AS (
  SELECT
    L_COMMITDATE,
    L_LINENUMBER,
    L_ORDERKEY,
    L_RECEIPTDATE,
    L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    L_COMMITDATE < L_RECEIPTDATE
), "_t3" AS (
  SELECT
    "_t5".L_LINENUMBER,
    "_t5".L_ORDERKEY,
    ORDERS.O_ORDERKEY,
    ANY_VALUE("_t5".L_SUPPKEY) AS ANYTHING_L_SUPPKEY,
    ANY_VALUE(ORDERS.O_ORDERSTATUS) AS ANYTHING_O_ORDERSTATUS
  FROM "_t5" "_t5"
  JOIN TPCH.ORDERS ORDERS
    ON ORDERS.O_ORDERKEY = "_t5".L_ORDERKEY
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY AND LINEITEM.L_SUPPKEY <> "_t5".L_SUPPKEY
  GROUP BY
    "_t5".L_LINENUMBER,
    "_t5".L_ORDERKEY,
    ORDERS.O_ORDERKEY
), "_u_0" AS (
  SELECT
    "_t6".L_LINENUMBER AS "_u_1",
    "_t6".L_ORDERKEY AS "_u_2"
  FROM "_t5" "_t6"
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_COMMITDATE < LINEITEM.L_RECEIPTDATE
    AND LINEITEM.L_ORDERKEY = "_t6".L_ORDERKEY
    AND LINEITEM.L_SUPPKEY <> "_t6".L_SUPPKEY
  GROUP BY
    "_t6".L_LINENUMBER,
    "_t6".L_ORDERKEY
), "_s11" AS (
  SELECT
    "_t3".ANYTHING_L_SUPPKEY
  FROM "_t3" "_t3"
  LEFT JOIN "_u_0" "_u_0"
    ON "_t3".L_LINENUMBER = "_u_0"."_u_1"
    AND "_t3".L_ORDERKEY = "_u_0"."_u_2"
    AND "_t3".O_ORDERKEY = "_u_0"."_u_2"
  WHERE
    "_t3".ANYTHING_O_ORDERSTATUS = 'F' AND "_u_0"."_u_1" IS NULL
)
SELECT
  ANY_VALUE(SUPPLIER.S_NAME) AS S_NAME,
  COUNT("_s11".ANYTHING_L_SUPPKEY) AS NUMWAIT
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.N_NAME = 'SAUDI ARABIA' AND NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
LEFT JOIN "_s11" "_s11"
  ON SUPPLIER.S_SUPPKEY = "_s11".ANYTHING_L_SUPPKEY
GROUP BY
  SUPPLIER.S_SUPPKEY
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
