WITH "_s1" AS (
  SELECT
    O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  WHERE
    NOT O_COMMENT LIKE '%special%requests%'
  GROUP BY
    O_CUSTKEY
)
SELECT
  COALESCE("_s1".N_ROWS, 0) AS C_COUNT,
  COUNT(*) AS CUSTDIST
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s1" "_s1"
  ON CUSTOMER.C_CUSTKEY = "_s1".O_CUSTKEY
GROUP BY
  COALESCE("_s1".N_ROWS, 0)
ORDER BY
  2 DESC NULLS LAST,
  1 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
