WITH _S1 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
  WHERE
    NOT o_comment LIKE '%special%requests%'
  GROUP BY
    o_custkey
)
SELECT
  COALESCE(_S1.N_ROWS, 0) AS C_COUNT,
  COUNT(*) AS CUSTDIST
FROM TPCH.CUSTOMER AS CUSTOMER
LEFT JOIN _S1 AS _S1
  ON CUSTOMER.c_custkey = _S1.O_CUSTKEY
GROUP BY
  COALESCE(_S1.N_ROWS, 0)
ORDER BY
  CUSTDIST DESC NULLS LAST,
  COALESCE(_S1.N_ROWS, 0) DESC NULLS LAST
LIMIT 10
