SELECT
  L_RETURNFLAG,
  L_LINESTATUS,
  COALESCE(SUM(L_QUANTITY), 0) AS SUM_QTY,
  COALESCE(SUM(L_EXTENDEDPRICE), 0) AS SUM_BASE_PRICE,
  COALESCE(SUM(L_EXTENDEDPRICE * (
    1 - L_DISCOUNT
  )), 0) AS SUM_DISC_PRICE,
  COALESCE(SUM(L_EXTENDEDPRICE * (
    1 - L_DISCOUNT
  ) * (
    1 + L_TAX
  )), 0) AS SUM_CHARGE,
  AVG(L_QUANTITY) AS AVG_QTY,
  AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
  AVG(L_DISCOUNT) AS AVG_DISC,
  COUNT(*) AS COUNT_ORDER
FROM TPCH.LINEITEM
WHERE
  L_SHIPDATE <= TO_DATE('1998-12-01', 'YYYY-MM-DD')
GROUP BY
  L_LINESTATUS,
  L_RETURNFLAG
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST
