SELECT
  LINEITEM.l_shipmode AS L_SHIPMODE,
  COALESCE(COUNT_IF(ORDERS.o_orderpriority IN ('1-URGENT', '2-HIGH')), 0) AS HIGH_LINE_COUNT,
  COALESCE(COUNT_IF(NOT ORDERS.o_orderpriority IN ('1-URGENT', '2-HIGH')), 0) AS LOW_LINE_COUNT
FROM TPCH.LINEITEM AS LINEITEM
JOIN TPCH.ORDERS AS ORDERS
  ON LINEITEM.l_orderkey = ORDERS.o_orderkey
WHERE
  LINEITEM.l_commitdate < LINEITEM.l_receiptdate
  AND LINEITEM.l_commitdate > LINEITEM.l_shipdate
  AND (
    LINEITEM.l_shipmode = 'MAIL' OR LINEITEM.l_shipmode = 'SHIP'
  )
  AND YEAR(CAST(LINEITEM.l_receiptdate AS TIMESTAMP)) = 1994
GROUP BY
  1
ORDER BY
  1 NULLS FIRST
