WITH _T3 AS (
  SELECT
    l_discount AS L_DISCOUNT,
    l_extendedprice AS L_EXTENDEDPRICE,
    l_shipdate AS L_SHIPDATE,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    l_shipdate < CAST('1996-04-01' AS DATE)
    AND l_shipdate >= CAST('1996-01-01' AS DATE)
), _S1 AS (
  SELECT
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR_2,
    L_SUPPKEY
  FROM _T3
  GROUP BY
    L_SUPPKEY
), _S2 AS (
  SELECT
    MAX(COALESCE(_S1.SUM_EXPR_2, 0)) AS MAX_REVENUE
  FROM TPCH.SUPPLIER AS SUPPLIER
  JOIN _S1 AS _S1
    ON SUPPLIER.s_suppkey = _S1.L_SUPPKEY
), _S5 AS (
  SELECT
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR_3,
    L_SUPPKEY
  FROM _T3
  GROUP BY
    L_SUPPKEY
)
SELECT
  SUPPLIER.s_suppkey AS S_SUPPKEY,
  SUPPLIER.s_name AS S_NAME,
  SUPPLIER.s_address AS S_ADDRESS,
  SUPPLIER.s_phone AS S_PHONE,
  COALESCE(_S5.SUM_EXPR_3, 0) AS TOTAL_REVENUE
FROM _S2 AS _S2
CROSS JOIN TPCH.SUPPLIER AS SUPPLIER
JOIN _S5 AS _S5
  ON SUPPLIER.s_suppkey = _S5.L_SUPPKEY
  AND _S2.MAX_REVENUE = COALESCE(_S5.SUM_EXPR_3, 0)
ORDER BY
  S_SUPPKEY NULLS FIRST
