WITH "_s11" AS (
  SELECT
    NATION.N_NAME,
    SUPPLIER.S_SUPPKEY
  FROM TPCH.SUPPLIER SUPPLIER
  JOIN TPCH.NATION NATION
    ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
)
SELECT
  ANY_VALUE(NATION.N_NAME) AS N_NAME,
  COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS REVENUE
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'ASIA'
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
  AND ORDERS.O_ORDERDATE < TO_DATE('1995-01-01', 'YYYY-MM-DD')
  AND ORDERS.O_ORDERDATE >= TO_DATE('1994-01-01', 'YYYY-MM-DD')
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN "_s11" "_s11"
  ON LINEITEM.L_SUPPKEY = "_s11".S_SUPPKEY AND NATION.N_NAME = "_s11".N_NAME
GROUP BY
  NATION.N_NATIONKEY
ORDER BY
  2 DESC NULLS LAST
