SELECT
  COALESCE(SUM(L_EXTENDEDPRICE * L_DISCOUNT), 0) AS REVENUE
FROM TPCH.LINEITEM
WHERE
  L_DISCOUNT <= 0.07
  AND L_DISCOUNT >= 0.05
  AND L_QUANTITY < 24
  AND L_SHIPDATE < TO_DATE('1995-01-01', 'YYYY-MM-DD')
  AND L_SHIPDATE >= TO_DATE('1994-01-01', 'YYYY-MM-DD')
