WITH _S1 AS (
  SELECT
    COUNT(*) AS AGG_0,
    o_custkey AS CUSTOMER_KEY
  FROM TPCH.ORDERS
  WHERE
    NOT o_comment LIKE '%special%requests%'
  GROUP BY
    o_custkey
), _T0 AS (
  SELECT
    COUNT(*) AS CUSTDIST,
    COALESCE(_S1.AGG_0, 0) AS C_COUNT
  FROM TPCH.CUSTOMER AS CUSTOMER
  LEFT JOIN _S1 AS _S1
    ON CUSTOMER.c_custkey = _S1.CUSTOMER_KEY
  GROUP BY
    COALESCE(_S1.AGG_0, 0)
)
SELECT
  C_COUNT,
  CUSTDIST
FROM _T0
ORDER BY
  CUSTDIST DESC NULLS LAST,
  C_COUNT DESC NULLS LAST
LIMIT 10
