WITH "_s0" AS (
  SELECT
    AVG(C_ACCTBAL) AS AVG_C_ACCTBAL
  FROM TPCH.CUSTOMER
  WHERE
    C_ACCTBAL > 0.0
    AND SUBSTR(C_PHONE, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
), "_u_0" AS (
  SELECT
    O_CUSTKEY AS "_u_1"
  FROM TPCH.ORDERS
  GROUP BY
    O_CUSTKEY
)
SELECT
  SUBSTR(CUSTOMER.C_PHONE, 1, 2) AS CNTRY_CODE,
  COUNT(*) AS NUM_CUSTS,
  COALESCE(SUM(CUSTOMER.C_ACCTBAL), 0) AS TOTACCTBAL
FROM "_s0" "_s0"
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_ACCTBAL > "_s0".AVG_C_ACCTBAL
  AND SUBSTR(CUSTOMER.C_PHONE, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
LEFT JOIN "_u_0" "_u_0"
  ON CUSTOMER.C_CUSTKEY = "_u_0"."_u_1"
WHERE
  "_u_0"."_u_1" IS NULL
GROUP BY
  SUBSTR(CUSTOMER.C_PHONE, 1, 2)
ORDER BY
  1 NULLS FIRST
