WITH "_u_0" AS (
  SELECT
    L_ORDERKEY AS "_u_1"
  FROM TPCH.LINEITEM
  WHERE
    L_COMMITDATE < L_RECEIPTDATE
  GROUP BY
    L_ORDERKEY
)
SELECT
  ORDERS.O_ORDERPRIORITY,
  COUNT(*) AS ORDER_COUNT
FROM TPCH.ORDERS ORDERS
LEFT JOIN "_u_0" "_u_0"
  ON ORDERS.O_ORDERKEY = "_u_0"."_u_1"
WHERE
  EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)) IN (7, 8, 9)
  AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1993
  AND NOT "_u_0"."_u_1" IS NULL
GROUP BY
  ORDERS.O_ORDERPRIORITY
ORDER BY
  1 NULLS FIRST
