WITH "_S3" AS (
  SELECT
    ORDERS.o_custkey AS O_CUSTKEY,
    SUM(LINEITEM.l_extendedprice * (
      1 - LINEITEM.l_discount
    )) AS SUM_EXPR
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey AND LINEITEM.l_returnflag = 'R'
  WHERE
    EXTRACT(MONTH FROM CAST(ORDERS.o_orderdate AS DATE)) IN (10, 11, 12)
    AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1993
  GROUP BY
    ORDERS.o_custkey
)
SELECT
  CUSTOMER.c_custkey AS C_CUSTKEY,
  CUSTOMER.c_name AS C_NAME,
  COALESCE("_S3".SUM_EXPR, 0) AS REVENUE,
  CUSTOMER.c_acctbal AS C_ACCTBAL,
  NATION.n_name AS N_NAME,
  CUSTOMER.c_address AS C_ADDRESS,
  CUSTOMER.c_phone AS C_PHONE,
  CUSTOMER.c_comment AS C_COMMENT
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_S3" "_S3"
  ON CUSTOMER.c_custkey = "_S3".O_CUSTKEY
JOIN TPCH.NATION NATION
  ON CUSTOMER.c_nationkey = NATION.n_nationkey
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 20 ROWS ONLY
