WITH "_t3" AS (
  SELECT
    L_DISCOUNT,
    L_EXTENDEDPRICE,
    L_SHIPDATE,
    L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    L_SHIPDATE < TO_DATE('1996-04-01', 'YYYY-MM-DD')
    AND L_SHIPDATE >= TO_DATE('1996-01-01', 'YYYY-MM-DD')
), "_t1" AS (
  SELECT
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR
  FROM "_t3"
  GROUP BY
    L_SUPPKEY
), "_s0" AS (
  SELECT
    MAX(COALESCE(SUM_EXPR, 0)) AS MAX_TOTAL_REVENUE
  FROM "_t1"
), "_s3" AS (
  SELECT
    L_SUPPKEY,
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS SUM_EXPR
  FROM "_t3"
  GROUP BY
    L_SUPPKEY
)
SELECT
  SUPPLIER.S_SUPPKEY,
  SUPPLIER.S_NAME,
  SUPPLIER.S_ADDRESS,
  SUPPLIER.S_PHONE,
  COALESCE("_s3".SUM_EXPR, 0) AS TOTAL_REVENUE
FROM "_s0" "_s0"
CROSS JOIN TPCH.SUPPLIER SUPPLIER
JOIN "_s3" "_s3"
  ON SUPPLIER.S_SUPPKEY = "_s3".L_SUPPKEY
  AND "_s0".MAX_TOTAL_REVENUE = COALESCE("_s3".SUM_EXPR, 0)
ORDER BY
  1 NULLS FIRST
