WITH "_t" AS (
  SELECT
    LINEITEM.L_EXTENDEDPRICE,
    LINEITEM.L_QUANTITY,
    AVG(CAST(LINEITEM.L_QUANTITY AS DOUBLE PRECISION)) OVER (PARTITION BY LINEITEM.L_PARTKEY) AS "_w"
  FROM TPCH.PART PART
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
  WHERE
    PART.P_BRAND = 'Brand#23' AND PART.P_CONTAINER = 'MED BOX'
)
SELECT
  COALESCE(SUM(L_EXTENDEDPRICE), 0) / 7.0 AS AVG_YEARLY
FROM "_t"
WHERE
  L_QUANTITY < (
    0.2 * "_w"
  )
