WITH "_S11" AS (
  SELECT
    NATION.n_name AS N_NAME,
    SUPPLIER.s_suppkey AS S_SUPPKEY
  FROM TPCH.SUPPLIER SUPPLIER
  JOIN TPCH.NATION NATION
    ON NATION.n_nationkey = SUPPLIER.s_nationkey
)
SELECT
  ANY_VALUE(NATION.n_name) AS N_NAME,
  NVL(SUM(LINEITEM.l_extendedprice * (
    1 - LINEITEM.l_discount
  )), 0) AS REVENUE
FROM TPCH.NATION NATION
JOIN TPCH.REGION REGION
  ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'ASIA'
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_nationkey = NATION.n_nationkey
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.c_custkey = ORDERS.o_custkey
  AND ORDERS.o_orderdate < TO_DATE('1995-01-01', 'YYYY-MM-DD')
  AND ORDERS.o_orderdate >= TO_DATE('1994-01-01', 'YYYY-MM-DD')
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.l_orderkey = ORDERS.o_orderkey
JOIN "_S11" "_S11"
  ON LINEITEM.l_suppkey = "_S11".S_SUPPKEY AND NATION.n_name = "_S11".N_NAME
GROUP BY
  NATION.n_nationkey
ORDER BY
  2 DESC NULLS LAST
