SELECT
  NATION.n_name AS NATION,
  DATE_PART(YEAR, CAST(ORDERS.o_orderdate AS DATETIME)) AS O_YEAR,
  COALESCE(
    SUM(
      LINEITEM.l_extendedprice * (
        1 - LINEITEM.l_discount
      ) - PARTSUPP.ps_supplycost * LINEITEM.l_quantity
    ),
    0
  ) AS AMOUNT
FROM TPCH.LINEITEM AS LINEITEM
JOIN TPCH.PART AS PART
  ON LINEITEM.l_partkey = PART.p_partkey AND PART.p_name LIKE '%green%'
JOIN TPCH.SUPPLIER AS SUPPLIER
  ON LINEITEM.l_suppkey = SUPPLIER.s_suppkey
JOIN TPCH.NATION AS NATION
  ON NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN TPCH.ORDERS AS ORDERS
  ON LINEITEM.l_orderkey = ORDERS.o_orderkey
JOIN TPCH.PARTSUPP AS PARTSUPP
  ON LINEITEM.l_partkey = PARTSUPP.ps_partkey
  AND LINEITEM.l_suppkey = PARTSUPP.ps_suppkey
GROUP BY
  NATION.n_name,
  DATE_PART(YEAR, CAST(ORDERS.o_orderdate AS DATETIME))
ORDER BY
  NATION.n_name NULLS FIRST,
  O_YEAR DESC NULLS LAST
LIMIT 10
