WITH _S0 AS (
  SELECT
    SUPPLIER.s_suppkey AS KEY,
    SUPPLIER.s_name AS NAME,
    SUPPLIER.s_nationkey AS NATION_KEY
  FROM TPCH.SUPPLIER AS SUPPLIER
), _T2 AS (
  SELECT
    NATION.n_nationkey AS KEY,
    NATION.n_name AS NAME
  FROM TPCH.NATION AS NATION
), _S1 AS (
  SELECT
    _T2.KEY AS KEY
  FROM _T2 AS _T2
  WHERE
    _T2.NAME = 'SAUDI ARABIA'
), _S8 AS (
  SELECT
    _S0.KEY AS KEY,
    _S0.NAME AS NAME
  FROM _S0 AS _S0
  JOIN _S1 AS _S1
    ON _S0.NATION_KEY = _S1.KEY
), _T4 AS (
  SELECT
    LINEITEM.l_commitdate AS COMMIT_DATE,
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_receiptdate AS RECEIPT_DATE,
    LINEITEM.l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM AS LINEITEM
), _S4 AS (
  SELECT
    _T4.SUPPLIER_KEY AS ORIGINAL_KEY,
    _T4.ORDER_KEY AS ORDER_KEY,
    _T4.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _T4 AS _T4
  WHERE
    _T4.COMMIT_DATE < _T4.RECEIPT_DATE
), _T5 AS (
  SELECT
    ORDERS.o_orderkey AS KEY,
    ORDERS.o_orderstatus AS ORDER_STATUS
  FROM TPCH.ORDERS AS ORDERS
), _S5 AS (
  SELECT
    _T5.KEY AS KEY
  FROM _T5 AS _T5
  WHERE
    _T5.ORDER_STATUS = 'F'
), _S3 AS (
  SELECT
    _S5.KEY AS KEY,
    _S4.ORIGINAL_KEY AS ORIGINAL_KEY,
    _S4.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _S4 AS _S4
  JOIN _S5 AS _S5
    ON _S4.ORDER_KEY = _S5.KEY
), _T6 AS (
  SELECT
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM AS LINEITEM
), _S6 AS (
  SELECT
    _T6.ORDER_KEY AS ORDER_KEY
  FROM _T6 AS _T6
  WHERE
    _S3.ORIGINAL_KEY <> _T6.SUPPLIER_KEY
), _S2 AS (
  SELECT
    _S3.KEY AS KEY,
    _S3.ORIGINAL_KEY AS ORIGINAL_KEY,
    _S3.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _S3 AS _S3
  WHERE
    EXISTS(
      SELECT
        1 AS "1"
      FROM _S6 AS _S6
      WHERE
        _S3.KEY = _S6.ORDER_KEY
    )
), _S7 AS (
  SELECT
    _T7.ORDER_KEY AS ORDER_KEY
  FROM _T4 AS _T7
  WHERE
    _S2.ORIGINAL_KEY <> _T7.SUPPLIER_KEY AND _T7.COMMIT_DATE < _T7.RECEIPT_DATE
), _T3 AS (
  SELECT
    _S2.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _S2 AS _S2
  WHERE
    NOT EXISTS(
      SELECT
        1 AS "1"
      FROM _S7 AS _S7
      WHERE
        _S2.KEY = _S7.ORDER_KEY
    )
), _S9 AS (
  SELECT
    COUNT(*) AS AGG_0,
    _T3.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _T3 AS _T3
  GROUP BY
    _T3.SUPPLIER_KEY
), _T1 AS (
  SELECT
    _S9.AGG_0 AS AGG_0,
    _S8.NAME AS NAME
  FROM _S8 AS _S8
  LEFT JOIN _S9 AS _S9
    ON _S8.KEY = _S9.SUPPLIER_KEY
), _T0 AS (
  SELECT
    COALESCE(_T1.AGG_0, 0) AS NUMWAIT,
    _T1.NAME AS S_NAME
  FROM _T1 AS _T1
)
SELECT
  _T0.S_NAME AS S_NAME,
  _T0.NUMWAIT AS NUMWAIT
FROM _T0 AS _T0
ORDER BY
  NUMWAIT DESC NULLS LAST,
  S_NAME NULLS FIRST
LIMIT 10
