SELECT
  ORDERS.o_orderpriority AS O_ORDERPRIORITY,
  COUNT(*) AS ORDER_COUNT
FROM TPCH.ORDERS ORDERS
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.l_commitdate < LINEITEM.l_receiptdate
  AND LINEITEM.l_orderkey = ORDERS.o_orderkey
WHERE
  EXTRACT(MONTH FROM CAST(ORDERS.o_orderdate AS DATE)) IN (7, 8, 9)
  AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1993
GROUP BY
  ORDERS.o_orderpriority
ORDER BY
  1 NULLS FIRST
