WITH _T4 AS (
  SELECT
    l_discount AS DISCOUNT,
    l_extendedprice AS EXTENDED_PRICE,
    l_shipdate AS SHIP_DATE,
    l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM
), _T1 AS (
  SELECT
    SUM(EXTENDED_PRICE * (
      1 - DISCOUNT
    )) AS AGG_0,
    SUPPLIER_KEY
  FROM _T4
  WHERE
    SHIP_DATE < CAST('1996-04-01' AS DATE)
    AND SHIP_DATE >= CAST('1996-01-01' AS DATE)
  GROUP BY
    SUPPLIER_KEY
), _S2 AS (
  SELECT
    MAX(COALESCE(_T1.AGG_0, 0)) AS MAX_REVENUE
  FROM TPCH.SUPPLIER AS SUPPLIER
  JOIN _T1 AS _T1
    ON SUPPLIER.s_suppkey = _T1.SUPPLIER_KEY
), _T5 AS (
  SELECT
    SUM(EXTENDED_PRICE * (
      1 - DISCOUNT
    )) AS AGG_1,
    SUPPLIER_KEY
  FROM _T4
  WHERE
    SHIP_DATE < CAST('1996-04-01' AS DATE)
    AND SHIP_DATE >= CAST('1996-01-01' AS DATE)
  GROUP BY
    SUPPLIER_KEY
)
SELECT
  SUPPLIER.s_suppkey AS S_SUPPKEY,
  SUPPLIER.s_name AS S_NAME,
  SUPPLIER.s_address AS S_ADDRESS,
  SUPPLIER.s_phone AS S_PHONE,
  COALESCE(_T5.AGG_1, 0) AS TOTAL_REVENUE
FROM _S2 AS _S2
CROSS JOIN TPCH.SUPPLIER AS SUPPLIER
JOIN _T5 AS _T5
  ON SUPPLIER.s_suppkey = _T5.SUPPLIER_KEY
  AND _S2.MAX_REVENUE = COALESCE(_T5.AGG_1, 0)
ORDER BY
  S_SUPPKEY NULLS FIRST
