SELECT
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS O_YEAR,
  COALESCE(
    SUM(
      CASE
        WHEN NATION_2.N_NAME = 'BRAZIL'
        THEN LINEITEM.L_EXTENDEDPRICE * (
          1 - LINEITEM.L_DISCOUNT
        )
        ELSE 0
      END
    ),
    0
  ) / COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS MKT_SHARE
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.PART PART
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY AND PART.P_TYPE = 'ECONOMY ANODIZED STEEL'
JOIN TPCH.ORDERS ORDERS
  ON EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) IN (1995, 1996)
  AND LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
JOIN TPCH.NATION NATION
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
JOIN TPCH.REGION REGION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AMERICA'
JOIN TPCH.SUPPLIER SUPPLIER
  ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN TPCH.NATION NATION_2
  ON NATION_2.N_NATIONKEY = SUPPLIER.S_NATIONKEY
GROUP BY
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE))
