WITH _T1 AS (
  SELECT
    SUPPLIER.s_comment AS COMMENT_8,
    SUPPLIER.s_name AS NAME_10,
    PART.p_mfgr AS P_MFGR,
    PART.p_partkey AS P_PARTKEY,
    SUPPLIER.s_acctbal AS ACCOUNT_BALANCE,
    SUPPLIER.s_address AS ADDRESS,
    NATION.n_name AS EXPR_8,
    SUPPLIER.s_phone AS PHONE
  FROM TPCH.PART AS PART
  JOIN TPCH.PARTSUPP AS PARTSUPP
    ON PART.p_partkey = PARTSUPP.ps_partkey
  JOIN TPCH.SUPPLIER AS SUPPLIER
    ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
  JOIN TPCH.NATION AS NATION
    ON NATION.n_nationkey = SUPPLIER.s_nationkey
  JOIN TPCH.REGION AS REGION
    ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'EUROPE'
  WHERE
    ENDSWITH(PART.p_type, 'BRASS') AND PART.p_size = 15
  QUALIFY
    RANK() OVER (PARTITION BY PARTSUPP.ps_partkey ORDER BY PARTSUPP.ps_supplycost) = 1
)
SELECT
  ACCOUNT_BALANCE AS S_ACCTBAL,
  NAME_10 AS S_NAME,
  EXPR_8 AS N_NAME,
  P_PARTKEY,
  P_MFGR,
  ADDRESS AS S_ADDRESS,
  PHONE AS S_PHONE,
  COMMENT_8 AS S_COMMENT
FROM _T1
ORDER BY
  S_ACCTBAL DESC NULLS LAST,
  N_NAME NULLS FIRST,
  S_NAME NULLS FIRST,
  P_PARTKEY NULLS FIRST
LIMIT 10
