WITH _S3 AS (
  SELECT
    SUM(l_quantity) AS SUM_L_QUANTITY,
    l_partkey AS L_PARTKEY
  FROM TPCH.LINEITEM
  WHERE
    YEAR(CAST(l_shipdate AS TIMESTAMP)) = 1994
  GROUP BY
    l_partkey
), _S5 AS (
  SELECT
    PART.p_partkey AS P_PARTKEY,
    _S3.SUM_L_QUANTITY
  FROM TPCH.PART AS PART
  JOIN _S3 AS _S3
    ON PART.p_partkey = _S3.L_PARTKEY
  WHERE
    STARTSWITH(PART.p_name, 'forest')
), _S7 AS (
  SELECT DISTINCT
    PARTSUPP.ps_suppkey AS PS_SUPPKEY
  FROM TPCH.PARTSUPP AS PARTSUPP
  JOIN _S5 AS _S5
    ON PARTSUPP.ps_availqty > (
      0.5 * COALESCE(_S5.SUM_L_QUANTITY, 0)
    )
    AND PARTSUPP.ps_partkey = _S5.P_PARTKEY
)
SELECT
  SUPPLIER.s_name AS S_NAME,
  SUPPLIER.s_address AS S_ADDRESS
FROM TPCH.SUPPLIER AS SUPPLIER
JOIN TPCH.NATION AS NATION
  ON NATION.n_name = 'CANADA' AND NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN _S7 AS _S7
  ON SUPPLIER.s_suppkey = _S7.PS_SUPPKEY
ORDER BY
  S_NAME NULLS FIRST
LIMIT 10
