WITH _T7 AS (
  SELECT
    l_commitdate AS L_COMMITDATE,
    l_linenumber AS L_LINENUMBER,
    l_orderkey AS L_ORDERKEY,
    l_receiptdate AS L_RECEIPTDATE,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    _T2.NAME = 'SAUDI ARABIA'
), _S12 AS (
  SELECT
    _S0.KEY AS KEY,
    _S0.NAME AS NAME
  FROM _S0 AS _S0
  JOIN _S1 AS _S1
    ON _S0.NATION_KEY = _S1.KEY
), _T7 AS (
  SELECT
    LINEITEM.l_commitdate AS COMMIT_DATE,
    LINEITEM.l_linenumber AS LINE_NUMBER,
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_receiptdate AS RECEIPT_DATE,
    LINEITEM.l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM AS LINEITEM
), _S2 AS (
  SELECT
    _T7.SUPPLIER_KEY AS ORIGINAL_KEY,
    _T7.LINE_NUMBER AS LINE_NUMBER,
    _T7.ORDER_KEY AS ORDER_KEY,
    _T7.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _T7 AS _T7
  WHERE
    _T7.COMMIT_DATE < _T7.RECEIPT_DATE
), _S3 AS (
  SELECT
    ORDERS.o_orderkey AS KEY,
    ORDERS.o_orderstatus AS ORDER_STATUS
  FROM TPCH.ORDERS AS ORDERS
), _S4 AS (
  SELECT
    _S3.KEY AS KEY,
    _S2.LINE_NUMBER AS LINE_NUMBER,
    _S2.ORDER_KEY AS ORDER_KEY,
    _S3.ORDER_STATUS AS ORDER_STATUS,
    _S2.ORIGINAL_KEY AS ORIGINAL_KEY,
    _S2.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _S2 AS _S2
  JOIN _S3 AS _S3
    ON _S2.ORDER_KEY = _S3.KEY
), _S5 AS (
  SELECT
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM AS LINEITEM
), _T6 AS (
  SELECT
    _S4.ORDER_KEY AS ORDER_KEY,
    _S4.SUPPLIER_KEY AS SUPPLIER_KEY,
    _S5.SUPPLIER_KEY AS SUPPLIER_KEY_19,
    _S4.KEY AS KEY,
    _S4.LINE_NUMBER AS LINE_NUMBER,
    _S4.ORDER_STATUS AS ORDER_STATUS,
    _S4.ORIGINAL_KEY AS ORIGINAL_KEY
  FROM _S4 AS _S4
  JOIN _S5 AS _S5
    ON _S4.KEY = _S5.ORDER_KEY
), _T5 AS (
  SELECT
    _T6.KEY AS KEY,
    _T6.LINE_NUMBER AS LINE_NUMBER,
    _T6.ORDER_KEY AS ORDER_KEY,
    _T6.ORDER_STATUS AS ORDER_STATUS,
    _T6.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _T6 AS _T6
  WHERE
    _T6.ORIGINAL_KEY <> _T6.SUPPLIER_KEY_19
), _T4 AS (
  SELECT
    ANY_VALUE(_T5.LINE_NUMBER) AS AGG_13,
    ANY_VALUE(_T5.ORDER_KEY) AS AGG_14,
    ANY_VALUE(_T5.SUPPLIER_KEY) AS AGG_24,
    ANY_VALUE(_T5.KEY) AS AGG_3,
    ANY_VALUE(_T5.ORDER_STATUS) AS AGG_6
  FROM _T5 AS _T5
  GROUP BY
    _T5.KEY,
    _T5.LINE_NUMBER,
    _T5.ORDER_KEY
), _S10 AS (
  SELECT
    _T4.AGG_13 AS AGG_13,
    _T4.AGG_14 AS AGG_14,
    _T4.AGG_24 AS AGG_24,
    _T4.AGG_3 AS AGG_3
  FROM _T4 AS _T4
  WHERE
    _T4.AGG_6 = 'F'
), _S6 AS (
  SELECT
    _T9.SUPPLIER_KEY AS ORIGINAL_KEY,
    _T9.LINE_NUMBER AS LINE_NUMBER,
    _T9.ORDER_KEY AS ORDER_KEY
  FROM _T7 AS _T9
  WHERE
    _T9.COMMIT_DATE < _T9.RECEIPT_DATE
), _S7 AS (
  SELECT
    ORDERS.o_orderkey AS KEY
  FROM TPCH.ORDERS AS ORDERS
), _S8 AS (
  SELECT
    _S7.KEY AS KEY,
    _S6.LINE_NUMBER AS LINE_NUMBER,
    _S6.ORDER_KEY AS ORDER_KEY,
    _S6.ORIGINAL_KEY AS ORIGINAL_KEY
  FROM _S6 AS _S6
  JOIN _S7 AS _S7
    ON _S6.ORDER_KEY = _S7.KEY
), _T10 AS (
  SELECT
    LINEITEM.l_commitdate AS COMMIT_DATE,
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_receiptdate AS RECEIPT_DATE,
    LINEITEM.l_suppkey AS SUPPLIER_KEY
  FROM TPCH.LINEITEM AS LINEITEM
), _S9 AS (
  SELECT
    _T10.ORDER_KEY AS ORDER_KEY,
    _T10.SUPPLIER_KEY AS SUPPLIER_KEY
  FROM _T10 AS _T10
  WHERE
    _T10.COMMIT_DATE < _T10.RECEIPT_DATE
), _T8 AS (
  SELECT
    _S8.ORDER_KEY AS ORDER_KEY,
    _S9.SUPPLIER_KEY AS SUPPLIER_KEY_36,
    _S8.KEY AS KEY,
    _S8.LINE_NUMBER AS LINE_NUMBER,
    _S8.ORIGINAL_KEY AS ORIGINAL_KEY
  FROM _S8 AS _S8
  JOIN _S9 AS _S9
    ON _S8.KEY = _S9.ORDER_KEY
), _S11 AS (
  SELECT
    _T8.KEY AS KEY,
    _T8.LINE_NUMBER AS LINE_NUMBER,
    _T8.ORDER_KEY AS ORDER_KEY
  FROM _T8 AS _T8
  WHERE
    _T8.ORIGINAL_KEY <> _T8.SUPPLIER_KEY_36
), _T3 AS (
  SELECT
    _S10.AGG_24 AS AGG_24
  FROM _S10 AS _S10
  WHERE
    NOT EXISTS(
      SELECT
        1 AS "1"
      FROM _S11 AS _S11
      WHERE
        _S10.AGG_13 = _S11.LINE_NUMBER
        AND _S10.AGG_14 = _S11.ORDER_KEY
        AND _S10.AGG_3 = _S11.KEY
    )
), _S13 AS (
  SELECT
    COUNT(*) AS AGG_0,
    _T3.AGG_24 AS AGG_24
  FROM _T3 AS _T3
  GROUP BY
    _T3.AGG_24
), _T1 AS (
  SELECT
    _S13.AGG_0 AS AGG_0,
    _S12.NAME AS NAME
  FROM _S12 AS _S12
  LEFT JOIN _S13 AS _S13
    ON _S12.KEY = _S13.AGG_24
), _T0 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _T4.ANYTHING_L_SUPPKEY
  FROM _T4 AS _T4
  LEFT JOIN _u_0 AS _u_0
    ON _T4.ANYTHING_L_LINENUMBER = _u_0._u_1
    AND _T4.ANYTHING_L_ORDERKEY = _u_0._u_2
    AND _T4.ANYTHING_O_ORDERKEY = _u_0._u_3
  WHERE
    _T4.ANYTHING_O_ORDERSTATUS = 'F' AND _u_0._u_1 IS NULL
  GROUP BY
    _T4.ANYTHING_L_SUPPKEY
)
SELECT
  SUPPLIER.s_name AS S_NAME,
  COALESCE(_S13.N_ROWS, 0) AS NUMWAIT
FROM TPCH.SUPPLIER AS SUPPLIER
JOIN TPCH.NATION AS NATION
  ON NATION.n_name = 'SAUDI ARABIA' AND NATION.n_nationkey = SUPPLIER.s_nationkey
LEFT JOIN _S13 AS _S13
  ON SUPPLIER.s_suppkey = _S13.ANYTHING_L_SUPPKEY
ORDER BY
  NUMWAIT DESC NULLS LAST,
  S_NAME NULLS FIRST
LIMIT 10
