WITH "_s9" AS (
  SELECT
    NATION.N_NAME,
    ORDERS.O_ORDERKEY
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
    AND (
      NATION.N_NAME = 'FRANCE' OR NATION.N_NAME = 'GERMANY'
    )
)
SELECT
  NATION.N_NAME AS SUPP_NATION,
  "_s9".N_NAME AS CUST_NATION,
  EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) AS L_YEAR,
  COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS REVENUE
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.SUPPLIER SUPPLIER
  ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN TPCH.NATION NATION
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN "_s9" "_s9"
  ON LINEITEM.L_ORDERKEY = "_s9".O_ORDERKEY
  AND (
    NATION.N_NAME = 'FRANCE' OR NATION.N_NAME = 'GERMANY'
  )
  AND (
    NATION.N_NAME = 'FRANCE' OR "_s9".N_NAME = 'FRANCE'
  )
  AND (
    NATION.N_NAME = 'GERMANY' OR "_s9".N_NAME = 'GERMANY'
  )
WHERE
  EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) IN (1995, 1996)
GROUP BY
  EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)),
  "_s9".N_NAME,
  NATION.N_NAME
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST
