WITH _T0 AS (
  SELECT
    SUM(l_quantity) AS AGG_0,
    l_orderkey AS ORDER_KEY
  FROM TPCH.LINEITEM
  GROUP BY
    l_orderkey
)
SELECT
  CUSTOMER.c_name AS C_NAME,
  CUSTOMER.c_custkey AS C_CUSTKEY,
  ORDERS.o_orderkey AS O_ORDERKEY,
  ORDERS.o_orderdate AS O_ORDERDATE,
  ORDERS.o_totalprice AS O_TOTALPRICE,
  COALESCE(_T0.AGG_0, 0) AS TOTAL_QUANTITY
FROM TPCH.ORDERS AS ORDERS
JOIN TPCH.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey
JOIN _T0 AS _T0
  ON ORDERS.o_orderkey = _T0.ORDER_KEY
WHERE
  NOT _T0.AGG_0 IS NULL AND _T0.AGG_0 > 300
ORDER BY
  O_TOTALPRICE DESC NULLS LAST,
  O_ORDERDATE NULLS FIRST
LIMIT 10
