WITH "_t" AS (
  SELECT
    NATION.N_NAME,
    PART.P_MFGR,
    PART.P_PARTKEY,
    SUPPLIER.S_ACCTBAL,
    SUPPLIER.S_ADDRESS,
    SUPPLIER.S_COMMENT,
    SUPPLIER.S_NAME,
    SUPPLIER.S_PHONE,
    RANK() OVER (PARTITION BY PARTSUPP.PS_PARTKEY ORDER BY PARTSUPP.PS_SUPPLYCOST) AS "_w"
  FROM TPCH.PART PART
  JOIN TPCH.PARTSUPP PARTSUPP
    ON PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
  JOIN TPCH.SUPPLIER SUPPLIER
    ON PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
  JOIN TPCH.NATION NATION
    ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
  JOIN TPCH.REGION REGION
    ON NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'EUROPE'
  WHERE
    PART.P_SIZE = 15 AND PART.P_TYPE LIKE '%BRASS'
)
SELECT
  S_ACCTBAL,
  S_NAME,
  N_NAME,
  P_PARTKEY,
  P_MFGR,
  S_ADDRESS,
  S_PHONE,
  S_COMMENT
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 DESC NULLS LAST,
  3 NULLS FIRST,
  2 NULLS FIRST,
  4 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
