WITH _S1 AS (
  SELECT
    n_name AS N_NAME,
    n_nationkey AS N_NATIONKEY
  FROM TPCH.NATION
  WHERE
    n_name = 'FRANCE' OR n_name = 'GERMANY'
), _S9 AS (
  SELECT
    _S7.N_NAME,
    ORDERS.o_orderkey AS O_ORDERKEY
  FROM TPCH.ORDERS AS ORDERS
  JOIN TPCH.CUSTOMER AS CUSTOMER
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
  JOIN _S1 AS _S7
    ON CUSTOMER.c_nationkey = _S7.N_NATIONKEY
)
SELECT
  _S1.N_NAME AS SUPP_NATION,
  _S9.N_NAME AS CUST_NATION,
  YEAR(LINEITEM.l_shipdate) AS L_YEAR,
  COALESCE(SUM(LINEITEM.l_extendedprice * (
    1 - LINEITEM.l_discount
  )), 0) AS REVENUE
FROM TPCH.LINEITEM AS LINEITEM
JOIN TPCH.SUPPLIER AS SUPPLIER
  ON LINEITEM.l_suppkey = SUPPLIER.s_suppkey
JOIN _S1 AS _S1
  ON SUPPLIER.s_nationkey = _S1.N_NATIONKEY
JOIN _S9 AS _S9
  ON LINEITEM.l_orderkey = _S9.O_ORDERKEY
  AND (
    _S1.N_NAME = 'FRANCE' OR _S9.N_NAME = 'FRANCE'
  )
  AND (
    _S1.N_NAME = 'GERMANY' OR _S9.N_NAME = 'GERMANY'
  )
WHERE
  YEAR(LINEITEM.l_shipdate) IN (1995, 1996)
GROUP BY
  YEAR(LINEITEM.l_shipdate),
  _S9.N_NAME,
  _S1.N_NAME
ORDER BY
  _S1.N_NAME NULLS FIRST,
  CUST_NATION NULLS FIRST,
  L_YEAR NULLS FIRST
