WITH "_s5" AS (
  SELECT
    LINEITEM.L_PARTKEY AS P_PARTKEY,
    SUM(LINEITEM.L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.PART PART
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1994
    AND LINEITEM.L_PARTKEY = PART.P_PARTKEY
  WHERE
    PART.P_NAME LIKE 'forest%'
  GROUP BY
    LINEITEM.L_PARTKEY
)
SELECT
  ANY_VALUE(SUPPLIER.S_NAME) AS S_NAME,
  ANY_VALUE(SUPPLIER.S_ADDRESS) AS S_ADDRESS
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.N_NAME = 'CANADA' AND NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN TPCH.PARTSUPP PARTSUPP
  ON PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN "_s5" "_s5"
  ON PARTSUPP.PS_AVAILQTY > (
    0.5 * COALESCE("_s5".SUM_L_QUANTITY, 0)
  )
  AND PARTSUPP.PS_PARTKEY = "_s5".P_PARTKEY
GROUP BY
  PARTSUPP.PS_SUPPKEY
ORDER BY
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
