WITH "_S9" AS (
  SELECT
    NATION.n_name AS N_NAME,
    ORDERS.o_orderkey AS O_ORDERKEY
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey
    AND (
      NATION.n_name = 'FRANCE' OR NATION.n_name = 'GERMANY'
    )
)
SELECT
  NATION.n_name AS SUPP_NATION,
  "_S9".N_NAME AS CUST_NATION,
  EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATETIME)) AS L_YEAR,
  NVL(SUM(LINEITEM.l_extendedprice * (
    1 - LINEITEM.l_discount
  )), 0) AS REVENUE
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.SUPPLIER SUPPLIER
  ON LINEITEM.l_suppkey = SUPPLIER.s_suppkey
JOIN TPCH.NATION NATION
  ON NATION.n_nationkey = SUPPLIER.s_nationkey
JOIN "_S9" "_S9"
  ON LINEITEM.l_orderkey = "_S9".O_ORDERKEY
  AND (
    NATION.n_name = 'FRANCE' OR NATION.n_name = 'GERMANY'
  )
  AND (
    NATION.n_name = 'FRANCE' OR "_S9".N_NAME = 'FRANCE'
  )
  AND (
    NATION.n_name = 'GERMANY' OR "_S9".N_NAME = 'GERMANY'
  )
WHERE
  EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATETIME)) IN (1995, 1996)
GROUP BY
  EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATETIME)),
  "_S9".N_NAME,
  NATION.n_name
ORDER BY
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST
