WITH "_T5" AS (
  SELECT
    l_commitdate AS L_COMMITDATE,
    l_linenumber AS L_LINENUMBER,
    l_orderkey AS L_ORDERKEY,
    l_receiptdate AS L_RECEIPTDATE,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    l_commitdate < l_receiptdate
), "_T3" AS (
  SELECT
    "_T5".L_LINENUMBER,
    "_T5".L_ORDERKEY,
    ORDERS.o_orderkey AS O_ORDERKEY,
    ANY_VALUE("_T5".L_SUPPKEY) AS ANYTHING_L_SUPPKEY,
    ANY_VALUE(ORDERS.o_orderstatus) AS ANYTHING_O_ORDERSTATUS
  FROM "_T5" "_T5"
  JOIN TPCH.ORDERS ORDERS
    ON ORDERS.o_orderkey = "_T5".L_ORDERKEY
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey AND LINEITEM.l_suppkey <> "_T5".L_SUPPKEY
  GROUP BY
    "_T5".L_LINENUMBER,
    "_T5".L_ORDERKEY,
    ORDERS.o_orderkey
), "_S11" AS (
  SELECT
    "_T3".ANYTHING_L_SUPPKEY
  FROM "_T3" "_T3"
  JOIN "_T5" "_T6"
    ON "_T3".L_LINENUMBER = "_T6".L_LINENUMBER
    AND "_T3".L_ORDERKEY = "_T6".L_ORDERKEY
    AND "_T3".O_ORDERKEY = "_T6".L_ORDERKEY
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.l_commitdate < LINEITEM.l_receiptdate
    AND LINEITEM.l_orderkey = "_T6".L_ORDERKEY
    AND LINEITEM.l_suppkey <> "_T6".L_SUPPKEY
  WHERE
    "_T3".ANYTHING_O_ORDERSTATUS = 'F'
)
SELECT
  ANY_VALUE(SUPPLIER.s_name) AS S_NAME,
  NVL(NULLIF(COUNT("_S11".ANYTHING_L_SUPPKEY), 0), 0) AS NUMWAIT
FROM TPCH.SUPPLIER SUPPLIER
JOIN TPCH.NATION NATION
  ON NATION.n_name = 'SAUDI ARABIA' AND NATION.n_nationkey = SUPPLIER.s_nationkey
LEFT JOIN "_S11" "_S11"
  ON SUPPLIER.s_suppkey = "_S11".ANYTHING_L_SUPPKEY
GROUP BY
  SUPPLIER.s_suppkey
ORDER BY
  2 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
