WITH _T6 AS (
  SELECT
    l_commitdate AS L_COMMITDATE,
    l_linenumber AS L_LINENUMBER,
    l_orderkey AS L_ORDERKEY,
    l_receiptdate AS L_RECEIPTDATE,
    l_suppkey AS L_SUPPKEY
  FROM TPCH.LINEITEM
  WHERE
    l_commitdate < l_receiptdate
), _T3 AS (
  SELECT
    ANY_VALUE(_T6.L_LINENUMBER) AS ANYTHING_L_LINENUMBER,
    ANY_VALUE(_T6.L_ORDERKEY) AS ANYTHING_L_ORDERKEY,
    ANY_VALUE(_T6.L_SUPPKEY) AS ANYTHING_L_SUPPKEY,
    ANY_VALUE(ORDERS.o_orderkey) AS ANYTHING_O_ORDERKEY,
    ANY_VALUE(ORDERS.o_orderstatus) AS ANYTHING_O_ORDERSTATUS
  FROM _T6 AS _T6
  JOIN TPCH.ORDERS AS ORDERS
    ON ORDERS.o_orderkey = _T6.L_ORDERKEY
  JOIN TPCH.LINEITEM AS LINEITEM
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey AND LINEITEM.l_suppkey <> _T6.L_SUPPKEY
  GROUP BY
    _T6.L_LINENUMBER,
    _T6.L_ORDERKEY,
    ORDERS.o_orderkey
), _u_0 AS (
  SELECT
    _T8.L_LINENUMBER AS _u_1,
    _T8.L_ORDERKEY AS _u_2,
    ORDERS.o_orderkey AS _u_3
  FROM _T6 AS _T8
  JOIN TPCH.ORDERS AS ORDERS
    ON ORDERS.o_orderkey = _T8.L_ORDERKEY
  JOIN TPCH.LINEITEM AS LINEITEM
    ON LINEITEM.l_commitdate < LINEITEM.l_receiptdate
    AND LINEITEM.l_orderkey = ORDERS.o_orderkey
    AND LINEITEM.l_suppkey <> _T8.L_SUPPKEY
  GROUP BY
    _T8.L_LINENUMBER,
    _T8.L_ORDERKEY,
    ORDERS.o_orderkey
), _S13 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    _T3.ANYTHING_L_SUPPKEY
  FROM _T3 AS _T3
  LEFT JOIN _u_0 AS _u_0
    ON _T3.ANYTHING_L_LINENUMBER = _u_0._u_1
    AND _T3.ANYTHING_L_ORDERKEY = _u_0._u_2
    AND _T3.ANYTHING_O_ORDERKEY = _u_0._u_3
  WHERE
    _T3.ANYTHING_O_ORDERSTATUS = 'F' AND _u_0._u_1 IS NULL
  GROUP BY
    _T3.ANYTHING_L_SUPPKEY
)
SELECT
  SUPPLIER.s_name AS S_NAME,
  COALESCE(_S13.N_ROWS, 0) AS NUMWAIT
FROM TPCH.SUPPLIER AS SUPPLIER
JOIN TPCH.NATION AS NATION
  ON NATION.n_name = 'SAUDI ARABIA' AND NATION.n_nationkey = SUPPLIER.s_nationkey
LEFT JOIN _S13 AS _S13
  ON SUPPLIER.s_suppkey = _S13.ANYTHING_L_SUPPKEY
ORDER BY
  COALESCE(_S13.N_ROWS, 0) DESC NULLS LAST,
  S_NAME NULLS FIRST
LIMIT 10
