SELECT
  LINEITEM.L_SHIPMODE,
  COALESCE(SUM(ORDERS.O_ORDERPRIORITY IN ('1-URGENT', '2-HIGH')), 0) AS HIGH_LINE_COUNT,
  COALESCE(SUM(NOT ORDERS.O_ORDERPRIORITY IN ('1-URGENT', '2-HIGH')), 0) AS LOW_LINE_COUNT
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.ORDERS ORDERS
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
WHERE
  EXTRACT(YEAR FROM CAST(LINEITEM.L_RECEIPTDATE AS DATE)) = 1994
  AND LINEITEM.L_COMMITDATE < LINEITEM.L_RECEIPTDATE
  AND LINEITEM.L_COMMITDATE > LINEITEM.L_SHIPDATE
  AND (
    LINEITEM.L_SHIPMODE = 'MAIL' OR LINEITEM.L_SHIPMODE = 'SHIP'
  )
GROUP BY
  LINEITEM.L_SHIPMODE
ORDER BY
  1 NULLS FIRST
