WITH "_S0" AS (
  SELECT
    s_nationkey AS S_NATIONKEY,
    s_suppkey AS S_SUPPKEY
  FROM TPCH.SUPPLIER
), "_T2" AS (
  SELECT
    n_name AS N_NAME,
    n_nationkey AS N_NATIONKEY
  FROM TPCH.NATION
  WHERE
    n_name = 'GERMANY'
), "_S6" AS (
  SELECT
    COUNT(DISTINCT "_S0".S_SUPPKEY) AS NDISTINCT_S_SUPPKEY
  FROM "_S0" "_S0"
  JOIN "_T2" "_T2"
    ON "_S0".S_NATIONKEY = "_T2".N_NATIONKEY
), "_S7" AS (
  SELECT
    PARTSUPP.ps_partkey AS PS_PARTKEY,
    SUM(PARTSUPP.ps_supplycost * PARTSUPP.ps_availqty) AS SUM_EXPR
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN "_S0" "_S2"
    ON PARTSUPP.ps_suppkey = "_S2".S_SUPPKEY
  JOIN "_T2" "_T4"
    ON "_S2".S_NATIONKEY = "_T4".N_NATIONKEY
  GROUP BY
    PARTSUPP.ps_partkey
)
SELECT
  "_S7".PS_PARTKEY,
  COALESCE("_S7".SUM_EXPR, 0) AS VALUE
FROM "_S6" "_S6"
JOIN "_S7" "_S7"
  ON (
    "_S6".NDISTINCT_S_SUPPKEY * 0.0001
  ) < COALESCE("_S7".SUM_EXPR, 0)
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
