SELECT
  COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS REVENUE
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.PART PART
  ON (
    (
      LINEITEM.L_QUANTITY <= 11
      AND LINEITEM.L_QUANTITY >= 1
      AND PART.P_BRAND = 'Brand#12'
      AND PART.P_CONTAINER IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
      AND PART.P_SIZE <= 5
      AND PART.P_SIZE >= 1
    )
    OR (
      LINEITEM.L_QUANTITY <= 20
      AND LINEITEM.L_QUANTITY >= 10
      AND PART.P_BRAND = 'Brand#23'
      AND PART.P_CONTAINER IN ('MED BAG', 'MED BOX', 'MED PACK', 'MED PKG')
      AND PART.P_SIZE <= 10
      AND PART.P_SIZE >= 1
    )
    OR (
      LINEITEM.L_QUANTITY <= 30
      AND LINEITEM.L_QUANTITY >= 20
      AND PART.P_BRAND = 'Brand#34'
      AND PART.P_CONTAINER IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
      AND PART.P_SIZE <= 15
      AND PART.P_SIZE >= 1
    )
  )
  AND LINEITEM.L_PARTKEY = PART.P_PARTKEY
WHERE
  LINEITEM.L_SHIPINSTRUCT = 'DELIVER IN PERSON'
  AND LINEITEM.L_SHIPMODE IN ('AIR', 'AIR REG')
