WITH _S3 AS (
  SELECT
    SUM(LINEITEM.l_extendedprice * (
      1 - LINEITEM.l_discount
    )) AS SUM_EXPR_1,
    ORDERS.o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS AS ORDERS
  JOIN TPCH.LINEITEM AS LINEITEM
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey AND LINEITEM.l_returnflag = 'R'
  WHERE
    QUARTER(ORDERS.o_orderdate) = 4 AND YEAR(ORDERS.o_orderdate) = 1993
  GROUP BY
    ORDERS.o_custkey
)
SELECT
  CUSTOMER.c_custkey AS C_CUSTKEY,
  CUSTOMER.c_name AS C_NAME,
  COALESCE(_S3.SUM_EXPR_1, 0) AS REVENUE,
  CUSTOMER.c_acctbal AS C_ACCTBAL,
  NATION.n_name AS N_NAME,
  CUSTOMER.c_address AS C_ADDRESS,
  CUSTOMER.c_phone AS C_PHONE,
  CUSTOMER.c_comment AS C_COMMENT
FROM TPCH.CUSTOMER AS CUSTOMER
LEFT JOIN _S3 AS _S3
  ON CUSTOMER.c_custkey = _S3.O_CUSTKEY
JOIN TPCH.NATION AS NATION
  ON CUSTOMER.c_nationkey = NATION.n_nationkey
ORDER BY
  COALESCE(_S3.SUM_EXPR_1, 0) DESC NULLS LAST,
  C_CUSTKEY NULLS FIRST
LIMIT 20
