SELECT
  LINEITEM.L_ORDERKEY,
  COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS REVENUE,
  ORDERS.O_ORDERDATE,
  ORDERS.O_SHIPPRIORITY
FROM TPCH.ORDERS ORDERS
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND CUSTOMER.C_MKTSEGMENT = 'BUILDING'
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
  AND LINEITEM.L_SHIPDATE > TO_DATE('1995-03-15', 'YYYY-MM-DD')
WHERE
  ORDERS.O_ORDERDATE < TO_DATE('1995-03-15', 'YYYY-MM-DD')
GROUP BY
  LINEITEM.L_ORDERKEY,
  ORDERS.O_ORDERDATE,
  ORDERS.O_SHIPPRIORITY
ORDER BY
  2 DESC NULLS LAST,
  3 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
