SELECT
  (
    100.0 * COALESCE(
      SUM(
        CASE
          WHEN PART.P_TYPE LIKE 'PROMO%'
          THEN LINEITEM.L_EXTENDEDPRICE * (
            1 - LINEITEM.L_DISCOUNT
          )
          ELSE 0
        END
      ),
      0
    )
  ) / COALESCE(SUM(LINEITEM.L_EXTENDEDPRICE * (
    1 - LINEITEM.L_DISCOUNT
  )), 0) AS PROMO_REVENUE
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.PART PART
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
WHERE
  EXTRACT(MONTH FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 9
  AND EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1995
