WITH _T AS (
  SELECT
    NATION.n_name AS N_NAME,
    PART.p_mfgr AS P_MFGR,
    PART.p_partkey AS P_PARTKEY,
    SUPPLIER.s_acctbal AS S_ACCTBAL,
    SUPPLIER.s_address AS S_ADDRESS,
    SUPPLIER.s_comment AS S_COMMENT,
    SUPPLIER.s_name AS S_NAME,
    SUPPLIER.s_phone AS S_PHONE,
    RANK() OVER (PARTITION BY PARTSUPP.ps_partkey ORDER BY PARTSUPP.ps_supplycost) AS _W
  FROM TPCH.PART PART
  JOIN TPCH.PARTSUPP PARTSUPP
    ON PART.p_partkey = PARTSUPP.ps_partkey
  JOIN TPCH.SUPPLIER SUPPLIER
    ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
  JOIN TPCH.NATION NATION
    ON NATION.n_nationkey = SUPPLIER.s_nationkey
  JOIN TPCH.REGION REGION
    ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'EUROPE'
  WHERE
    PART.p_size = 15 AND PART.p_type LIKE '%BRASS'
)
SELECT
  S_ACCTBAL,
  S_NAME,
  N_NAME,
  P_PARTKEY,
  P_MFGR,
  S_ADDRESS,
  S_PHONE,
  S_COMMENT
FROM _T
WHERE
  _W = 1
ORDER BY
  1 DESC NULLS LAST,
  3 NULLS FIRST,
  2 NULLS FIRST,
  4 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
