WITH "_s3" AS (
  SELECT
    ORDERS.O_CUSTKEY,
    SUM(LINEITEM.L_EXTENDEDPRICE * (
      1 - LINEITEM.L_DISCOUNT
    )) AS SUM_EXPR
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.LINEITEM LINEITEM
    ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY AND LINEITEM.L_RETURNFLAG = 'R'
  WHERE
    EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)) IN (10, 11, 12)
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1993
  GROUP BY
    ORDERS.O_CUSTKEY
)
SELECT
  CUSTOMER.C_CUSTKEY,
  CUSTOMER.C_NAME,
  COALESCE("_s3".SUM_EXPR, 0) AS REVENUE,
  CUSTOMER.C_ACCTBAL,
  NATION.N_NAME,
  CUSTOMER.C_ADDRESS,
  CUSTOMER.C_PHONE,
  CUSTOMER.C_COMMENT
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN "_s3" "_s3"
  ON CUSTOMER.C_CUSTKEY = "_s3".O_CUSTKEY
JOIN TPCH.NATION NATION
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
ORDER BY
  3 DESC NULLS LAST,
  1 NULLS FIRST
FETCH FIRST 20 ROWS ONLY
