WITH _S1 AS (
  SELECT
    o_custkey AS O_CUSTKEY,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  WHERE
    NOT o_comment LIKE '%special%requests%'
  GROUP BY
    o_custkey
)
SELECT
  NVL(_S1.N_ROWS, 0) AS C_COUNT,
  COUNT(*) AS CUSTDIST
FROM TPCH.CUSTOMER CUSTOMER
LEFT JOIN _S1 _S1
  ON CUSTOMER.c_custkey = _S1.O_CUSTKEY
GROUP BY
  NVL(_S1.N_ROWS, 0)
ORDER BY
  2 DESC NULLS LAST,
  1 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
