SELECT
  PART.P_BRAND,
  PART.P_TYPE,
  PART.P_SIZE,
  COUNT(DISTINCT PARTSUPP.PS_SUPPKEY) AS SUPPLIER_COUNT
FROM TPCH.PARTSUPP PARTSUPP
JOIN TPCH.SUPPLIER SUPPLIER
  ON NOT SUPPLIER.S_COMMENT LIKE '%Customer%Complaints%'
  AND PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN TPCH.PART PART
  ON NOT PART.P_TYPE LIKE 'MEDIUM POLISHED%%'
  AND PART.P_BRAND <> 'BRAND#45'
  AND PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
  AND PART.P_SIZE IN (49, 14, 23, 45, 19, 3, 36, 9)
GROUP BY
  PART.P_BRAND,
  PART.P_SIZE,
  PART.P_TYPE
ORDER BY
  4 DESC NULLS LAST,
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
