WITH _T0 AS (
  SELECT
    NATION.n_name AS N_NAME,
    PART.p_mfgr AS P_MFGR,
    PART.p_partkey AS P_PARTKEY,
    SUPPLIER.s_acctbal AS S_ACCTBAL,
    SUPPLIER.s_address AS S_ADDRESS,
    SUPPLIER.s_comment AS S_COMMENT,
    SUPPLIER.s_name AS S_NAME,
    SUPPLIER.s_phone AS S_PHONE
  FROM TPCH.PART AS PART
  JOIN TPCH.PARTSUPP AS PARTSUPP
    ON PART.p_partkey = PARTSUPP.ps_partkey
  JOIN TPCH.SUPPLIER AS SUPPLIER
    ON PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
  JOIN TPCH.NATION AS NATION
    ON NATION.n_nationkey = SUPPLIER.s_nationkey
  JOIN TPCH.REGION AS REGION
    ON NATION.n_regionkey = REGION.r_regionkey AND REGION.r_name = 'EUROPE'
  WHERE
    PART.p_size = 15 AND PART.p_type LIKE '%BRASS'
  QUALIFY
    RANK() OVER (PARTITION BY PARTSUPP.ps_partkey ORDER BY PARTSUPP.ps_supplycost) = 1
)
SELECT
  S_ACCTBAL,
  S_NAME,
  N_NAME,
  P_PARTKEY,
  P_MFGR,
  S_ADDRESS,
  S_PHONE,
  S_COMMENT
FROM _T0
ORDER BY
  S_ACCTBAL DESC NULLS LAST,
  N_NAME NULLS FIRST,
  S_NAME NULLS FIRST,
  P_PARTKEY NULLS FIRST
LIMIT 10
