WITH "_s0" AS (
  SELECT
    S_NATIONKEY,
    S_SUPPKEY
  FROM TPCH.SUPPLIER
), "_t2" AS (
  SELECT
    N_NAME,
    N_NATIONKEY
  FROM TPCH.NATION
  WHERE
    N_NAME = 'GERMANY'
), "_s8" AS (
  SELECT
    SUM(PARTSUPP.PS_SUPPLYCOST * PARTSUPP.PS_AVAILQTY) AS SUM_METRIC
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN "_s0" "_s0"
    ON PARTSUPP.PS_SUPPKEY = "_s0".S_SUPPKEY
  JOIN "_t2" "_t2"
    ON "_s0".S_NATIONKEY = "_t2".N_NATIONKEY
), "_s9" AS (
  SELECT
    PARTSUPP.PS_PARTKEY,
    SUM(PARTSUPP.PS_SUPPLYCOST * PARTSUPP.PS_AVAILQTY) AS SUM_EXPR
  FROM TPCH.PARTSUPP PARTSUPP
  JOIN "_s0" "_s4"
    ON PARTSUPP.PS_SUPPKEY = "_s4".S_SUPPKEY
  JOIN "_t2" "_t4"
    ON "_s4".S_NATIONKEY = "_t4".N_NATIONKEY
  GROUP BY
    PARTSUPP.PS_PARTKEY
)
SELECT
  "_s9".PS_PARTKEY,
  COALESCE("_s9".SUM_EXPR, 0) AS VALUE
FROM "_s8" "_s8"
JOIN "_s9" "_s9"
  ON (
    COALESCE("_s8".SUM_METRIC, 0) * 0.0001
  ) < COALESCE("_s9".SUM_EXPR, 0)
ORDER BY
  2 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
