WITH "_t1" AS (
  SELECT
    L_ORDERKEY,
    SUM(L_QUANTITY) AS SUM_L_QUANTITY
  FROM TPCH.LINEITEM
  GROUP BY
    L_ORDERKEY
)
SELECT
  CUSTOMER.C_NAME,
  CUSTOMER.C_CUSTKEY,
  ORDERS.O_ORDERKEY,
  ORDERS.O_ORDERDATE,
  ORDERS.O_TOTALPRICE,
  "_t1".SUM_L_QUANTITY AS TOTAL_QUANTITY
FROM TPCH.ORDERS ORDERS
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
JOIN "_t1" "_t1"
  ON NOT "_t1".SUM_L_QUANTITY IS NULL
  AND ORDERS.O_ORDERKEY = "_t1".L_ORDERKEY
  AND "_t1".SUM_L_QUANTITY > 300
ORDER BY
  5 DESC NULLS LAST,
  4 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
