SELECT
  NATION.N_NAME AS NATION,
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS O_YEAR,
  COALESCE(
    SUM(
      LINEITEM.L_EXTENDEDPRICE * (
        1 - LINEITEM.L_DISCOUNT
      ) - PARTSUPP.PS_SUPPLYCOST * LINEITEM.L_QUANTITY
    ),
    0
  ) AS AMOUNT
FROM TPCH.LINEITEM LINEITEM
JOIN TPCH.PART PART
  ON LINEITEM.L_PARTKEY = PART.P_PARTKEY AND PART.P_NAME LIKE '%green%'
JOIN TPCH.SUPPLIER SUPPLIER
  ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
JOIN TPCH.NATION NATION
  ON NATION.N_NATIONKEY = SUPPLIER.S_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN TPCH.PARTSUPP PARTSUPP
  ON LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY
  AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
GROUP BY
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)),
  NATION.N_NAME
ORDER BY
  1 NULLS FIRST,
  2 DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY
