WITH _T2 AS (
  SELECT
    ORDERS.o_orderkey AS KEY,
    ORDERS.o_orderdate AS ORDER_DATE,
    ORDERS.o_orderpriority AS ORDER_PRIORITY
  FROM TPCH.ORDERS AS ORDERS
), _S0 AS (
  SELECT
    _T2.KEY AS KEY,
    _T2.ORDER_PRIORITY AS ORDER_PRIORITY
  FROM _T2 AS _T2
  WHERE
    DATE_PART(QUARTER, _T2.ORDER_DATE) = 3 AND DATE_PART(YEAR, _T2.ORDER_DATE) = 1993
), _T3 AS (
  SELECT
    LINEITEM.l_commitdate AS COMMIT_DATE,
    LINEITEM.l_orderkey AS ORDER_KEY,
    LINEITEM.l_receiptdate AS RECEIPT_DATE
  FROM TPCH.LINEITEM AS LINEITEM
), _S1 AS (
  SELECT
    _T3.ORDER_KEY AS ORDER_KEY
  FROM _T3 AS _T3
  WHERE
    _T3.COMMIT_DATE < _T3.RECEIPT_DATE
), _T1 AS (
  SELECT
    _S0.ORDER_PRIORITY AS ORDER_PRIORITY
  FROM _S0 AS _S0
  WHERE
    EXISTS(
      SELECT
        1 AS "1"
      FROM _S1 AS _S1
      WHERE
        _S0.KEY = _S1.ORDER_KEY
    )
), _T0 AS (
  SELECT
    COUNT(*) AS ORDER_COUNT,
    _T1.ORDER_PRIORITY AS O_ORDERPRIORITY
  FROM _T1 AS _T1
  GROUP BY
    _T1.ORDER_PRIORITY
)
SELECT
  _T0.O_ORDERPRIORITY AS O_ORDERPRIORITY,
  _T0.ORDER_COUNT AS ORDER_COUNT
FROM _T0 AS _T0
ORDER BY
  O_ORDERPRIORITY NULLS FIRST
