SELECT
  LINEITEM.l_orderkey AS L_ORDERKEY,
  COALESCE(SUM(LINEITEM.l_extendedprice * (
    1 - LINEITEM.l_discount
  )), 0) AS REVENUE,
  ORDERS.o_orderdate AS O_ORDERDATE,
  ORDERS.o_shippriority AS O_SHIPPRIORITY
FROM TPCH.ORDERS ORDERS
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey AND CUSTOMER.c_mktsegment = 'BUILDING'
JOIN TPCH.LINEITEM LINEITEM
  ON LINEITEM.l_orderkey = ORDERS.o_orderkey
  AND LINEITEM.l_shipdate > TO_DATE('1995-03-15', 'YYYY-MM-DD')
WHERE
  ORDERS.o_orderdate < TO_DATE('1995-03-15', 'YYYY-MM-DD')
GROUP BY
  LINEITEM.l_orderkey,
  ORDERS.o_orderdate,
  ORDERS.o_shippriority
ORDER BY
  2 DESC NULLS LAST,
  3 NULLS FIRST,
  1 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
