SELECT
  o_orderpriority AS O_ORDERPRIORITY,
  COUNT(*) AS ORDER_COUNT
FROM tpch.orders
WHERE
  EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) IN (7, 8, 9)
  AND EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME)) = 1993
GROUP BY
  1
ORDER BY
  1
