SELECT
  LINEITEM.l_orderkey AS L_ORDERKEY,
  COALESCE(SUM(LINEITEM.l_extendedprice * (
    1 - LINEITEM.l_discount
  )), 0) AS REVENUE,
  ORDERS.o_orderdate AS O_ORDERDATE,
  ORDERS.o_shippriority AS O_SHIPPRIORITY
FROM TPCH.ORDERS AS ORDERS
JOIN TPCH.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey AND CUSTOMER.c_mktsegment = 'BUILDING'
JOIN TPCH.LINEITEM AS LINEITEM
  ON LINEITEM.l_orderkey = ORDERS.o_orderkey
  AND LINEITEM.l_shipdate > CAST('1995-03-15' AS DATE)
WHERE
  ORDERS.o_orderdate < CAST('1995-03-15' AS DATE)
GROUP BY
  1,
  3,
  4
ORDER BY
  2 DESC NULLS LAST,
  3 NULLS FIRST,
  1 NULLS FIRST
LIMIT 10
