WITH _S0 AS (
  SELECT
    AVG(c_acctbal) AS GLOBAL_AVG_BALANCE
  FROM TPCH.CUSTOMER
  WHERE
    c_acctbal > 0.0
    AND SUBSTRING(c_phone, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
), _S3 AS (
  SELECT
    COUNT(*) AS N_ROWS,
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
  GROUP BY
    o_custkey
)
SELECT
  SUBSTRING(CUSTOMER.c_phone, 1, 2) AS CNTRY_CODE,
  COUNT(*) AS NUM_CUSTS,
  COALESCE(SUM(CUSTOMER.c_acctbal), 0) AS TOTACCTBAL
FROM _S0 AS _S0
JOIN TPCH.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_acctbal > _S0.GLOBAL_AVG_BALANCE
  AND SUBSTRING(CUSTOMER.c_phone, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
LEFT JOIN _S3 AS _S3
  ON CUSTOMER.c_custkey = _S3.O_CUSTKEY
WHERE
  _S3.N_ROWS = 0 OR _S3.N_ROWS IS NULL
GROUP BY
  SUBSTRING(CUSTOMER.c_phone, 1, 2)
ORDER BY
  CNTRY_CODE NULLS FIRST
