SELECT
  PART.p_brand AS P_BRAND,
  PART.p_type AS P_TYPE,
  PART.p_size AS P_SIZE,
  COUNT(DISTINCT PARTSUPP.ps_suppkey) AS SUPPLIER_COUNT
FROM TPCH.PARTSUPP AS PARTSUPP
JOIN TPCH.SUPPLIER AS SUPPLIER
  ON NOT SUPPLIER.s_comment LIKE '%Customer%Complaints%'
  AND PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
JOIN TPCH.PART AS PART
  ON NOT STARTSWITH(PART.p_type, 'MEDIUM POLISHED%')
  AND PART.p_brand <> 'BRAND#45'
  AND PART.p_partkey = PARTSUPP.ps_partkey
  AND PART.p_size IN (49, 14, 23, 45, 19, 3, 36, 9)
GROUP BY
  PART.p_brand,
  PART.p_size,
  PART.p_type
ORDER BY
  SUPPLIER_COUNT DESC NULLS LAST,
  P_BRAND NULLS FIRST,
  P_TYPE NULLS FIRST,
  P_SIZE NULLS FIRST
LIMIT 10
