WITH _S0 AS (
  SELECT
    s_suppkey AS KEY,
    s_nationkey AS NATION_KEY
  FROM TPCH.SUPPLIER
), _T4 AS (
  SELECT
    n_nationkey AS KEY,
    n_name AS NAME
  FROM TPCH.NATION
), _T1 AS (
  SELECT
    SUM(PARTSUPP.ps_supplycost * PARTSUPP.ps_availqty) AS AGG_0
  FROM TPCH.PARTSUPP AS PARTSUPP
  JOIN _S0 AS _S0
    ON PARTSUPP.ps_suppkey = _S0.KEY
  JOIN _T4 AS _T4
    ON _S0.NATION_KEY = _T4.KEY AND _T4.NAME = 'GERMANY'
), _T5 AS (
  SELECT
    SUM(PARTSUPP.ps_supplycost * PARTSUPP.ps_availqty) AS AGG_1,
    PARTSUPP.ps_partkey AS PART_KEY
  FROM TPCH.PARTSUPP AS PARTSUPP
  JOIN _S0 AS _S4
    ON PARTSUPP.ps_suppkey = _S4.KEY
  JOIN _T4 AS _T8
    ON _S4.NATION_KEY = _T8.KEY AND _T8.NAME = 'GERMANY'
  GROUP BY
    PARTSUPP.ps_partkey
)
SELECT
  _T5.PART_KEY AS PS_PARTKEY,
  COALESCE(_T5.AGG_1, 0) AS VALUE
FROM _T1 AS _T1
CROSS JOIN _T5 AS _T5
WHERE
  (
    COALESCE(_T1.AGG_0, 0) * 0.0001
  ) < COALESCE(_T5.AGG_1, 0)
ORDER BY
  VALUE DESC NULLS LAST
LIMIT 10
