WITH _T1 AS (
  SELECT
    COUNT_IF(ORDERS.o_orderpriority IN ('1-URGENT', '2-HIGH')) AS AGG_0,
    COUNT_IF(NOT ORDERS.o_orderpriority IN ('1-URGENT', '2-HIGH')) AS AGG_1,
    LINEITEM.l_shipmode AS SHIP_MODE
  FROM TPCH.LINEITEM AS LINEITEM
  JOIN TPCH.ORDERS AS ORDERS
    ON LINEITEM.l_orderkey = ORDERS.o_orderkey
  WHERE
    DATE_PART(YEAR, LINEITEM.l_receiptdate) = 1994
    AND LINEITEM.l_commitdate < LINEITEM.l_receiptdate
    AND LINEITEM.l_commitdate > LINEITEM.l_shipdate
    AND (
      LINEITEM.l_shipmode = 'MAIL' OR LINEITEM.l_shipmode = 'SHIP'
    )
  GROUP BY
    LINEITEM.l_shipmode
)
SELECT
  SHIP_MODE AS L_SHIPMODE,
  COALESCE(AGG_0, 0) AS HIGH_LINE_COUNT,
  COALESCE(AGG_1, 0) AS LOW_LINE_COUNT
FROM _T1
ORDER BY
  L_SHIPMODE NULLS FIRST
