WITH "_T1" AS (
  SELECT
    l_orderkey AS L_ORDERKEY,
    SUM(l_quantity) AS SUM_L_QUANTITY
  FROM TPCH.LINEITEM
  GROUP BY
    l_orderkey
)
SELECT
  CUSTOMER.c_name AS C_NAME,
  CUSTOMER.c_custkey AS C_CUSTKEY,
  ORDERS.o_orderkey AS O_ORDERKEY,
  ORDERS.o_orderdate AS O_ORDERDATE,
  ORDERS.o_totalprice AS O_TOTALPRICE,
  "_T1".SUM_L_QUANTITY AS TOTAL_QUANTITY
FROM TPCH.ORDERS ORDERS
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey
JOIN "_T1" "_T1"
  ON NOT "_T1".SUM_L_QUANTITY IS NULL
  AND ORDERS.o_orderkey = "_T1".L_ORDERKEY
  AND "_T1".SUM_L_QUANTITY > 300
ORDER BY
  5 DESC NULLS LAST,
  4 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
