WITH _T0 AS (
  SELECT
    SUM(l_quantity) AS SUM_L_QUANTITY,
    l_orderkey AS L_ORDERKEY
  FROM TPCH.LINEITEM
  GROUP BY
    l_orderkey
)
SELECT
  CUSTOMER.c_name AS C_NAME,
  CUSTOMER.c_custkey AS C_CUSTKEY,
  ORDERS.o_orderkey AS O_ORDERKEY,
  ORDERS.o_orderdate AS O_ORDERDATE,
  ORDERS.o_totalprice AS O_TOTALPRICE,
  COALESCE(_T0.SUM_L_QUANTITY, 0) AS TOTAL_QUANTITY
FROM TPCH.ORDERS AS ORDERS
JOIN TPCH.CUSTOMER AS CUSTOMER
  ON CUSTOMER.c_custkey = ORDERS.o_custkey
JOIN _T0 AS _T0
  ON NOT _T0.SUM_L_QUANTITY IS NULL
  AND ORDERS.o_orderkey = _T0.L_ORDERKEY
  AND _T0.SUM_L_QUANTITY > 300
ORDER BY
  O_TOTALPRICE DESC NULLS LAST,
  O_ORDERDATE NULLS FIRST
LIMIT 10
