SELECT
  PART.p_brand AS P_BRAND,
  PART.p_type AS P_TYPE,
  PART.p_size AS P_SIZE,
  COUNT(DISTINCT PARTSUPP.ps_suppkey) AS SUPPLIER_COUNT
FROM TPCH.PARTSUPP PARTSUPP
JOIN TPCH.SUPPLIER SUPPLIER
  ON NOT SUPPLIER.s_comment LIKE '%Customer%Complaints%'
  AND PARTSUPP.ps_suppkey = SUPPLIER.s_suppkey
JOIN TPCH.PART PART
  ON NOT PART.p_type LIKE 'MEDIUM POLISHED%%'
  AND PART.p_brand <> 'BRAND#45'
  AND PART.p_partkey = PARTSUPP.ps_partkey
  AND PART.p_size IN (49, 14, 23, 45, 19, 3, 36, 9)
GROUP BY
  PART.p_brand,
  PART.p_size,
  PART.p_type
ORDER BY
  4 DESC NULLS LAST,
  1 NULLS FIRST,
  2 NULLS FIRST,
  3 NULLS FIRST
FETCH FIRST 10 ROWS ONLY
