WITH "_S3" AS (
  SELECT
    n_nationkey AS N_NATIONKEY,
    n_regionkey AS N_REGIONKEY
  FROM TPCH.NATION
), "_S5" AS (
  SELECT
    r_name AS R_NAME,
    r_regionkey AS R_REGIONKEY
  FROM TPCH.REGION
), "_S14" AS (
  SELECT
    ORDERS.o_custkey AS O_CUSTKEY,
    PART.p_type AS P_TYPE,
    "_S5".R_NAME,
    COUNT(*) AS N_ROWS
  FROM TPCH.PART PART
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(MONTH FROM CAST(LINEITEM.l_shipdate AS DATE)) = 6
    AND EXTRACT(YEAR FROM CAST(LINEITEM.l_shipdate AS DATE)) = 1992
    AND LINEITEM.l_partkey = PART.p_partkey
  JOIN TPCH.SUPPLIER SUPPLIER
    ON LINEITEM.l_suppkey = SUPPLIER.s_suppkey
  JOIN "_S3" "_S3"
    ON SUPPLIER.s_nationkey = "_S3".N_NATIONKEY
  JOIN "_S5" "_S5"
    ON "_S3".N_REGIONKEY = "_S5".R_REGIONKEY
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1992
    AND LINEITEM.l_orderkey = ORDERS.o_orderkey
  WHERE
    PART.p_container LIKE 'SM%'
  GROUP BY
    ORDERS.o_custkey,
    PART.p_type,
    "_S5".R_NAME
), "_T2" AS (
  SELECT
    "_S13".R_NAME AS CUST_REGION,
    "_S14".R_NAME,
    SUM("_S14".N_ROWS) AS SUM_N_ROWS
  FROM "_S14" "_S14"
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_custkey = "_S14".O_CUSTKEY
  JOIN "_S3" "_S11"
    ON CUSTOMER.c_nationkey = "_S11".N_NATIONKEY
  JOIN "_S5" "_S13"
    ON "_S11".N_REGIONKEY = "_S13".R_REGIONKEY
  GROUP BY
    "_S13".R_NAME,
    "_S14".P_TYPE,
    "_S14".R_NAME
), "_T1" AS (
  SELECT
    R_NAME,
    MAX(SUM_N_ROWS) AS MAX_SUM_N_ROWS,
    SUM(SUM_N_ROWS) AS SUM_SUM_N_ROWS
  FROM "_T2"
  GROUP BY
    CUST_REGION,
    R_NAME
)
SELECT
  R_NAME AS region,
  AVG((
    100.0 * MAX_SUM_N_ROWS
  ) / SUM_SUM_N_ROWS) AS avgpct
FROM "_T1"
GROUP BY
  R_NAME
ORDER BY
  1 NULLS FIRST
