WITH "_s3" AS (
  SELECT
    N_NATIONKEY,
    N_REGIONKEY
  FROM TPCH.NATION
), "_s5" AS (
  SELECT
    R_NAME,
    R_REGIONKEY
  FROM TPCH.REGION
), "_s14" AS (
  SELECT
    ORDERS.O_CUSTKEY,
    PART.P_TYPE,
    "_s5".R_NAME,
    COUNT(*) AS N_ROWS
  FROM TPCH.PART PART
  JOIN TPCH.LINEITEM LINEITEM
    ON EXTRACT(MONTH FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 6
    AND EXTRACT(YEAR FROM CAST(LINEITEM.L_SHIPDATE AS DATE)) = 1992
    AND LINEITEM.L_PARTKEY = PART.P_PARTKEY
  JOIN TPCH.SUPPLIER SUPPLIER
    ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
  JOIN "_s3" "_s3"
    ON SUPPLIER.S_NATIONKEY = "_s3".N_NATIONKEY
  JOIN "_s5" "_s5"
    ON "_s3".N_REGIONKEY = "_s5".R_REGIONKEY
  JOIN TPCH.ORDERS ORDERS
    ON EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1992
    AND LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
  WHERE
    PART.P_CONTAINER LIKE 'SM%'
  GROUP BY
    ORDERS.O_CUSTKEY,
    PART.P_TYPE,
    "_s5".R_NAME
), "_t2" AS (
  SELECT
    "_s13".R_NAME AS CUST_REGION,
    "_s14".R_NAME,
    SUM("_s14".N_ROWS) AS SUM_N_ROWS
  FROM "_s14" "_s14"
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_CUSTKEY = "_s14".O_CUSTKEY
  JOIN "_s3" "_s11"
    ON CUSTOMER.C_NATIONKEY = "_s11".N_NATIONKEY
  JOIN "_s5" "_s13"
    ON "_s11".N_REGIONKEY = "_s13".R_REGIONKEY
  GROUP BY
    "_s13".R_NAME,
    "_s14".P_TYPE,
    "_s14".R_NAME
), "_t1" AS (
  SELECT
    R_NAME,
    MAX(SUM_N_ROWS) AS MAX_SUM_N_ROWS,
    SUM(SUM_N_ROWS) AS SUM_SUM_N_ROWS
  FROM "_t2"
  GROUP BY
    CUST_REGION,
    R_NAME
)
SELECT
  R_NAME AS region,
  AVG((
    100.0 * MAX_SUM_N_ROWS
  ) / SUM_SUM_N_ROWS) AS avgpct
FROM "_t1"
GROUP BY
  R_NAME
ORDER BY
  1 NULLS FIRST
