WITH a AS (
  SELECT
    SEQ4() AS x
  FROM TABLE(GENERATOR(ROWCOUNT => 10)) AS _0
), b AS (
  SELECT
    SEQ4() * 2 AS y
  FROM TABLE(GENERATOR(ROWCOUNT => 501)) AS _1
), a_2 AS (
  SELECT
    SEQ4() AS x
  FROM TABLE(GENERATOR(ROWCOUNT => 10)) AS _2
), b_2 AS (
  SELECT
    SEQ4() * 2 AS y
  FROM TABLE(GENERATOR(ROWCOUNT => 501)) AS _3
), _s5 AS (
  SELECT
    a_2.x,
    COUNT(*) AS n_rows
  FROM a_2 AS a_2
  JOIN b_2 AS b_2
    ON ENDSWITH(CAST(b_2.y AS VARCHAR), CAST(a_2.x AS VARCHAR))
  GROUP BY
    1
)
SELECT
  a.x,
  COUNT(*) AS n_prefix,
  ANY_VALUE(_s5.n_rows) AS n_suffix
FROM a AS a
JOIN b AS b
  ON STARTSWITH(CAST(b.y AS VARCHAR), CAST(a.x AS VARCHAR))
JOIN _s5 AS _s5
  ON _s5.x = a.x
GROUP BY
  1
ORDER BY
  1 NULLS FIRST
