WITH "_t" AS (
  SELECT
    PART.P_NAME,
    PART.P_RETAILPRICE,
    SIZES.PART_SIZE,
    ROW_NUMBER() OVER (PARTITION BY SIZES.PART_SIZE ORDER BY PART.P_RETAILPRICE) AS "_w"
  FROM (VALUES
    (1),
    (2),
    (3),
    (4),
    (5),
    (6),
    (7),
    (8),
    (9),
    (10)) AS SIZES(PART_SIZE)
  JOIN TPCH.PART PART
    ON PART.P_CONTAINER LIKE '%SM DRUM%'
    AND PART.P_NAME LIKE '%azure%'
    AND PART.P_SIZE = SIZES.PART_SIZE
    AND PART.P_TYPE LIKE '%PLATED%'
)
SELECT
  PART_SIZE AS part_size,
  P_NAME AS name,
  P_RETAILPRICE AS retail_price
FROM "_t"
WHERE
  "_w" = 1
ORDER BY
  1 NULLS FIRST
