WITH "_s5" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS YEAR_O_ORDERDATE,
    COUNT(DISTINCT ORDERS.O_CUSTKEY) AS NDISTINCT_O_CUSTKEY
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND CUSTOMER.C_MKTSEGMENT = 'AUTOMOBILE'
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'JAPAN'
  WHERE
    ORDERS.O_CLERK = 'Clerk#000000925'
  GROUP BY
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE))
)
SELECT
  YEARS.YEAR AS year,
  COALESCE("_s5".NDISTINCT_O_CUSTKEY, 0) AS n_orders
FROM (VALUES
  (1990),
  (1991),
  (1992),
  (1993),
  (1994),
  (1995),
  (1996),
  (1997),
  (1998),
  (1999),
  (2000)) AS YEARS(YEAR)
LEFT JOIN "_s5" "_s5"
  ON YEARS.YEAR = "_s5".YEAR_O_ORDERDATE
ORDER BY
  1 NULLS FIRST
