WITH _S5 AS (
  SELECT
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) AS YEAR_O_ORDERDATE,
    COUNT(DISTINCT ORDERS.o_custkey) AS NDISTINCT_O_CUSTKEY
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_custkey = ORDERS.o_custkey AND CUSTOMER.c_mktsegment = 'AUTOMOBILE'
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'JAPAN'
  WHERE
    ORDERS.o_clerk = 'Clerk#000000925'
  GROUP BY
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME))
)
SELECT
  COLUMN1 AS year,
  NVL(_S5.NDISTINCT_O_CUSTKEY, 0) AS n_orders
FROM (VALUES
  (1990),
  (1991),
  (1992),
  (1993),
  (1994),
  (1995),
  (1996),
  (1997),
  (1998),
  (1999),
  (2000)) AS YEARS(YEAR)
LEFT JOIN _S5 _S5
  ON COLUMN1 = _S5.YEAR_O_ORDERDATE
ORDER BY
  1 NULLS FIRST
