SELECT
  FOOTNOTES.DESCRIPTION AS footnote_description
FROM MAIN.COUNTRY COUNTRY
JOIN MAIN.FOOTNOTES FOOTNOTES
  ON COUNTRY.COUNTRYCODE = FOOTNOTES.COUNTRYCODE AND FOOTNOTES.YEAR = 'YR2012'
WHERE
  COUNTRY.SHORTNAME = 'Albania'
