WITH "_u_0" AS (
  SELECT
    COUNTRYCODE AS "_u_1"
  FROM MAIN.COUNTRYNOTES
  WHERE
    SERIESCODE = 'DT.DOD.DECT.CD'
  GROUP BY
    COUNTRYCODE
)
SELECT
  COUNTRY.COUNTRYCODE AS country_code
FROM MAIN.COUNTRY COUNTRY
LEFT JOIN "_u_0" "_u_0"
  ON COUNTRY.COUNTRYCODE = "_u_0"."_u_1"
WHERE
  COUNTRY.INCOMEGROUP = 'Low income' AND NOT "_u_0"."_u_1" IS NULL
