WITH "_t" AS (
  SELECT
    S_ACCTBAL,
    S_NAME,
    ROW_NUMBER() OVER (ORDER BY S_ACCTBAL DESC, S_NAME) AS "_w"
  FROM TPCH.SUPPLIER
)
SELECT
  S_NAME AS name,
  S_ACCTBAL AS account_balance
FROM "_t"
WHERE
  "_w" = 1
