WITH "_s3" AS (
  SELECT
    O_CUSTKEY
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(MONTH FROM CAST(O_ORDERDATE AS DATE)) = 1
    AND EXTRACT(YEAR FROM CAST(O_ORDERDATE AS DATE)) = 1998
), "_t2" AS (
  SELECT
    ANY_VALUE(CUSTOMER.C_ACCTBAL) AS ANYTHING_C_ACCTBAL,
    COUNT("_s3".O_CUSTKEY) AS COUNT_O_CUSTKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'FRANCE'
  LEFT JOIN "_s3" "_s3"
    ON CUSTOMER.C_CUSTKEY = "_s3".O_CUSTKEY
  GROUP BY
    CUSTOMER.C_CUSTKEY
), "_t" AS (
  SELECT
    ANYTHING_C_ACCTBAL,
    COUNT_O_CUSTKEY,
    SUM(COALESCE(CASE WHEN COUNT_O_CUSTKEY <> 0 THEN COUNT_O_CUSTKEY ELSE NULL END, 0)) OVER () AS "_w"
  FROM "_t2"
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  NULLIF(COUNT_O_CUSTKEY, 0) IS NULL AND ANYTHING_C_ACCTBAL < "_w"
