WITH "_T2" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'GERMANY'
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.c_custkey = ORDERS.o_custkey
    AND EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATETIME)) = 1992
  GROUP BY
    ORDERS.o_custkey
), "_T" AS (
  SELECT
    N_ROWS,
    AVG(CAST(N_ROWS AS DOUBLE PRECISION)) OVER () AS "_W"
  FROM "_T2"
)
SELECT
  COUNT(*) AS n
FROM "_T"
WHERE
  N_ROWS < "_W"
