SELECT
  SBTXID AS transaction_id,
  SUM(SBTXSHARES) OVER (ORDER BY SBTXDATETIME, SBTXID ROWS BETWEEN CURRENT ROW AND 4 FOLLOWING) AS w1,
  SUM(SBTXSHARES) OVER (
    PARTITION BY SBTXCUSTID
    ORDER BY SBTXDATETIME, SBTXID
    ROWS BETWEEN CURRENT ROW AND 4 FOLLOWING
  ) AS w2,
  SUM(SBTXSHARES) OVER (ORDER BY SBTXDATETIME, SBTXID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS w3,
  SUM(SBTXSHARES) OVER (
    PARTITION BY SBTXCUSTID
    ORDER BY SBTXDATETIME, SBTXID
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
  ) AS w4,
  SUM(SBTXSHARES) OVER (ORDER BY SBTXDATETIME, SBTXID ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) AS w5,
  SUM(SBTXSHARES) OVER (
    PARTITION BY SBTXCUSTID
    ORDER BY SBTXDATETIME, SBTXID
    ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING
  ) AS w6,
  SUM(SBTXSHARES) OVER (ORDER BY SBTXDATETIME, SBTXID ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) AS w7,
  SUM(SBTXSHARES) OVER (
    PARTITION BY SBTXCUSTID
    ORDER BY SBTXDATETIME, SBTXID
    ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
  ) AS w8
FROM MAIN.SBTRANSACTION
ORDER BY
  SBTXDATETIME NULLS FIRST
FETCH FIRST 8 ROWS ONLY
