WITH "_S1" AS (
  SELECT
    1 AS EXPR_0,
    c_acctbal AS C_ACCTBAL,
    c_custkey AS C_CUSTKEY
  FROM TPCH.CUSTOMER
  WHERE
    c_mktsegment = 'BUILDING'
), "_T" AS (
  SELECT
    "_S1".C_ACCTBAL,
    "_S1".EXPR_0,
    AVG(CAST(COALESCE("_S1".C_ACCTBAL, 0) AS DOUBLE PRECISION)) OVER () AS "_W"
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_S1" "_S1"
    ON ORDERS.o_custkey = "_S1".C_CUSTKEY
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1995
)
SELECT
  COUNT(*) AS n
FROM "_T"
WHERE
  NOT EXPR_0 IS NULL AND C_ACCTBAL < "_W"
