WITH "_t" AS (
  SELECT
    CUSTOMER.C_ACCTBAL,
    AVG(CAST(CUSTOMER.C_ACCTBAL AS DOUBLE PRECISION)) OVER () AS "_w"
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND CUSTOMER.C_MKTSEGMENT = 'BUILDING'
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1995
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  C_ACCTBAL < "_w"
