WITH "_T" AS (
  SELECT
    CUSTOMER.c_acctbal AS C_ACCTBAL,
    AVG(CAST(CUSTOMER.c_acctbal AS DOUBLE PRECISION)) OVER () AS "_W"
  FROM TPCH.ORDERS ORDERS
  JOIN TPCH.CUSTOMER CUSTOMER
    ON CUSTOMER.c_custkey = ORDERS.o_custkey AND CUSTOMER.c_mktsegment = 'BUILDING'
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) = 1995
)
SELECT
  COUNT(*) AS n
FROM "_T"
WHERE
  C_ACCTBAL < "_W"
