WITH "_s1" AS (
  SELECT DISTINCT
    C_CUSTKEY
  FROM TPCH.CUSTOMER
  WHERE
    C_MKTSEGMENT = 'BUILDING'
), "_u_0" AS (
  SELECT
    C_CUSTKEY AS "_u_1"
  FROM "_s1"
  GROUP BY
    C_CUSTKEY
), "_t" AS (
  SELECT
    ORDERS.O_TOTALPRICE,
    AVG(CAST(NULL AS INT)) OVER () AS "_w"
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_u_0" "_u_0"
    ON ORDERS.O_CUSTKEY = "_u_0"."_u_1"
  WHERE
    ORDERS.O_CLERK = 'Clerk#000000001' AND "_u_0"."_u_1" IS NULL
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  O_TOTALPRICE < (
    0.05 * "_w"
  )
