WITH "_S3" AS (
  SELECT
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME)) = 1992
), "_T2" AS (
  SELECT
    COUNT("_S3".O_CUSTKEY) AS COUNT_O_CUSTKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'GERMANY'
  LEFT JOIN "_S3" "_S3"
    ON CUSTOMER.c_custkey = "_S3".O_CUSTKEY
  GROUP BY
    CUSTOMER.c_custkey
), "_T" AS (
  SELECT
    COUNT_O_CUSTKEY,
    AVG(CAST(NVL(NULLIF(COUNT_O_CUSTKEY, 0), 0) AS DOUBLE PRECISION)) OVER () AS "_W"
  FROM "_T2"
)
SELECT
  COUNT(*) AS n
FROM "_T"
WHERE
  NULLIF(COUNT_O_CUSTKEY, 0) <> 0 AND "_W" > NVL(NULLIF(COUNT_O_CUSTKEY, 0), 0)
