SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  COUNT(*) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS w1,
  COUNT(*) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS w2,
  COUNT(*) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS w3,
  COUNT(*) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS w4,
  COUNT(*) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS w5,
  COUNT(*) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS w6,
  COUNT(*) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 3 PRECEDING AND 5 FOLLOWING) AS w7,
  COUNT(*) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 3 PRECEDING AND 5 FOLLOWING) AS w8
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
ORDER BY
  SBTRANSACTION.sbtxdatetime NULLS FIRST
LIMIT 8
