SELECT
  DENSE_RANK() OVER (ORDER BY CUSTOMER.C_ACCTBAL DESC) AS rank_value,
  NTILE(10) OVER (ORDER BY CUSTOMER.C_ACCTBAL) AS precentile_value,
  LAG(CUSTOMER.C_ACCTBAL, 2, 0.0) OVER (PARTITION BY NATION.N_REGIONKEY ORDER BY CUSTOMER.C_ACCTBAL) AS two_prev_value,
  LEAD(CUSTOMER.C_ACCTBAL, 2) OVER (PARTITION BY CUSTOMER.C_NATIONKEY ORDER BY CUSTOMER.C_ACCTBAL) AS two_next_value,
  SUM(CUSTOMER.C_ACCTBAL) OVER (
    PARTITION BY NATION.N_REGIONKEY
    ORDER BY CUSTOMER.C_ACCTBAL
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
  ) AS relsum_value,
  SUM(CUSTOMER.C_ACCTBAL) OVER (ORDER BY CUSTOMER.C_ACCTBAL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS relsum_value2,
  CUSTOMER.C_ACCTBAL / AVG(CAST(CUSTOMER.C_ACCTBAL AS DOUBLE PRECISION)) OVER (ORDER BY CUSTOMER.C_ACCTBAL ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS relavg_value,
  CUSTOMER.C_ACCTBAL / COUNT(CASE WHEN CUSTOMER.C_ACCTBAL > 0.0 THEN CUSTOMER.C_ACCTBAL ELSE NULL END) OVER () AS relcount_value,
  CUSTOMER.C_ACCTBAL / COUNT(*) OVER () AS relsize_value
FROM TPCH.NATION NATION
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
