WITH "_S3" AS (
  SELECT
    o_custkey AS O_CUSTKEY
  FROM TPCH.ORDERS
  WHERE
    EXTRACT(MONTH FROM CAST(o_orderdate AS DATETIME)) = 1
    AND EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME)) = 1998
), "_T2" AS (
  SELECT
    ANY_VALUE(CUSTOMER.c_acctbal) AS ANYTHING_C_ACCTBAL,
    COUNT("_S3".O_CUSTKEY) AS COUNT_O_CUSTKEY
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.c_nationkey = NATION.n_nationkey AND NATION.n_name = 'FRANCE'
  LEFT JOIN "_S3" "_S3"
    ON CUSTOMER.c_custkey = "_S3".O_CUSTKEY
  GROUP BY
    CUSTOMER.c_custkey
), "_T" AS (
  SELECT
    ANYTHING_C_ACCTBAL,
    COUNT_O_CUSTKEY,
    SUM(NVL(NULLIF(COUNT_O_CUSTKEY, 0), 0)) OVER () AS "_W"
  FROM "_T2"
)
SELECT
  COUNT(*) AS n
FROM "_T"
WHERE
  NULLIF(COUNT_O_CUSTKEY, 0) IS NULL AND ANYTHING_C_ACCTBAL < "_W"
