WITH "_s1" AS (
  SELECT
    1 AS EXPR_0,
    C_ACCTBAL,
    C_CUSTKEY
  FROM TPCH.CUSTOMER
  WHERE
    C_MKTSEGMENT = 'BUILDING'
), "_t" AS (
  SELECT
    "_s1".C_ACCTBAL,
    "_s1".EXPR_0,
    AVG(CAST(COALESCE("_s1".C_ACCTBAL, 0) AS DOUBLE PRECISION)) OVER () AS "_w"
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_s1" "_s1"
    ON ORDERS.O_CUSTKEY = "_s1".C_CUSTKEY
  WHERE
    EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1995
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  NOT EXPR_0 IS NULL AND C_ACCTBAL < "_w"
