WITH "_t2" AS (
  SELECT
    COUNT(*) AS N_ROWS
  FROM TPCH.CUSTOMER CUSTOMER
  JOIN TPCH.NATION NATION
    ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = 'GERMANY'
  JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
    AND EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) = 1992
  GROUP BY
    ORDERS.O_CUSTKEY
), "_t" AS (
  SELECT
    N_ROWS,
    AVG(CAST(N_ROWS AS DOUBLE PRECISION)) OVER () AS "_w"
  FROM "_t2"
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  N_ROWS < "_w"
