SELECT
  SBTRANSACTION.sbtxid AS transaction_id,
  SUM(SBTRANSACTION.sbtxshares) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND 4 FOLLOWING) AS w1,
  SUM(SBTRANSACTION.sbtxshares) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND 4 FOLLOWING) AS w2,
  SUM(SBTRANSACTION.sbtxshares) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS w3,
  SUM(SBTRANSACTION.sbtxshares) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS w4,
  SUM(SBTRANSACTION.sbtxshares) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) AS w5,
  SUM(SBTRANSACTION.sbtxshares) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) AS w6,
  SUM(SBTRANSACTION.sbtxshares) OVER (ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) AS w7,
  SUM(SBTRANSACTION.sbtxshares) OVER (PARTITION BY SBTRANSACTION.sbtxcustid ORDER BY SBTRANSACTION.sbtxdatetime, SBTRANSACTION.sbtxid ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) AS w8
FROM MAIN.SBCUSTOMER AS SBCUSTOMER
JOIN MAIN.SBTRANSACTION AS SBTRANSACTION
  ON SBCUSTOMER.sbcustid = SBTRANSACTION.sbtxcustid
ORDER BY
  SBTRANSACTION.sbtxdatetime NULLS FIRST
LIMIT 8
