WITH "_s3" AS (
  SELECT
    1 AS EXPR_0,
    COALESCE(SUM(ORDERS.O_TOTALPRICE), 0) AS TOTAL_SPENT,
    CUSTOMER.C_CUSTKEY
  FROM TPCH.CUSTOMER CUSTOMER
  LEFT JOIN TPCH.ORDERS ORDERS
    ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
  WHERE
    CUSTOMER.C_MKTSEGMENT = 'BUILDING'
  GROUP BY
    CUSTOMER.C_CUSTKEY
), "_t" AS (
  SELECT
    "_s3".EXPR_0,
    ORDERS.O_TOTALPRICE,
    AVG(CAST("_s3".TOTAL_SPENT AS DOUBLE PRECISION)) OVER () AS "_w"
  FROM TPCH.ORDERS ORDERS
  LEFT JOIN "_s3" "_s3"
    ON ORDERS.O_CUSTKEY = "_s3".C_CUSTKEY
  WHERE
    ORDERS.O_CLERK = 'Clerk#000000001'
)
SELECT
  COUNT(*) AS n
FROM "_t"
WHERE
  EXPR_0 IS NULL AND O_TOTALPRICE < (
    0.05 * "_w"
  )
