SELECT
  NATION.N_NAME AS nation_name,
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS order_year,
  EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)) AS order_month,
  COUNT(*) AS n_orders
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY AND ORDERS.O_ORDERPRIORITY = '1-URGENT'
WHERE
  REGION.R_NAME IN ('ASIA', 'AFRICA')
GROUP BY
  EXTRACT(MONTH FROM CAST(ORDERS.O_ORDERDATE AS DATE)),
  EXTRACT(YEAR FROM CAST(ORDERS.O_ORDERDATE AS DATE)),
  NATION.N_NAME
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
