SELECT
  NATION.n_name AS nation_name,
  EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)) AS order_year,
  EXTRACT(MONTH FROM CAST(ORDERS.o_orderdate AS DATE)) AS order_month,
  COUNT(*) AS n_orders
FROM TPCH.REGION REGION
JOIN TPCH.NATION NATION
  ON NATION.n_regionkey = REGION.r_regionkey
JOIN TPCH.CUSTOMER CUSTOMER
  ON CUSTOMER.c_nationkey = NATION.n_nationkey
JOIN TPCH.ORDERS ORDERS
  ON CUSTOMER.c_custkey = ORDERS.o_custkey AND ORDERS.o_orderpriority = '1-URGENT'
WHERE
  REGION.r_name IN ('ASIA', 'AFRICA')
GROUP BY
  EXTRACT(MONTH FROM CAST(ORDERS.o_orderdate AS DATE)),
  EXTRACT(YEAR FROM CAST(ORDERS.o_orderdate AS DATE)),
  NATION.n_name
ORDER BY
  4 DESC NULLS LAST
FETCH FIRST 5 ROWS ONLY
