WITH "_T0" AS (
  SELECT
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME)) AS YEAR_O_ORDERDATE,
    COUNT(*) AS N_ROWS
  FROM TPCH.ORDERS
  GROUP BY
    EXTRACT(YEAR FROM CAST(o_orderdate AS DATETIME))
)
SELECT
  YEAR_O_ORDERDATE AS year,
  N_ROWS AS current_year_orders,
  (
    100.0 * CAST(N_ROWS - LAG(N_ROWS, 1) OVER (ORDER BY YEAR_O_ORDERDATE) AS DOUBLE PRECISION)
  ) / LAG(N_ROWS, 1) OVER (ORDER BY YEAR_O_ORDERDATE) AS pct_change
FROM "_T0"
ORDER BY
  1 NULLS FIRST
