name: Build PyDough Pip Wheel

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_pydough_wheels:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Build PyDough Wheels

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::427443013497:role/PyDoughBuildWheelRole
          role-session-name: PyDoughBuildWheelSession
          role-skip-session-tagging: true

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.23"

      - name: Build Wheels
        run: |
          uv build

      - uses: actions/upload-artifact@v4
        with:
          name: upload-wheels
          path: ./dist/*.whl
