name: Run Postgres Tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: "JSON string of Python versions"
        type: string
        required: true
    secrets:
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true

jobs:
  postgres-test:
    name: Postgres Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    # Define services here to run Docker containers alongside your job
    services:
      postgres:
        image: bodoai1/pydough-postgres-tpch:latest
        env:
          # Set environment variables for Postgres container
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: "pydough-test"
        ports:
          - 5432:5432
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: pydough-test
      POSTGRES_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.23"

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e ".[postgres]" 

      - name: Wait for Postgres to be ready
        run: |
          for i in $(seq 1 240); do
            pg_isready -U $POSTGRES_USER -d $POSTGRES_DB && break || sleep 2;
          done
          pg_isready -U $POSTGRES_USER -d $POSTGRES_DB && echo "postgreSQL is running" && break || exit 1;
      - name: Confirm Postgres connector is installed
        run: uv run python -c "import psycopg2; print('Postgres connector installed')"

      - name: Run Postgres Tests
        run: uv run pytest -m postgres tests/ -rs
