name: Run Snowflake Tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: "JSON string of Python versions"
        type: string
        required: true
    secrets:
      SF_USERNAME:
        required: true
      SF_PASSWORD:
        required: true
      SF_ACCOUNT:
        required: true

jobs:
  sf-tests:
    name: Snowflake Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    env:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.23"

      - name: Create virtual environment
        # uv requires an existing virtual environment to install packages.
        # Running `uv venv` creates the `.venv` directory so that subsequent
        # `uv pip install` commands install dependencies inside this environment.
        # Without this step, `uv pip install` fails with 
        # "No virtual environment found".
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e ".[snowflake]"

      - name: Confirm Snowflake connector is installed
        run: uv run python -c "import snowflake.connector; print(snowflake.connector.__version__)"

      - name: Run Snowflake Tests
        run: uv run pytest -m snowflake tests/ -rs